import { afterEach, beforeEach, describe, expect, it } from "bun:test";
import { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { App } from "../src/contracts.js";
import { appVersion, escapeHtml, generateSite, installCommand, renderAppPage, renderIndexPage } from "../src/site.js";

function makeApp(appId: string, overrides: Partial<App> = {}): App {
  return {
    schema: "hasna.app.v1",
    id: `app_${appId.replaceAll("-", "_")}`,
    createdAt: "2026-07-06T08:00:00.000Z",
    appId,
    npmName: `@example/${appId.replace(/^open-/, "")}`,
    repoFolder: appId,
    githubUrl: `https://github.com/example/${appId}`,
    projectSlug: appId,
    surfaces: { bins: [appId.replace(/^open-/, "")] },
    lifecycle: "active",
    releaseChannel: "stable",
    tags: ["oss"],
    metadata: { version: "1.2.3" },
    ...overrides,
  } as App;
}

let outDir: string;

beforeEach(() => {
  outDir = mkdtempSync(join(tmpdir(), "catalog-site-"));
});

afterEach(() => {
  rmSync(outDir, { recursive: true, force: true });
});

describe("generateSite", () => {
  it("renders an index page and one landing page per app", () => {
    const apps = [makeApp("open-alpha", { summary: "Task tracking" }), makeApp("open-beta")];
    const result = generateSite({ apps, outDir, generatedAt: "2026-07-06T09:00:00.000Z" });
    expect(result.appCount).toBe(2);
    expect(result.pages.length).toBe(3);
    expect(existsSync(join(outDir, "index.html"))).toBe(true);
    expect(existsSync(join(outDir, "apps", "open-alpha", "index.html"))).toBe(true);

    const index = readFileSync(join(outDir, "index.html"), "utf8");
    expect(index).toContain("open-alpha");
    expect(index).toContain("Task tracking");
    expect(index).toContain("v1.2.3");

    const page = readFileSync(join(outDir, "apps", "open-alpha", "index.html"), "utf8");
    expect(page).toContain("bun add -g @example/alpha");
    expect(page).toContain("https://github.com/example/open-alpha");
    expect(page).toContain("https://www.npmjs.com/package/@example/alpha");
    expect(page).toContain("v1.2.3");
  });

  it("escapes HTML in app fields", () => {
    const app = makeApp("open-x", { summary: 'Hello <script>alert("x")</script>' });
    const html = renderAppPage(app, { apps: [app], outDir });
    expect(html).not.toContain("<script>alert");
    expect(html).toContain("&lt;script&gt;");
  });

  it("renders apps in deterministic appId order regardless of input order", () => {
    // A site whose card order depends on input order is unreproducible: the
    // same catalog produces a different site depending on upsert order.
    const apps = [makeApp("open-zeta"), makeApp("open-alpha")];
    const result = generateSite({ apps, outDir, generatedAt: "2026-07-06T09:00:00.000Z" });
    const index = readFileSync(join(outDir, "index.html"), "utf8");
    expect(index.indexOf("open-alpha")).toBeLessThan(index.indexOf("open-zeta"));
    // The page list is written in the same sorted order.
    expect(result.pages[1]).toContain(join("apps", "open-alpha", "index.html"));
  });

  it("renders an empty catalog without per-app pages", () => {
    const result = generateSite({ apps: [], outDir, generatedAt: "2026-07-06T09:00:00.000Z" });
    expect(result.appCount).toBe(0);
    expect(result.pages.length).toBe(1);
    expect(readFileSync(join(outDir, "index.html"), "utf8")).toContain("0 open-source apps");
    expect(existsSync(join(outDir, "apps"))).toBe(false);
  });

  it("strips git+ and .git from the rendered GitHub link", () => {
    const app = makeApp("open-alpha", { githubUrl: "git+https://github.com/example/todos.git" });
    const html = renderAppPage(app, { apps: [app], outDir });
    expect(html).toContain('href="https://github.com/example/todos">GitHub');
    expect(html).not.toContain("git+");
  });

  it("escapes the generatedAt footer timestamp", () => {
    const html = renderIndexPage({ apps: [], outDir, generatedAt: '2026-07-06T09:00:00.000Z <b>x</b>' });
    expect(html).toContain("&lt;b&gt;");
    expect(html).not.toContain('<footer>Generated by @hasna/catalog on 2026-07-06T09:00:00.000Z <b>');
  });

  it("produces byte-identical output for reversed input order with a fixed generatedAt", () => {
    // Two generations of the same catalog must be byte-identical: same page
    // set, same relative paths, same content. Only the timestamp is free to
    // vary, and it is fixed here.
    const appsForward = [makeApp("open-alpha", { summary: "Task tracking" }), makeApp("open-beta")];
    const appsReversed = [makeApp("open-beta"), makeApp("open-alpha", { summary: "Task tracking" })];
    const outA = mkdtempSync(join(tmpdir(), "catalog-site-a-"));
    const outB = mkdtempSync(join(tmpdir(), "catalog-site-b-"));
    try {
      const resultA = generateSite({ apps: appsForward, outDir: outA, generatedAt: "2026-07-06T09:00:00.000Z" });
      const resultB = generateSite({ apps: appsReversed, outDir: outB, generatedAt: "2026-07-06T09:00:00.000Z" });
      const relA = resultA.pages.map((p) => p.replace(outA, "")).sort();
      const relB = resultB.pages.map((p) => p.replace(outB, "")).sort();
      expect(relA).toEqual(relB);
      for (const rel of relA) {
        const pathB = join(outB, rel);
        expect(existsSync(pathB)).toBe(true);
        expect(readFileSync(join(outA, rel), "utf8")).toBe(readFileSync(pathB, "utf8"));
      }
      // The caller's array is not reordered by generation.
      expect(appsForward.map((a) => a.appId)).toEqual(["open-alpha", "open-beta"]);
    } finally {
      rmSync(outA, { recursive: true, force: true });
      rmSync(outB, { recursive: true, force: true });
    }
  });
});

describe("helpers", () => {
  it("escapeHtml escapes all special characters", () => {
    expect(escapeHtml(`<a href="x">&'`)).toBe("&lt;a href=&quot;x&quot;&gt;&amp;&#39;");
  });

  it("installCommand uses bun", () => {
    expect(installCommand(makeApp("open-alpha"))).toBe("bun add -g @example/alpha");
  });

  it("appVersion returns null for missing, empty, or non-string versions", () => {
    expect(appVersion(makeApp("open-a", { metadata: {} }))).toBeNull();
    expect(appVersion(makeApp("open-b", { metadata: { version: "" } }))).toBeNull();
    expect(appVersion(makeApp("open-c", { metadata: { version: 42 } }))).toBeNull();
    expect(appVersion(makeApp("open-d", { metadata: { version: "1.2.3" } }))).toBe("1.2.3");
  });

  it("omits the version badge and Provides line when they do not apply", () => {
    const noVersion = renderAppPage(makeApp("open-a", { metadata: {} }), { apps: [], outDir });
    expect(noVersion).not.toContain("badge version");
    const noBins = renderAppPage(makeApp("open-b", { surfaces: { bins: [] } }), { apps: [], outDir });
    expect(noBins).not.toContain("Provides:");
  });
});

describe("helpers", () => {
  it("escapeHtml escapes all special characters", () => {
    expect(escapeHtml(`<a href="x">&'`)).toBe("&lt;a href=&quot;x&quot;&gt;&amp;&#39;");
  });

  it("installCommand uses bun", () => {
    expect(installCommand(makeApp("open-alpha"))).toBe("bun add -g @example/alpha");
  });
});
