#!/usr/bin/env bun
/**
 * Generate the /v1 TypeScript client from openapi.json via
 * @hasna/contracts/sdk. The output is committed under
 * src/generated/v1/client.ts and is the source the hasna.contract.json sdk
 * surface claims (`generatedFrom: /openapi.json`).
 *
 * Usage: bun scripts/generate-v1-sdk.mjs [--check]
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { generateSdkFromOpenApi } from '@hasna/contracts/sdk'

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..')
const specPath = join(root, 'openapi.json')
const outPath = join(root, 'src', 'generated', 'v1', 'client.ts')
const check = process.argv.includes('--check')

const spec = JSON.parse(readFileSync(specPath, 'utf8'))
const generated = generateSdkFromOpenApi(spec, {
  className: 'PromptsV1Client',
  apiKeyHeader: 'x-api-key',
})

const header =
  '// @generated by @hasna/prompts scripts/generate-v1-sdk.mjs from openapi.json — DO NOT EDIT.\n' +
  '// Regenerate: bun scripts/generate-v1-sdk.mjs\n'

if (check) {
  if (!existsSync(outPath)) {
    console.error('generated SDK missing; run bun scripts/generate-v1-sdk.mjs')
    process.exit(1)
  }
  const current = readFileSync(outPath, 'utf8')
  if (current !== header + generated.code) {
    console.error('generated SDK is stale; run bun scripts/generate-v1-sdk.mjs')
    process.exit(1)
  }
  console.log(`generated SDK current (${generated.operations.length} operations)`)
  process.exit(0)
}

mkdirSync(dirname(outPath), { recursive: true })
writeFileSync(outPath, header + generated.code)
console.log(`wrote ${outPath} (${generated.operations.length} operations)`)
if (generated.warnings.length > 0) {
  for (const warning of generated.warnings) console.warn(`warning: ${warning}`)
}
