import {
  type McpHttpServerHandle,
  healthPayload,
  isHttpMode as harnessIsHttpMode,
  isStdioMode as harnessIsStdioMode,
  resetMcpHttpStateForTests as harnessResetMcpHttpStateForTests,
  resolveMcpHttpPort as harnessResolveMcpHttpPort,
  startMcpHttpServer as harnessStartMcpHttpServer,
} from "./harness.js";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";

/**
 * logs MCP transport/port boilerplate — thin shim over the vendored harness
 * (./harness.ts). Public API preserved; hand-rolled transport/port/health
 * removed.
 * Generated by open-mcp/scripts/adopt-harness.ts.
 */

export const MCP_HTTP_SERVICE_NAME = "logs";
export const DEFAULT_MCP_HTTP_PORT = 8864;

export type { McpHttpServerHandle };
export function isHttpMode(
  argv: readonly string[] = process.argv,
  env: NodeJS.ProcessEnv = process.env,
): boolean {
  return harnessIsHttpMode(argv, env);
}
export function isStdioMode(
  argv: readonly string[] = process.argv,
  env: NodeJS.ProcessEnv = process.env,
): boolean {
  return harnessIsStdioMode(argv, env);
}
export function resolveMcpHttpPort(
  argv: readonly string[] = process.argv,
  env: NodeJS.ProcessEnv = process.env,
): number {
  return harnessResolveMcpHttpPort({
    argv,
    env,
    default: DEFAULT_MCP_HTTP_PORT,
  });
}
export async function startMcpHttpServer(
  buildServer: () => McpServer,
  options?: { port?: number; host?: string; serviceName?: string },
) {
  return harnessStartMcpHttpServer(buildServer, {
    port: options?.port,
    host: options?.host,
    serviceName: options?.serviceName ?? MCP_HTTP_SERVICE_NAME,
    defaultPort: DEFAULT_MCP_HTTP_PORT,
  });
}
