import {
  type McpHttpServerHandle,
  healthPayload,
  isHttpMode as harnessIsHttpMode,
  isStdioMode as harnessIsStdioMode,
  resetMcpHttpStateForTests as harnessResetMcpHttpStateForTests,
  resolveMcpHttpPort as harnessResolveMcpHttpPort,
  startMcpHttpServer as harnessStartMcpHttpServer,
} from "./harness.js";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { assertStoreConfigured } from "../store/index.ts";

/**
 * logs MCP transport/port boilerplate — thin shim over the vendored harness
 * (./harness.ts). Public API preserved; hand-rolled transport/port/health
 * removed.
 * Generated by open-mcp/scripts/adopt-harness.ts.
 *
 * Local addition (hasna/apps#1720 validation, round 3): the listener factory
 * runs the authority preflight ITSELF before the harness creates a socket —
 * see {@link startMcpHttpServer}.
 */

export const MCP_HTTP_SERVICE_NAME = "logs";
export const DEFAULT_MCP_HTTP_PORT = 8864;

export type { McpHttpServerHandle };
export function isHttpMode(
  argv: readonly string[] = process.argv,
  env: NodeJS.ProcessEnv = process.env,
): boolean {
  return harnessIsHttpMode(argv, env);
}
export function isStdioMode(
  argv: readonly string[] = process.argv,
  env: NodeJS.ProcessEnv = process.env,
): boolean {
  return harnessIsStdioMode(argv, env);
}
export function resolveMcpHttpPort(
  argv: readonly string[] = process.argv,
  env: NodeJS.ProcessEnv = process.env,
): number {
  return harnessResolveMcpHttpPort({
    argv,
    env,
    default: DEFAULT_MCP_HTTP_PORT,
  });
}
export async function startMcpHttpServer(
  buildServer: () => McpServer,
  options?: { port?: number; host?: string; serviceName?: string },
) {
  // AUTHORITY PREFLIGHT AT THE LISTENER (owner ruling 2026-09-04, hasna/apps#1720
  // acceptance (c), round 3). The socket is HTTP mode's point of no return:
  // once bound, a process with no resolvable credential looks alive (`/health`
  // 200, "Streamable HTTP listening" on stderr) and refuses every session with
  // -32603 instead of failing at start — exactly what 0.5.0 shipped. The
  // `logs-mcp` startup gate runs first and prints the remedy; this preflight
  // makes the invariant local to the code that binds, so NO caller of this
  // factory (an embedder, a future CLI verb) can create a listener ungated.
  // Rejects with the resolver's remedy; nothing is created before it resolves.
  await assertStoreConfigured();
  return harnessStartMcpHttpServer(buildServer, {
    port: options?.port,
    host: options?.host,
    serviceName: options?.serviceName ?? MCP_HTTP_SERVICE_NAME,
    defaultPort: DEFAULT_MCP_HTTP_PORT,
  });
}
