#!/usr/bin/env bun
/**
 * Stamp the canonical Postgres migrations into ./migrations/*.sql for inventory
 * and inspection. The runner (src/db/pg-migrate.ts) uses the same in-code
 * definitions as the source of truth; these files mirror them 1:1.
 *
 *   bun run scripts/gen-migrations.ts
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { getPgMigrations } from "../src/db/pg-migrate.js";

const dir = join(import.meta.dir, "..", "migrations");
mkdirSync(dir, { recursive: true });

const migrations = getPgMigrations();
for (const m of migrations) {
  const file = join(dir, `${m.id}.sql`);
  const header = `-- @generated by scripts/gen-migrations.ts — DO NOT EDIT.\n-- id: ${m.id}\n-- checksum: ${m.checksum}\n\n`;
  writeFileSync(file, header + m.sql.trim() + "\n");
  console.log(`wrote migrations/${m.id}.sql`);
}
console.log(`done: ${migrations.length} migration file(s)`);
