import {test,expect} from "bun:test";
import {mkdir,mkdtemp,readFile,writeFile,rm,symlink,readdir} from "node:fs/promises";
import {join} from "node:path";
import {homedir} from "node:os";
import {Database} from "bun:sqlite";
import {kiloSettings,kiloConfigText} from "../src/kilo-config";
import {validateKiloArgs,validateKiloConfiguration} from "../src/kilo";
import {prepareHarnessLaunch,validateHarnessVersion} from "../src/harnesses";
import {requireOriHarness} from "../src/ori-backend";

async function fixture(){const base=process.env.SWITCHER_TEST_ROOT??join(homedir(),"Workspace/scratch/switcher-tests");await mkdir(base,{recursive:true});const root=await mkdtemp(join(base,"kilo-"));const env={HOME:join(root,"home"),XDG_CONFIG_HOME:join(root,"config")};await mkdir(join(env.XDG_CONFIG_HOME,"kilo"),{recursive:true});await mkdir(env.HOME);return{root,env};}
async function isolated<T>(env:Record<string,string>,run:()=>Promise<T>){const names=["HOME","XDG_CONFIG_HOME","KILO_CONFIG","KILO_CONFIG_CONTENT","KILO_CONFIG_DIR","KILO_PERMISSION"];const prior=Object.fromEntries(names.map(k=>[k,process.env[k]]));try{for(const name of names)delete process.env[name];Object.assign(process.env,env);return await run();}finally{for(const name of names)if(prior[name]===undefined)delete process.env[name];else process.env[name]=prior[name];}}

test("Kilo sanitizes provider and agent overrides while retaining ordered native policies and instructions",async()=>{const{root,env}=await fixture();try{
 const global=join(env.XDG_CONFIG_HOME,"kilo/kilo.jsonc");await writeFile(global,'{// global policy\n"permission":{"bash":"deny","read":{"~/private/*":"deny"}},"agent":{"build":{"permission":{"edit":"deny"}}}}');
 await writeFile(join(root,"kilo.json"),JSON.stringify({permission:{read:{"allowed.txt":"allow"}},agent:{build:{prompt:"PROJECT_AGENT_RULE"}},instructions:["EXPLICIT.md"]}));
 await writeFile(join(root,"AGENTS.md"),"PROJECT_RULE");await writeFile(join(root,"EXPLICIT.md"),"EXPLICIT_RULE");await mkdir(join(root,".kilo/agents"),{recursive:true});await writeFile(join(root,".kilo/agents/limited.md"),'---\npermission:\n  read:\n    protected.txt: deny\n---\nLIMITED_RULE');
 const settings=await kiloSettings(root,root,env);const text=JSON.stringify(settings.config);expect(text).not.toContain("outside.invalid");expect(text).not.toContain("SWITCHER_HARNESS_API_KEY");expect(text).not.toContain("do-not-copy");expect(settings.config.permission).toEqual({bash:"deny",read:{[join(env.HOME,"private/*")]:"deny","allowed.txt":"allow"}});expect((settings.config.agent as any).limited.permission.read["protected.txt"]).toBe("deny");expect((settings.config.agent as any).build.prompt).toBe("PROJECT_AGENT_RULE");expect((settings.global.permission as any).bash).toBe("deny");expect((await Promise.all(settings.instructions.map(path=>readFile(path,"utf8")))).join("\n")).toContain("EXPLICIT_RULE");expect(await readFile(global,"utf8")).toContain("// global policy");
}finally{await rm(root,{recursive:true,force:true});}});

test("Kilo fails closed on malformed policy, duplicate JSON/YAML, instruction substitutions and external project files",async()=>{const{root,env}=await fixture();try{
 const config=join(root,"kilo.json");for(const content of ['{"permission":{"read":null}}','{"permission":{"read":"deny"},"permission":{"read":"allow"}}','{"permission":{"read":true}}','{"sandbox":{"enabled":true}}','{"experimental":{"sandbox":true}}','{"permissions":[{"action":"read","resource":"*","effect":"deny"}]}','{"agent":{"bad":{"permission":{"read":[]}}}}']){await writeFile(config,content);await expect(kiloSettings(root,root,env)).rejects.toThrow("Kilo cannot preserve");}
 await writeFile(config,'{"instructions":["https://outside.invalid/rules"]}');await expect(kiloSettings(root,root,env)).rejects.toThrow("remote instruction");await writeFile(config,'{}');await writeFile(join(root,"AGENTS.md"),"{env:SWITCHER_HARNESS_API_KEY}");await expect(kiloSettings(root,root,env)).rejects.toThrow("variable reference");await rm(join(root,"AGENTS.md"));
 await mkdir(join(root,"project"));await writeFile(join(root,"outside.md"),"PRIVATE_OUTSIDE");await symlink(join(root,"outside.md"),join(root,"project/AGENTS.md"));await expect(kiloSettings(join(root,"project"),root,env)).rejects.toThrow("external project instruction");
 await mkdir(join(root,".kilo/agents"),{recursive:true});await writeFile(join(root,".kilo/agents/limited.md"),'---\npermission: deny\npermission: allow\n---\nRULE');await expect(kiloSettings(root,root,env)).rejects.toThrow("YAML");
}finally{await rm(root,{recursive:true,force:true});}});

test("Kilo serializes only the generated credential reference and reserves native authority arguments",()=>{
 const text=kiloConfigText({agent:{build:{prompt:"literal {env:SECRET}"}},provider:{scope:{options:{apiKey:"unused"},models:{"{file:/outside}":{}}}}},"scope","KEY");expect(text.match(/\{env:/g)).toHaveLength(1);expect(text).toContain("{env:KEY}");expect(text).toContain('\\u007benv:SECRET');expect(JSON.parse(text).agent.build.prompt).toBe("literal {env:SECRET}");
 for(const args of [["run","--model","outside"],["run","-moutside"],["run","-cmSECOND"],["run","--prompt","--model"],["run","--attach=http://outside"],["run","-psecret"],["models","other"],["--worktree","other"],["--config","outside.json"]])expect(()=>validateKiloArgs(args)).toThrow();for(const args of [["run","--auto"],["run","--continue","hello"],["run","--prompt=--model"],["run","-f--model"],["models","--verbose"],["models","--log-level","DEBUG"],["--session","session","--agent","build"]])expect(()=>validateKiloArgs(args)).not.toThrow();expect(()=>validateHarnessVersion("kilo","7.5.14")).toThrow("7.5.15");expect(()=>requireOriHarness({version:"0.12.1"} as any,"kilo")).toThrow("Kilo");
});

test("Kilo policy preflight is credential-free and produces no instruction snapshots",async()=>{const{root}=await fixture();try{await writeFile(join(root,"AGENTS.md"),"PROJECT_RULE");await validateKiloConfiguration(root,["run","--prompt=--model"]);expect((await readdir(root)).filter(name=>name.startsWith("kilo-instructions-")).length).toBe(0);}finally{await rm(root,{recursive:true,force:true});}});

test("Kilo rejects project provider and agent routing overrides before launch",async()=>{const{root,env}=await fixture();try{await writeFile(join(root,"kilo.json"),JSON.stringify({model:"outside/model"}));await expect(kiloSettings(root,root,env)).rejects.toThrow("provider/model authority");await writeFile(join(root,"kilo.json"),JSON.stringify({agent:{build:{model:"outside/model"}}}));await expect(kiloSettings(root,root,env)).rejects.toThrow("agent provider/model authority");}finally{await rm(root,{recursive:true,force:true});}});

test("Kilo preserves full native SDK catalog, stable sessions and authenticated protocol bridges",async()=>{const{root,env}=await fixture();const seen:any[]=[];const upstream=Bun.serve({hostname:"127.0.0.1",port:0,async fetch(req){seen.push({path:new URL(req.url).pathname,key:req.headers.get("x-api-key"),auth:req.headers.get("authorization"),body:await req.json()});return Response.json({ok:true});}});try{await isolated(env,async()=>{
 for(const [index,protocol]of (["openai-chat","openai-responses","anthropic-messages"] as const).entries()){
  const input={harness:"kilo" as const,version:"7.5.15",stateDir:join(root,"launch"+index),sessionDir:join(root,"durable"),cwd:root,baseUrl:upstream.url.origin+"/prefix/v1",protocol,authStyle:protocol==="anthropic-messages"?"bearer" as const:"x-api-key" as const,credential:"synthetic-fixture",model:"vendor/model",models:[{id:"vendor/model",name:"Model",contextWindow:32000,maxOutputTokens:1024,inputModalities:["text","image"]},{id:"another/namespace/model",name:"Other"}],args:["run","--continue","hello"]};
  const prepared=await prepareHarnessLaunch(input);try{
   const config=JSON.parse(await readFile(prepared.configPaths[0],"utf8")),provider:any=Object.values(config.provider)[0],providerID=Object.keys(config.provider)[0];expect(Object.keys(provider.models)).toEqual(input.models.map(m=>m.id));expect(provider.models[input.model].modalities.input).toEqual(["text","image"]);expect(provider.options.baseURL).toStartWith("http://127.0.0.1:");expect(JSON.stringify(config)).not.toContain(input.credential);expect(prepared.env.KILO_NO_DAEMON).toBe("1");expect(prepared.env.KILO_AUTH_CONTENT).toBe("{}");expect(prepared.env.XDG_DATA_HOME).toBe(join(root,"durable/data"));expect(prepared.args).toEqual(["run","--model",providerID+"/vendor/model","--continue","hello"]);
   const route=protocol==="openai-chat"?"/chat/completions":protocol==="openai-responses"?"/responses":"/messages";const auth=protocol==="anthropic-messages"?{"x-api-key":prepared.env.SWITCHER_HARNESS_API_KEY}:{authorization:"Bearer "+prepared.env.SWITCHER_HARNESS_API_KEY};const request=(body:unknown,headers:HeadersInit=auth)=>fetch(provider.options.baseURL+route,{method:"POST",headers:{"content-type":"application/json",...headers},body:JSON.stringify(body)});
   expect((await request({model:input.model})).status).toBe(200);expect((await request({model:"outside"})).status).toBe(403);expect((await request({model:input.model},{authorization:"Bearer wrong"})).status).toBe(401);
  }finally{await prepared.cleanup?.();}
 }
 expect(seen.map(v=>v.path)).toEqual(["/prefix/v1/chat/completions","/prefix/v1/responses","/prefix/v1/messages"]);expect(seen[0].key).toBe("synthetic-fixture");expect(seen[0].auth).toBeNull();expect(seen[2].auth).toBe("Bearer synthetic-fixture");expect(seen[2].key).toBeNull();
 });}finally{await upstream.stop(true);await rm(root,{recursive:true,force:true});}});

test("Kilo uses the parent bridge for credentialless providers without forwarding auth",async()=>{const{root,env}=await fixture();let auth:string|null=null,key:string|null=null;const upstream=Bun.serve({hostname:"127.0.0.1",port:0,fetch(req){auth=req.headers.get("authorization");key=req.headers.get("x-api-key");return Response.json({ok:true});}});let prepared:Awaited<ReturnType<typeof prepareHarnessLaunch>>|undefined;try{await isolated(env,async()=>{prepared=await prepareHarnessLaunch({harness:"kilo",version:"7.5.15",cwd:root,stateDir:join(root,"launch"),baseUrl:upstream.url.origin+"/v1",protocol:"openai-chat",authStyle:"bearer",model:"fixture",models:[{id:"fixture",name:"Fixture"}],args:[]});const config=JSON.parse(await readFile(prepared!.configPaths[0],"utf8"));const provider:any=Object.values(config.provider)[0];const response=await fetch(provider.options.baseURL+"/chat/completions",{method:"POST",headers:{authorization:`Bearer ${prepared!.env.SWITCHER_HARNESS_API_KEY}`,"content-type":"application/json"},body:JSON.stringify({model:"fixture"})});expect(response.status).toBe(200);expect(auth).toBeNull();expect(key).toBeNull();expect(prepared!.env.SWITCHER_HARNESS_API_KEY).not.toBe("switcher-local-no-auth");});}finally{await prepared?.cleanup?.();await upstream.stop(true);await rm(root,{recursive:true,force:true});}});

test("Kilo rejects durable native account configuration without changing the native database",async()=>{const{root,env}=await fixture();try{const sessionDir=join(root,"sessions");await mkdir(join(sessionDir,"data/kilo"),{recursive:true});const path=join(sessionDir,"data/kilo/kilo.db");const db=new Database(path);db.exec("CREATE TABLE account_state(active_account_id TEXT); INSERT INTO account_state VALUES('test-account')");db.close();const before=await readFile(path);await isolated(env,async()=>{await expect(prepareHarnessLaunch({harness:"kilo",version:"7.5.15",cwd:root,stateDir:join(root,"launch"),sessionDir,protocol:"openai-chat",baseUrl:"https://example.com/v1",model:"fixture",models:[{id:"fixture",name:"Fixture"}],credential:"synthetic"})).rejects.toThrow("active account");});expect(await readFile(path)).toEqual(before);}finally{await rm(root,{recursive:true,force:true});}});
