// Generated by scripts/sdk-declarations.mjs; edit the canonical source instead.
/**
 * Resolve the authenticated HTTPS client from the environment through the
 * @hasna/contracts chain. The report names the sources (never values).
 */
/** @param {NotesEnvironment} [env] */
export function resolveNotesClientStore(env?: NotesEnvironment): {
    transport: "http";
    report: import("./types.js").NotesTransportReport;
    httpStore: NotesHttpStore;
};
/**
 * Stable SDK facade over the canonical authenticated HTTPS store.
 *
 * `env` defaults to the live `process.env` — hand it to the resolver AS-IS
 * (#1788) so the ambient Keychain/disk tiers stay on. Callers that pass a
 * custom env object should also pass `keychain: { enabled: true }` through a
 * store built with explicit credentials if they intend the machine Keychain.
 * An explicit `baseUrl` with no `apiKey` throws; it never borrows the ambient
 * fleet credential (#1794).
 */
export class NotesClient {
    /** @param {NotesEnvironment} [env] @param {typeof fetch} [fetchImpl] */
    constructor(env?: NotesEnvironment, fetchImpl?: typeof fetch);
    store: NotesHttpStore;
    /** @returns {Promise<NotesHealth>} */
    health(): Promise<NotesHealth>;
    /** @param {NotesListOptions} [params] @returns {Promise<NotesPage>} */
    list(params?: NotesListOptions): Promise<NotesPage>;
    /** @param {string} id @returns {Promise<Note>} */
    get(id: string): Promise<Note>;
    /** @param {NoteInput} input @returns {Promise<Note>} */
    create(input: NoteInput): Promise<Note>;
    /** @param {string} id @param {NoteUpdate} input @returns {Promise<Note>} */
    update(id: string, input: NoteUpdate): Promise<Note>;
    /** @param {string} id @returns {Promise<NotesDeleteResult>} */
    delete(id: string): Promise<NotesDeleteResult>;
    /** @returns {Promise<NotesExport>} */
    export(): Promise<NotesExport>;
}
export type JsonValue = import("./types.js").JsonValue;
export type NotesTransportReport = import("./types.js").NotesTransportReport;
export type NotesStoreConfiguration = import("./types.js").NotesStoreConfiguration;
export type NotesErrorOptions = import("./types.js").NotesErrorOptions;
export type NotesRequestOptions = import("./types.js").NotesRequestOptions;
export type NotesEnvironment = import("./types.js").NotesEnvironment;
export type Note = import("./types.js").Note;
export type NoteInput = import("./types.js").NoteInput;
export type NoteUpdate = import("./types.js").NoteUpdate;
export type NotesListOptions = import("./types.js").NotesListOptions;
export type NotesPage = import("./types.js").NotesPage;
export type NotesExport = import("./types.js").NotesExport;
export type NotesDeleteResult = import("./types.js").NotesDeleteResult;
export type NotesHealth = import("./types.js").NotesHealth;
import { NotesHttpStore } from '../client/http-store.mjs';
import { NOTES_APP_SLUG } from '../client/transport.mjs';
import { NOTES_API_URL_ENV } from '../client/transport.mjs';
import { NOTES_API_KEY_ENV } from '../client/transport.mjs';
import { NOTES_DATABASE_URL_ENV } from '../client/transport.mjs';
import { NOTES_API_URL_ENV_KEYS } from '../client/transport.mjs';
import { NOTES_API_KEY_ENV_KEYS } from '../client/transport.mjs';
import { NOTES_CLIENT_TRANSPORTS } from '../client/transport.mjs';
import { resolveNotesClientTransport } from '../client/transport.mjs';
import { NotesHttpStoreError } from '../client/http-store.mjs';
import { createNotesHttpStore } from '../client/http-store.mjs';
export { NOTES_APP_SLUG, NOTES_API_URL_ENV, NOTES_API_KEY_ENV, NOTES_DATABASE_URL_ENV, NOTES_API_URL_ENV_KEYS, NOTES_API_KEY_ENV_KEYS, NOTES_CLIENT_TRANSPORTS, resolveNotesClientTransport, NotesHttpStore, NotesHttpStoreError, createNotesHttpStore };
