// Generated by scripts/sdk-declarations.mjs; edit the canonical source instead.
/** The classic personalnotes/v1 HTTP contract used by the root and ./sdk client. */
import type { ClientTransportResolution, CredentialTier, HasnaHttpTransport } from '@hasna/contracts/client';
export type NotesEnvironment = Record<string, string | undefined>;
export type JsonValue = null | boolean | number | string | JsonValue[] | {
    [key: string]: JsonValue;
};
export interface Note {
    id: string;
    tenantId: string;
    clientId: string | null;
    slug: string | null;
    title: string;
    bodyMarkdown: string;
    frontmatterJson: Record<string, JsonValue>;
    folder: string | null;
    labels: string[];
    pinned: boolean;
    archived: boolean;
    revision: number;
    seq: number;
    contentHash: string;
    source: string;
    agentProvenanceJson: Record<string, JsonValue>;
    deletedAt: string | null;
    purgedAt: string | null;
    createdAt: string;
    updatedAt: string;
}
export interface NoteInput {
    clientId?: string;
    slug?: string;
    title?: string;
    bodyMarkdown?: string;
    frontmatterJson?: Record<string, JsonValue>;
    folder?: string | null;
    labels?: string[];
    pinned?: boolean;
    archived?: boolean;
    source?: string;
    agentProvenanceJson?: Record<string, JsonValue>;
}
export type NoteUpdate = Omit<NoteInput, 'clientId'>;
export interface NotesListOptions {
    limit?: number;
    cursor?: string;
    includeDeleted?: boolean;
}
export interface NotesPage {
    data: Note[];
    nextCursor: string | null;
}
export interface NotesExport {
    exportId: string;
    notes: Note[];
}
export interface NotesDeleteResult {
    deleted: true;
    id: string;
    revision: number;
}
export interface NotesHealth {
    status: 'healthy';
    service: string;
    version: string;
}
export interface NotesTransportReport {
    transport: 'http';
    baseUrl: string;
    source: string;
    apiUrlSource: ClientTransportResolution['apiUrlSource'];
    apiKeySource: ClientTransportResolution['apiKeySource'];
    apiKeyTier: CredentialTier;
    api_url_present: boolean;
    api_key_present: boolean;
    scheme: string;
    localFallback: false;
    clientDatabaseDsn: false;
    warning: string | null;
}
export type NotesStoreConfiguration = {
    apiUrl: string;
    apiKey: string;
    transport?: never;
    redactionKey?: never;
} | {
    transport: HasnaHttpTransport;
    redactionKey?: string;
    apiUrl?: never;
    apiKey?: never;
};
export interface NotesRequestOptions {
    body?: unknown;
    query?: Record<string, string>;
}
export interface NotesErrorOptions {
    status?: number;
    code?: string;
    details?: unknown;
}
