// Product-owned Emails Postgres storage utilities.
// Forked from storage-kit 0.4.2 and maintained in this repository.

// Public surface of the Emails Postgres storage utilities.
//
// This is a canonical Postgres storage kit generated by `@hasna/contracts`.
// It is PURE REMOTE per Amendment A1: API-client configuration reads AND writes go directly
// to self-hosted Postgres. There is NO sync engine, NO cache-as-mode, and NO merge
// logic anywhere in this kit.

export * from "./tls.js";
export * from "./query.js";
export * from "./pool.js";
export * from "./migrations.js";
export * from "./health.js";
