import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import {
  handleMcpHttpRequest as harnessHandleMcpHttpRequest,
  healthPayload,
  isHttpMode as harnessIsHttpMode,
  isStdioMode as harnessIsStdioMode,
  resetMcpHttpStateForTests as harnessResetMcpHttpStateForTests,
  resolveMcpHttpPort as harnessResolveMcpHttpPort,
  startBunHttpServer,
} from "./harness.js";

/**
 * open-domains MCP transport/port boilerplate — thin shim over the vendored
 * harness (./harness.js). Public API preserved; hand-rolled
 * transport/port/health removed.
 * Generated by open-mcp/scripts/adopt-harness.ts.
 */

export const MCP_HTTP_HOST = "127.0.0.1";
export const MCP_SERVER_NAME = "domains";
export const DEFAULT_MCP_HTTP_PORT = 8859;

export function isHttpMode(argv: readonly string[] = process.argv): boolean {
  return harnessIsHttpMode(argv);
}
export function isStdioMode(argv: readonly string[] = process.argv): boolean {
  return harnessIsStdioMode(argv);
}
export function resolveMcpHttpPort(
  argv: readonly string[] = process.argv,
  env: NodeJS.ProcessEnv = process.env,
): number {
  return harnessResolveMcpHttpPort({ argv, env, default: DEFAULT_MCP_HTTP_PORT });
}
export function mcpHealthJson(): { status: string; name: string } {
  return healthPayload(MCP_SERVER_NAME);
}
export function handleMcpHttpRequest(
  req: Request,
  buildServer: () => McpServer,
): Promise<Response> {
  return harnessHandleMcpHttpRequest(req, buildServer);
}
export async function startHttpServer(
  buildServer: () => McpServer,
  port: number,
): Promise<{ port: number; stop: () => void }> {
  return startBunHttpServer(buildServer, {
    port,
    host: MCP_HTTP_HOST,
    serviceName: MCP_SERVER_NAME,
  });
}
export function resetMcpHttpStateForTests(): void {
  harnessResetMcpHttpStateForTests();
}
