const FULL_GIT_SHA = /^[0-9a-f]{40}$/;

export function renderBuildShaModule(sha: string, required = false): string {
  if (!sha) {
    if (required) {
      throw new Error("BUILD_SHA is required for this artifact build");
    }

    return [
      "// Generated by scripts/ci/render-build-sha.ts during the image build.",
      "// This generic/local artifact does not claim a source identity.",
      "export const BAKED_BUILD_SHA: string | null = null;",
      "",
    ].join("\n");
  }

  if (!FULL_GIT_SHA.test(sha)) {
    throw new Error("BUILD_SHA must be a full 40-character lowercase Git SHA");
  }

  return [
    "// Generated by scripts/ci/render-build-sha.ts during the image build.",
    "// Runtime configuration must not replace this artifact identity.",
    `export const BAKED_BUILD_SHA: string | null = ${JSON.stringify(sha)};`,
    "",
  ].join("\n");
}

if (import.meta.main) {
  const [sha, outputPath, requireFlag = "0"] = Bun.argv.slice(2);
  if (sha === undefined || !outputPath) {
    console.error("usage: bun run scripts/ci/render-build-sha.ts <git-sha-or-empty> <output-path> [require:0|1]");
    process.exit(2);
  }
  if (requireFlag !== "0" && requireFlag !== "1") {
    throw new Error("require flag must be 0 or 1");
  }

  await Bun.write(outputPath, renderBuildShaModule(sha, requireFlag === "1"));
}
