#!/usr/bin/env bun
/**
 * Generate the typed `/v1` SDK client from the serve OpenAPI document.
 *
 * Source of truth: src/server/openapi.ts (also served at GET /openapi.json).
 * Output: src/sdk/v1.generated.ts — a dependency-free typed fetch client.
 *
 * Usage: bun run scripts/generate-sdk.ts
 */
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { generateSdkFromOpenApi } from "@hasna/contracts/sdk";
import { buildV1OpenApiDocument } from "../src/server/openapi.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const spec = buildV1OpenApiDocument();
const { code, operations, warnings } = generateSdkFromOpenApi(spec as never, {
  className: "RecordingsV1Client",
  apiKeyHeader: "x-api-key",
});

// @hasna/contracts 0.13.1 emits array-aware query serialization natively —
// per-item append, null/undefined items skipped — which is exactly OpenAPI's
// form+explode semantics the 0.8.4-era transform used to add by hand. Assert
// the measured 0.13.1 shape so a future serializer change fails generation
// loudly instead of silently altering request semantics.
const arrayQuerySerialization =
  "        if (value === undefined || value === null) continue;\n" +
  "        if (Array.isArray(value)) {\n" +
  "          for (const item of value) {\n" +
  "            if (item !== undefined && item !== null) url.searchParams.append(key, String(item));\n" +
  "          }\n" +
  "        } else {\n" +
  "          url.searchParams.set(key, String(value));\n" +
  "        }";
if (!code.includes(arrayQuerySerialization)) {
  throw new Error("Generated SDK query serializer changed; update the serializer shape assertion");
}
const compatibleCode = code;

const header =
  "// AUTO-GENERATED by scripts/generate-sdk.ts from src/server/openapi.ts — DO NOT EDIT BY HAND.\n" +
  "// Regenerate: bun run scripts/generate-sdk.ts\n\n";
const outPath = join(root, "src/sdk/v1.generated.ts");
writeFileSync(outPath, header + compatibleCode);

console.log(`Wrote ${outPath}`);
console.log(`Operations: ${operations.map((o) => o.functionName).join(", ")}`);
if (warnings.length) console.log(`Warnings:\n  ${warnings.join("\n  ")}`);
