export const ACCOUNTS_V11_CONTRACT_SHA256 =
  "662842e91a4b58475b92f28eec8caeead4cd7955a485f3d20b16032ab4fa9167" as const;
export const ACCOUNTS_RUNTIME_CONTRACT_SHA256 = ACCOUNTS_V11_CONTRACT_SHA256;
/** @deprecated Slot/online v1 semantics are unchanged, but runtime provenance is v11. */
export const ACCOUNTS_V10_CONTRACT_SHA256 = ACCOUNTS_V11_CONTRACT_SHA256;

export const SLOT_ELIGIBILITY_SCHEMA_VERSION_V1 =
  "accounts.slot-eligibility/v1" as const;
export const SLOT_ELIGIBILITY_SCHEMA_DIGEST_V1 =
  "sha256:b3415ad8bb71951a628f9744b7949f49d794adde55fb965c73e9b4936c691a55" as const;
export const ONLINE_GENERATION_CHECK_RECEIPT_SCHEMA_VERSION_V1 =
  "accounts.online-generation-check-receipt/v1" as const;
export const ONLINE_GENERATION_CHECK_RECEIPT_SCHEMA_DIGEST_V1 =
  "sha256:5061db743dafa19f9ea2e586494f4205e10549ad546ea92fa6fbc8c2e55a4210" as const;
export const ACCOUNTS_EVIDENCE_SIGNER_HISTORY_SCHEMA_VERSION_V2 =
  "accounts.evidence-signer-history/v2" as const;
export const ACCOUNTS_ELIGIBILITY_REQUEST_SCHEMA_VERSION_V1 =
  "accounts.eligibility-request.v1" as const;

export const ACCOUNTS_V10_MAX_CLOCK_SKEW_MS = 5_000;
export const SLOT_ELIGIBILITY_MAX_LIFETIME_MS = 30_000;
export const SLOT_ELIGIBILITY_MAX_AGE_MS = 30_000;
export const ONLINE_GENERATION_CHECK_MAX_LIFETIME_MS = 120_000;
export const ONLINE_GENERATION_CHECK_MAX_AGE_MS = 60_000;

export const SLOT_ELIGIBILITY_REASON_CODES_V1 = [
  "ACCESS_METHOD_NOT_READY",
  "ACCOUNT_NOT_ACTIVE",
  "ATTESTATION_STALE",
  "CAPACITY_EVIDENCE_STALE",
  "CAPACITY_POOL_NOT_ACTIVE",
  "CAPSULE_NOT_READY",
  "CAPSULE_OWNER_MISMATCH",
  "CAPSULE_PLACEMENT_INVALID",
  "CAPSULE_REQUIRED",
  "CREDENTIAL_BINDING_EXPIRED",
  "CREDENTIAL_BINDING_NOT_ACTIVE",
  "CREDENTIAL_BINDING_REQUIRED",
  "CREDENTIAL_BINDING_RETIRING",
  "CURRENT_DENY",
  "DATA_CLASSIFICATION_NOT_ALLOWED",
  "DEPENDENCY_UNAVAILABLE",
  "DESTINATION_POLICY_NOT_ALLOWED",
  "ENTITLEMENT_NOT_ACTIVE",
  "GENERATION_MISMATCH",
  "HEALTH_NOT_HEALTHY",
  "HEALTH_STALE",
  "INVALID_ACCESS_TARGET",
  "MODEL_NOT_ALLOWED",
  "OPERATION_NOT_ALLOWED",
  "POLICY_DIGEST_MISMATCH",
  "POLICY_EVIDENCE_STALE",
  "RECOVERY_HOLD",
  "TERMS_NOT_ALLOWED",
  "TERMS_STALE",
] as const;

export const ONLINE_GENERATION_CHECK_REASON_CODES_V1 = [
  ...SLOT_ELIGIBILITY_REASON_CODES_V1,
  "USE_LIMIT_REACHED",
] as const;

export const SLOT_COMMON_FIELDS_V1 = [
  "schema_version",
  "schema_digest",
  "evidence_id",
  "issuer",
  "issuer_incarnation",
  "catalog_incarnation",
  "audience",
  "key_id",
  "nonce",
  "account_lane_id",
  "eligibility_request_digest",
  "eligible",
  "reason_codes",
  "issued_at",
  "expires_at",
  "signature",
] as const;

export const SLOT_RESOLVED_FIELDS_V1 = [
  "recovery_frontier_sequence",
  "recovery_frontier_hash",
  "accounts_build_digest",
  "accounts_attestation_issuer_ref",
  "accounts_attestation_digest",
  "accounts_attested_at",
  "accounts_attestation_expires_at",
  "effect_namespace_id",
  "provider_account_id",
  "entitlement_id",
  "capacity_pool_id",
  "capacity_domain_ref",
  "provider_key",
  "provider_subject_ref",
  "owner_ref",
  "identity_realm",
  "access_transport",
  "allowed_channel_class",
  "access_target",
  "serialization_key",
  "serialization_key_digest",
  "max_concurrency",
  "capacity_evidence_ref",
  "capacity_evidence_issuer_ref",
  "capacity_evidence_version",
  "capacity_evidence_digest",
  "capacity_evidence_issued_at",
  "capacity_evidence_expires_at",
  "capacity_evidence_generation",
  "capacity_policy_version",
  "capacity_generation",
  "deny_generation",
  "deny_state",
  "credential_family_id",
  "credential_generation",
  "record_revision_set",
  "accounts_revision_set_digest",
  "ownership_evidence_issuer_ref",
  "ownership_evidence_version",
  "ownership_evidence_digest",
  "ownership_evidence_issued_at",
  "ownership_evidence_expires_at",
  "ownership_generation",
  "terms_evidence_issuer_ref",
  "terms_evidence_version",
  "terms_evidence_digest",
  "terms_evidence_issued_at",
  "terms_evidence_expires_at",
  "execution_policy_evidence_issuer_ref",
  "execution_policy_evidence_version",
  "execution_policy_evidence_digest",
  "execution_policy_evidence_issued_at",
  "execution_policy_evidence_expires_at",
  "data_policy_evidence_issuer_ref",
  "data_policy_evidence_version",
  "data_policy_evidence_digest",
  "data_policy_evidence_issued_at",
  "data_policy_evidence_expires_at",
  "isolation_policy_evidence_issuer_ref",
  "isolation_policy_evidence_version",
  "isolation_policy_evidence_digest",
  "isolation_policy_evidence_issued_at",
  "isolation_policy_evidence_expires_at",
  "health_evidence_issuer_ref",
  "health_evidence_version",
  "health_evidence_digest",
  "health_evidence_issued_at",
  "health_evidence_expires_at",
] as const;

export const SLOT_BROKERED_FIELDS_V1 = [
  ...SLOT_COMMON_FIELDS_V1,
  ...SLOT_RESOLVED_FIELDS_V1,
  "binding_policy_digest",
] as const;
export const SLOT_NATIVE_FIELDS_V1 = [
  ...SLOT_COMMON_FIELDS_V1,
  ...SLOT_RESOLVED_FIELDS_V1,
  "capsule_attestation_issuer_ref",
  "capsule_attestation_version",
  "capsule_attestation_digest",
  "capsule_attestation_issued_at",
  "capsule_attestation_expires_at",
] as const;
export const SLOT_UNRESOLVED_FIELDS_V1 = [
  ...SLOT_COMMON_FIELDS_V1,
  "rejection_stage",
] as const;

export const ONLINE_BASE_FIELDS_V1 = [
  "schema_version",
  "schema_digest",
  "receipt_id",
  "issuer",
  "issuer_incarnation",
  "key_id",
  "audience",
  "nonce",
  "issued_at",
  "not_before",
  "expires_at",
  "signature",
  "capability_id",
  "capability_digest",
  "authority_epoch",
  "route_lineage_id",
  "route_id",
  "route_epoch",
  "run_id",
  "attempt_id",
  "attempt_lease_id",
  "lease_epoch",
  "resource_lease_id",
  "resource_id",
  "resource_lifecycle_generation",
  "lease_expires_at",
  "operation_id",
  "operation_digest",
  "operation_execution_epoch",
  "operation_execution_expires_at",
  "subject",
  "actor_principal",
  "lease_holder_principal",
  "operation_executor_principal",
  "sender_key_thumbprint",
  "effect_namespace_id",
  "provider_account_id",
  "account_lane_id",
  "capacity_pool_id",
  "capacity_domain_ref",
  "serialization_key",
  "serialization_key_digest",
  "access_transport",
  "credential_family_id",
  "allowed",
  "deny_state",
  "reason_codes",
  "capacity_generation",
  "deny_generation",
  "credential_generation",
  "accounts_revision_set_digest",
  "allowed_channel_class",
  "slot_eligibility_digest",
  "approval_mode",
  "approval_binding_digest",
  "policy_digest",
  "canonical_request_digest",
  "provider_destination_policy",
  "provider_destination_policy_digest",
  "sender_constraint_confirmation",
  "max_uses",
  "use_count",
  "catalog_incarnation",
  "recovery_frontier_sequence",
  "recovery_frontier_hash",
] as const;
export const ONLINE_BROKERED_FIELDS_V1 = [
  ...ONLINE_BASE_FIELDS_V1,
  "credential_binding_id",
  "broker_ref",
] as const;
export const ONLINE_NATIVE_FIELDS_V1 = [
  ...ONLINE_BASE_FIELDS_V1,
  "auth_capsule_id",
  "canonical_node_id",
  "node_key_thumbprint",
  "node_generation",
  "placement_generation",
  "auth_generation",
  "auth_state_revision",
] as const;

export const PROVIDER_DESTINATION_POLICY_FIELDS_V1 = [
  "scheme",
  "normalized_host",
  "port",
  "operation_path",
  "model",
  "request_body_digest",
  "tls_server_name",
  "resolved_address_class",
  "egress_policy_digest",
] as const;

export const ONLINE_GENERATION_CONTEXT_FIELDS_V1 = [
  "authenticated_actor_principal",
  "account_lane_id",
  "capability_id",
  "capability_digest",
  "nonce",
  "authority_epoch",
  "route_lineage_id",
  "route_id",
  "route_epoch",
  "run_id",
  "attempt_id",
  "attempt_lease_id",
  "lease_epoch",
  "resource_lease_id",
  "resource_id",
  "resource_lifecycle_generation",
  "lease_expires_at",
  "operation_id",
  "operation_digest",
  "operation_execution_epoch",
  "operation_execution_expires_at",
  "subject",
  "actor_principal",
  "lease_holder_principal",
  "operation_executor_principal",
  "sender_key_thumbprint",
  "approval_mode",
  "approval_binding_digest",
  "policy_digest",
  "canonical_request_digest",
  "provider_destination_policy",
  "provider_destination_policy_digest",
  "sender_constraint_confirmation",
  "max_uses",
] as const;
