// OpenAPI 3.1 document for projects-serve. Single source of truth for the
// served /openapi.json and for the generated SDK (scripts/generate-sdk.ts uses
// @hasna/contracts/sdk `generateSdkFromOpenApi` on this exact object).

import { WORKSPACE_LIST_DEFAULT_LIMIT, WORKSPACE_LIST_MAX_LIMIT } from "./pg-store.js";
import { COMPLETE_STABLE_PROJECT_ID_PATTERN } from "../lib/guarded-project-mutation.js";
import { COMPLETE_EXTERNAL_UUID_PATTERN } from "../lib/project-resource-links.js";

export function buildOpenApiSpec(version: string): Record<string, unknown> {
  const ID_PARAM = {
    name: "id",
    in: "path",
    required: true,
    description: "Resource id or slug",
    schema: { type: "string" },
  } as const;
  const EXACT_PROJECT_ID_PARAM = {
    name: "id",
    in: "path",
    required: true,
    description: "Complete stable project id beginning with wks_; slugs and partial ids are refused",
    schema: { type: "string", pattern: COMPLETE_STABLE_PROJECT_ID_PATTERN },
  } as const;

  const ref = (name: string) => ({ $ref: `#/components/schemas/${name}` });
  const jsonBody = (schemaName: string, required = true) => ({
    required,
    content: { "application/json": { schema: ref(schemaName) } },
  });
  const jsonResp = (schemaName: string, description = "OK") => ({
    description,
    content: { "application/json": { schema: ref(schemaName) } },
  });
  const projectResourceLinkInputBranch = (
    authority: string,
    sourcePackage: string,
    targetKinds: readonly string[],
    locator: Record<string, unknown> = ref("ProjectResourcePortableLocator"),
    labels: Record<string, unknown> = ref("ProjectResourceLinkLabels"),
  ) => ({
    type: "object",
    additionalProperties: false,
    properties: {
      authority: { type: "string", enum: [authority] },
      service_instance: { type: "string" },
      source_package: { type: "string", enum: [sourcePackage] },
      target_kind: { type: "string", enum: targetKinds },
      locator,
      scope: { type: "string", enum: ["resource", "collection"] },
      labels,
    },
    required: ["authority", "service_instance", "source_package", "target_kind", "locator", "scope"],
  });
  const projectResourceLinkBranch = (
    authority: string,
    sourcePackage: string,
    targetKinds: readonly string[],
    locator: Record<string, unknown> = ref("ProjectResourcePortableLocator"),
    labels: Record<string, unknown> = ref("ProjectResourceLinkLabels"),
  ) => {
    const input = projectResourceLinkInputBranch(
      authority,
      sourcePackage,
      targetKinds,
      locator,
      labels,
    );
    return {
      ...input,
      properties: {
        ...input.properties,
        id: { type: "string" },
        project_id: { type: "string" },
        labels,
        created_at: { type: "string" },
        updated_at: { type: "string" },
      },
      required: [...input.required, "id", "project_id", "labels", "created_at", "updated_at"],
    };
  };

  return {
    openapi: "3.1.0",
    info: {
      title: "Projects API",
      version,
      description:
        "Self-hosted HTTP API for @hasna/projects (workspace/project management). Amendment A1 pure-remote: reads and writes go directly to cloud Postgres. All /v1 routes require an API key (x-api-key or Authorization: Bearer).",
    },
    servers: [{ url: "/" }],
    components: {
      securitySchemes: {
        apiKey: { type: "apiKey", in: "header", name: "x-api-key" },
      },
      schemas: {
        Root: {
          type: "object",
          properties: {
            id: { type: "string" },
            slug: { type: "string" },
            name: { type: "string" },
            base_path: { type: "string" },
            tags: { type: "array", items: { type: "string" } },
            default_kind: { type: "string", nullable: true },
            repo_visibility: { type: "string", nullable: true },
            allowed_recipes: { type: "array", items: { type: "string" } },
            allowed_agents: { type: "array", items: { type: "string" } },
            metadata: { type: "object", additionalProperties: true },
            created_at: { type: "string" },
            updated_at: { type: "string" },
          },
          required: ["id", "slug", "name", "base_path"],
        },
        CreateRoot: {
          type: "object",
          properties: {
            name: { type: "string" },
            base_path: { type: "string" },
            slug: { type: "string" },
            tags: { type: "array", items: { type: "string" } },
            default_kind: { type: "string" },
            repo_visibility: { type: "string", enum: ["public", "private"] },
            github_org: { type: "string" },
            metadata: { type: "object", additionalProperties: true },
          },
          required: ["name", "base_path"],
        },
        UpdateRoot: {
          type: "object",
          properties: {
            name: { type: "string" },
            base_path: { type: "string" },
            slug: { type: "string" },
            tags: { type: "array", items: { type: "string" } },
            default_kind: { type: "string" },
            repo_visibility: { type: "string", enum: ["public", "private"] },
            github_org: { type: "string" },
            metadata: { type: "object", additionalProperties: true },
          },
        },
        Agent: {
          type: "object",
          properties: {
            id: { type: "string" },
            slug: { type: "string" },
            name: { type: "string" },
            kind: { type: "string", enum: ["human", "ai", "service", "cli"] },
            provider: { type: "string", nullable: true },
            model: { type: "string", nullable: true },
            role: { type: "string", nullable: true },
            permissions: { type: "array", items: { type: "string" } },
            metadata: { type: "object", additionalProperties: true },
            created_at: { type: "string" },
            updated_at: { type: "string" },
          },
          required: ["id", "slug", "name", "kind"],
        },
        CreateAgent: {
          type: "object",
          properties: {
            name: { type: "string" },
            kind: { type: "string", enum: ["human", "ai", "service", "cli"] },
            slug: { type: "string" },
            provider: { type: "string" },
            model: { type: "string" },
            role: { type: "string" },
            permissions: { type: "array", items: { type: "string" } },
            metadata: { type: "object", additionalProperties: true },
          },
          required: ["name"],
        },
        Recipe: {
          type: "object",
          properties: {
            id: { type: "string" },
            slug: { type: "string" },
            name: { type: "string" },
            description: { type: "string", nullable: true },
            kind: { type: "string", nullable: true },
            version: { type: "integer" },
            steps: { type: "array", items: { type: "object", additionalProperties: true } },
            default_tags: { type: "array", items: { type: "string" } },
            metadata: { type: "object", additionalProperties: true },
            created_at: { type: "string" },
            updated_at: { type: "string" },
          },
          required: ["id", "slug", "name"],
        },
        CreateRecipe: {
          type: "object",
          properties: {
            name: { type: "string" },
            slug: { type: "string" },
            description: { type: "string" },
            kind: { type: "string" },
            version: { type: "integer" },
            steps: { type: "array", items: { type: "object", additionalProperties: true } },
            default_tags: { type: "array", items: { type: "string" } },
            metadata: { type: "object", additionalProperties: true },
          },
          required: ["name"],
        },
        Workspace: {
          type: "object",
          properties: {
            id: { type: "string" },
            slug: { type: "string" },
            name: { type: "string" },
            description: { type: "string", nullable: true },
            kind: { type: "string" },
            status: { type: "string", enum: ["active", "archived", "deleted"] },
            root_id: { type: "string", nullable: true },
            recipe_id: { type: "string", nullable: true },
            canonical_machine: { type: "string", nullable: true },
            primary_path: { type: "string", nullable: true },
            git_remote: { type: "string", nullable: true },
            s3_bucket: { type: "string", nullable: true },
            s3_prefix: { type: "string", nullable: true },
            tags: { type: "array", items: { type: "string" } },
            integrations: { type: "object", additionalProperties: { type: "string" } },
            metadata: { type: "object", additionalProperties: true },
            last_opened_at: { type: "string", nullable: true },
            created_at: { type: "string" },
            updated_at: { type: "string" },
            synced_at: { type: "string", nullable: true },
          },
          required: [
            "id", "slug", "name", "kind", "status",
            "s3_bucket", "s3_prefix", "last_opened_at", "synced_at",
          ],
        },
        CreateWorkspace: {
          type: "object",
          properties: {
            name: { type: "string" },
            slug: { type: "string" },
            description: { type: "string" },
            kind: { type: "string" },
            root_id: { type: "string" },
            recipe_id: { type: "string" },
            primary_path: { type: "string" },
            git_remote: { type: "string" },
            tags: { type: "array", items: { type: "string" } },
            integrations: { type: "object", additionalProperties: true },
            metadata: { type: "object", additionalProperties: true },
            agent_id: { type: "string" },
          },
          required: ["name"],
        },
        UpdateWorkspace: {
          type: "object",
          properties: {
            name: { type: "string" },
            slug: { type: "string" },
            description: { type: "string", nullable: true },
            kind: { type: "string" },
            status: { type: "string", enum: ["active", "archived", "deleted"] },
            root_id: { type: "string", nullable: true },
            recipe_id: { type: "string", nullable: true },
            canonical_machine: { type: "string", nullable: true },
            primary_path: { type: "string", nullable: true },
            git_remote: { type: "string", nullable: true },
            tags: { type: "array", items: { type: "string" } },
            integrations: { type: "object", additionalProperties: true },
            metadata: { type: "object", additionalProperties: true },
            last_opened_at: { type: "string", nullable: true },
            agent_id: { type: "string" },
          },
        },
        WorkspaceEvent: {
          type: "object",
          properties: {
            id: { type: "string" },
            workspace_id: { type: "string", nullable: true },
            agent_id: { type: "string", nullable: true },
            event_type: { type: "string" },
            source: { type: "string" },
            metadata: { type: "object", additionalProperties: true },
            created_at: { type: "string" },
          },
          required: ["id", "event_type", "source"],
        },
        WorkspaceList: {
          type: "object",
          description:
            "A single page of projects. `count` is the page length; `total` is how many rows match the filter. When `has_more` is true the caller must request the next page with `offset` — a full page is otherwise indistinguishable from the last one.",
          properties: {
            workspaces: { type: "array", items: ref("Workspace") },
            count: { type: "integer", description: "Rows in this page." },
            total: { type: "integer", description: "Rows matching the filter, ignoring limit/offset." },
            offset: { type: "integer", description: "Offset this page starts at." },
            limit: { type: "integer", description: "Effective per-page limit after server clamping." },
            has_more: { type: "boolean", description: "More rows exist past this page." },
            complete: { type: "boolean", description: "True only when this page proves the complete matching population." },
          },
          required: ["workspaces", "count", "total", "offset", "limit", "has_more", "complete"],
        },
        GuardedResponseControl: {
          type: "object",
          properties: {
            response_byte_limit: { type: "integer", minimum: 1 },
            time_budget_ms: { type: "integer", minimum: 1 },
            response_bytes: { type: "integer", minimum: 1 },
            elapsed_ms: { type: "integer", minimum: 0 },
            complete: { type: "boolean", const: true },
            truncated: { type: "boolean", const: false },
          },
          required: [
            "response_byte_limit",
            "time_budget_ms",
            "response_bytes",
            "elapsed_ms",
            "complete",
            "truncated",
          ],
        },
        GuardedProjectRead: {
          type: "object",
          properties: {
            ok: { type: "boolean", const: true },
            project_id: { type: "string" },
            project: ref("Workspace"),
            current_revision: { type: "string" },
            resource_links: { type: "array", items: ref("ProjectResourceLink") },
            resource_link_count: { type: "integer", minimum: 0 },
            resource_link_max_items: { type: "integer", minimum: 1 },
            resource_link_collection_digest: { type: "string" },
            response_control: ref("GuardedResponseControl"),
          },
          required: [
            "ok", "project_id", "project", "current_revision", "resource_links",
            "resource_link_count", "resource_link_max_items", "resource_link_collection_digest",
            "response_control",
          ],
        },
        ProjectResourceLinkLabels: {
          type: "object",
          additionalProperties: false,
          properties: {
            name: { type: "string" },
            channel_name: { type: "string" },
            path: { type: "string" },
            tags: { type: "array", items: { type: "string" } },
          },
        },
        ProjectResourceConversationsChannelLabels: {
          type: "object",
          additionalProperties: false,
          properties: {
            name: { type: "string" },
            channel_name: { type: "string" },
            path: { type: "string" },
            tags: { type: "array", items: { type: "string" } },
          },
          required: ["channel_name"],
        },
        ProjectResourceExternalUuidLocator: {
          type: "object",
          additionalProperties: false,
          properties: {
            kind: { type: "string", enum: ["external_uuid"] },
            value: { type: "string", pattern: COMPLETE_EXTERNAL_UUID_PATTERN },
          },
          required: ["kind", "value"],
        },
        ProjectResourceCanonicalUriLocator: {
          type: "object",
          additionalProperties: false,
          properties: {
            kind: { type: "string", enum: ["canonical_uri"] },
            value: { type: "string" },
          },
          required: ["kind", "value"],
        },
        ProjectResourceConversationsChannelLocator: {
          type: "object",
          additionalProperties: false,
          properties: {
            kind: { type: "string", enum: ["conversations_channel_id"] },
            value: { type: "string", pattern: "^chn_[0-9a-f]{32}$" },
          },
          required: ["kind", "value"],
        },
        ProjectResourceLinkLocator: {
          oneOf: [
            ref("ProjectResourceExternalUuidLocator"),
            ref("ProjectResourceCanonicalUriLocator"),
            ref("ProjectResourceConversationsChannelLocator"),
          ],
        },
        ProjectResourcePortableLocator: {
          oneOf: [
            ref("ProjectResourceExternalUuidLocator"),
            ref("ProjectResourceCanonicalUriLocator"),
          ],
        },
        ProjectResourceConversationsChannelLinkLocator: {
          oneOf: [
            ref("ProjectResourceExternalUuidLocator"),
            ref("ProjectResourceConversationsChannelLocator"),
          ],
        },
        ProjectResourceLinkInput: {
          oneOf: [
            projectResourceLinkInputBranch("todos", "@hasna/todos", ["project", "task_list", "plan"]),
            projectResourceLinkInputBranch(
              "todos",
              "@hasna/todos",
              ["task"],
              ref("ProjectResourceExternalUuidLocator"),
            ),
            projectResourceLinkInputBranch("conversations", "@hasna/conversations", ["project"]),
            projectResourceLinkInputBranch(
              "conversations",
              "@hasna/conversations",
              ["channel"],
              ref("ProjectResourceConversationsChannelLinkLocator"),
              ref("ProjectResourceConversationsChannelLabels"),
            ),
            projectResourceLinkInputBranch("knowledge", "@hasna/knowledge", ["collection", "item"]),
            projectResourceLinkInputBranch("mementos", "@hasna/mementos", ["project", "item"]),
            projectResourceLinkInputBranch("orgs", "@hasna/orgs", ["org", "project"]),
            projectResourceLinkInputBranch(
              "contacts",
              "@hasna/contacts",
              ["contact"],
              ref("ProjectResourceExternalUuidLocator"),
            ),
          ],
        },
        ProjectResourceLink: {
          oneOf: [
            projectResourceLinkBranch("todos", "@hasna/todos", ["project", "task_list", "plan"]),
            projectResourceLinkBranch(
              "todos",
              "@hasna/todos",
              ["task"],
              ref("ProjectResourceExternalUuidLocator"),
            ),
            projectResourceLinkBranch("conversations", "@hasna/conversations", ["project"]),
            projectResourceLinkBranch(
              "conversations",
              "@hasna/conversations",
              ["channel"],
              ref("ProjectResourceConversationsChannelLinkLocator"),
              ref("ProjectResourceConversationsChannelLabels"),
            ),
            projectResourceLinkBranch("knowledge", "@hasna/knowledge", ["collection", "item"]),
            projectResourceLinkBranch("mementos", "@hasna/mementos", ["project", "item"]),
            projectResourceLinkBranch("orgs", "@hasna/orgs", ["org", "project"]),
            projectResourceLinkBranch(
              "contacts",
              "@hasna/contacts",
              ["contact"],
              ref("ProjectResourceExternalUuidLocator"),
            ),
          ],
        },
        ProjectResourceLinkCollectionV1: {
          type: "object",
          additionalProperties: false,
          properties: {
            schema: { type: "string", enum: ["hasna.project_resource_link_collection.v1"] },
            project_id: { type: "string" },
            current_revision: { type: "string" },
            links: { type: "array", items: ref("ProjectResourceLink") },
            link_count: { type: "integer", minimum: 0 },
            max_items: { type: "integer", minimum: 1 },
            collection_digest: { type: "string" },
            complete: { type: "boolean", enum: [true] },
            truncated: { type: "boolean", enum: [false] },
          },
          required: [
            "schema", "project_id", "current_revision", "links", "link_count",
            "max_items", "collection_digest", "complete", "truncated",
          ],
        },
        ProjectResourceLinkSnapshot: {
          type: "object",
          properties: {
            project: ref("Workspace"),
            links: { type: "array", items: ref("ProjectResourceLink") },
            collection_digest: { type: "string" },
          },
          required: ["project", "links", "collection_digest"],
        },
        ProjectResourceLinkRead: {
          type: "object",
          properties: {
            ok: { type: "boolean", const: true },
            project_id: { type: "string" },
            project: ref("Workspace"),
            current_revision: { type: "string" },
            links: { type: "array", items: ref("ProjectResourceLink") },
            link_count: { type: "integer", minimum: 0 },
            max_items: { type: "integer", minimum: 1 },
            collection_digest: { type: "string" },
            complete: { type: "boolean", const: true },
            truncated: { type: "boolean", const: false },
            contract: ref("ProjectResourceLinkCollectionV1"),
            response_control: ref("GuardedResponseControl"),
          },
          required: [
            "ok", "project_id", "project", "current_revision", "links", "link_count",
            "max_items", "collection_digest", "complete", "truncated", "contract", "response_control",
          ],
        },
        ProjectResourceLinkMutationRequest: {
          type: "object",
          properties: {
            operation_id: { type: "string" },
            step_id: { type: "string" },
            mode: { type: "string", enum: ["add", "reconcile"] },
            expected_revision: { type: "string" },
            links: { type: "array", items: ref("ProjectResourceLinkInput") },
            integrations: { type: "object", additionalProperties: true },
            max_items: { type: "integer", minimum: 1 },
            dry_run: { type: "boolean" },
            agent_id: { type: "string" },
            source: { type: "string" },
            command: { type: "string" },
            response_byte_limit: { type: "integer", minimum: 1 },
            time_budget_ms: { type: "integer", minimum: 1 },
          },
          required: [
            "operation_id", "step_id", "expected_revision", "links",
            "response_byte_limit", "time_budget_ms",
          ],
        },
        ProjectResourceLinkMutationResult: {
          type: "object",
          properties: {
            ok: { type: "boolean" },
            dry_run: { type: "boolean" },
            outcome: { type: "string", enum: ["accepted", "duplicate_of_accepted", "terminal_nonacceptance", "planned"] },
            mode: { type: "string", enum: ["add", "reconcile"] },
            idempotency_key: { type: "string" },
            request_digest: { type: "string" },
            precondition_digest: { type: "string" },
            project_id: { type: "string" },
            expected_revision: { type: "string" },
            current_revision: { type: "string" },
            before: ref("ProjectResourceLinkSnapshot"),
            after: { anyOf: [ref("ProjectResourceLinkSnapshot"), { type: "null" }] },
            receipt: { anyOf: [ref("GuardedProjectMutationReceipt"), { type: "null" }] },
            response_control: ref("GuardedResponseControl"),
          },
          required: [
            "ok", "dry_run", "outcome", "mode", "idempotency_key", "request_digest",
            "precondition_digest", "project_id", "expected_revision", "current_revision",
            "before", "after", "receipt", "response_control",
          ],
        },
        WorkspaceLocation: {
          type: "object",
          additionalProperties: false,
          properties: {
            id: { type: "string" },
            workspace_id: { type: "string" },
            path: { type: "string" },
            machine_id: { type: "string" },
            label: { type: "string" },
            kind: { type: "string" },
            is_primary: { type: "boolean" },
            exists_at_create: { type: "boolean" },
            metadata: { type: "object", additionalProperties: true },
            created_at: { type: "string" },
          },
          required: [
            "id", "workspace_id", "path", "machine_id", "label", "kind",
            "is_primary", "exists_at_create", "metadata", "created_at",
          ],
        },
        AddWorkspaceLocation: {
          type: "object",
          additionalProperties: false,
          properties: {
            path: { type: "string" },
            machine_id: { type: "string" },
            label: { type: "string" },
            kind: { type: "string" },
            is_primary: { type: "boolean" },
            metadata: { type: "object", additionalProperties: true },
          },
          required: ["path"],
        },
        WorkspaceAgentAssignment: {
          type: "object",
          additionalProperties: false,
          properties: {
            id: { type: "string" },
            workspace_id: { type: "string" },
            agent_id: { type: "string" },
            role: { type: "string" },
            assigned_by: { type: "string", nullable: true },
            metadata: { type: "object", additionalProperties: true },
            created_at: { type: "string" },
            agent: ref("Agent"),
          },
          required: ["id", "workspace_id", "agent_id", "role", "metadata", "created_at"],
        },
        AssignWorkspaceAgent: {
          type: "object",
          additionalProperties: false,
          properties: {
            agent_id: { type: "string" },
            role: { type: "string" },
            assigned_by: { type: "string" },
            metadata: { type: "object", additionalProperties: true },
          },
          required: ["agent_id"],
        },
        WorkspaceLock: {
          type: "object",
          additionalProperties: false,
          properties: {
            id: { type: "string" },
            lock_key: { type: "string" },
            workspace_id: { type: "string", nullable: true },
            agent_id: { type: "string", nullable: true },
            reason: { type: "string", nullable: true },
            created_at: { type: "string" },
            expires_at: { type: "string", nullable: true },
          },
          required: ["id", "lock_key", "created_at"],
        },
        AcquireWorkspaceLock: {
          type: "object",
          additionalProperties: false,
          properties: {
            lock_key: { type: "string" },
            workspace_id: { type: "string" },
            agent_id: { type: "string" },
            reason: { type: "string" },
            ttl_seconds: { type: "integer" },
          },
          required: ["lock_key"],
        },
        ProjectQuarantineSnapshot: {
          type: "object",
          additionalProperties: false,
          properties: {
            project: ref("Workspace"),
            project_digest: { type: "string" },
            resource_links: { type: "array", items: ref("ProjectResourceLink") },
            resource_link_collection_digest: { type: "string" },
            workspace_locations: { type: "array", items: ref("WorkspaceLocation") },
            workspace_location_collection_digest: { type: "string" },
          },
          required: [
            "project", "project_digest", "resource_links", "resource_link_collection_digest",
            "workspace_locations", "workspace_location_collection_digest",
          ],
        },
        ProjectQuarantineRead: {
          type: "object",
          additionalProperties: false,
          properties: {
            ok: { type: "boolean", const: true },
            project_id: { type: "string" },
            current_revision: { type: "string" },
            snapshot: ref("ProjectQuarantineSnapshot"),
            resource_link_count: { type: "integer", minimum: 0 },
            workspace_location_count: { type: "integer", minimum: 0 },
            complete: { type: "boolean", const: true },
            truncated: { type: "boolean", const: false },
            response_control: ref("GuardedResponseControl"),
          },
          required: [
            "ok", "project_id", "current_revision", "snapshot", "resource_link_count",
            "workspace_location_count", "complete", "truncated", "response_control",
          ],
        },
        ProjectQuarantineRequest: {
          type: "object",
          additionalProperties: false,
          properties: {
            operation_id: { type: "string" },
            step_id: { type: "string" },
            expected_revision: { type: "string" },
            expected_project_digest: { type: "string" },
            expected_resource_link_collection_digest: { type: "string" },
            expected_resource_link_ids: { type: "array", items: { type: "string" } },
            resource_link_max_items: { type: "integer", minimum: 1 },
            expected_workspace_location_collection_digest: { type: "string" },
            expected_workspace_location_ids: { type: "array", items: { type: "string" } },
            workspace_location_max_items: { type: "integer", minimum: 1 },
            quarantine_name: { type: "string", minLength: 1 },
            quarantine_slug: { type: "string", pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$" },
            dry_run: { type: "boolean" },
            agent_id: { type: "string" },
            source: { type: "string" },
            command: { type: "string" },
            response_byte_limit: { type: "integer", minimum: 1 },
            time_budget_ms: { type: "integer", minimum: 1 },
          },
          required: [
            "operation_id", "step_id", "expected_revision", "expected_project_digest",
            "expected_resource_link_collection_digest", "expected_resource_link_ids",
            "resource_link_max_items", "expected_workspace_location_collection_digest",
            "expected_workspace_location_ids", "workspace_location_max_items",
            "quarantine_name", "quarantine_slug", "response_byte_limit", "time_budget_ms",
          ],
        },
        ProjectQuarantineRollbackRequest: {
          type: "object",
          additionalProperties: false,
          properties: {
            operation_id: { type: "string" },
            step_id: { type: "string" },
            accepted_receipt_id: { type: "string" },
            expected_current_revision: { type: "string" },
            resource_link_max_items: { type: "integer", minimum: 1 },
            workspace_location_max_items: { type: "integer", minimum: 1 },
            agent_id: { type: "string" },
            source: { type: "string" },
            command: { type: "string" },
            response_byte_limit: { type: "integer", minimum: 1 },
            time_budget_ms: { type: "integer", minimum: 1 },
          },
          required: [
            "operation_id", "step_id", "accepted_receipt_id", "expected_current_revision",
            "resource_link_max_items", "workspace_location_max_items",
            "response_byte_limit", "time_budget_ms",
          ],
        },
        ProjectQuarantineResult: {
          type: "object",
          additionalProperties: false,
          properties: {
            ok: { type: "boolean" },
            dry_run: { type: "boolean" },
            outcome: { type: "string", enum: ["accepted", "duplicate_of_accepted", "terminal_nonacceptance", "planned"] },
            idempotency_key: { type: "string" },
            request_digest: { type: "string" },
            precondition_digest: { type: "string" },
            project_id: { type: "string" },
            expected_revision: { type: "string" },
            current_revision: { type: "string" },
            before: ref("ProjectQuarantineSnapshot"),
            after: { anyOf: [ref("ProjectQuarantineSnapshot"), { type: "null" }] },
            receipt: { anyOf: [ref("GuardedProjectMutationReceipt"), { type: "null" }] },
            rollback: {
              anyOf: [
                {
                  type: "object",
                  additionalProperties: false,
                  properties: {
                    accepted_receipt_id: { type: "string" },
                    expected_current_revision: { type: "string" },
                  },
                  required: ["accepted_receipt_id", "expected_current_revision"],
                },
                { type: "null" },
              ],
            },
            response_control: ref("GuardedResponseControl"),
          },
          required: [
            "ok", "dry_run", "outcome", "idempotency_key", "request_digest",
            "precondition_digest", "project_id", "expected_revision", "current_revision",
            "before", "after", "receipt", "rollback", "response_control",
          ],
        },
        ContactProjectMembershipSnapshot: {
          type: "object",
          additionalProperties: false,
          properties: {
            contact_id: { type: "string" },
            project_id: { type: "string" },
            linked: { type: "boolean" },
            version: { type: "string" },
          },
          required: ["contact_id", "project_id", "linked", "version"],
        },
        ProjectContactLinkEvidence: {
          type: "object",
          additionalProperties: false,
          properties: {
            system: { type: "string", enum: ["contacts", "projects"] },
            step_id: { type: "string" },
            outcome: { type: "string" },
            receipt_id: { type: ["string", "null"] },
            compensated: { type: "boolean" },
          },
          required: ["system", "step_id", "outcome", "receipt_id", "compensated"],
        },
        ProjectContactLinkMutationRequest: {
          type: "object",
          additionalProperties: false,
          properties: {
            operation_id: { type: "string" },
            labels: ref("ProjectResourceLinkLabels"),
            max_items: { type: "integer", minimum: 1 },
            response_byte_limit: { type: "integer", minimum: 1 },
            time_budget_ms: { type: "integer", minimum: 1 },
          },
          required: ["operation_id", "max_items", "response_byte_limit", "time_budget_ms"],
        },
        ProjectContactLinkMutationResult: {
          type: "object",
          additionalProperties: false,
          properties: {
            ok: { type: "boolean", const: true },
            outcome: { type: "string", enum: ["accepted", "duplicate_of_accepted"] },
            authority: { type: "string", const: "contacts" },
            project_id: { type: "string" },
            contact_id: { type: "string" },
            membership: ref("ContactProjectMembershipSnapshot"),
            project_link: { anyOf: [ref("ProjectResourceLink"), { type: "null" }] },
            evidence: { type: "array", items: ref("ProjectContactLinkEvidence") },
            response_control: ref("GuardedResponseControl"),
          },
          required: [
            "ok", "outcome", "authority", "project_id", "contact_id",
            "membership", "project_link", "evidence", "response_control",
          ],
        },
        ProjectContactLinkListResult: {
          type: "object",
          additionalProperties: false,
          properties: {
            ok: { type: "boolean", const: true },
            authority: { type: "string", const: "contacts" },
            project_id: { type: "string" },
            membership_revision: { type: "string" },
            project_revision: { type: "string" },
            contact_ids: { type: "array", items: { type: "string" } },
            synchronized_contact_ids: { type: "array", items: { type: "string" } },
            missing_project_link_contact_ids: { type: "array", items: { type: "string" } },
            stale_project_link_contact_ids: { type: "array", items: { type: "string" } },
            project_links: { type: "array", items: ref("ProjectResourceLink") },
            response_control: ref("GuardedResponseControl"),
          },
          required: [
            "ok", "authority", "project_id", "membership_revision", "project_revision",
            "contact_ids", "synchronized_contact_ids", "missing_project_link_contact_ids",
            "stale_project_link_contact_ids", "project_links", "response_control",
          ],
        },
        ProjectResourceLinkRollbackRequest: {
          type: "object",
          properties: {
            operation_id: { type: "string" },
            step_id: { type: "string" },
            accepted_receipt_id: { type: "string" },
            expected_current_revision: { type: "string" },
            max_items: { type: "integer", minimum: 1 },
            agent_id: { type: "string" },
            source: { type: "string" },
            command: { type: "string" },
            response_byte_limit: { type: "integer", minimum: 1 },
            time_budget_ms: { type: "integer", minimum: 1 },
          },
          required: [
            "operation_id", "step_id", "accepted_receipt_id", "expected_current_revision",
            "response_byte_limit", "time_budget_ms",
          ],
        },
        ProjectResourceLinkProducerBinding: {
          type: "object",
          additionalProperties: false,
          properties: {
            authority_id: { type: "string" },
            tenant_id: { type: "string" },
            corpus_id: { anyOf: [{ type: "string" }, { type: "null" }] },
            capability_digest: { type: "string" },
          },
          required: ["authority_id", "tenant_id", "corpus_id", "capability_digest"],
        },
        ProjectResourceLinkProducerEvidence: {
          type: "object",
          additionalProperties: false,
          properties: {
            created_by_operation: { type: "boolean" },
            forward_receipt_id: { anyOf: [{ type: "string" }, { type: "null" }] },
            child_link_receipt_ids: { type: "array", items: { type: "string" } },
            target_revision: { type: "string" },
            target_digest: { type: "string" },
            inverse_verified: { anyOf: [{ type: "boolean" }, { type: "null" }] },
            inverse_outcome: { anyOf: [{ type: "string" }, { type: "null" }] },
          },
          required: [
            "created_by_operation", "forward_receipt_id", "child_link_receipt_ids",
            "target_revision", "target_digest", "inverse_verified", "inverse_outcome",
          ],
        },
        ProjectResourceLinkMigrationItemInput: {
          type: "object",
          additionalProperties: false,
          properties: {
            link: ref("ProjectResourceLinkInput"),
            producer_resource_kind: { type: "string" },
            producer_binding: ref("ProjectResourceLinkProducerBinding"),
          },
          required: ["link", "producer_resource_kind", "producer_binding"],
        },
        ProjectResourceLinkMigrationItem: {
          type: "object",
          additionalProperties: false,
          properties: {
            link: ref("ProjectResourceLinkInput"),
            link_id: { type: "string", pattern: "^prl_" },
            producer_resource_kind: { type: "string" },
            producer_binding: ref("ProjectResourceLinkProducerBinding"),
            producer_evidence: {
              anyOf: [ref("ProjectResourceLinkProducerEvidence"), { type: "null" }],
            },
          },
          required: [
            "link", "link_id", "producer_resource_kind", "producer_binding", "producer_evidence",
          ],
        },
        ProjectResourceLinkProjectsReferenceProof: {
          oneOf: [
            {
              type: "object",
              additionalProperties: false,
              properties: {
                kind: { type: "string", enum: ["accepted_inverse"] },
                forward_receipt_id: { type: "string" },
                inverse_receipt_id: { type: "string" },
                verified_revision: { type: "string" },
                collection_digest: { type: "string" },
                link_ids_checked: { type: "array", items: { type: "string" } },
                complete: { type: "boolean", enum: [true] },
                truncated: { type: "boolean", enum: [false] },
                request_digest: { type: "string" },
                precondition_digest: { type: "string" },
              },
              required: [
                "kind", "forward_receipt_id", "inverse_receipt_id", "verified_revision",
                "collection_digest", "link_ids_checked", "complete", "truncated",
                "request_digest", "precondition_digest",
              ],
            },
            {
              type: "object",
              additionalProperties: false,
              properties: {
                kind: { type: "string", enum: ["no_projects_write"] },
                verified_revision: { type: "string" },
                collection_digest: { type: "string" },
                link_ids_checked: { type: "array", items: { type: "string" } },
                complete: { type: "boolean", enum: [true] },
                truncated: { type: "boolean", enum: [false] },
                request_digest: { type: "string" },
                precondition_digest: { type: "string" },
              },
              required: [
                "kind", "verified_revision", "collection_digest", "link_ids_checked",
                "complete", "truncated", "request_digest", "precondition_digest",
              ],
            },
          ],
        },
        ProjectResourceLinkMigrationManifestV1: {
          type: "object",
          additionalProperties: false,
          properties: {
            schema: { type: "string", enum: ["projects.project_resource_link_migration_manifest.v1"] },
            manifest_id: { type: "string", pattern: "^prlm_" },
            project_id: { type: "string" },
            operation_id: { type: "string" },
            step_id: { type: "string" },
            state: {
              type: "string",
              enum: [
                "planned", "producer_applied", "projects_applied", "verified",
                "rollback_in_progress", "rolled_back", "retained_target", "failed_reconcilable",
              ],
            },
            expected_project_revision: { type: "string" },
            desired_collection_digest: { type: "string" },
            links: { type: "array", items: ref("ProjectResourceLinkMigrationItem") },
            projects_forward_receipt_id: { anyOf: [{ type: "string" }, { type: "null" }] },
            projects_inverse_receipt_id: { anyOf: [{ type: "string" }, { type: "null" }] },
            projects_reference_proof: {
              anyOf: [ref("ProjectResourceLinkProjectsReferenceProof"), { type: "null" }],
            },
            last_verified_projects_revision: { anyOf: [{ type: "string" }, { type: "null" }] },
            last_verified_projects_digest: { anyOf: [{ type: "string" }, { type: "null" }] },
            transition_version: { type: "integer", minimum: 1 },
            created_at: { type: "string" },
            updated_at: { type: "string" },
          },
          required: [
            "schema", "manifest_id", "project_id", "operation_id", "step_id", "state",
            "expected_project_revision", "desired_collection_digest", "links",
            "projects_forward_receipt_id", "projects_inverse_receipt_id",
            "projects_reference_proof", "last_verified_projects_revision",
            "last_verified_projects_digest", "transition_version", "created_at", "updated_at",
          ],
        },
        ProjectResourceLinkMigrationEvent: {
          type: "object",
          additionalProperties: false,
          properties: {
            event_id: { type: "string", pattern: "^prlme_" },
            manifest_id: { type: "string", pattern: "^prlm_" },
            transition_version: { type: "integer", minimum: 1 },
            from_state: { anyOf: [{ type: "string" }, { type: "null" }] },
            to_state: { type: "string" },
            request_digest: { type: "string" },
            precondition_digest: { type: "string" },
            evidence: { type: "object", additionalProperties: true },
            created_at: { type: "string" },
          },
          required: [
            "event_id", "manifest_id", "transition_version", "from_state", "to_state",
            "request_digest", "precondition_digest", "evidence", "created_at",
          ],
        },
        ProjectResourceLinkMigrationPlanRequest: {
          type: "object",
          additionalProperties: false,
          properties: {
            operation_id: { type: "string" },
            step_id: { type: "string" },
            expected_project_revision: { type: "string" },
            links: { type: "array", items: ref("ProjectResourceLinkMigrationItemInput") },
            max_items: { type: "integer", minimum: 1 },
            response_byte_limit: { type: "integer", minimum: 1 },
            time_budget_ms: { type: "integer", minimum: 1 },
          },
          required: [
            "operation_id", "step_id", "expected_project_revision", "links",
            "response_byte_limit", "time_budget_ms",
          ],
        },
        ProjectResourceLinkMigrationAdvanceRequest: {
          type: "object",
          additionalProperties: false,
          properties: {
            expected_transition_version: { type: "integer", minimum: 1 },
            next_state: {
              type: "string",
              enum: ["producer_applied", "projects_applied", "verified", "failed_reconcilable"],
            },
            max_items: { type: "integer", minimum: 1 },
            producer_evidence: {
              type: "array",
              items: ref("ProjectResourceLinkProducerEvidence"),
            },
            projects_forward_receipt_id: { type: "string" },
            last_verified_projects_revision: { type: "string" },
            last_verified_projects_digest: { type: "string" },
            evidence: { type: "object", additionalProperties: true },
            response_byte_limit: { type: "integer", minimum: 1 },
            time_budget_ms: { type: "integer", minimum: 1 },
          },
          required: [
            "expected_transition_version", "next_state", "evidence",
            "response_byte_limit", "time_budget_ms",
          ],
        },
        ProjectResourceLinkMigrationRollbackRequest: {
          type: "object",
          additionalProperties: false,
          properties: {
            expected_transition_version: { type: "integer", minimum: 1 },
            max_items: { type: "integer", minimum: 1 },
            producer_outcome: {
              type: "string",
              enum: ["pending", "complete", "retained_target", "failed_reconcilable"],
            },
            producer_evidence: {
              type: "array",
              items: ref("ProjectResourceLinkProducerEvidence"),
            },
            evidence: { type: "object", additionalProperties: true },
            agent_id: { type: "string" },
            source: { type: "string" },
            command: { type: "string" },
            response_byte_limit: { type: "integer", minimum: 1 },
            time_budget_ms: { type: "integer", minimum: 1 },
          },
          required: [
            "expected_transition_version", "producer_outcome", "evidence",
            "response_byte_limit", "time_budget_ms",
          ],
        },
        ProjectResourceLinkMigrationResult: {
          type: "object",
          additionalProperties: false,
          properties: {
            ok: { type: "boolean" },
            outcome: {
              type: "string",
              enum: ["accepted", "duplicate_of_accepted", "terminal_nonacceptance"],
            },
            manifest: ref("ProjectResourceLinkMigrationManifestV1"),
            events: { type: "array", items: ref("ProjectResourceLinkMigrationEvent") },
            response_control: ref("GuardedResponseControl"),
          },
          required: ["ok", "outcome", "manifest", "events", "response_control"],
        },
        GuardedProjectMutationReceipt: {
          type: "object",
          properties: {
            receipt_id: { type: "string" },
            operation_id: { type: "string" },
            step_id: { type: "string" },
            direction: { type: "string", enum: ["forward", "inverse"] },
            idempotency_key: { type: "string" },
            target_id: { type: "string" },
            request_digest: { type: "string" },
            precondition_digest: { type: "string" },
            expected_revision: { type: "string" },
            outcome: { type: "string", enum: ["accepted", "duplicate_of_accepted", "terminal_nonacceptance"] },
            reason: { type: "string", nullable: true },
            result_project_id: { type: "string", nullable: true },
            duplicate_of_receipt_id: { type: "string", nullable: true },
            before: { type: "object", additionalProperties: true, nullable: true },
            after: { type: "object", additionalProperties: true, nullable: true },
            post_revision: { type: "string", nullable: true },
            created_at: { type: "string" },
          },
          required: [
            "receipt_id", "operation_id", "step_id", "direction", "idempotency_key", "target_id",
            "request_digest", "precondition_digest", "expected_revision", "outcome", "reason",
            "result_project_id", "duplicate_of_receipt_id", "before", "after", "post_revision", "created_at",
          ],
        },
        GuardedProjectMutationRequest: {
          type: "object",
          properties: {
            operation_id: { type: "string" },
            step_id: { type: "string" },
            direction: { type: "string", enum: ["forward", "inverse"] },
            expected_revision: { type: "string" },
            patch: ref("UpdateWorkspace"),
            dry_run: { type: "boolean" },
            agent_id: { type: "string" },
            source: { type: "string" },
            command: { type: "string" },
            response_byte_limit: { type: "integer", minimum: 1 },
            time_budget_ms: { type: "integer", minimum: 1 },
          },
          required: ["operation_id", "step_id", "expected_revision", "patch", "response_byte_limit", "time_budget_ms"],
        },
        GuardedProjectMutationResult: {
          type: "object",
          properties: {
            ok: { type: "boolean" },
            dry_run: { type: "boolean" },
            outcome: { type: "string", enum: ["accepted", "duplicate_of_accepted", "terminal_nonacceptance", "planned"] },
            idempotency_key: { type: "string" },
            request_digest: { type: "string" },
            precondition_digest: { type: "string" },
            project_id: { type: "string" },
            expected_revision: { type: "string" },
            current_revision: { type: "string" },
            before: ref("Workspace"),
            after: { anyOf: [ref("Workspace"), { type: "null" }] },
            receipt: { anyOf: [ref("GuardedProjectMutationReceipt"), { type: "null" }] },
            response_control: ref("GuardedResponseControl"),
          },
          required: [
            "ok", "dry_run", "outcome", "idempotency_key", "request_digest", "precondition_digest",
            "project_id", "expected_revision", "current_revision", "before", "after", "receipt", "response_control",
          ],
        },
        GuardedProjectMutationReceiptLookup: {
          type: "object",
          properties: {
            receipt: ref("GuardedProjectMutationReceipt"),
            response_control: ref("GuardedResponseControl"),
          },
          required: ["receipt", "response_control"],
        },
        GuardedProjectMutationRollbackRequest: {
          type: "object",
          properties: {
            operation_id: { type: "string" },
            step_id: { type: "string" },
            accepted_receipt_id: { type: "string" },
            expected_current_revision: { type: "string" },
            agent_id: { type: "string" },
            source: { type: "string" },
            command: { type: "string" },
            response_byte_limit: { type: "integer", minimum: 1 },
            time_budget_ms: { type: "integer", minimum: 1 },
          },
          required: [
            "operation_id", "step_id", "accepted_receipt_id", "expected_current_revision",
            "response_byte_limit", "time_budget_ms",
          ],
        },
        RootList: {
          type: "object",
          properties: { roots: { type: "array", items: ref("Root") }, count: { type: "integer" } },
          required: ["roots", "count"],
        },
        AgentList: {
          type: "object",
          properties: { agents: { type: "array", items: ref("Agent") }, count: { type: "integer" } },
          required: ["agents", "count"],
        },
        RecipeList: {
          type: "object",
          properties: { recipes: { type: "array", items: ref("Recipe") }, count: { type: "integer" } },
          required: ["recipes", "count"],
        },
        EventList: {
          type: "object",
          properties: { events: { type: "array", items: ref("WorkspaceEvent") }, count: { type: "integer" } },
          required: ["events", "count"],
        },
        LocationList: {
          type: "object",
          properties: { locations: { type: "array", items: ref("WorkspaceLocation") }, count: { type: "integer" } },
          required: ["locations", "count"],
        },
        LocationAdded: {
          type: "object",
          properties: { project: ref("Workspace"), location: ref("WorkspaceLocation") },
          required: ["project", "location"],
        },
        AgentAssignmentList: {
          type: "object",
          properties: { assignments: { type: "array", items: ref("WorkspaceAgentAssignment") }, count: { type: "integer" } },
          required: ["assignments", "count"],
        },
        LockList: {
          type: "object",
          properties: { locks: { type: "array", items: ref("WorkspaceLock") }, count: { type: "integer" } },
          required: ["locks", "count"],
        },
        LockRelease: {
          type: "object",
          properties: { released: { type: "boolean" } },
          required: ["released"],
        },
        RecordEvent: {
          type: "object",
          properties: {
            event_type: { type: "string" },
            source: { type: "string" },
            agent_id: { type: "string" },
            prompt: { type: "string" },
            command: { type: "string" },
            before: { type: "object", additionalProperties: true, nullable: true },
            after: { type: "object", additionalProperties: true, nullable: true },
            metadata: { type: "object", additionalProperties: true },
          },
          required: ["event_type"],
        },
        EventRecorded: {
          type: "object",
          properties: { event: ref("WorkspaceEvent") },
          required: ["event"],
        },
        DeleteResult: {
          type: "object",
          properties: { deleted: { type: "boolean" }, hard: { type: "boolean" }, id: { type: "string" } },
          required: ["deleted"],
        },
        Health: {
          type: "object",
          properties: { status: { type: "string" }, version: { type: "string" } },
          required: ["status", "version"],
        },
        LegacyVersionResponse: {
          type: "object",
          description: "Legacy compatibility response for /version.",
          properties: {
            status: { type: "string" },
            version: { type: "string" },
            mode: {
              type: "string",
              deprecated: true,
              description: "Deprecated compatibility field; do not use it for deployment branching.",
            },
          },
          required: ["status", "version", "mode"],
        },
        Error: {
          type: "object",
          properties: { error: { type: "string" }, reason: { type: "string" } },
          required: ["error"],
        },
      },
    },
    security: [{ apiKey: [] }],
    paths: {
      "/health": {
        get: {
          operationId: "getHealth",
          summary: "Liveness probe",
          security: [],
          responses: { "200": jsonResp("Health") },
        },
      },
      "/ready": {
        get: {
          operationId: "getReady",
          summary: "Readiness probe (checks DB connectivity)",
          security: [],
          responses: { "200": jsonResp("Health"), "503": jsonResp("Health", "Not ready") },
        },
      },
      "/version": {
        get: {
          operationId: "getVersion",
          summary: "Service version",
          security: [],
          responses: { "200": jsonResp("LegacyVersionResponse") },
        },
      },
      "/v1/projects": {
        get: {
          operationId: "listProjects",
          summary: "List projects (workspaces)",
          parameters: [
            { name: "status", in: "query", required: false, schema: { type: "string" } },
            { name: "kind", in: "query", required: false, schema: { type: "string" } },
            { name: "root_id", in: "query", required: false, schema: { type: "string" } },
            { name: "query", in: "query", required: false, schema: { type: "string" } },
            { name: "tag", in: "query", required: false, schema: { type: "string" } },
            {
              name: "limit",
              in: "query",
              required: false,
              description: `Rows per page (default ${WORKSPACE_LIST_DEFAULT_LIMIT}, clamped to ${WORKSPACE_LIST_MAX_LIMIT}). A larger value is clamped, not honoured — page with offset and read has_more.`,
              schema: { type: "integer" },
            },
            { name: "offset", in: "query", required: false, schema: { type: "integer" } },
          ],
          responses: { "200": jsonResp("WorkspaceList") },
        },
        post: {
          operationId: "createProject",
          summary: "Create a project (workspace)",
          requestBody: jsonBody("CreateWorkspace"),
          responses: { "201": jsonResp("Workspace", "Created"), "400": jsonResp("Error", "Invalid") },
        },
      },
      "/v1/projects/{id}": {
        get: {
          operationId: "getProject",
          summary: "Get a project by id or slug",
          parameters: [ID_PARAM],
          responses: { "200": jsonResp("Workspace"), "404": jsonResp("Error", "Not found") },
        },
        patch: {
          operationId: "updateProject",
          summary: "Update a project",
          parameters: [ID_PARAM],
          requestBody: jsonBody("UpdateWorkspace"),
          responses: { "200": jsonResp("Workspace"), "404": jsonResp("Error", "Not found") },
        },
        delete: {
          operationId: "deleteProject",
          summary: "Delete a project (soft by default, ?hard=true for hard delete)",
          parameters: [
            ID_PARAM,
            { name: "hard", in: "query", required: false, schema: { type: "boolean" } },
          ],
          responses: { "200": jsonResp("DeleteResult"), "404": jsonResp("Error", "Not found") },
        },
      },
      "/v1/projects/{id}/guarded-metadata": {
        get: {
          operationId: "guardedReadProject",
          summary: "Read one project by exact stable id with bounded complete JSON and its current mutation revision",
          parameters: [
            EXACT_PROJECT_ID_PARAM,
            {
              name: "response_byte_limit",
              in: "query",
              required: true,
              schema: { type: "integer", minimum: 1 },
            },
            {
              name: "time_budget_ms",
              in: "query",
              required: true,
              schema: { type: "integer", minimum: 1 },
            },
            {
              name: "resource_link_max_items",
              in: "query",
              required: false,
              schema: { type: "integer", minimum: 1, default: 1000 },
            },
          ],
          responses: {
            "200": jsonResp("GuardedProjectRead"),
            "400": jsonResp("Error", "Invalid target or budget"),
            "404": jsonResp("Error", "Not found"),
          },
        },
        post: {
          operationId: "guardedUpdateProject",
          summary: "Conditionally update one exact project and return a deterministic terminal receipt",
          parameters: [EXACT_PROJECT_ID_PARAM],
          requestBody: jsonBody("GuardedProjectMutationRequest"),
          responses: {
            "200": jsonResp("GuardedProjectMutationResult"),
            "400": jsonResp("Error", "Invalid target, precondition, or budget"),
            "404": jsonResp("Error", "Not found"),
          },
        },
      },
      "/v1/projects/{id}/guarded-metadata/receipts": {
        get: {
          operationId: "lookupGuardedProjectMutationReceipt",
          summary: "Look up exactly one terminal guarded mutation receipt",
          parameters: [
            EXACT_PROJECT_ID_PARAM,
            { name: "operation_id", in: "query", required: true, schema: { type: "string" } },
            { name: "step_id", in: "query", required: true, schema: { type: "string" } },
            { name: "direction", in: "query", required: true, schema: { type: "string", enum: ["forward", "inverse"] } },
            { name: "idempotency_key", in: "query", required: true, schema: { type: "string" } },
            { name: "max_items", in: "query", required: true, schema: { type: "integer", const: 1 } },
            { name: "response_byte_limit", in: "query", required: true, schema: { type: "integer", minimum: 1 } },
            { name: "time_budget_ms", in: "query", required: true, schema: { type: "integer", minimum: 1 } },
          ],
          responses: {
            "200": jsonResp("GuardedProjectMutationReceiptLookup"),
            "400": jsonResp("Error", "Invalid lookup or terminal cardinality"),
            "404": jsonResp("Error", "Not found"),
          },
        },
      },
      "/v1/projects/{id}/guarded-metadata/rollback": {
        post: {
          operationId: "rollbackGuardedProjectMutation",
          summary: "Conditionally roll back one accepted guarded mutation receipt",
          parameters: [EXACT_PROJECT_ID_PARAM],
          requestBody: jsonBody("GuardedProjectMutationRollbackRequest"),
          responses: {
            "200": jsonResp("GuardedProjectMutationResult"),
            "400": jsonResp("Error", "Invalid receipt, precondition, or budget"),
            "404": jsonResp("Error", "Not found"),
          },
        },
      },
      "/v1/projects/{id}/resource-links": {
        get: {
          operationId: "readProjectResourceLinks",
          summary: "Read the complete typed project resource-link collection under explicit bounds",
          parameters: [
            EXACT_PROJECT_ID_PARAM,
            { name: "max_items", in: "query", required: true, schema: { type: "integer", minimum: 1 } },
            { name: "response_byte_limit", in: "query", required: true, schema: { type: "integer", minimum: 1 } },
            { name: "time_budget_ms", in: "query", required: true, schema: { type: "integer", minimum: 1 } },
          ],
          responses: {
            "200": jsonResp("ProjectResourceLinkRead"),
            "400": jsonResp("Error", "Invalid target or collection bound"),
            "404": jsonResp("Error", "Not found"),
          },
        },
      },
      "/v1/projects/{id}/resource-links/add": {
        post: {
          operationId: "addProjectResourceLinks",
          summary: "Idempotently add typed resource links under a project revision CAS",
          parameters: [EXACT_PROJECT_ID_PARAM],
          requestBody: jsonBody("ProjectResourceLinkMutationRequest"),
          responses: {
            "200": jsonResp("ProjectResourceLinkMutationResult"),
            "400": jsonResp("Error", "Invalid link, revision, digest, or bound"),
            "404": jsonResp("Error", "Not found"),
          },
        },
      },
      "/v1/projects/{id}/resource-links/reconcile": {
        post: {
          operationId: "reconcileProjectResourceLinks",
          summary: "Reconcile the complete typed resource-link collection under a project revision CAS",
          parameters: [EXACT_PROJECT_ID_PARAM],
          requestBody: jsonBody("ProjectResourceLinkMutationRequest"),
          responses: {
            "200": jsonResp("ProjectResourceLinkMutationResult"),
            "400": jsonResp("Error", "Invalid link, revision, digest, or bound"),
            "404": jsonResp("Error", "Not found"),
          },
        },
      },
      "/v1/projects/{id}/resource-links/rollback": {
        post: {
          operationId: "rollbackProjectResourceLinks",
          summary: "Restore the exact pre-mutation typed resource-link collection from an accepted receipt",
          parameters: [EXACT_PROJECT_ID_PARAM],
          requestBody: jsonBody("ProjectResourceLinkRollbackRequest"),
          responses: {
            "200": jsonResp("ProjectResourceLinkMutationResult"),
            "400": jsonResp("Error", "Invalid receipt, revision, digest, or bound"),
            "404": jsonResp("Error", "Not found"),
          },
        },
      },
      "/v1/projects/{id}/duplicate-quarantine": {
        get: {
          operationId: "readDuplicateProjectQuarantinePreimage",
          summary: "Read the exact complete project, resource-link, and path-selector preimage for quarantine",
          parameters: [
            EXACT_PROJECT_ID_PARAM,
            { name: "resource_link_max_items", in: "query", required: true, schema: { type: "integer", minimum: 1 } },
            { name: "workspace_location_max_items", in: "query", required: true, schema: { type: "integer", minimum: 1 } },
            { name: "response_byte_limit", in: "query", required: true, schema: { type: "integer", minimum: 1 } },
            { name: "time_budget_ms", in: "query", required: true, schema: { type: "integer", minimum: 1 } },
          ],
          responses: {
            "200": jsonResp("ProjectQuarantineRead"),
            "400": jsonResp("Error", "Invalid target or incomplete collection bound"),
            "404": jsonResp("Error", "Not found"),
          },
        },
        post: {
          operationId: "quarantineDuplicateProject",
          summary: "Atomically retire duplicate selectors and links while retaining reversible provenance",
          parameters: [EXACT_PROJECT_ID_PARAM],
          requestBody: jsonBody("ProjectQuarantineRequest"),
          responses: {
            "200": jsonResp("ProjectQuarantineResult"),
            "400": jsonResp("Error", "Invalid precondition, target set, digest, or collection bound"),
            "404": jsonResp("Error", "Not found"),
          },
        },
      },
      "/v1/projects/{id}/duplicate-quarantine/rollback": {
        post: {
          operationId: "rollbackDuplicateProjectQuarantine",
          summary: "Restore the exact project metadata, resource links, and path selectors from the accepted receipt",
          parameters: [EXACT_PROJECT_ID_PARAM],
          requestBody: jsonBody("ProjectQuarantineRollbackRequest"),
          responses: {
            "200": jsonResp("ProjectQuarantineResult"),
            "400": jsonResp("Error", "Invalid receipt, revision, digest, or post-write state"),
            "404": jsonResp("Error", "Not found"),
          },
        },
      },
      "/v1/projects/{id}/resource-link-migrations/plan": {
        post: {
          operationId: "planProjectResourceLinkMigration",
          summary: "Persist a durable resource-link migration manifest before any authority write",
          parameters: [EXACT_PROJECT_ID_PARAM],
          requestBody: jsonBody("ProjectResourceLinkMigrationPlanRequest"),
          responses: {
            "200": jsonResp("ProjectResourceLinkMigrationResult"),
            "400": jsonResp("Error", "Invalid link, authority binding, revision, or bound"),
            "404": jsonResp("Error", "Not found"),
          },
        },
      },
      "/v1/projects/{id}/resource-link-migrations/{manifestId}": {
        get: {
          operationId: "readProjectResourceLinkMigration",
          summary: "Read one durable migration manifest and its complete immutable event history",
          parameters: [
            EXACT_PROJECT_ID_PARAM,
            { name: "manifestId", in: "path", required: true, schema: { type: "string", pattern: "^prlm_" } },
            { name: "max_items", in: "query", required: true, schema: { type: "integer", minimum: 1 } },
            { name: "response_byte_limit", in: "query", required: true, schema: { type: "integer", minimum: 1 } },
            { name: "time_budget_ms", in: "query", required: true, schema: { type: "integer", minimum: 1 } },
          ],
          responses: {
            "200": jsonResp("ProjectResourceLinkMigrationResult"),
            "400": jsonResp("Error", "Invalid manifest target or bound"),
            "404": jsonResp("Error", "Not found"),
          },
        },
      },
      "/v1/projects/{id}/resource-link-migrations/{manifestId}/advance": {
        post: {
          operationId: "advanceProjectResourceLinkMigration",
          summary: "CAS-advance a manifest after reconciling exact producer or Projects evidence",
          parameters: [
            EXACT_PROJECT_ID_PARAM,
            { name: "manifestId", in: "path", required: true, schema: { type: "string", pattern: "^prlm_" } },
          ],
          requestBody: jsonBody("ProjectResourceLinkMigrationAdvanceRequest"),
          responses: {
            "200": jsonResp("ProjectResourceLinkMigrationResult"),
            "400": jsonResp("Error", "Invalid transition, receipt, readback, or bound"),
            "404": jsonResp("Error", "Not found"),
          },
        },
      },
      "/v1/projects/{id}/resource-link-migrations/{manifestId}/rollback": {
        post: {
          operationId: "rollbackProjectResourceLinkMigration",
          summary: "Remove Projects references first, persist proof, then record producer rollback outcome",
          parameters: [
            EXACT_PROJECT_ID_PARAM,
            { name: "manifestId", in: "path", required: true, schema: { type: "string", pattern: "^prlm_" } },
          ],
          requestBody: jsonBody("ProjectResourceLinkMigrationRollbackRequest"),
          responses: {
            "200": jsonResp("ProjectResourceLinkMigrationResult"),
            "400": jsonResp("Error", "Ambiguous state, failed reference proof, stale transition, or bound"),
            "404": jsonResp("Error", "Not found"),
          },
        },
      },
      "/v1/projects/{id}/contacts": {
        get: {
          operationId: "listProjectContacts",
          summary: "List Contacts-authoritative project memberships and compare synchronized Project resource links",
          parameters: [
            EXACT_PROJECT_ID_PARAM,
            { name: "max_items", in: "query", required: true, schema: { type: "integer", minimum: 1 } },
            { name: "response_byte_limit", in: "query", required: true, schema: { type: "integer", minimum: 1 } },
            { name: "time_budget_ms", in: "query", required: true, schema: { type: "integer", minimum: 1 } },
          ],
          responses: {
            "200": jsonResp("ProjectContactLinkListResult"),
            "400": jsonResp("Error", "Invalid target or collection bound"),
            "404": jsonResp("Error", "Not found"),
            "503": jsonResp("Error", "Contacts authority is not configured"),
          },
        },
      },
      "/v1/projects/{id}/contacts/{contact_id}/attach": {
        post: {
          operationId: "attachProjectContact",
          summary: "Attach a Contact through Contacts-authoritative compensation-safe coordination",
          parameters: [
            EXACT_PROJECT_ID_PARAM,
            { name: "contact_id", in: "path", required: true, schema: { type: "string", pattern: COMPLETE_EXTERNAL_UUID_PATTERN } },
          ],
          requestBody: jsonBody("ProjectContactLinkMutationRequest"),
          responses: {
            "200": jsonResp("ProjectContactLinkMutationResult"),
            "400": jsonResp("Error", "Invalid target, operation, or bound"),
            "404": jsonResp("Error", "Not found"),
            "409": jsonResp("Error", "Contacts or Projects compare-and-swap conflict"),
            "503": jsonResp("Error", "Contacts authority is not configured"),
          },
        },
      },
      "/v1/projects/{id}/contacts/{contact_id}/detach": {
        post: {
          operationId: "detachProjectContact",
          summary: "Detach a Contact through Contacts-authoritative compensation-safe coordination",
          parameters: [
            EXACT_PROJECT_ID_PARAM,
            { name: "contact_id", in: "path", required: true, schema: { type: "string", pattern: COMPLETE_EXTERNAL_UUID_PATTERN } },
          ],
          requestBody: jsonBody("ProjectContactLinkMutationRequest"),
          responses: {
            "200": jsonResp("ProjectContactLinkMutationResult"),
            "400": jsonResp("Error", "Invalid target, operation, or bound"),
            "404": jsonResp("Error", "Not found"),
            "409": jsonResp("Error", "Contacts or Projects compare-and-swap conflict"),
            "503": jsonResp("Error", "Contacts authority is not configured"),
          },
        },
      },
      "/v1/projects/{id}/archive": {
        post: {
          operationId: "archiveProject",
          summary: "Archive a project",
          parameters: [ID_PARAM],
          responses: { "200": jsonResp("Workspace"), "404": jsonResp("Error", "Not found") },
        },
      },
      "/v1/projects/{id}/unarchive": {
        post: {
          operationId: "unarchiveProject",
          summary: "Unarchive a project",
          parameters: [ID_PARAM],
          responses: { "200": jsonResp("Workspace"), "404": jsonResp("Error", "Not found") },
        },
      },
      "/v1/projects/{id}/events": {
        get: {
          operationId: "listProjectEvents",
          summary: "List a project's events",
          parameters: [ID_PARAM, { name: "limit", in: "query", required: false, schema: { type: "integer" } }],
          responses: { "200": jsonResp("EventList"), "404": jsonResp("Error", "Not found") },
        },
        post: {
          operationId: "recordProjectEvent",
          summary: "Record a custom audit event for a project",
          parameters: [ID_PARAM],
          requestBody: jsonBody("RecordEvent"),
          responses: { "201": jsonResp("EventRecorded", "Created"), "400": jsonResp("Error", "Invalid"), "404": jsonResp("Error", "Not found") },
        },
      },
      "/v1/projects/{id}/locations": {
        get: {
          operationId: "listProjectLocations",
          summary: "List a project's registered folder locations",
          parameters: [ID_PARAM],
          responses: { "200": jsonResp("LocationList"), "404": jsonResp("Error", "Not found") },
        },
        post: {
          operationId: "addProjectLocation",
          summary: "Register an extra folder location for a project",
          parameters: [ID_PARAM],
          requestBody: jsonBody("AddWorkspaceLocation"),
          responses: { "201": jsonResp("LocationAdded", "Created"), "400": jsonResp("Error", "Invalid"), "404": jsonResp("Error", "Not found") },
        },
      },
      "/v1/projects/{id}/agents": {
        get: {
          operationId: "listProjectAgents",
          summary: "List a project's agent assignments",
          parameters: [ID_PARAM],
          responses: { "200": jsonResp("AgentAssignmentList"), "404": jsonResp("Error", "Not found") },
        },
        post: {
          operationId: "assignProjectAgent",
          summary: "Assign a registered agent to a project role",
          parameters: [ID_PARAM],
          requestBody: jsonBody("AssignWorkspaceAgent"),
          responses: { "201": jsonResp("AgentAssignment", "Created"), "400": jsonResp("Error", "Invalid"), "404": jsonResp("Error", "Not found") },
        },
      },
      "/v1/locks": {
        get: {
          operationId: "listLocks",
          summary: "List active project mutation locks",
          responses: { "200": jsonResp("LockList") },
        },
        post: {
          operationId: "acquireLock",
          summary: "Acquire a project mutation lock",
          requestBody: jsonBody("AcquireWorkspaceLock"),
          responses: { "201": jsonResp("Lock", "Created"), "400": jsonResp("Error", "Invalid or held") },
        },
      },
      "/v1/locks/{key}": {
        delete: {
          operationId: "releaseLock",
          summary: "Release a project mutation lock by key",
          parameters: [{
            name: "key",
            in: "path",
            required: true,
            description: "Lock key",
            schema: { type: "string" },
          } as const],
          responses: { "200": jsonResp("LockRelease"), "404": jsonResp("Error", "Not found") },
        },
      },
      "/v1/roots": {
        get: {
          operationId: "listRoots",
          summary: "List roots",
          responses: { "200": jsonResp("RootList") },
        },
        post: {
          operationId: "createRoot",
          summary: "Create a root",
          requestBody: jsonBody("CreateRoot"),
          responses: { "201": jsonResp("Root", "Created"), "400": jsonResp("Error", "Invalid") },
        },
      },
      "/v1/roots/{id}": {
        get: {
          operationId: "getRoot",
          summary: "Get a root by id or slug",
          parameters: [ID_PARAM],
          responses: { "200": jsonResp("Root"), "404": jsonResp("Error", "Not found") },
        },
        patch: {
          operationId: "updateRoot",
          summary: "Update a root",
          parameters: [ID_PARAM],
          requestBody: jsonBody("UpdateRoot"),
          responses: { "200": jsonResp("Root"), "404": jsonResp("Error", "Not found") },
        },
        delete: {
          operationId: "deleteRoot",
          summary: "Delete a root",
          parameters: [
            ID_PARAM,
            { name: "detach", in: "query", required: false, schema: { type: "boolean" } },
          ],
          responses: { "200": jsonResp("DeleteResult"), "404": jsonResp("Error", "Not found") },
        },
      },
      "/v1/agents": {
        get: {
          operationId: "listAgents",
          summary: "List agents",
          responses: { "200": jsonResp("AgentList") },
        },
        post: {
          operationId: "createAgent",
          summary: "Create an agent",
          requestBody: jsonBody("CreateAgent"),
          responses: { "201": jsonResp("Agent", "Created"), "400": jsonResp("Error", "Invalid") },
        },
      },
      "/v1/agents/{id}": {
        get: {
          operationId: "getAgent",
          summary: "Get an agent by id or slug",
          parameters: [ID_PARAM],
          responses: { "200": jsonResp("Agent"), "404": jsonResp("Error", "Not found") },
        },
      },
      "/v1/recipes": {
        get: {
          operationId: "listRecipes",
          summary: "List recipes",
          responses: { "200": jsonResp("RecipeList") },
        },
        post: {
          operationId: "createRecipe",
          summary: "Create a recipe",
          requestBody: jsonBody("CreateRecipe"),
          responses: { "201": jsonResp("Recipe", "Created"), "400": jsonResp("Error", "Invalid") },
        },
      },
      "/v1/recipes/{id}": {
        get: {
          operationId: "getRecipe",
          summary: "Get a recipe by id or slug",
          parameters: [ID_PARAM],
          responses: { "200": jsonResp("Recipe"), "404": jsonResp("Error", "Not found") },
        },
      },
    },
  };
}
