#!/usr/bin/env bun
/**
 * Generate the typed `/v1` SDK client from the serve OpenAPI document.
 *
 * Source of truth: src/server/openapi.ts (also served at GET /openapi.json).
 * Output: src/sdk/v1.generated.ts — a dependency-free typed fetch client.
 *
 * Usage: bun run scripts/generate-sdk.ts
 */
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { generateSdkFromOpenApi } from "@hasna/contracts/sdk";
import { buildV1OpenApiDocument } from "../src/server/openapi.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const spec = buildV1OpenApiDocument();
const { code, operations, warnings } = generateSdkFromOpenApi(spec as never, {
  className: "TodosV1Client",
  apiKeyHeader: "x-api-key",
});

const generatedValidationMethod = `    /** Fail closed unless one prior accepted registration still matches its exact current resource */
    async validatePriorRegistrationAdoption(body: { "source_request": ProjectRegistrationRequest; "source_receipt": ProjectRegistrationReceipt; "current_record": Project | TaskList }, init?: RequestInit): Promise<{ "validation": PriorRegistrationAdoptionValidation }> {
      return this.request("POST", \`/v1/project-registration/validate-prior-adoption\`, {
        body,
        query: undefined,
        init,
      });
    }`;
const validatedValidationMethod = `    /** Fail closed unless one prior accepted registration still matches its exact current resource */
    async validatePriorRegistrationAdoption(body: { "source_request": ProjectRegistrationRequest; "source_receipt": ProjectRegistrationReceipt; "current_record": Project | TaskList }, init?: RequestInit): Promise<{ "validation": PriorRegistrationAdoptionValidation }> {
      const response = await this.request<unknown>("POST", \`/v1/project-registration/validate-prior-adoption\`, {
        body,
        query: undefined,
        init,
      });
      return {
        validation: assertTodosPriorRegistrationAdoptionValidationEnvelope(response, body),
      };
    }`;
if (!code.includes(generatedValidationMethod)) {
  throw new Error(
    "generated SDK prior-adoption method changed; refusing to emit a client without runtime validation",
  );
}
let validatedCode = code.replace(
  generatedValidationMethod,
  validatedValidationMethod,
);
const machineImportStart = 'return this.request("POST", `/v1/import`, {';
if (!validatedCode.includes(machineImportStart)) throw new Error("Generated importSnapshot method changed; refusing to omit machine capability validation");
validatedCode = validatedCode.replace(machineImportStart, `if (body.machines !== undefined && !Array.isArray(body.machines)) throw new Error("Invalid machine snapshot array; no snapshot was posted");
      if (body.machines?.length) {
        let capability;
        try { capability = await this.listMachines(init); }
        catch { throw new Error("REMOTE_API_INCOMPATIBLE: machine import requires an upgraded Todos server; no snapshot was posted"); }
        if (capability?.schema_version !== 2 || !Array.isArray(capability.machines) || !capability.authority || typeof capability.authority.tenant_id !== "string" || !capability.authority.tenant_id || typeof capability.authority.kid !== "string" || !capability.authority.kid) throw new Error("REMOTE_API_INCOMPATIBLE: machine registry capability is missing; no snapshot was posted");
        if (body.expected_machine_authority && (body.expected_machine_authority.kid !== capability.authority.kid || body.expected_machine_authority.tenant_id !== capability.authority.tenant_id)) throw new Error("Machine migration authority changed before POST; no snapshot was posted");
        body = { ...body, expected_machine_authority: { ...capability.authority } };
      }
      ${machineImportStart}`);
const importRequest = 'return this.request("POST", `/v1/import`, {\n        body,\n        query: undefined,\n        init,\n      });';
if (!validatedCode.includes(importRequest)) throw new Error("Generated import request changed; refusing to omit authority receipt validation");
validatedCode = validatedCode.replace(importRequest, `const result = await this.request<Awaited<ReturnType<TodosV1Client["importSnapshot"]>>>("POST", \`/v1/import\`, {
        body, query: undefined, init,
      });
      if (body.machines?.length && (result.machine_authority?.kid !== body.expected_machine_authority?.kid || result.machine_authority?.tenant_id !== body.expected_machine_authority?.tenant_id)) throw new Error("Machine receipt authority changed; preserve the source and inspect before retrying");
      return result;`);
const header =
  "// AUTO-GENERATED by scripts/generate-sdk.ts from src/server/openapi.ts — DO NOT EDIT BY HAND.\n" +
  "// Regenerate: bun run scripts/generate-sdk.ts\n\n" +
  "import { assertTodosPriorRegistrationAdoptionValidationEnvelope } from \"../project-registration/adoption-validation.js\";\n\n";
const outPath = join(root, "src/sdk/v1.generated.ts");
writeFileSync(outPath, header + validatedCode);

console.log(`Wrote ${outPath}`);
console.log(`Operations: ${operations.map((o) => o.functionName).join(", ")}`);
if (warnings.length) console.log(`Warnings:\n  ${warnings.join("\n  ")}`);
