// Generated by scripts/sdk-declarations.mjs; edit the canonical source instead.
/**
 * Create the HTTP store from an environment. Fails closed when the chain
 * resolves no credential. The key is never included in the returned object;
 * the transport re-resolves it per request.
 */
/** @param {import('../sdk/types.js').NotesEnvironment} [env] @param {typeof fetch} [fetchImpl] */
export function createNotesHttpStore(env?: import("../sdk/types.js").NotesEnvironment, fetchImpl?: typeof fetch): NotesHttpStore;
export class NotesHttpStoreError extends Error {
    /** @param {string} message @param {import('../sdk/types.js').NotesErrorOptions} [options] */
    constructor(message: string, { status, code, details }?: import("../sdk/types.js").NotesErrorOptions);
    status: number | undefined;
    code: string | undefined;
    details: unknown;
}
export class NotesHttpStore {
    /**
     * Direct config form: an explicit authority + credential pair (tier 1, a
     * pin the caller owns). An explicit baseUrl WITHOUT an apiKey throws — the
     * ambient fleet credential is never attached to an explicit authority
     * (#1794).
     */
    /** @param {import('../sdk/types.js').NotesStoreConfiguration} config @param {typeof fetch} [fetchImpl] */
    constructor(config: import("../sdk/types.js").NotesStoreConfiguration, fetchImpl?: typeof fetch);
    transport: "http";
    /** The origin the store talks to (the /v1 suffix is added by the transport base). */
    get apiUrl(): string;
    /** The `<origin>/v1` base the transport was built with. */
    get baseUrl(): string;
    /** @param {unknown} error @param {string} method @param {string} path @returns {NotesHttpStoreError} */
    mapTransportError(error: unknown, method: string, path: string): NotesHttpStoreError;
    /** @param {string} method @param {string} path @param {import('../sdk/types.js').NotesRequestOptions} [options] @returns {Promise<unknown>} */
    request(method: string, path: string, { body, query }?: import("../sdk/types.js").NotesRequestOptions): Promise<unknown>;
    /** @returns {Promise<import('../sdk/types.js').NotesHealth>} */
    health(): Promise<import("../sdk/types.js").NotesHealth>;
    /** @param {import('../sdk/types.js').NotesListOptions} [params] @returns {Promise<import('../sdk/types.js').NotesPage>} */
    listNotes(params?: import("../sdk/types.js").NotesListOptions): Promise<import("../sdk/types.js").NotesPage>;
    /** @param {string} id @returns {Promise<import('../sdk/types.js').Note>} */
    getNote(id: string): Promise<import("../sdk/types.js").Note>;
    /** @param {import('../sdk/types.js').NoteInput} input @returns {Promise<import('../sdk/types.js').Note>} */
    createNote(input: import("../sdk/types.js").NoteInput): Promise<import("../sdk/types.js").Note>;
    /** @param {string} id @param {import('../sdk/types.js').NoteUpdate} input @returns {Promise<import('../sdk/types.js').Note>} */
    updateNote(id: string, input: import("../sdk/types.js").NoteUpdate): Promise<import("../sdk/types.js").Note>;
    /** @param {string} id @returns {Promise<import('../sdk/types.js').NotesDeleteResult>} */
    deleteNote(id: string): Promise<import("../sdk/types.js").NotesDeleteResult>;
    /** @returns {Promise<import('../sdk/types.js').NotesExport>} */
    exportNotes(): Promise<import("../sdk/types.js").NotesExport>;
    #private;
}
