// Generated by scripts/sdk-declarations.mjs; edit the canonical source instead.
/** Read data properties only: credential getters must not be invoked on config. */
/** @param {object} object @param {string} key @returns {string | undefined} */
export function readPlainClientValue(object: object, key: string): string | undefined;
/** @param {import('../sdk/types.js').NotesEnvironment} env @param {string} key @returns {boolean} */
export function isPresent(env: import("../sdk/types.js").NotesEnvironment, key: string): boolean;
/**
 * A client process must not carry the server DSN: presence alone (even blank)
 * is a refusal, so a wrapper that sources both sides cannot quietly run a
 * client that believes it is configured. Presence is checked without copying
 * or normalising the env.
 */
/** @param {import('../sdk/types.js').NotesEnvironment} [env] @returns {void} */
export function assertNoClientDatabaseDsn(env?: import("../sdk/types.js").NotesEnvironment): void;
/**
 * Resolve the only client connection through the @hasna/contracts chain.
 * Values are never included in the report or in errors.
 *
 * `credentials` are @hasna/contracts CredentialChainOptions (an explicit
 * `apiKey`/`profile` and the `keychain` tier controls tests inject). They are
 * passed through untouched — the env itself is never copied.
 */
/** @param {import('../sdk/types.js').NotesEnvironment} [env] @param {import('@hasna/contracts/client').CredentialChainOptions} [credentials] @returns {import('../sdk/types.js').NotesTransportReport} */
export function resolveNotesClientTransport(env?: import("../sdk/types.js").NotesEnvironment, credentials?: import("@hasna/contracts/client").CredentialChainOptions): import("../sdk/types.js").NotesTransportReport;
/**
 * Build the authenticated HTTP transport for a resolved chain. Every request
 * re-resolves the credential through the chain (and re-validates that neither
 * the authority nor the credential changed since construction — see
 * `createClientTransport`), so a long-lived MCP server or SDK client picks up
 * a rotation without a restart. Retry is off: the notes store never retried
 * and its failure semantics are deterministic.
 */
/** @param {import('../sdk/types.js').NotesEnvironment} [env] @param {typeof fetch} [fetchImpl] @param {import('@hasna/contracts/client').CredentialChainOptions} [credentials] */
export function createNotesClientTransport(env?: import("../sdk/types.js").NotesEnvironment, fetchImpl?: typeof fetch, credentials?: import("@hasna/contracts/client").CredentialChainOptions): {
    transport: "http";
    client: import("@hasna/contracts/client").HasnaHttpTransport;
    resolution: import("@hasna/contracts/client").ClientTransportResolution;
};
/**
 * Build the transport for an EXPLICIT authority + credential pair (the direct
 * `NotesHttpStore` config form). Explicit arguments are tier 1: a pin the
 * caller owns. An explicit authority without an explicit credential THROWS —
 * the ambient fleet credential is never attached to an arbitrary baseUrl
 * (#1794).
 */
/** @param {{apiUrl?: string, apiKey?: string}} [config] @param {typeof fetch} [fetchImpl] */
export function createNotesExplicitTransport(config?: {
    apiUrl?: string;
    apiKey?: string;
}, fetchImpl?: typeof fetch): import("@hasna/contracts/client").HasnaHttpTransport;
/**
 * The credential VALUE as resolved by the same chain, used ONLY to redact
 * credential material a server or transport error echoes back. Never logged,
 * never returned in reports, never sent — the transport owns the header.
 * Empty when nothing resolved (the store refuses to exist in that case, so a
 * caller of this function only ever sees empty during a deliberate pivot).
 */
/** @param {import('../sdk/types.js').NotesEnvironment} [env] @param {import('@hasna/contracts/client').CredentialChainOptions} [credentials] @returns {string} */
export function resolveNotesClientCredential(env?: import("../sdk/types.js").NotesEnvironment, credentials?: import("@hasna/contracts/client").CredentialChainOptions): string;
export const NOTES_APP_SLUG: "notes";
export const NOTES_API_URL_ENV: "HASNA_NOTES_API_URL";
export const NOTES_API_KEY_ENV: "HASNA_NOTES_API_KEY";
export const NOTES_DATABASE_URL_ENV: "HASNA_NOTES_DATABASE_URL";
/** Canonical client variables. The resolver's own legacy alias handling applies. */
export const NOTES_API_URL_ENV_KEYS: string[];
export const NOTES_API_KEY_ENV_KEYS: string[];
export const NOTES_CLIENT_TRANSPORTS: string[];
