import { beforeAll, afterAll, expect, test } from "bun:test";
import { randomBytes } from "node:crypto";
import { mintApiKey, verifyApiKey } from "@hasna/contracts/auth";
import { createPgPool, createQueryClient, MigrationLedger, type PoolQueryClient } from "../../storage-kit/index.js";
import { emailsSelfHostedMigrations, DEFAULT_TENANT_ID } from "./migrations.js";
import { EmailsSelfHostedStore } from "./store.js";
import { WorkerSupervisorStore, workerFence } from "./worker-supervisor.js";
import { handleSelfHostedRequest, type SelfHostedServiceDeps } from "./service.js";
import { testAuthDeps } from "./auth/test-support.js";
const url = process.env.EMAILS_TEST_POSTGRES_URL, run = test.skipIf(!url), other = "00000000-0000-4000-8000-000000000038"; let db: PoolQueryClient;
beforeAll(async () => { if (!url) return; db = createQueryClient(createPgPool({ connectionString: url, env: { PGSSLMODE: "disable" } })); await db.execute("DROP SCHEMA IF EXISTS public CASCADE; CREATE SCHEMA public"); await new MigrationLedger(db, emailsSelfHostedMigrations()).migrate(); await db.execute("INSERT INTO tenants(id,name,slug,status) VALUES($1,'Other','worker-other','active')", [other]); }, 60000);
afterAll(async () => { await db?.close(); });
async function worker() { const backend = new WorkerSupervisorStore(db, DEFAULT_TENANT_ID), id = crypto.randomUUID(), token = randomBytes(32).toString("base64url"), fence = workerFence(id, { generation: 1, owner_token: token }); await backend.register(id, { owner_token: token, component: "scheduler", interval_ms: 1000 }); await backend.started(fence); return { backend, id, token, fence }; }
run("worker ownership is tenant scoped and only a hash is stored or exposed", async () => {
  const w = await worker(); const row = await db.one<{ owner_hash: string }>("SELECT owner_hash FROM runtime_workers WHERE tenant_id=$1 AND id=$2", [DEFAULT_TENANT_ID, w.id]); expect(row.owner_hash).not.toBe(w.token); expect(row.owner_hash).toHaveLength(64); expect(JSON.stringify(await w.backend.list())).not.toContain(w.token); expect(JSON.stringify(await w.backend.list())).not.toContain("owner_hash"); await expect(new WorkerSupervisorStore(db, other).heartbeat(w.fence)).rejects.toThrow("ownership"); await expect(w.backend.heartbeat({ ...w.fence, ownerHash: "0".repeat(64) })).rejects.toThrow("ownership");
});
run("restart requests are concurrent/idempotent and require actual drain plus replacement start", async () => {
  const w = await worker(), operationId = crypto.randomUUID(), key = crypto.randomUUID(); expect((await w.backend.beginOperation(w.fence, operationId)).claimed).toBe(true);
  const [a, b] = await Promise.all([w.backend.restart(w.id, key), w.backend.restart(w.id, key)]); expect(a.id).toBe(b.id); expect(a.status).toBe("draining"); await expect(w.backend.drain(w.fence, false)).rejects.toThrow("In-flight"); expect((await w.backend.heartbeat(w.fence)).state).toBe("draining");
  await w.backend.finishOperation(w.fence, operationId, { outcome: "returned", http_status: 200 }); const next = await w.backend.drain(w.fence, false); expect(next.generation).toBe(2); expect((await w.backend.restartStatus(w.id, key)).status).toBe("starting"); await expect(w.backend.heartbeat(w.fence)).rejects.toThrow("generation"); await w.backend.started({ ...w.fence, generation: 2 }); expect(await w.backend.restart(w.id, key)).toMatchObject({ status: "complete", old_generation: 1, new_generation: 2 });
});
run("actual scheduled and sequence claims fence draining and stale worker generations atomically", async () => {
  const w = await worker(), root = new EmailsSelfHostedStore(db), store = root.forTenant(DEFAULT_TENANT_ID).withWorkerFence(w.fence), scheduled = crypto.randomUUID(), second = crypto.randomUUID(), sequence = crypto.randomUUID(), enrollment = crypto.randomUUID();
  await db.execute("INSERT INTO scheduled_emails(id,tenant_id,scheduled_at,status) VALUES($1,$3,now()-interval '1 minute','pending'),($2,$3,now()-interval '1 minute','pending')", [scheduled, second, DEFAULT_TENANT_ID]); expect(await store.claimDueScheduled(1)).toHaveLength(1);
  await db.execute("INSERT INTO sequences(id,tenant_id,name,status) VALUES($1,$2,'Fixture','active')", [sequence, DEFAULT_TENANT_ID]); await db.execute("INSERT INTO sequence_enrollments(id,tenant_id,sequence_id,contact_email,status,next_send_at) VALUES($1,$2,$3,'fixture@example.test','active',now()-interval '1 minute')", [enrollment, DEFAULT_TENANT_ID, sequence]);
  await w.backend.restart(w.id, crypto.randomUUID()); expect(await store.claimDueScheduled(1)).toEqual([]); expect(await store.sequenceWorker().claim(1)).toEqual([]); const next = await w.backend.drain(w.fence, false); await w.backend.started({ ...w.fence, generation: next.generation }); expect(await store.claimDueScheduled(1)).toEqual([]); expect(await root.forTenant(DEFAULT_TENANT_ID).withWorkerFence({ ...w.fence, generation: 2 }).sequenceWorker().claim(1)).toHaveLength(1);
  // Clear only synthetic pending fixtures so subsequent real handler ticks never attempt a send.
  await db.execute("UPDATE scheduled_emails SET status='cancelled' WHERE tenant_id=$1", [DEFAULT_TENANT_ID]); await db.execute("UPDATE sequence_enrollments SET status='cancelled' WHERE tenant_id=$1", [DEFAULT_TENANT_ID]);
});
function fixture() { const secret = crypto.randomUUID(); let sends = 0; const deps = { client: db, store: new EmailsSelfHostedStore(db), verifier: verifyApiKey({ app: "emails", signingSecret: secret, keyStatus: async () => "active" }), version: "fixture", migrations: [], ...testAuthDeps(db, secret), env: {}, sender: { provider: "ses", send: async () => { sends++; throw Error("No synthetic fixture may send"); } } } as SelfHostedServiceDeps; return { deps, secret, get sends() { return sends; }, request: async (path: string, body?: unknown, scopes = ["emails:*"]) => handleSelfHostedRequest(deps, new Request(`https://fixture${path}`, { method: body === undefined ? "GET" : "POST", headers: { authorization: `Bearer ${mintApiKey({ app: "emails", scopes, signingSecret: secret }).token}`, "content-type": "application/json" }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) })) }; }
run("actual operator API tick returns a durable replayable receipt while reader/writer controls fail", async () => {
  const w = await worker(), f = fixture(), request_id = crypto.randomUUID(), body = { action: "tick", owner_token: w.token, generation: 1, request_id };
  for (const scopes of [["emails:read"], ["emails:write"]]) { expect((await f.request(`/v1/workers/${w.id}/control`, body, scopes))!.status).toBe(403); expect((await f.request('/v1/workers', undefined, scopes))!.status).toBe(403); }
  const first = (await f.request(`/v1/workers/${w.id}/control`, body))!; expect(first.status).toBe(200); const receipt = await first.json(); expect(receipt.operation).toMatchObject({ id: request_id, status: "complete", generation: 1 }); expect(await (await f.request(`/v1/workers/${w.id}/control`, body))!.json()).toEqual(receipt); expect(f.sends).toBe(0); expect(JSON.stringify(receipt)).not.toContain(w.token);
});
run("expired ownership cannot heartbeat, claim or fake restart but server completion can still settle", async () => {
  const w = await worker(), id = crypto.randomUUID(); await w.backend.beginOperation(w.fence, id); await db.execute("UPDATE runtime_workers SET lease_until=now()-interval '1 second' WHERE tenant_id=$1 AND id=$2", [DEFAULT_TENANT_ID, w.id]); await expect(w.backend.heartbeat(w.fence)).rejects.toThrow("expired"); await expect(w.backend.restart(w.id, crypto.randomUUID())).rejects.toThrow("actively owned"); await expect(w.backend.drain(w.fence, false)).rejects.toThrow("expired"); expect((await w.backend.finishOperation(w.fence, id, { outcome: "returned" })).status).toBe("complete"); expect((await w.backend.list()).find(row => row.id === w.id)?.lease_fresh).toBe(false);
});
run("two actual CLI processes start, cooperatively restart and drain a foreground worker without real sends", async () => {
  const { mkdtemp, rm } = await import("node:fs/promises"), { tmpdir } = await import("node:os"), { join } = await import("node:path"); const home = await mkdtemp(join(tmpdir(), "emails-supervisor-cli-")), f = fixture(), id = crypto.randomUUID(), key = crypto.randomUUID();
  const server = Bun.serve({ hostname: "127.0.0.1", port: 0, fetch: async req => (await handleSelfHostedRequest(f.deps, req)) ?? new Response(null, { status: 404 }) });
  const env = Object.fromEntries(Object.entries(process.env).filter(([name]) => !name.startsWith("EMAILS_") && !name.startsWith("HASNA_EMAILS_"))); Object.assign(env, { HOME: home, HASNA_EMAILS_HOME: home, EMAILS_HOME: home, HASNA_EMAILS_API_URL: server.url.origin, HASNA_EMAILS_API_KEY: mintApiKey({ app: "emails", scopes: ["emails:*"], signingSecret: f.secret }).token, EMAILS_CLIENT_ENV_LOADED: "1", NO_COLOR: "1" });
  const start = Bun.spawn({ cmd: [process.execPath, "--no-env-file", "src/cli/index.tsx", "--json", "daemon", "start", "--worker", id, "--interval", "1"], env, stdout: "pipe", stderr: "pipe" }); let stdout = ""; const stderr = new Response(start.stderr).text(); const pump = (async () => { for await (const bytes of start.stdout) { stdout += new TextDecoder().decode(bytes); } })();
  try {
    const deadline = Date.now() + 10000; while (!stdout.includes('"started"') && Date.now() < deadline) await new Promise(r => setTimeout(r, 20)); expect(stdout).toContain('"started"');
    const restart = Bun.spawn({ cmd: [process.execPath, "--no-env-file", "src/cli/index.tsx", "--json", "daemon", "restart", "--worker", id, "--idempotency-key", key, "--timeout", "10"], env, stdout: "pipe", stderr: "pipe" }); const [code, out, err] = await Promise.all([restart.exited, new Response(restart.stdout).text(), new Response(restart.stderr).text()]); expect(code).toBe(0); expect(err).toBe(""); expect(JSON.parse(out)).toMatchObject({ restarted: true, restart: { old_generation: 1, new_generation: 2, status: "complete" } });
    start.kill("SIGTERM"); expect(await start.exited).toBe(0); await pump; expect(await stderr).toBe(""); expect(stdout).toContain('"stopped"'); expect(stdout).not.toContain("owner_token"); expect((await new WorkerSupervisorStore(db, DEFAULT_TENANT_ID).list()).find(row => row.id === id)).toMatchObject({ state: "stopped", generation: 2 }); expect(f.sends).toBe(0);
  } finally { if (start.exitCode === null) start.kill("SIGKILL"); await start.exited; await pump; server.stop(true); await rm(home, { recursive: true, force: true }); }
}, 30000);
run("a confirmed stopped registration can acquire a new owner and generation without reusing its token", async () => {
  const w = await worker(); await w.backend.stopRequest(w.fence); await w.backend.drain(w.fence, true); const replacement = randomBytes(32).toString("base64url"), next = await w.backend.register(w.id, { owner_token: replacement, component: "scheduler", interval_ms: 2000 }); expect(next).toMatchObject({ generation: 2, state: "starting", interval_ms: 2000 }); await expect(w.backend.heartbeat(w.fence)).rejects.toThrow("ownership"); expect((await w.backend.started(workerFence(w.id, { generation: 2, owner_token: replacement }))).state).toBe("running");
  const secondFence = workerFence(w.id, { generation: 2, owner_token: replacement }), requestId = crypto.randomUUID(); await w.backend.restart(w.id, requestId); await w.backend.drain(secondFence, false);
  await db.execute("UPDATE runtime_workers SET lease_until=clock_timestamp()-interval '1 second' WHERE tenant_id=$1 AND id=$2", [DEFAULT_TENANT_ID, w.id]);
  const recoveryToken = randomBytes(32).toString("base64url"), recovered = await w.backend.register(w.id, { owner_token: recoveryToken, component: "scheduler", interval_ms: 2000 }); expect(recovered).toMatchObject({ generation: 3, state: "starting", restart_id: requestId }); await w.backend.started(workerFence(w.id, { generation: 3, owner_token: recoveryToken })); expect(await w.backend.restartStatus(w.id, requestId)).toMatchObject({ status: "complete", old_generation: 2, new_generation: 3 });

});
