import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dir, "../../../..");
const workflow = readFileSync(join(root, ".github/workflows/files-current-server-deploy.yml"), "utf8");
const rollout = readFileSync(join(root, "tooling/deploy/files-current/verify-ecs-rollout.sh"), "utf8");
const ledgerProbe = readFileSync(join(root, "tooling/deploy/files-current/ledger-probe.sh"), "utf8");
const migrationRunner = readFileSync(join(root, "tooling/deploy/files-current/run-migration.sh"), "utf8");
const readiness = readFileSync(join(root, "tooling/deploy/files-current/verify-readiness.sh"), "utf8");
const dataPlane = readFileSync(join(root, "tooling/deploy/files-current/verify-canonical-data-plane.sh"), "utf8");
const restore = readFileSync(join(root, "tooling/deploy/files-current/restore-service-anchor.sh"), "utf8");

describe("Files current-server deployment lane", () => {
  test("is manual, exact-current-main, and CI-bound", () => {
    expect(workflow).toContain("name: files-current-server-deploy");
    expect(workflow).toContain("workflow_dispatch: {}");
    expect(workflow).not.toMatch(/^\s+push:/m);
    expect(workflow).not.toMatch(/^\s+workflow_run:/m);
    expect(workflow).toContain("refs/remotes/origin/main");
    expect(workflow).toContain("head_sha=${source_sha}");
    expect(workflow).toContain('conclusion == "success"');
    expect(workflow).toContain('[[ "${GITHUB_SHA}" == "${main_tip}" ]]');
    expect(workflow).toContain('source_sha="${GITHUB_SHA}"');
    expect(workflow).toContain('[[ "$(git rev-parse HEAD)" == "${GITHUB_SHA}" ]]');
  });

  test("builds and scans the exact ARM64 Files server before AWS authority", () => {
    const build = workflow.indexOf("Build native ARM64 image locally");
    const scan = workflow.indexOf("Enforce local vulnerability gate");
    const authority = workflow.indexOf("Configure AWS credentials with GitHub OIDC");
    expect(build).toBeGreaterThan(0);
    expect(scan).toBeGreaterThan(build);
    expect(authority).toBeGreaterThan(scan);
    expect(workflow).toContain("--platform linux/arm64");
    expect(workflow).toContain("--target runner");
    expect(workflow).toContain("dist/server/index.js --version");
    expect(workflow).toContain("role/files-prod-gha-deploy");
    expect(workflow).not.toMatch(/npm publish|bun publish/);
  });

  test("uses only the Files manifest targets, digest pins both tasks, and proves readiness", () => {
    expect(workflow).toContain("DEPLOY_MANIFEST: /hasna/deploy/files");
    expect(workflow).toContain("EXPECTED_SERVICE: files-prod");
    expect(workflow).toContain("EXPECTED_ECR_REPOSITORY: open-files");
    expect(workflow).toContain("EXPECTED_MIGRATION_FAMILY: files-prod-migrate");
    expect(workflow).toContain('digest_image=%s@%s');
    expect(workflow).toContain('deploymentCircuitBreaker={enable=true,rollback=false}');
    expect(workflow).toContain('ready_url="${HEALTH_URL%/health}/ready"');
    expect(workflow).toContain('https://api.hasna.com/files/ready');
    expect(workflow).toContain('verify-canonical-data-plane.sh');
    expect(workflow).toContain('https://api.hasna.com/files');
    expect(workflow).toContain('canonical_data_plane:$data_plane_canonical[0]');
    expect(workflow).toContain("hasna.files.production_deploy.v1");
    expect(workflow).toContain('describe-task-definition --task-definition "${PREVIOUS_TASK_DEFINITION}"');
    expect(workflow).not.toContain('describe-task-definition --task-definition "${WEB_FAMILY}"');
    const anchorCheck = workflow.indexOf("assert-service-anchor.sh");
    const mutation = workflow.indexOf("aws ecs update-service", anchorCheck);
    expect(anchorCheck).toBeGreaterThan(0);
    expect(mutation).toBeGreaterThan(anchorCheck);
    expect(readiness).toContain("--max-redirs 0");
    expect(readiness).toContain('HTTP_STATUS" == "200"');
    expect(readiness).toContain('.status == "ok" and .storage == "postgres" and .version == $version');
    expect(readiness).toContain('.deployment_environment == "production"');
    expect(readiness).toContain('.source_commit == $source');
    expect(readiness).toContain('.image_digest == $digest');
    expect(readiness).not.toContain('has("source_commit") | not');
    expect(dataPlane).toContain('/v1/knowledge/manifest?limit=1');
    expect(dataPlane).toContain('credentials_sent:false');
    expect(dataPlane).toContain('credentials_sent:true');
    expect(dataPlane).toContain('authenticated_manifest');
    expect(dataPlane).toContain('files.knowledge.manifest.v1');
    expect(dataPlane).toContain('--header "@${HEADER_FILE}"');
    expect(dataPlane).toContain('double_v1_paths:0');
    expect(workflow).toContain('FILES_CLIENT_KEY_SECRET_ID: hasna/oss/files/api-key');
    expect(workflow).toContain('Resolve authenticated receipt credential before mutation');
    expect(workflow).toContain('aws secretsmanager get-secret-value');
    expect(workflow).toContain('Remove authenticated receipt credential');
    expect(workflow).toContain('apps/files/data-plane-canonical.json');
    const credentialPreflight = workflow.indexOf('Resolve authenticated receipt credential before mutation');
    const authorityStep = workflow.indexOf("Configure AWS credentials with GitHub OIDC");
    expect(credentialPreflight).toBeGreaterThan(authorityStep);
    expect(credentialPreflight).toBeLessThan(mutation);
    expect(workflow).toContain('HASNA_FILES_DEPLOY_SOURCE_COMMIT');
    expect(workflow).toContain('HASNA_FILES_DEPLOY_IMAGE_DIGEST');
    expect(workflow).toContain('deployed_source_commit');
    expect(workflow).toContain('deployed_image_digest');
    expect(rollout).toContain('LIVE_TD" != "$EXPECTED_TASK_DEF');
  });

  test("binds migration ledger state and never rolls an advanced schema to an unproven binary", () => {
    const before = workflow.indexOf("Capture exact pre-migration ledger receipt");
    const migrate = workflow.indexOf("Run one-shot migration task on the exact digest");
    const after = workflow.indexOf("Capture exact post-migration ledger receipt");
    const classify = workflow.indexOf("Classify migration result and refuse uncertain state");
    const deploy = workflow.indexOf("Register digest-pinned task definition and update service");
    expect(before).toBeGreaterThan(0);
    expect(migrate).toBeGreaterThan(before);
    expect(after).toBeGreaterThan(migrate);
    expect(classify).toBeGreaterThan(after);
    expect(deploy).toBeGreaterThan(classify);
    expect(workflow).toContain("hasna.files.migration_uncertain_state.v1");
    expect(workflow).toContain("hasna.files.deployment_reconciliation_required.v1");
    expect(workflow).toContain('compatibility:"unproven_against_advanced_schema"');
    expect(workflow).toContain("automatic_rollback_performed:false");
    expect(workflow).toContain("steps.ledger-classify.outputs.schema_advanced == 'false'");
    expect(workflow).toContain("steps.ledger-classify.outputs.schema_advanced == 'true'");
    expect(workflow).not.toContain("Restore rollback anchor after a failed service rollout");
    expect(workflow).toContain("restore-service-anchor.sh");
    expect(restore).toContain("concurrent_service_change_before_rollback");
    expect(restore).toContain('automatic_rollback_performed:false');
    expect(restore.indexOf("describe-services")).toBeLessThan(restore.indexOf("update-service"));
    expect(ledgerProbe).toContain("SELECT id, checksum FROM schema_migrations ORDER BY id ASC");
    expect(ledgerProbe).toContain("applied ledger is unknown to or checksum-incompatible with this candidate");
    expect(ledgerProbe).toContain("ledger probe task identity mismatch");
    expect(ledgerProbe).not.toMatch(/echo[^\n]*HASNA_FILES_DATABASE_URL/);
  });
});
