import type { Scenario } from "./adversarial-types.js";

const note = "Synthetic hard terminal workload with preserved critical markers.";
const rep = (count: number, fn: (i: number) => string): string => Array.from({ length: count }, (_, i) => fn(i + 1)).join("\n");
const join = (...parts: string[]): string => parts.join("\n");
const count = (seed: number, base: number, step: number, mod: number): number => base + (seed % mod) * step;

function packageInstallOutput(): string {
  return join(rep(45, (i) => `npm warn deprecated package-${i}@1.0.0: use package-${i + 1}`), "added 847 packages in 12s", "", "143 packages are looking for funding", "  run `npm fund` for details", "", "found 0 vulnerabilities");
}

function passingTestsOutput(): string {
  return join("bun test v1.3.13", rep(180, (i) => `src/module-${i}.test.ts: pass ${i} should preserve behavior`), "", "180 pass", "0 fail", "360 expect() calls");
}

function failingStackOutput(): string {
  return join("FAIL src/auth/session.test.ts", "  login refreshes expired token", "TypeError: Cannot read properties of undefined (reading 'expiresAt')", rep(70, (i) => `    at frame${i} (/repo/src/auth/session.ts:${20 + i}:13)`), "", "1 fail", "42 pass");
}

const typescriptErrorsOutput = () => rep(44, (i) => `${i % 2 === 0 ? "src/api/client.ts" : "src/ui/App.tsx"}:${10 + i}:7 - error TS${2300 + i}: Type 'unknown' is not assignable to type 'Session${i}'.`);
const lintErrorsOutput = () => rep(32, (i) => `/repo/src/file-${i}.ts:${i}:3  error  ${["no-floating-promises", "no-unused-vars", "react-hooks/exhaustive-deps"][i % 3]}  eslint`);
const gitStatusOutput = () => join("On branch main", "Your branch is up to date with 'origin/main'.", "", "Changes not staged for commit:", rep(18, (i) => `  modified:   src/feature-${i}.ts`), "", "Untracked files:", rep(9, (i) => `  src/new-test-${i}.test.ts`));
const gitDiffOutput = () => join("diff --git a/src/billing.ts b/src/billing.ts", "index 1234567..89abcde 100644", "--- a/src/billing.ts", "+++ b/src/billing.ts", rep(260, (i) => i % 2 === 0 ? `+ const changed${i} = calculate(${i});` : `- const old${i} = calculateOld(${i});`), "src/billing.ts | 260 +++++++++++++++++++++++++++++++++------------------------");
const gitShowOutput = () => join("commit abcdef1234567890", "Author: Dev <dev@example.com>", "Date: Sun May 3 21:00:00 2026 +0300", "", "    fix: preserve critical terminal errors", "", rep(80, (i) => ` src/file-${i}.ts | ${i % 10} +-${i % 7}`));
const searchOutput = () => rep(140, (i) => `src/module-${i % 25}.ts:${i}:export const value${i} = createThing("${"x".repeat(90)}");`);
const fileListingOutput = () => join(rep(60, (i) => `./src/components/component-${String(i).padStart(3, "0")}.tsx`), rep(45, (i) => `./node_modules/package-${i % 5}/dist/index-${i}.js`), rep(25, (i) => `./.next/cache/chunk-${i}.json`));
const hugeOutput = () => rep(1200, (i) => `[${i}] build-worker-${i % 8}: processed package-${i % 120} in ${i % 17}ms`);
const compactJsonOutput = () => JSON.stringify({ ok: true, changed: 1, tests: { pass: 12, fail: 0 } });
const fullDetailOutput = () => join("Security review found 4 call sites requiring manual inspection.", rep(90, (i) => `src/security/path-${i}.ts:${i}: userControlledInput flows into execute(${i}) with sanitizer=${i % 4 === 0 ? "missing" : "present"}`), "Manual review required: do not summarize away individual call sites.");
const providerRateLimitOutput = () => join("cerebras API error 429: queue_exceeded", "Falling back to CPU compression.", rep(55, (i) => `Compilation note ${i}: generated declaration for package-${i}`));
const coldCacheOutput = () => join("Natural language prompt: show me every auth-related file and failing test", "Cache miss: no learned prompt-to-command mapping yet", "AI translated command: rg -n 'auth|session|token' src tests", rep(50, (i) => `src/auth/file-${i % 8}.ts:${i}: token auth session reference ${i}`));
const criticalErrorTrapOutput = () => join("PASS src/safe.test.ts", "FAIL src/migrations/prod.test.ts", "FATAL: migration would drop table users in production", "DETAIL: generated SQL contains DROP TABLE users;", rep(40, (i) => `    at migrationFrame${i} (/repo/src/db/migrate.ts:${100 + i}:9)`), "1 fail, 19 pass");

const base = (scenario: Scenario): Scenario => scenario;

function curatedScenarios(): Scenario[] {
  const repeatedA = rep(120, (i) => `PASS test ${i}`) + "\nFAIL payment retries after timeout\nTests: 119 passed, 1 failed";
  const repeatedB = rep(120, (i) => `PASS test ${i}`) + "\nPASS payment retries after timeout\nTests: 120 passed, 0 failed";
  return [
    base({ id: "tests-pass", workflow: "tests passing", category: "tests", command: "bun test", weight: 8, raw: passingTestsOutput(), strategy: "structured", compact: "bun test: 180 pass, 0 fail, 360 expect() calls", provider: "none", expansionRate: 0.02, requiredPatterns: ["180 pass", "0 fail"], notes: "Passing test output should collapse to counts but preserve pass/fail truth." }),
    base({ id: "tests-fail-stack", workflow: "tests failing with stack traces", category: "tests", command: "bun test", weight: 10, raw: failingStackOutput(), strategy: "structured", compact: "FAIL src/auth/session.test.ts\nTypeError: Cannot read properties of undefined (reading 'expiresAt')\nFirst stack: /repo/src/auth/session.ts:21:13\n1 fail, 42 pass", provider: "groq", expansionRate: 0.35, progressiveExpansionRate: 0.18, progressiveExpansionTokenCap: 220, requiredPatterns: ["FAIL src/auth/session.test.ts", "TypeError", "expiresAt", "1 fail"], notes: "Failure summaries often need some stack expansion." }),
    base({ id: "ts-build-errors", workflow: "typescript/build errors", category: "build", command: "bun run build", weight: 7, raw: typescriptErrorsOutput(), strategy: "structured", compact: "44 TypeScript errors across src/api/client.ts and src/ui/App.tsx\nTop: TS2301 unknown not assignable to Session1\nRun expand for full list.", provider: "cerebras", expansionRate: 0.45, progressiveCompact: "44 TypeScript errors across 2 files. First per file: src/api/client.ts:12 TS2301; src/ui/App.tsx:11 TS2300. Full diagnostics stored; expand with offset/limit.", progressiveExpansionRate: 0.18, progressiveExpansionTokenCap: 260, requiredPatterns: ["44 TypeScript errors", "TS2301", "expand"], notes: "Build errors compress, but fixing often needs more than one diagnostic." }),
    base({ id: "lint-errors", workflow: "lint errors", category: "lint", command: "bun run lint", weight: 4, raw: lintErrorsOutput(), strategy: "structured", compact: "32 lint errors: no-floating-promises, no-unused-vars, react-hooks/exhaustive-deps. Top files: file-1.ts, file-2.ts, file-3.ts.", provider: "groq", expansionRate: 0.3, progressiveCompact: "32 lint errors grouped by rule: no-floating-promises, no-unused-vars, react-hooks/exhaustive-deps. First files: file-1.ts, file-2.ts, file-3.ts. Expand by rule.", progressiveExpansionRate: 0.12, progressiveExpansionTokenCap: 120, requiredPatterns: ["32 lint errors", "no-floating-promises"], notes: "Lint output is repetitive but individual files may still matter." }),
    base({ id: "git-status", workflow: "git status/log/diff/show", category: "git", command: "git status", weight: 6, raw: gitStatusOutput(), strategy: "structured", compact: "On branch main, up to date. 18 modified files, 9 untracked files.", provider: "none", expansionRate: 0.15, progressiveExpansionRate: 0.05, progressiveExpansionTokenCap: 60, requiredPatterns: ["main", "18 modified", "9 untracked"], notes: "Structured git status saves tokens but users may inspect file names." }),
    base({ id: "git-diff", workflow: "git status/log/diff/show", category: "git", command: "git diff", weight: 9, raw: gitDiffOutput(), strategy: "structured", compact: "src/billing.ts changed: 130 additions, 130 removals. Full diff required before commit.", provider: "none", expansionRate: 1, progressiveCompact: "src/billing.ts changed: 130 additions, 130 removals. Full diff required, stored as line-window chunks; hunk manifest says calculate() replaced calculateOld().", progressiveExpansionRate: 0.2, progressiveExpansionTokenCap: 420, requiredPatterns: ["src/billing.ts", "Full diff required"], notes: "A commit decision often requires full diff expansion, which can wipe out savings." }),
    base({ id: "git-show", workflow: "git status/log/diff/show", category: "git", command: "git show --stat HEAD", weight: 3, raw: gitShowOutput(), strategy: "structured", compact: "abcdef1 fix: preserve critical terminal errors. 80 files touched. Use expand for full stat.", provider: "none", expansionRate: 0.25, progressiveExpansionRate: 0.1, progressiveExpansionTokenCap: 120, requiredPatterns: ["abcdef1", "80 files"], notes: "Commit inspection usually benefits from a stat-level first pass." }),
    base({ id: "rg-search", workflow: "rg/search results", category: "search", command: "rg -n export src", weight: 8, raw: searchOutput(), strategy: "structured", compact: "140 matches across 25 files. Showing top files only: module-0.ts, module-1.ts, module-2.ts. Results truncated; narrow the query or expand.", provider: "none", expansionRate: 0.35, progressiveCompact: "140 matches across 25 files. Top files: module-0.ts, module-1.ts, module-2.ts. Results truncated; use expand with offset/limit or narrow query.", progressiveExpansionRate: 0.14, progressiveExpansionTokenCap: 360, requiredPatterns: ["140 matches", "25 files", "truncated"], notes: "Search cannot claim perfect savings because agents often refine or expand." }),
    base({ id: "file-listing", workflow: "file listings and trees", category: "files", command: "find . -type f", weight: 5, raw: fileListingOutput(), strategy: "smart-display", provider: "none", expansionRate: 0.1, progressiveExpansionRate: 0.04, progressiveExpansionTokenCap: 120, requiredPatterns: ["node_modules"], notes: "Smart display groups paths but should not hide that dependency noise existed." }),
    base({ id: "package-install", workflow: "package installs", category: "install", command: "bun install", weight: 3, raw: packageInstallOutput(), strategy: "noise", provider: "none", expansionRate: 0, requiredPatterns: ["added 847 packages"], notes: "Install logs contain much removable noise, but useful success lines remain." }),
    base({ id: "command-retry", workflow: "command retries", category: "execution", command: "rg auth src --glob '*.tsx'", weight: 5, raw: "rg: regex parse error: unclosed character class\nretry: rg -n 'auth' src --glob '*.tsx'\nsrc/auth/Login.tsx:12:export function Login() {}", strategy: "structured", compact: "First command failed: regex parse error. Retried safely. 1 auth match in src/auth/Login.tsx:12.", provider: "groq", progressiveProvider: "none", progressiveCompact: "regex parse error; Retried safely; src/auth/Login.tsx:12", expansionRate: 0.1, retryOverhead: "retry prompt and validation overhead", progressiveRetryOverhead: "", requiredPatterns: ["regex parse error", "Retried", "src/auth/Login.tsx:12"], notes: "Retry loops add overhead that optimistic output-only benchmarks miss." }),
    base({ id: "repeated-test-diff", workflow: "repeated test loops with small diffs", category: "tests", command: "bun test", weight: 8, previous: repeatedA, raw: repeatedB, strategy: "diff", provider: "none", expansionRate: 0.05, requiredPatterns: ["payment retries", "120 passed"], notes: "Diff cache is one of the strongest legitimate savings paths." }),
    base({ id: "huge-output", workflow: "huge output", category: "huge", command: "bun run build --verbose", weight: 4, raw: hugeOutput(), strategy: "compress", maxTokens: 220, provider: "none", expansionRate: 0.2, progressiveExpansionRate: 0.08, progressiveExpansionTokenCap: 480, requiredPatterns: ["build-worker"], notes: "Huge repetitive output compresses well, but expansion is still sometimes needed." }),
    base({ id: "small-output", workflow: "small output where compression should not claim savings", category: "small", command: "pwd", weight: 7, raw: "/home/hasna/workspace/repos/hasna/apps/apps/terminal", strategy: "passthrough", provider: "none", expansionRate: 0, notes: "Small output should honestly report no meaningful savings." }),
    base({ id: "compact-json", workflow: "already-compact/non-compressible output", category: "small", command: "terminal snapshot --json", weight: 4, raw: compactJsonOutput(), strategy: "passthrough", provider: "none", expansionRate: 0, requiredPatterns: ["ok"], notes: "Already-compact data should not be counted as a win." }),
    base({ id: "full-detail-required", workflow: "output where full detail is required", category: "detail", command: "security review", weight: 6, raw: fullDetailOutput(), strategy: "structured", compact: "Security review found 4 risky call sites. Manual review required; expand for every call site.", provider: "cerebras", expansionRate: 1, progressiveCompact: "Security review found 4 risky and 90 total call sites. Manual review required; line manifest stored, expand by grep/offset/limit.", progressiveExpansionRate: 0.22, progressiveExpansionTokenCap: 520, requiredPatterns: ["Manual review required", "expand"], notes: "Full-detail workflows can be net negative after summarization overhead." }),
    base({ id: "provider-unavailable", workflow: "AI provider unavailable/rate-limited", category: "provider", command: "terminal execute_smart 'bun run build'", weight: 3, raw: providerRateLimitOutput(), strategy: "compress", maxTokens: 120, provider: "cerebras", providerUnavailable: true, expansionRate: 0.2, progressiveExpansionRate: 0.08, progressiveExpansionTokenCap: 120, requiredPatterns: ["429", "Falling back"], notes: "Rate limits force fallback behavior and should not assume AI success." }),
    base({ id: "cold-cache", workflow: "cache miss/cold start", category: "cache", command: "terminal 'show auth files'", weight: 6, raw: coldCacheOutput(), strategy: "structured", compact: "Cache miss: translated prompt to rg auth/session/token. 50 matches across 8 auth files.", provider: "groq", expansionRate: 0.25, retryOverhead: "NL translation prompt overhead before cache is warm", progressiveCompact: "Cache miss: translated prompt to rg auth/session/token. 50 matches across 8 auth files. Learned mapping recorded for next run; expand with offset/limit.", progressiveExpansionRate: 0.1, progressiveExpansionTokenCap: 160, requiredPatterns: ["Cache miss", "50 matches"], notes: "Cold starts include prompt translation cost that repeated-cache claims skip." }),
    base({ id: "expansion-followup", workflow: "expansion/full-output follow-up cost", category: "detail", command: "terminal expand detail-key", weight: 4, raw: searchOutput(), strategy: "structured", compact: "Search summary looked insufficient; agent requested full expansion.", provider: "none", expansionRate: 1, progressiveCompact: "Expansion returned indexed page 1: 140 matches across 25 files, first 20 line refs, full output remains stored for offset/limit paging.", progressiveExpansionRate: 0.16, progressiveExpansionTokenCap: 420, notes: "The second call returns the full output, so savings should be near zero or negative." }),
    base({ id: "critical-error-trap", workflow: "summary inaccuracies or missing critical errors", category: "quality", command: "bun test src/migrations/prod.test.ts", weight: 7, raw: criticalErrorTrapOutput(), strategy: "structured", compact: "FAIL src/migrations/prod.test.ts\nFATAL: migration would drop table users in production\nDETAIL: generated SQL contains DROP TABLE users;\n1 fail, 19 pass", provider: "groq", expansionRate: 0.6, progressiveExpansionRate: 0.22, progressiveExpansionTokenCap: 260, requiredPatterns: ["FATAL", "DROP TABLE users", "1 fail"], notes: "The benchmark fails quality if critical failure markers disappear." }),
  ];
}

const stressRaw = {
  pass: (s: number) => join("bun test v1.3.13", rep(count(s, 90, 11, 14), (i) => `packages/pkg-${s % 9}/src/case-${i}.test.ts: pass ${i} scenario ${s}`), "", `${count(s, 90, 11, 14)} pass`, "0 fail", `${count(s, 90, 11, 14) * 2} expect() calls`),
  fail: (s: number) => join(`FAIL src/agents/runner-${s % 11}.test.ts`, `  should recover interrupted command ${s}`, `AssertionError: expected token budget ${s} to be below cap`, rep(count(s, 24, 6, 12), (i) => `    at recover${i} (/repo/src/agents/runner-${s % 11}.ts:${40 + i}:17)`), "", "1 fail", `${35 + s % 30} pass`),
  build: (s: number) => rep(count(s, 18, 4, 12), (i) => `${["src/server/api.ts", "src/client/ui.tsx", "src/db/schema.ts"][i % 3]}:${20 + i}:11 - error TS${2300 + ((s + i) % 90)}: Type 'Generated${s}_${i}' is not assignable to type 'Expected${i}'.`),
  lint: (s: number) => rep(count(s, 24, 5, 12), (i) => `/repo/src/workflow-${s % 8}/file-${i}.ts:${i + 3}:5  error  ${["no-floating-promises", "no-unused-vars", "react-hooks/exhaustive-deps", "prefer-const"][(s + i) % 4]}  eslint`),
  status: (s: number) => join("On branch main", "Your branch is up to date with 'origin/main'.", "", "Changes not staged for commit:", rep(count(s, 8, 3, 12), (i) => `  modified:   packages/pkg-${s % 7}/src/feature-${i}.ts`), "", "Untracked files:", rep(2 + s % 8, (i) => `  packages/pkg-${s % 7}/tests/new-case-${i}.test.ts`)),
  diff: (s: number) => join(`diff --git a/src/module-${s}.ts b/src/module-${s}.ts`, "index 1234567..89abcde 100644", `--- a/src/module-${s}.ts`, `+++ b/src/module-${s}.ts`, rep(count(s, 120, 32, 14), (i) => `${i % 2 === 0 ? "+" : "-"} const value${i} = ${i % 2 === 0 ? "newPipeline" : "oldPipeline"}(${s}, ${i}, { preserveErrors: ${i % 5 === 0} });`), `src/module-${s}.ts | ${count(s, 120, 32, 14)} +++++++++++++++++++++++++----------------`),
  show: (s: number) => join(`commit ${String(s).padStart(4, "0")}abcdef1234567890`, "Author: Dev <dev@example.com>", "Date: Mon May 4 04:00:00 2026 +0300", "", `    fix: stress scenario ${s}`, "", rep(count(s, 25, 4, 12), (i) => ` packages/pkg-${s % 8}/src/file-${i}.ts | ${1 + (i % 12)} +-${i % 7}`)),
  search: (s: number) => rep(count(s, 120, 18, 14), (i) => `src/domain-${s % 9}/module-${i % 31}.ts:${10 + i}:export const token${s}_${i} = createThing("${"value".repeat(12)}-${s}-${i}");`),
  files: (s: number) => join(rep(count(s, 80, 20, 10), (i) => `./packages/pkg-${s % 10}/src/components/component-${String(i).padStart(3, "0")}.tsx`), rep(count(s, 90, 15, 8), (i) => `./node_modules/package-${i % 12}/dist/chunk-${s}-${i}.js`), rep(20 + s % 30, (i) => `./.next/cache/${s}/artifact-${i}.json`)),
  install: (s: number) => join(rep(count(s, 55, 7, 13), (i) => `npm warn deprecated stress-package-${s}-${i}@1.0.0: replaced by stress-package-${s}-${i + 1}`), `added ${400 + s * 3} packages in ${8 + s % 14}s`, "", `${40 + s % 80} packages are looking for funding`, "found 0 vulnerabilities"),
  retry: (s: number) => join("rg: regex parse error: unclosed group", `retry: rg -n 'session-${s}' src tests --glob '*.ts'`, `src/sessions/session-${s % 9}.ts:${20 + s}:export const session${s} = true`),
  huge: (s: number) => rep(count(s, 900, 180, 12), (i) => `[${s}:${i}] worker-${i % 16}: processed workspace package-${i % 180} phase=${i % 7} duration=${i % 31}ms`),
  detail: (s: number) => join(`Security review found ${3 + s % 6} risky call sites requiring manual inspection.`, rep(count(s, 70, 9, 14), (i) => `src/security/stress-${s}/path-${i}.ts:${i + 1}: userControlledInput flows into execute(${i}) with sanitizer=${i % 5 === 0 ? "missing" : "present"}`), "Manual review required: do not summarize away individual call sites."),
  provider: (s: number) => join("groq API error 429: rate_limit_exceeded", "Falling back to deterministic local indexing.", rep(count(s, 45, 5, 10), (i) => `Compilation note ${s}.${i}: generated declaration for package-${i % 14}`)),
  cold: (s: number) => join(`Natural language prompt: find auth/session/token regressions for workspace ${s}`, "Cache miss: no learned prompt-to-command mapping yet", "AI translated command: rg -n 'auth|session|token' src tests", rep(count(s, 45, 8, 12), (i) => `src/auth/stress-${s % 8}/file-${i % 12}.ts:${i}: token auth session reference ${s}-${i}`)),
  critical: (s: number) => join("PASS src/safe.test.ts", `FAIL src/migrations/prod-${s}.test.ts`, `FATAL: migration would drop table users_${s} in production`, `DETAIL: generated SQL contains DROP TABLE users_${s};`, rep(count(s, 28, 4, 12), (i) => `    at migrationFrame${i} (/repo/src/db/migrate-${s}.ts:${100 + i}:9)`), "1 fail, 19 pass"),
};

function stressScenarios(seed: number): Scenario[] {
  const pass = count(seed, 90, 11, 14), build = count(seed, 18, 4, 12), lint = count(seed, 24, 5, 12), diff = count(seed, 120, 32, 14);
  const matches = count(seed, 120, 18, 14), risky = 3 + seed % 6, cold = count(seed, 45, 8, 12), table = `users_${seed}`;
  const previous = rep(count(seed, 70, 5, 9), (i) => `PASS stress ${seed}.${i}`) + `\nFAIL replay job ${seed}\nTests: ${count(seed, 70, 5, 9) - 1} passed, 1 failed`;
  const raw = rep(count(seed, 70, 5, 9), (i) => `PASS stress ${seed}.${i}`) + `\nPASS replay job ${seed}\nTests: ${count(seed, 70, 5, 9)} passed, 0 failed`;
  const S = (s: Omit<Scenario, "stress" | "notes"> & { notes?: string }): Scenario => ({ stress: true, notes: s.notes ?? note, ...s });
  return [
    S({ id: `stress-tests-pass-${seed}`, workflow: "tests passing", category: "tests", command: `bun test packages/pkg-${seed % 9}`, weight: 3, raw: stressRaw.pass(seed), strategy: "structured", compact: `bun test: ${pass} pass, 0 fail`, expansionRate: 0.02, indexedExpansionRate: 0.005, indexedExpansionTokenCap: 24, requiredPatterns: ["pass", "0 fail"] }),
    S({ id: `stress-tests-fail-${seed}`, workflow: "tests failing with stack traces", category: "tests", command: `bun test packages/pkg-${seed % 11}`, weight: 5, raw: stressRaw.fail(seed), strategy: "structured", compact: `FAIL src/agents/runner-${seed % 11}.test.ts\nAssertionError: expected token budget ${seed} to be below cap\n1 fail`, expansionRate: 0.34, progressiveExpansionRate: 0.16, indexedCompact: `FAIL src/agents/runner-${seed % 11}.test.ts; AssertionError token budget ${seed}; first stack /repo/src/agents/runner-${seed % 11}.ts:41; 1 fail; stack stored`, indexedExpansionRate: 0.035, indexedExpansionTokenCap: 90, requiredPatterns: ["FAIL", "AssertionError", "1 fail"] }),
    S({ id: `stress-build-${seed}`, workflow: "typescript/build errors", category: "build", command: "bun run build", weight: 4, raw: stressRaw.build(seed), strategy: "structured", compact: `${build} TypeScript errors across server/api, client/ui, db/schema. First TS${2300 + ((seed + 1) % 90)}. Expand for full diagnostics.`, expansionRate: 0.42, progressiveExpansionRate: 0.15, indexedCompact: `${build} TypeScript errors across 3 files; first per file indexed with TS codes and line refs; diagnostics stored`, indexedExpansionRate: 0.035, indexedExpansionTokenCap: 95, requiredPatterns: ["TypeScript errors", "TS", "diagnostics"] }),
    S({ id: `stress-lint-${seed}`, workflow: "lint errors", category: "lint", command: "bun run lint", weight: 3, raw: stressRaw.lint(seed), strategy: "structured", compact: `${lint} lint errors grouped by rule. Top: no-floating-promises, no-unused-vars, react-hooks/exhaustive-deps.`, expansionRate: 0.28, progressiveExpansionRate: 0.11, indexedCompact: `${lint} lint errors indexed by rule and file; no-floating-promises/no-unused-vars/react-hooks samples stored`, indexedExpansionRate: 0.025, indexedExpansionTokenCap: 70, requiredPatterns: ["lint errors", "no-floating-promises"] }),
    S({ id: `stress-git-status-${seed}`, workflow: "git status/log/diff/show", category: "git", command: "git status --short", weight: 2, raw: stressRaw.status(seed), strategy: "structured", compact: `main branch, ${count(seed, 8, 3, 12)} modified files, ${2 + seed % 8} untracked files.`, expansionRate: 0.12, progressiveExpansionRate: 0.05, indexedExpansionRate: 0.015, indexedExpansionTokenCap: 35, requiredPatterns: ["main", "modified", "untracked"] }),
    S({ id: `stress-git-diff-${seed}`, workflow: "git status/log/diff/show", category: "git", command: "git diff", weight: 6, raw: stressRaw.diff(seed), strategy: "structured", compact: `src/module-${seed}.ts changed with ${diff} diff lines. Full diff stored for review.`, expansionRate: 1, progressiveExpansionRate: 0.18, progressiveExpansionTokenCap: 420, indexedCompact: `src/module-${seed}.ts changed; ${diff} diff lines; hunk manifest: oldPipeline -> newPipeline; Full diff stored in indexed chunks`, indexedExpansionRate: 0.035, indexedExpansionTokenCap: 160, requiredPatterns: [`src/module-${seed}.ts`, "Full diff stored"] }),
    S({ id: `stress-git-show-${seed}`, workflow: "git status/log/diff/show", category: "git", command: "git show --stat HEAD", weight: 2, raw: stressRaw.show(seed), strategy: "structured", compact: `${String(seed).padStart(4, "0")}abcdef1 fix: stress scenario ${seed}. ${count(seed, 25, 4, 12)} files touched.`, expansionRate: 0.2, progressiveExpansionRate: 0.08, indexedExpansionRate: 0.02, indexedExpansionTokenCap: 55, requiredPatterns: ["abcdef", "files"] }),
    S({ id: `stress-search-${seed}`, workflow: "rg/search results", category: "search", command: `rg -n token${seed} src`, weight: 6, raw: stressRaw.search(seed), strategy: "structured", compact: `${matches} matches across domain modules. Results truncated; use expand offset/limit.`, expansionRate: 0.32, progressiveExpansionRate: 0.12, progressiveExpansionTokenCap: 300, indexedCompact: `${matches} matches across indexed files; top files and first 20 refs stored; use offset/limit`, indexedExpansionRate: 0.025, indexedExpansionTokenCap: 120, requiredPatterns: ["matches", "offset/limit"] }),
    S({ id: `stress-files-${seed}`, workflow: "file listings and trees", category: "files", command: "find . -type f", weight: 4, raw: stressRaw.files(seed), strategy: "smart-display", expansionRate: 0.1, progressiveExpansionRate: 0.035, indexedCompact: `file tree indexed: app components, node_modules collapsed, .next cache collapsed for seed ${seed}`, indexedExpansionRate: 0.015, indexedExpansionTokenCap: 80, requiredPatterns: ["node_modules"] }),
    S({ id: `stress-install-${seed}`, workflow: "package installs", category: "install", command: "bun install", weight: 2, raw: stressRaw.install(seed), strategy: "noise", expansionRate: 0, indexedExpansionRate: 0, requiredPatterns: ["added", "packages"] }),
    S({ id: `stress-retry-${seed}`, workflow: "command retries", category: "execution", command: "rg session src --glob '*.ts'", weight: 1, raw: stressRaw.retry(seed), strategy: "structured", compact: `regex parse error; retried safely; src/sessions/session-${seed % 9}.ts:${20 + seed}`, provider: "groq", progressiveProvider: "none", expansionRate: 0.1, retryOverhead: "retry prompt and validation overhead", progressiveRetryOverhead: "", indexedRetryOverhead: "", indexedExpansionRate: 0.01, indexedExpansionTokenCap: 20, requiredPatterns: ["regex parse error", "retried", "src/sessions"] }),
    S({ id: `stress-repeat-diff-${seed}`, workflow: "repeated test loops with small diffs", category: "tests", command: "bun test", weight: 4, previous, raw, strategy: "diff", expansionRate: 0.04, indexedExpansionRate: 0.01, indexedExpansionTokenCap: 35, requiredPatterns: ["replay job", "0 failed"] }),
    S({ id: `stress-huge-${seed}`, workflow: "huge output", category: "huge", command: "bun run build --verbose", weight: 3, raw: stressRaw.huge(seed), strategy: "compress", maxTokens: 220, expansionRate: 0.18, progressiveExpansionRate: 0.06, progressiveExpansionTokenCap: 360, indexedCompact: `verbose build indexed: worker phases, package hot spots, first/last error-free windows for seed ${seed}`, indexedExpansionRate: 0.012, indexedExpansionTokenCap: 140, requiredPatterns: ["worker"] }),
    S({ id: `stress-small-${seed}`, workflow: "small output where compression should not claim savings", category: "small", command: seed % 2 === 0 ? "pwd" : "echo ok", weight: 1, raw: seed % 2 === 0 ? `/home/hasna/workspace/project-${seed}` : `ok ${seed}`, strategy: "passthrough", expansionRate: 0, indexedExpansionRate: 0 }),
    S({ id: `stress-compact-json-${seed}`, workflow: "already-compact/non-compressible output", category: "small", command: "terminal snapshot --json", weight: 1, raw: JSON.stringify({ ok: true, seed, changed: seed % 3, tests: { pass: 10 + seed % 20, fail: 0 } }), strategy: "passthrough", expansionRate: 0, indexedExpansionRate: 0, requiredPatterns: ["ok"] }),
    S({ id: `stress-detail-${seed}`, workflow: "output where full detail is required", category: "detail", command: "security review", weight: 4, raw: stressRaw.detail(seed), strategy: "structured", compact: `Security review found ${risky} risky call sites. Manual review required; expand for every call site.`, provider: "cerebras", expansionRate: 1, progressiveExpansionRate: 0.2, progressiveExpansionTokenCap: 500, indexedCompact: `Security review found ${risky} risky call sites; exact risky refs indexed; Manual review required; full call-site table stored in pages`, indexedExpansionRate: 0.045, indexedExpansionTokenCap: 180, requiredPatterns: ["Manual review required", "risky"] }),
    S({ id: `stress-provider-${seed}`, workflow: "AI provider unavailable/rate-limited", category: "provider", command: "terminal execute_smart 'bun run build'", weight: 2, raw: stressRaw.provider(seed), strategy: "compress", maxTokens: 120, provider: "groq", providerUnavailable: true, expansionRate: 0.18, progressiveExpansionRate: 0.06, indexedCompact: "429 rate_limit_exceeded; Falling back to deterministic local indexing; declaration notes grouped", indexedExpansionRate: 0.02, indexedExpansionTokenCap: 70, requiredPatterns: ["429", "Falling back"] }),
    S({ id: `stress-cold-cache-${seed}`, workflow: "cache miss/cold start", category: "cache", command: "terminal 'find auth regressions'", weight: 3, raw: stressRaw.cold(seed), strategy: "structured", compact: `Cache miss: translated prompt to rg auth/session/token. ${cold} matches.`, provider: "groq", expansionRate: 0.24, retryOverhead: "NL translation prompt overhead before cache is warm", progressiveExpansionRate: 0.09, progressiveExpansionTokenCap: 150, indexedCompact: `Cache miss: auth/session/token command selected; ${cold} matches indexed; learned mapping recorded`, indexedExpansionRate: 0.035, indexedExpansionTokenCap: 90, indexedRetryOverhead: "local prompt classification overhead", requiredPatterns: ["Cache miss", "matches"] }),
    S({ id: `stress-expansion-${seed}`, workflow: "expansion/full-output follow-up cost", category: "detail", command: "terminal expand detail-key --offset 40 --limit 20", weight: 3, raw: stressRaw.search(seed + 1000), strategy: "structured", compact: "Search summary looked insufficient; agent requested full expansion.", expansionRate: 1, progressiveExpansionRate: 0.14, progressiveExpansionTokenCap: 360, indexedCompact: `Expansion page returned ${Math.min(20, matches)} refs with offset/limit; full output remains stored`, indexedExpansionRate: 0.025, indexedExpansionTokenCap: 110, requiredPatterns: ["offset/limit", "stored"] }),
    S({ id: `stress-critical-${seed}`, workflow: "summary inaccuracies or missing critical errors", category: "quality", command: `bun test src/migrations/prod-${seed}.test.ts`, weight: 4, raw: stressRaw.critical(seed), strategy: "structured", compact: `FAIL src/migrations/prod-${seed}.test.ts\nFATAL: migration would drop table ${table} in production\nDETAIL: generated SQL contains DROP TABLE ${table};\n1 fail, 19 pass`, provider: "groq", expansionRate: 0.55, progressiveExpansionRate: 0.18, progressiveExpansionTokenCap: 220, indexedExpansionRate: 0.04, indexedExpansionTokenCap: 110, requiredPatterns: ["FATAL", `DROP TABLE ${table}`, "1 fail"] }),
  ];
}

export function adversarialScenarios(): Scenario[] {
  return [...curatedScenarios(), ...Array.from({ length: 16 }, (_, i) => i + 1).flatMap(stressScenarios)];
}
