import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { generateSdkFromOpenApi } from "@hasna/contracts/sdk";
import { buildV1OpenApiDocument } from "../server/openapi.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");

describe("generated SDK stays in sync with the OpenAPI document", () => {
  test("regenerating from src/server/openapi.ts reproduces v1.generated.ts (modulo the version stamp)", () => {
    const spec = buildV1OpenApiDocument();
    const { code, warnings } = generateSdkFromOpenApi(spec as never, {
      className: "CalendarV1Client",
      apiKeyHeader: "x-api-key",
    });
    expect(warnings).toHaveLength(0);
    const header =
      "// AUTO-GENERATED by scripts/generate-sdk.ts from src/server/openapi.ts — DO NOT EDIT BY HAND.\n" +
      "// Regenerate: bun run scripts/generate-sdk.ts\n\n";
    const checkedIn = readFileSync(join(root, "src/sdk/v1.generated.ts"), "utf8");
    // The "// Source: Calendar API X.Y.Z" line carries the package version and
    // legitimately drifts on every release without a regeneration. Every other
    // byte — routes, operationIds, schemas — must match exactly.
    const norm = (s: string): string => s.split("\n").filter((l) => !l.startsWith("// Source: Calendar API")).join("\n");
    expect(norm(header + code)).toBe(norm(checkedIn));
  });
});

describe("OpenAPI document invariants", () => {
  test("declares OpenAPI 3.1 with an apiKey security scheme", () => {
    const doc = buildV1OpenApiDocument();
    expect(doc.openapi).toBe("3.1.0");
    expect(doc.components).toMatchObject({
      securitySchemes: { apiKey: { type: "apiKey", in: "header", name: "x-api-key" } },
    });
    expect(doc.security).toEqual([{ apiKey: [] }]);
  });

  test("every operationId is unique", () => {
    const doc = buildV1OpenApiDocument();
    const ids = Object.values(doc.paths as Record<string, { get?: unknown; post?: unknown; patch?: unknown; delete?: unknown; put?: unknown }>)
      .flatMap((ops) => ["get", "post", "patch", "delete", "put"].map((m) => (ops as Record<string, { operationId?: string }>)[m]).filter(Boolean))
      .map((op) => (op as { operationId: string }).operationId);
    expect(ids.length).toBeGreaterThan(10);
    expect(new Set(ids).size).toBe(ids.length);
  });

  test("no route path contains a double /v1/v1", () => {
    const doc = buildV1OpenApiDocument();
    for (const path of Object.keys(doc.paths as Record<string, unknown>)) {
      expect(path).not.toMatch(/\/v1\/v1/);
      expect(path).toMatch(/^\/v1\//);
    }
  });

  test("every $ref resolves to a declared schema", () => {
    const doc = buildV1OpenApiDocument() as { components: { schemas: Record<string, unknown> }; paths: Record<string, unknown> };
    const declared = new Set(Object.keys(doc.components.schemas));
    const refs: string[] = [];
    const walk = (value: unknown): void => {
      if (Array.isArray(value)) { for (const v of value) walk(v); return; }
      if (value && typeof value === "object") {
        const record = value as Record<string, unknown>;
        if (typeof record.$ref === "string") refs.push(record.$ref);
        for (const v of Object.values(record)) walk(v);
      }
    };
    walk(doc);
    expect(refs.length).toBeGreaterThan(10);
    for (const ref of refs) {
      const name = ref.replace("#/components/schemas/", "");
      expect(declared.has(name), `unresolved $ref ${ref}`).toBe(true);
    }
  });
});
