// AUTO-GENERATED by scripts/generate-sdk.ts from src/server/openapi.ts — DO NOT EDIT BY HAND.
// Regenerate: bun run scripts/generate-sdk.ts

import { createHttpTransport, resolveStorageClient, type Env, type HttpTransport, type QueryParams } from "../store/http-storage.js";
// @generated from OpenAPI by @hasna/contracts SDK generator — DO NOT EDIT.
// Source: Calendar API 0.3.9

export interface Org { "id": string; "name": string; "slug": string; "description"?: string; "metadata"?: Record<string, unknown>; "created_at"?: string; "updated_at"?: string }

export interface CreateOrgInput { "name": string; "slug"?: string; "description"?: string; "metadata"?: Record<string, unknown> }

export interface UpdateOrgInput { "name"?: string; "description"?: string; "metadata"?: Record<string, unknown> }

export interface Calendar { "id": string; "org_id": string; "owner_id"?: string; "slug": string; "name": string; "description"?: string; "color"?: string; "timezone": string; "visibility": "public" | "org" | "private"; "metadata"?: Record<string, unknown>; "created_at"?: string; "updated_at"?: string }

export interface CreateCalendarInput { "org_id": string; "owner_id"?: string; "name": string; "slug"?: string; "description"?: string; "color"?: string; "timezone"?: string; "visibility"?: "public" | "org" | "private"; "metadata"?: Record<string, unknown> }

export interface UpdateCalendarInput { "name"?: string; "description"?: string; "color"?: string; "timezone"?: string; "visibility"?: "public" | "org" | "private"; "metadata"?: Record<string, unknown> }

export interface Event { "id": string; "calendar_id": string; "org_id": string; "title": string; "description"?: string; "location"?: string; "start_at": string; "end_at": string; "all_day"?: boolean; "timezone"?: string; "status"?: "tentative" | "confirmed" | "cancelled"; "busy_type"?: "busy" | "free" | "out_of_office"; "visibility"?: "default" | "private" | "confidential"; "recurrence_rule"?: string; "recurrence_exception_dates"?: Array<string>; "source_task_id"?: string; "created_by"?: string; "metadata"?: Record<string, unknown>; "created_at"?: string; "updated_at"?: string }

export interface CreateEventInput { "calendar_id": string; "org_id": string; "title": string; "description"?: string; "location"?: string; "start_at": string; "end_at": string; "all_day"?: boolean; "timezone"?: string; "status"?: "tentative" | "confirmed" | "cancelled"; "busy_type"?: "busy" | "free" | "out_of_office"; "visibility"?: "default" | "private" | "confidential"; "recurrence_rule"?: string; "recurrence_exception_dates"?: Array<string>; "source_task_id"?: string; "created_by"?: string; "metadata"?: Record<string, unknown> }

export interface UpdateEventInput { "title"?: string; "description"?: string; "location"?: string; "start_at"?: string; "end_at"?: string; "all_day"?: boolean; "timezone"?: string; "status"?: "tentative" | "confirmed" | "cancelled"; "busy_type"?: "busy" | "free" | "out_of_office"; "visibility"?: "default" | "private" | "confidential"; "recurrence_rule"?: string; "recurrence_exception_dates"?: Array<string>; "source_task_id"?: string; "metadata"?: Record<string, unknown> }

export interface Attendee { "id": string; "event_id": string; "agent_id"?: string; "display_name"?: string; "email"?: string; "status": "needsAction" | "accepted" | "declined" | "tentative"; "required"?: boolean; "response_comment"?: string; "responded_at"?: string; "created_at"?: string }

export interface CreateAttendeeInput { "event_id": string; "agent_id"?: string; "display_name"?: string; "email"?: string; "status"?: "needsAction" | "accepted" | "declined" | "tentative"; "required"?: boolean }

export interface UpdateAttendeeInput { "status"?: "needsAction" | "accepted" | "declined" | "tentative"; "response_comment"?: string; "required"?: boolean }

export interface Agent { "id": string; "name": string; "description"?: string; "role"?: string; "status"?: string; "metadata"?: Record<string, unknown>; "created_at"?: string; "last_seen_at"?: string }

export interface RegisterAgentInput { "name": string; "description"?: string; "role"?: string; "title"?: string; "level"?: string; "org_id"?: string }

export interface UpdateAgentInput { "description"?: string; "role"?: string; "title"?: string; "level"?: string; "org_id"?: string }

export interface Availability { "id": string; "agent_id": string; "org_id": string; "day_of_week": number; "start_time": string; "end_time": string; "exceptions"?: Array<string>; "created_at"?: string; "updated_at"?: string }

export interface UpsertAvailabilityInput { "agent_id": string; "org_id": string; "day_of_week": number; "start_time": string; "end_time": string }

export interface Membership { "id": string; "org_id": string; "agent_id": string; "role": "admin" | "member" | "service"; "created_at"?: string }

export interface CreateMembershipInput { "org_id": string; "agent_id": string; "role"?: "admin" | "member" | "service" }

export interface DeleteResult { "deleted": boolean }

export interface Error { "error": string }

export interface CalendarV1ClientOptions {
  baseUrl: string;
  apiKey: string;
  fetch?: typeof fetch;
  headers?: HeadersInit;
}
export { HasnaHttpError as ApiError } from "../store/http-storage.js";
export class CalendarV1Client {
  #transport: HttpTransport;
  #headers: Headers;
  constructor(options: CalendarV1ClientOptions | { env: Env }) {
    this.#transport = "env" in options ? resolveStorageClient("calendar", options.env).client.transport : createHttpTransport({ name: "calendar", baseUrl: options.baseUrl, apiKey: options.apiKey, fetchImpl: options.fetch });
    this.#headers = new Headers("env" in options ? undefined : options.headers);
    for (const h of ["authorization", "x-api-key", "host", "cookie", "proxy-authorization"]) {
      if (this.#headers.has(h)) throw new Error("Calendar authority headers cannot be overridden.");
    }
  }
  private request<T>(method: string, path: string, opts: { body?: unknown; query?: Record<string, unknown>; init?: RequestInit }): Promise<T> {
    if (opts.init) for (const k of Object.keys(opts.init)) {
      if (!["headers", "signal"].includes(k)) throw new Error("Calendar request only accepts headers and signal overrides.");
    }
    const headers = new Headers(this.#headers);
    new Headers(opts.init?.headers).forEach((v,k) => headers.set(k,v));
    return this.#transport.request<T>(method, path.replace(/^\/v1(?=\/)/, ""), opts.body, { query: opts.query as QueryParams, headers, signal: opts.init?.signal });
  }
    /** List agents */
    async listAgents(init?: RequestInit): Promise<{ "agents"?: Array<Agent>; "count"?: number }> {
      return this.request("GET", `/v1/agents`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Register (or upsert) an agent */
    async registerAgent(body: RegisterAgentInput, init?: RequestInit): Promise<{ "agent"?: Agent }> {
      return this.request("POST", `/v1/agents`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get an agent by id or name */
    async getAgent(id: string, init?: RequestInit): Promise<{ "agent"?: Agent }> {
      return this.request("GET", `/v1/agents/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Delete an agent */
    async deleteAgent(id: string, init?: RequestInit): Promise<DeleteResult> {
      return this.request("DELETE", `/v1/agents/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Update an agent */
    async updateAgent(id: string, body: UpdateAgentInput, init?: RequestInit): Promise<{ "agent"?: Agent }> {
      return this.request("PATCH", `/v1/agents/${encodeURIComponent(String(id))}`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Update an agent's last_seen_at */
    async heartbeatAgent(id: string, init?: RequestInit): Promise<{ "agent"?: Agent }> {
      return this.request("POST", `/v1/agents/${encodeURIComponent(String(id))}/heartbeat`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** List attendees for an event */
    async listAttendees(query?: { "event_id": string }, init?: RequestInit): Promise<{ "attendees"?: Array<Attendee>; "count"?: number }> {
      return this.request("GET", `/v1/attendees`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Add an attendee to an event */
    async addAttendee(body: CreateAttendeeInput, init?: RequestInit): Promise<{ "attendee"?: Attendee }> {
      return this.request("POST", `/v1/attendees`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Delete an attendee */
    async deleteAttendee(id: string, init?: RequestInit): Promise<DeleteResult> {
      return this.request("DELETE", `/v1/attendees/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Update / respond to an attendee */
    async updateAttendee(id: string, body: UpdateAttendeeInput, init?: RequestInit): Promise<{ "attendee"?: Attendee }> {
      return this.request("PATCH", `/v1/attendees/${encodeURIComponent(String(id))}`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get availability windows for an agent */
    async getAvailability(query?: { "agent_id": string; "org_id"?: string }, init?: RequestInit): Promise<{ "availability"?: Array<Availability>; "count"?: number }> {
      return this.request("GET", `/v1/availability`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Upsert an agent availability window */
    async upsertAvailability(body: UpsertAvailabilityInput, init?: RequestInit): Promise<{ "availability"?: Availability }> {
      return this.request("POST", `/v1/availability`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Delete an availability window */
    async deleteAvailability(id: string, init?: RequestInit): Promise<DeleteResult> {
      return this.request("DELETE", `/v1/availability/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** List calendars */
    async listCalendars(query?: { "org_id"?: string }, init?: RequestInit): Promise<{ "calendars"?: Array<Calendar>; "count"?: number }> {
      return this.request("GET", `/v1/calendars`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Create a calendar */
    async createCalendar(body: CreateCalendarInput, init?: RequestInit): Promise<{ "calendar"?: Calendar }> {
      return this.request("POST", `/v1/calendars`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get a calendar */
    async getCalendar(id: string, init?: RequestInit): Promise<{ "calendar"?: Calendar }> {
      return this.request("GET", `/v1/calendars/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Delete a calendar */
    async deleteCalendar(id: string, init?: RequestInit): Promise<DeleteResult> {
      return this.request("DELETE", `/v1/calendars/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Update a calendar */
    async updateCalendar(id: string, body: UpdateCalendarInput, init?: RequestInit): Promise<{ "calendar"?: Calendar }> {
      return this.request("PATCH", `/v1/calendars/${encodeURIComponent(String(id))}`, {
        body,
        query: undefined,
        init,
      });
    }

    /** List events */
    async listEvents(query?: { "calendar_id"?: string; "org_id"?: string; "status"?: string; "after"?: string; "before"?: string; "source_task_id"?: string; "limit"?: number }, init?: RequestInit): Promise<{ "events"?: Array<Event>; "count"?: number }> {
      return this.request("GET", `/v1/events`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Create an event */
    async createEvent(body: CreateEventInput, init?: RequestInit): Promise<{ "event"?: Event }> {
      return this.request("POST", `/v1/events`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Find overlapping events in a calendar */
    async findConflicts(query?: { "calendar_id": string; "start": string; "end": string }, init?: RequestInit): Promise<{ "conflicts"?: Array<Event>; "count"?: number }> {
      return this.request("GET", `/v1/events/conflicts`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Full-text search events */
    async searchEvents(query?: { "q": string; "org_id"?: string }, init?: RequestInit): Promise<{ "events"?: Array<Event>; "count"?: number }> {
      return this.request("GET", `/v1/events/search`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Get an event with attendees */
    async getEvent(id: string, init?: RequestInit): Promise<{ "event"?: Event; "attendees"?: Array<Attendee> }> {
      return this.request("GET", `/v1/events/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Delete an event */
    async deleteEvent(id: string, init?: RequestInit): Promise<DeleteResult> {
      return this.request("DELETE", `/v1/events/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Update an event */
    async updateEvent(id: string, body: UpdateEventInput, init?: RequestInit): Promise<{ "event"?: Event }> {
      return this.request("PATCH", `/v1/events/${encodeURIComponent(String(id))}`, {
        body,
        query: undefined,
        init,
      });
    }

    /** List memberships by org or by agent */
    async listMembers(query?: { "org_id"?: string; "agent_id"?: string }, init?: RequestInit): Promise<{ "members"?: Array<Membership>; "count"?: number }> {
      return this.request("GET", `/v1/members`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Add an agent to an org */
    async addMember(body: CreateMembershipInput, init?: RequestInit): Promise<{ "member"?: Membership }> {
      return this.request("POST", `/v1/members`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Remove an agent from an org */
    async removeMember(query?: { "agent_id": string; "org_id": string }, init?: RequestInit): Promise<DeleteResult> {
      return this.request("DELETE", `/v1/members`, {
        body: undefined,
        query,
        init,
      });
    }

    /** List organizations */
    async listOrgs(init?: RequestInit): Promise<{ "orgs"?: Array<Org>; "count"?: number }> {
      return this.request("GET", `/v1/orgs`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Create an organization */
    async createOrg(body: CreateOrgInput, init?: RequestInit): Promise<{ "org"?: Org }> {
      return this.request("POST", `/v1/orgs`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get an org by id or slug */
    async getOrg(id: string, init?: RequestInit): Promise<{ "org"?: Org }> {
      return this.request("GET", `/v1/orgs/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Delete an org */
    async deleteOrg(id: string, init?: RequestInit): Promise<DeleteResult> {
      return this.request("DELETE", `/v1/orgs/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Update an org */
    async updateOrg(id: string, body: UpdateOrgInput, init?: RequestInit): Promise<{ "org"?: Org }> {
      return this.request("PATCH", `/v1/orgs/${encodeURIComponent(String(id))}`, {
        body,
        query: undefined,
        init,
      });
    }
}
