/**
 * open-domains — Domain portfolio and DNS management for AI agents
 */

export {
  DOMAIN_STATUSES,
  DOMAIN_OFFER_STATUSES,
  DOMAIN_EMAIL_TYPES,
  createDomain,
  getDomain,
  getDomainByIdentifier,
  getDomainDetails,
  listDomains,
  updateDomain,
  markDomainPremium,
  updateDomainLifecycleStatus,
  recordDomainPurchase,
  deleteDomain,
  countDomains,
  searchDomains,
  getByRegistrar,
  listExpiring,
  listSslExpiring,
  getDomainStats,
  getDomainByName,
  createDomainOffer,
  getDomainOffer,
  listDomainOffers,
  linkDomainEmail,
  getDomainEmailLink,
  listDomainEmailLinks,
  type Domain,
  type DomainStatus,
  type CreateDomainInput,
  type UpdateDomainInput,
  type ListDomainsOptions,
  type DomainStats,
  type DomainOffer,
  type CreateDomainOfferInput,
  type DomainOfferStatus,
  type DomainEmailLink,
  type CreateDomainEmailLinkInput,
  type DomainEmailType,
  type DomainDetails,
  type RecordDomainPurchaseInput,
} from "./db/domains.js";

export {
  createDnsRecord,
  getDnsRecord,
  listDnsRecords,
  updateDnsRecord,
  deleteDnsRecord,
  type DnsRecord,
  type CreateDnsRecordInput,
  type UpdateDnsRecordInput,
} from "./db/domains.js";

export {
  createAlert,
  getAlert,
  listAlerts,
  deleteAlert,
  type Alert,
  type CreateAlertInput,
} from "./db/domains.js";

export {
  whoisLookup,
  checkDnsPropagation,
  checkSsl,
  exportZoneFile,
  importZoneFile,
  discoverSubdomains,
  validateDns,
  exportPortfolio,
  checkAllDomains,
  type WhoisResult,
  type DnsPropagationResult,
  type SslCheckResult,
  type ZoneImportResult,
  type SubdomainResult,
  type DnsValidationIssue,
  type DnsValidationResult,
  type BulkCheckResult,
} from "./db/domains.js";

export {
  getStore,
  isCloudStore,
  LocalStore,
  ApiStore,
  type DomainsStore,
} from "./db/store.js";
export {
  createDomainOwner,
  getDomainOwner,
  getDomainOwnerByDomain,
  getDomainOwnerByDomainName,
  listDomainOwners,
  updateDomainOwner,
  deleteDomainOwner,
  listDomainsWithOwners,
  extractOwnerFromWhois,
  linkOwnerToContacts,
  DOMAIN_OWNER_SOURCES,
  type DomainOwner,
  type DomainOwnerSource,
  type CreateDomainOwnerInput,
  type DomainWithOwner,
} from "./db/owners.js";
export {
  createHistoryEntry,
  getHistoryEntry,
  getHistoryByDomain,
  getLatestSnapshot,
  getHistoryByDateRange,
  getLatestByDomainName,
  listDomainsWithHistoryChanges,
  deleteHistoryEntry,
  deleteHistoryByDomain,
  HISTORY_TYPES,
  type DomainHistory,
  type DomainHistoryType,
  type CreateHistoryEntryInput,
} from "./db/history.js";
export {
  upsertDomainReputation,
  getDomainReputation,
  getDomainReputationByName,
  updateDomainReputation,
  listBlacklistedDomains,
  listHighThreatDomains,
  deleteDomainReputation,
  checkDomainReputation,
  checkDnsBlacklist,
  type DomainReputation,
  type CreateReputationInput,
} from "./db/reputation.js";
export { getDatabase, closeDatabase } from "./db/database.js";
export { PG_MIGRATIONS } from "./db/pg-migrations.js";
export { PgAdapterAsync } from "./db/remote-storage.js";
export {
  DOMAINS_STORAGE_FALLBACK_ENV,
  DOMAINS_STORAGE_MODE_ENV,
  DOMAINS_STORAGE_MODE_FALLBACK_ENV,
  DOMAINS_STORAGE_ENV,
  DOMAINS_STORAGE_TABLES,
  STORAGE_DATABASE_ENV,
  STORAGE_MODE_ENV,
  STORAGE_TABLES,
  getStorageDatabaseEnvName,
  getStorageDatabaseUrl,
  getStorageMode,
  getStoragePg,
  getStorageStatus,
  getStorageSyncMetaAll,
  getSyncMetaAll,
  resolveTables,
  runStorageMigrations,
  storagePull,
  storagePush,
  storageSync,
} from "./db/storage-sync.js";
export type {
  StorageMode,
  StorageStatus,
  StorageSyncMeta,
  StorageSyncResult,
  SyncMeta,
  SyncResult,
} from "./db/storage-sync.js";

// Registrar providers
export {
  getProvider,
  getAvailableProviders,
  getProviderInfo,
  getDomainInventoryProvider,
  providerHasRegistrar,
  providerHasDns,
  providerHasInventory,
  syncAll,
  autoDetectRegistrar,
  type DomainInventoryProvider,
  type RegistrarProvider,
  type ProviderDnsRecord,
  type ProviderDomainInfo,
  type ProviderSyncResult,
  type ProviderAvailability,
  type ProviderInfo,
  type SyncAllResult,
} from "./lib/registrar.js";

// Route 53
export {
  checkAvailability as r53CheckAvailability,
  getTldPrice as r53GetTldPrice,
  listTldPrices as r53ListTldPrices,
  registerDomain as r53RegisterDomain,
  transferDomain as r53TransferDomain,
  getRegistrationStatus as r53GetRegistrationStatus,
  requestTransferOutAuthCode as r53RequestTransferOutAuthCode,
  updateNameservers as r53UpdateNameservers,
  listRegisteredDomains as r53ListRegisteredDomains,
  createHostedZone as r53CreateHostedZone,
  listHostedZones as r53ListHostedZones,
  getHostedZone as r53GetHostedZone,
  deleteHostedZone as r53DeleteHostedZone,
  findHostedZoneByDomain as r53FindHostedZoneByDomain,
  findHostedZoneByNameservers as r53FindHostedZoneByNameservers,
  listRecords as r53ListRecords,
  upsertRecord as r53UpsertRecord,
  upsertRecords as r53UpsertRecords,
  deleteRecord as r53DeleteRecord,
  createRoute53Provider,
  getConfig as r53GetConfig,
  type Route53Config,
  type DomainContactInfo,
  type DomainAvailability,
  type Route53RegistrarOptions,
  type Route53OperationStatus,
  type Route53TransferOutAuthCode,
  type Route53TldPrice,
  type RegisteredDomain,
  type HostedZoneInfo,
  type Route53ChangeOptions,
  type Route53ChangeResult,
  type Route53Record,
  type Route53RecordInput,
} from "./lib/route53.js";

// ─── Provisioning integration contract ──────────────────────────────────────
// Stable surface for automated domain purchase + Cloudflare delegation.
export {
  createZone as cfCreateZone,
  getZone as cfGetZone,
  ensureZone as cfEnsureZone,
  upsertRecord as cfUpsertRecord,
  type CloudflareZone,
} from "./lib/cloudflare.js";
export { resolveCloudflareConfig, cloudflareAuthHeaders, type CloudflareConfig } from "./lib/cloudflare-auth.js";
export { delegateDomainToCloudflare, type DelegateResult } from "./lib/delegate.js";
export {
  PROVIDER_CAPABILITIES,
  getCapability,
  canBuy,
  selectBuyRegistrar,
  selectDnsProvider,
  type ProviderCapability,
} from "./lib/capability.js";
export {
  classifyRegistrationStatus,
  pollRegistrationUntilDone,
  type RegVerdict,
  type PollResult as RegistrationPollResult,
} from "./lib/registration-poll.js";
