// AUTO-GENERATED by scripts/generate-sdk.ts from src/server/openapi.ts — DO NOT EDIT BY HAND.
// Regenerate: bun run scripts/generate-sdk.ts

import { assertTodosPriorRegistrationAdoptionValidationEnvelope } from "../project-registration/adoption-validation.js";

// @generated from OpenAPI by @hasna/contracts SDK generator — DO NOT EDIT.
// Source: Todos V1 API 0.15.35

export interface Task { "id"?: string; "title"?: string; "description"?: string; "status"?: "pending" | "in_progress" | "completed" | "failed" | "cancelled"; "priority"?: "low" | "medium" | "high" | "critical"; "project_id"?: string | null; "parent_id"?: string | null; "assigned_to"?: string | null; "agent_id"?: string | null; "created_by"?: string | null; "reason"?: string | null; "tags"?: Array<string>; "version"?: number; "locked_by"?: string | null; "locked_at"?: string | null; "created_at"?: string; "updated_at"?: string }

export interface Project { "id"?: string; "name"?: string; "path"?: string; "description"?: string | null; "task_list_id"?: string | null; "task_prefix"?: string | null; "task_counter"?: number; "parent_id"?: string | null; "created_at"?: string; "updated_at"?: string }

export interface TaskManifestBounds { "tasks": number; "dependencies": number; "comments": number; "verifications": number; "effects": number; "metadata_fields": number; "effect_payload_fields": number; "request_bytes": number; "response_bytes": number }

export interface TaskManifestCapability { "authority": "todos"; "route": "todos.task-manifest.v1"; "schema_version": 1; "tenant_id": string; "backend": "sqlite" | "postgresql" | "http"; "deterministic_ids": true; "operation_step_identity": true; "deterministic_idempotency_keys": true; "terminal_nonacceptance_receipts": true; "plan_slug_provenance": "deterministic-v1"; "immutable_receipts": true; "transactional_outbox": true; "idempotent_outbox_delivery": true; "exact_bounded_readback": true; "conditional_compensation": true; "transcript_safe": false; "bounds": TaskManifestBounds }

export interface TaskManifestCapabilityResponse { "capability": TaskManifestCapability }

export interface TaskManifest { "version": 1; "operation_id": string; "step_id": string; "idempotency_key": string; "precondition_digest": string; "project_id": string; "task_list_id"?: string; "if_binding_version"?: number; "plan": { "key": string; "name": string; "description"?: string; "status"?: "active" | "completed" | "archived" }; "tasks": Array<{ "key": string; "title": string; "description"?: string; "status"?: "pending" | "in_progress" | "completed" | "failed" | "cancelled"; "priority"?: "low" | "medium" | "high" | "critical"; "assigned_to"?: string; "created_by"?: string; "tags"?: Array<string>; "metadata"?: Record<string, unknown>; "comments"?: Array<Record<string, unknown>>; "verifications"?: Array<Record<string, unknown>> }>; "dependencies"?: Array<Record<string, unknown>>; "effects"?: Array<Record<string, unknown>> }

export interface TaskManifestReceipt { "receipt_id": string; "authority": "todos"; "route": "todos.task-manifest.v1"; "schema_version": 1; "kind": "apply" | "compensate"; "operation_id": string; "step_id": string; "idempotency_key": string; "request_digest": string; "precondition_digest": string; "result_digest": string; "outcome": "accepted" | "duplicate_of_accepted" | "terminal_nonacceptance"; "reason": string | null; "duplicate_of_receipt_id": string | null; "binding_version": number; "apply_receipt_id": string | null; "created_at": string }

export interface TaskManifestApplyResult { "duplicate": boolean; "receipt": TaskManifestReceipt; "graph": Record<string, unknown>; "readback": Record<string, unknown>; "outbox_ids": Array<string>; "result_digest": string }

export interface TaskManifestApplyResponse { "result": TaskManifestApplyResult }

export interface TaskManifestCompensateRequest { "receipt_id": string; "operation_id": string; "step_id": string; "idempotency_key": string; "precondition_digest": string; "if_binding_version": number }

export interface TaskManifestCompensationResult { "duplicate": boolean; "receipt": TaskManifestReceipt; "absent": true; "readback": Record<string, unknown> }

export interface TaskManifestCompensateResponse { "result": TaskManifestCompensationResult }

export interface TaskManifestReadExactRequest { "receipt_id": string }

export interface TaskManifestBindingLookupRequest { "authority": "todos"; "route": "todos.task-manifest.v1"; "schema_version": 1; "tenant_id": string; "plan_id": string; "max_items": 1 }

export interface TaskManifestBindingLookupResult { "authority": "todos"; "route": "todos.task-manifest.v1"; "schema_version": 1; "tenant_id": string; "plan_id": string; "operation_id": string; "step_id": string; "apply_receipt_id": string; "binding_version": number; "state": "applied" | "compensated" }

export interface TaskManifestBindingLookupResponse { "result": TaskManifestBindingLookupResult }

export interface ProjectRegistrationCapability { "authority": "todos"; "route": "todos.project-registration.v1"; "package_version": string; "authority_id": string; "tenant_id": string; "corpus_id": string; "supported_resources": Array<"project" | "task_list">; "conditional_create": true; "immutable_receipts": true; "exact_terminal_lookup": true; "exact_readback": true; "bind_existing_adoption": true; "prior_registration_adoption_validation": true; "project_resource_enumeration": true; "project_resource_page_limit": number; "conditional_inverse": true; "ambiguous_outcome_reconciliation": true }

export interface ProjectRegistrationReceipt { "receipt_id": string; "authority": "todos"; "route": "todos.project-registration.v1"; "package_version": string; "authority_id": string; "tenant_id": string; "corpus_id": string; "operation_id": string; "step_id": string; "resource_kind": "project" | "task_list"; "direction": "forward" | "inverse"; "idempotency_key": string; "request_digest": string; "precondition_digest": string; "outcome": "accepted" | "duplicate_of_accepted" | "terminal_nonacceptance"; "reason": string | null; "target_id": string | null; "result_revision": string | null; "result_digest": string | null; "duplicate_of_receipt_id": string | null; "accepted_receipt_id": string | null; "created_by_operation": boolean; "created_at": string }

export interface ProjectRegistrationRequest { "operation_id": string; "step_id": string; "resource_kind": "project" | "task_list"; "direction": "forward" | "inverse"; "authority_route": string; "package_version": string; "authority_id": string; "tenant_id": string; "corpus_id": string; "target_selector": string; "idempotency_key": string; "request_digest": string; "precondition_digest": string; "project_id": string; "project_slug": string; "project_name": string; "desired": Record<string, unknown>; "bind_existing"?: boolean; "accepted_receipt"?: ProjectRegistrationReceipt; "response_byte_limit": number; "time_budget_ms": number }

export interface ProjectRegistrationLookupRequest { "operation_id": string; "step_id": string; "resource_kind": "project" | "task_list"; "direction": "forward" | "inverse"; "authority": "todos"; "authority_route": string; "package_version": string; "authority_id": string; "tenant_id": string; "corpus_id": string; "target_selector": string; "idempotency_key": string; "target_id"?: string; "max_items": 1; "response_byte_limit": number; "time_budget_ms": number }

export interface PriorRegistrationAdoptionValidation { "valid": true; "resource_kind": "project" | "task_list"; "target_id": string; "source_receipt_id": string; "accepted_receipt_id": string; "source_outcome": "accepted" | "duplicate_of_accepted"; "created_at": string; "current_revision": string; "accepted_result_digest": string }

export interface ProjectResource { "source_project_id": string; "kind": "project" | "task_list" | "plan" | "task"; "scope": "collection" | "resource"; "target_id": string; "parent_id": string | null; "revision": string; "digest": string }

export interface ProjectResourcePage { "authority": "todos"; "route": "todos.project-registration.v1"; "package_version": string; "authority_id": string; "tenant_id": string; "corpus_id": string; "source_project_id": string; "todos_project_id": string; "task_list_id": string; "include_anchors": boolean; "collection_revision": string; "limit": number; "count": number; "resources": Array<ProjectResource>; "has_more": boolean; "next_cursor": string | null; "complete": boolean; "truncated": false }

export interface TaskList { "id"?: string; "project_id"?: string | null; "slug"?: string; "name"?: string; "description"?: string | null; "metadata"?: Record<string, unknown>; "created_at"?: string; "updated_at"?: string }

export interface ProjectTaskListEnsureReceipt { "schema_version": "todos.project-task-list-ensure.v1"; "receipt_id": string; "idempotency_key": string; "project_id": string; "task_list_id": string; "slug": string; "created_by_operation": boolean; "result_revision": string; "result_digest": string; "rollback_supported": boolean; "created_at": string }

export interface ProjectTaskListEnsureResult { "mode": "plan" | "apply"; "action": "would_create" | "created" | "already_present"; "project": Project; "task_list": TaskList | null; "receipt": ProjectTaskListEnsureReceipt | null }

export interface ProjectTaskListRollbackResult { "schema_version": "todos.project-task-list-ensure.v1"; "action": "removed"; "project_id": string; "task_list_id": string; "accepted_receipt_id": string; "rollback_receipt_id": string; "removed_at": string }

export interface TaskComment { "id": string; "task_id": string; "agent_id": string | null; "session_id": string | null; "content": string; "type": "comment" | "progress" | "note"; "progress_pct": number | null; "created_at": string }

export interface StaleLockHandoffInput { "expected_holder": string; "expected_lock_version": string; "stale_after_seconds": number; "new_holder": string; "reason": string }

export interface StaleLockHandoffReceipt { "schema_version": "todos.stale-lock-handoff.v1"; "receipt_id": string; "task_id": string; "actor": string; "previous_holder": string; "previous_lock_version": string; "new_holder": string; "new_lock_version": string; "stale_after_seconds": number; "stale_cutoff": string; "reason": string; "created_at": string }

export interface TaskGitRef { "id": string; "task_id": string; "ref_type": "branch" | "pull_request"; "name": string; "url": string | null; "provider": string | null; "metadata": Record<string, unknown>; "created_at": string; "updated_at": string }

export interface Plan { "id": string; "slug": string | null; "project_id"?: string | null; "task_list_id"?: string | null; "agent_id"?: string | null; "name": string; "description"?: string | null; "status": "active" | "completed" | "archived"; "created_at": string; "updated_at": string }

export interface PlanProjectLinkReceipt { "schema_version": "todos.plan-project-link.v1"; "receipt_id": string; "idempotency_key": string; "plan_id": string; "project_id": string; "prior_plan_project_id": string | null; "prior_task_project_ids": Record<string, string | null>; "task_ids": Array<string>; "task_count": number; "result_plan_revision": string; "result_digest": string; "rollback_supported": true; "created_at": string }

export interface PlanProjectLinkResult { "mode": "plan" | "apply"; "action": "would_link" | "linked" | "already_linked"; "plan": Plan; "project": Project; "tasks": Array<Task>; "receipt": PlanProjectLinkReceipt | null }

export interface PlanProjectLinkRollbackResult { "schema_version": "todos.plan-project-link.v1"; "action": "restored"; "plan": Plan; "tasks": Array<Task>; "accepted_receipt_id": string; "rollback_receipt_id": string; "restored_at": string }

export interface Template { "id": string; "name": string; "title_pattern": string; "description"?: string | null; "priority": "low" | "medium" | "high" | "critical"; "tags": Array<string>; "variables": Array<{ "name"?: string; "required"?: boolean; "default"?: string; "description"?: string }>; "version": number; "project_id"?: string | null; "plan_id"?: string | null; "metadata": Record<string, unknown>; "created_at": string; "tasks"?: Array<TemplateTask> }

export interface TemplateTask { "id": string; "template_id": string; "position": number; "title_pattern": string; "description"?: string | null; "priority": "low" | "medium" | "high" | "critical"; "tags": Array<string>; "task_type"?: string | null; "condition"?: string | null; "include_template_id"?: string | null; "depends_on_positions": Array<number>; "metadata": Record<string, unknown>; "created_at": string }

export interface TemplateVariable { "name": string; "required": boolean; "default"?: string; "description"?: string }

export interface CreateTemplateTaskInput { "position"?: number; "title_pattern": string; "description"?: string | null; "priority"?: "low" | "medium" | "high" | "critical"; "tags"?: Array<string>; "task_type"?: string | null; "condition"?: string | null; "include_template_id"?: string | null; "depends_on"?: Array<number>; "depends_on_positions"?: Array<number>; "metadata"?: Record<string, unknown> }

export interface CreateTaskInput { "title": string; "description"?: string | null; "status"?: "pending" | "in_progress" | "completed" | "failed" | "cancelled"; "priority"?: "low" | "medium" | "high" | "critical"; "project_id"?: string; "parent_id"?: string; "plan_id"?: string; "assigned_to"?: string; "agent_id"?: string; "created_by"?: string; "tags"?: Array<string> }

export interface UpdateTaskInput { "title"?: string; "description"?: string; "status"?: "pending" | "in_progress" | "completed" | "failed" | "cancelled"; "priority"?: "low" | "medium" | "high" | "critical"; "assigned_to"?: string; "project_id"?: string | null; "parent_id"?: string | null; "plan_id"?: string | null; "task_list_id"?: string | null; "version"?: number }

export interface CompleteTaskInput { "agent_id"?: string; "attachment_ids"?: Array<string>; "files_changed"?: Array<string>; "test_results"?: string; "commit_hash"?: string; "notes"?: string; "confidence"?: number }

export interface FailTaskInput { "agent_id"?: string; "reason"?: string; "retry"?: boolean }

export interface TaskFailureResult { "task": Task; "retryTask"?: Task }

export interface CreateProjectInput { "name": string; "path": string; "description"?: string; "task_list_id"?: string; "task_prefix"?: string; "parent_id"?: string }

export interface UpdateProjectInput { "name"?: string; "path"?: string; "description"?: string | null; "parent_id"?: string | null }

export interface RenameProjectInput { "new_slug": string; "name"?: string }

export interface ProjectTaskListEnsureApplyInput { "expected_project_revision": string; "idempotency_key"?: string }

export interface ProjectTaskListRollbackInput { "receipt_id": string; "expected_task_list_revision": string }

export interface PlanProjectLinkApplyInput { "project_id": string; "expected_plan_revision": string; "expected_project_revision": string; "idempotency_key": string }

export interface PlanProjectLinkRollbackInput { "project_id": string; "receipt_id": string; "expected_plan_revision": string }

export interface ErrorResponse { "error": string; "code"?: string; "conflict"?: boolean }

export interface CreateTaskListInput { "name": string; "slug"?: string; "project_id"?: string; "description"?: string; "metadata"?: Record<string, unknown> }

export interface UpdateTaskListInput { "slug"?: string; "name"?: string; "description"?: string; "metadata"?: Record<string, unknown>; "project_id"?: string | null }

export interface CreateTaskCommentInput { "content": string; "agent_id"?: string; "session_id"?: string; "type"?: "comment" | "progress" | "note"; "progress_pct"?: number }

export interface CreatePlanInput { "name": string; "slug"?: string; "description"?: string; "project_id"?: string; "task_list_id"?: string; "agent_id"?: string; "status"?: "active" | "completed" | "archived" }

export interface UpdatePlanInput { "name"?: string; "slug"?: string; "description"?: string; "task_list_id"?: string; "agent_id"?: string; "status"?: "active" | "completed" | "archived" }

export interface CreateTemplateInput { "name": string; "title_pattern": string; "description"?: string | null; "priority"?: "low" | "medium" | "high" | "critical"; "tags"?: Array<string>; "variables"?: Array<TemplateVariable>; "project_id"?: string | null; "plan_id"?: string | null; "metadata"?: Record<string, unknown>; "tasks"?: Array<CreateTemplateTaskInput> }

export interface UpdateTemplateInput { "name"?: string; "title_pattern"?: string; "description"?: string | null; "priority"?: "low" | "medium" | "high" | "critical"; "tags"?: Array<string>; "variables"?: Array<Record<string, unknown>>; "project_id"?: string | null; "plan_id"?: string | null; "metadata"?: Record<string, unknown> }

export interface PrGroupCiProof { "provider": string; "provider_run_id": string; "status": "success"; "repository": string; "pr_number": number; "base_sha": string; "head_sha": string }

export interface PrGroupCleanupProof { "worktree_clean": boolean; "provider_reachable": boolean; "provider_head_sha": string; "pr_policy_satisfied": boolean; "terminal_disposition": "merged" | "cancelled" | "failed" | "no_go"; "writer_retired": boolean; "review_receipt_key": string | null; "conditional_merge_receipt_key": string | null; "merge_receipt_key": string | null }

export interface PrGroupRecord { "schema_version": number; "id": string; "identity_key": string; "root_request_id": string; "repository": string; "leaf_task_id": string; "branch": string; "pr_number": number | null; "base_sha": string | null; "state": "admitted" | "started" | "in_progress" | "handed_off" | "review_requested" | "reviewed" | "repair" | "merge_ready" | "merge_not_merged" | "merged" | "cancelled" | "failed" | "no_go" | "cleanup_eligible"; "active_attempt_id": string | null; "active_generation": string | null; "repair_cycle_count": number; "repair_cycle_limit": number; "terminal_attempt_id": string | null; "terminal_generation": string | null; "terminal_outcome": "merged" | "cancelled" | "failed" | "no_go" | null; "terminal_head_sha": string | null; "terminal_at": string | null; "cleanup_eligible_at": string | null; "revision": number; "created_at": string; "updated_at": string }

export interface PrGroupAttemptRecord { "schema_version": number; "id": string; "group_id": string; "leaf_task_id": string; "dispatch_attempt": string; "writer_generation": string; "previous_attempt_id": string | null; "worktree": string; "branch": string; "repository": string; "pr_number": number | null; "base_sha": string | null; "provider": string | null; "provider_run_id": string | null; "profile_alias": string | null; "status": "admitted" | "started" | "in_progress" | "handed_off" | "reviewing" | "repair" | "merge_ready" | "fenced" | "merged" | "cancelled" | "failed" | "no_go"; "admitted_at": string; "started_at": string | null; "last_heartbeat_at": string | null; "handed_off_at": string | null; "fenced_at": string | null; "terminal_at": string | null; "created_at": string; "updated_at": string }

export interface PrGroupEventRecord { "schema_version": number; "id": string; "group_id": string; "attempt_id": string; "writer_generation": string; "sequence": number; "idempotency_key": string; "event_type": "admission" | "started" | "progress" | "heartbeat" | "handoff" | "review_requested" | "review_receipt" | "repair_accepted" | "repair_rejected" | "conditional_merge_receipt" | "merge_outcome" | "recovery" | "cancellation" | "failure" | "cleanup_eligible" | "terminal_outcome"; "state": "admitted" | "started" | "in_progress" | "handed_off" | "review_requested" | "reviewed" | "repair" | "merge_ready" | "merge_not_merged" | "merged" | "cancelled" | "failed" | "no_go" | "cleanup_eligible"; "message": string | null; "head_sha": string | null; "receipt_key": string | null; "review_receipt_key": string | null; "conditional_merge_receipt_key": string | null; "outcome": "approved" | "changes_requested" | "dismissed" | "accepted" | "rejected" | "merged" | "not_merged" | "cancelled" | "failed" | "no_go" | null; "repository": string; "pr_number": number | null; "base_sha": string | null; "actor_id": string | null; "actor_run_id": string | null; "expected_reviewer_id": string | null; "expected_reviewer_run_id": string | null; "repair_cycle": number | null; "ci_proof": PrGroupCiProof | null; "cleanup_proof": PrGroupCleanupProof | null; "metadata": Record<string, unknown>; "payload_hash": string; "created_at": string }

export interface PrGroupWorkRunAdapter { "kind": string; "id": string; "group_id": string; "task_id": string; "dispatch_attempt": string; "writer_generation": string; "previous_run_id": string | null; "worktree": string; "branch": string; "repository": string; "pr_number": number | null; "base_sha": string | null; "provider": string | null; "provider_run_id": string | null; "profile_alias": string | null; "status": string; "admitted_at": string; "terminal_at": string | null }

export interface PrGroupEvidenceRefAdapter { "kind": string; "id": string; "group_id": string; "work_run_id": string; "sequence": number; "evidence_type": string; "repository": string; "pr_number": number | null; "base_sha": string | null; "head_sha": string | null; "receipt_key": string | null; "outcome": "approved" | "changes_requested" | "dismissed" | "accepted" | "rejected" | "merged" | "not_merged" | "cancelled" | "failed" | "no_go" | null; "actor_id": string | null; "actor_run_id": string | null; "payload_hash": string; "created_at": string }

export interface PrGroupProofBundleAdapter { "kind": string; "id": string; "group_id": string; "revision": number; "evidence_ref_ids": Array<string>; "exact_head": string | null; "complete": boolean }

export interface PrGroupDecisionEnvelopeAdapter { "kind": string; "id": string; "group_id": string; "state": string; "active_work_run_id": string | null; "active_writer_generation": string | null; "repair_cycle_count": number; "repair_cycle_limit": number; "terminal_outcome": "merged" | "cancelled" | "failed" | "no_go" | null; "terminal_head_sha": string | null; "cleanup_eligible": boolean; "revision": number }

export interface PrGroupStateView { "schema_version": number; "authoritative": boolean; "authority": "local" | "remote"; "group": PrGroupRecord; "attempts": Array<PrGroupAttemptRecord>; "latest_event": PrGroupEventRecord | null; "review_receipts": Array<PrGroupEventRecord>; "conditional_merge_receipts": Array<PrGroupEventRecord>; "merge_receipts": Array<PrGroupEventRecord>; "cleanup_receipts": Array<PrGroupEventRecord>; "cleanup_eligible": boolean; "adapters": { "work_runs": Array<PrGroupWorkRunAdapter>; "evidence_refs": Array<PrGroupEvidenceRefAdapter>; "proof_bundle": PrGroupProofBundleAdapter; "decision_envelope": PrGroupDecisionEnvelopeAdapter }; "diagnostics": { "event_count": number; "attempts_omitted": boolean; "receipt_history_complete": boolean; "projection_limits": { "attempts": number; "receipts": number } } }

export interface PrGroupStateResponse { "view": PrGroupStateView }

export interface PrGroupEventPage { "schema_version": number; "authoritative": boolean; "authority": "local" | "remote"; "group_id": string; "events": Array<PrGroupEventRecord>; "count": number; "has_more": boolean; "next_sequence": number | null }

export interface PrGroupEventHistoryResponse { "history": PrGroupEventPage }

export interface AdmitPrGroupInput { "root_request_id": string; "repository": string; "leaf_task_id": string; "dispatch_attempt": string; "writer_generation": string; "worktree": string; "branch": string; "pr_number"?: number | null; "base_sha"?: string | null; "provider"?: string | null; "provider_run_id"?: string | null; "profile_alias"?: string | null; "admitted_at"?: string }

export interface RecoverPrGroupInput { "root_request_id": string; "repository": string; "leaf_task_id": string; "expected_attempt_id": string; "dispatch_attempt": string; "expected_generation": string; "writer_generation": string; "worktree": string; "branch": string; "pr_number": number | null; "base_sha": string | null; "provider": string | null; "provider_run_id": string | null; "profile_alias": string | null; "idempotency_key": string; "message"?: string | null; "metadata"?: Record<string, unknown>; "recovered_at"?: string }

export interface AppendPrGroupEventInput { "attempt_id": string; "writer_generation": string; "idempotency_key": string; "event_type": "started" | "progress" | "heartbeat" | "handoff" | "review_requested" | "review_receipt" | "repair_accepted" | "repair_rejected" | "conditional_merge_receipt" | "merge_outcome" | "cancellation" | "failure" | "cleanup_eligible" | "terminal_outcome"; "message"?: string | null; "head_sha"?: string | null; "receipt_key"?: string | null; "review_receipt_key"?: string | null; "conditional_merge_receipt_key"?: string | null; "outcome"?: "approved" | "changes_requested" | "dismissed" | "accepted" | "rejected" | "merged" | "not_merged" | "cancelled" | "failed" | "no_go" | null; "repository"?: string; "pr_number"?: number | null; "base_sha"?: string | null; "actor_id"?: string | null; "actor_run_id"?: string | null; "expected_reviewer_id"?: string | null; "expected_reviewer_run_id"?: string | null; "repair_cycle"?: number | null; "ci_proof"?: PrGroupCiProof | null; "cleanup_proof"?: PrGroupCleanupProof | null; "metadata"?: Record<string, unknown>; "created_at"?: string }

export interface PrGroupMutationResult { "created": boolean; "adopted": boolean; "appended": boolean; "view": PrGroupStateView; "event": PrGroupEventRecord }

export interface TodosV1ClientOptions {
  /** Base URL, e.g. process.env.APP_API_URL. */
  baseUrl: string;
  /** API key, e.g. process.env.APP_API_KEY. Sent as the 'x-api-key' header. */
  apiKey?: string;
  /** Custom fetch (defaults to global fetch). */
  fetch?: typeof fetch;
  /** Extra headers merged into every request. */
  headers?: Record<string, string>;
}

export class ApiError extends Error {
  constructor(readonly status: number, message: string, readonly body: unknown) {
    super(message);
    this.name = "ApiError";
  }
}

export class TodosV1Client {
  private readonly baseUrl: string;
  private readonly apiKey: string | undefined;
  private readonly fetchImpl: typeof fetch;
  private readonly baseHeaders: Record<string, string>;

  constructor(options: TodosV1ClientOptions) {
    if (!options.baseUrl) throw new Error("TodosV1Client requires a baseUrl.");
    this.baseUrl = options.baseUrl.replace(/\/$/, "");
    this.apiKey = options.apiKey;
    this.fetchImpl = options.fetch ?? globalThis.fetch;
    this.baseHeaders = options.headers ?? {};
  }

  private async request<T>(method: string, path: string, opts: { body?: unknown; query?: Record<string, unknown>; init?: RequestInit }): Promise<T> {
    const url = new URL(this.baseUrl + path);
    if (opts.query) {
      for (const [key, value] of Object.entries(opts.query)) {
        if (value !== undefined && value !== null) url.searchParams.set(key, String(value));
      }
    }
    const headers: Record<string, string> = { Accept: "application/json", ...this.baseHeaders, ...(opts.init?.headers as Record<string, string> | undefined) };
    if (this.apiKey) headers["x-api-key"] = this.apiKey;
    let payload: BodyInit | undefined;
    if (opts.body !== undefined) {
      headers["Content-Type"] = "application/json";
      payload = JSON.stringify(opts.body);
    }
    const response = await this.fetchImpl(url.toString(), { ...opts.init, method, headers, body: payload });
    const text = await response.text();
    const data = text ? (() => { try { return JSON.parse(text); } catch { return text; } })() : undefined;
    if (!response.ok) {
      throw new ApiError(response.status, `${method} ${path} failed: ${response.status}`, data);
    }
    return data as T;
  }

    /** Bulk-ingest a snapshot or atomically complete one observed plan */
    async importSnapshot(body: { "exportedAt"?: string; "source"?: string; "tasks"?: Array<Task>; "projects"?: Array<Project>; "projectMachinePaths"?: Array<Record<string, unknown>>; "plans"?: Array<Record<string, unknown>>; "agents"?: Array<Record<string, unknown>>; "taskLists"?: Array<Record<string, unknown>>; "templates"?: Array<Record<string, unknown>>; "templateTasks"?: Array<TemplateTask>; "auditHistory"?: Array<Record<string, unknown>>; "tombstones"?: Array<Record<string, unknown>>; "planCompletions"?: Array<{ "id": string; "expected_updated_at": string; "status": "completed" }> }, init?: RequestInit): Promise<{ "received"?: number; "result"?: { "inserted"?: number; "updated"?: number; "deleted"?: number; "skipped"?: number; "errors"?: Array<string> }; "planCompletions"?: Array<{ "id": string; "status": "completed"; "expected_updated_at": string; "result_updated_at": string; "applied": boolean }> }> {
      return this.request("POST", `/v1/import`, {
        body,
        query: undefined,
        init,
      });
    }

    /** List plans */
    async listPlans(query?: { "project_id"?: string }, init?: RequestInit): Promise<{ "plans"?: Array<Plan>; "count"?: number }> {
      return this.request("GET", `/v1/plans`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Create a plan */
    async createPlan(body: CreatePlanInput, init?: RequestInit): Promise<{ "plan"?: Plan }> {
      return this.request("POST", `/v1/plans`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get a plan by id */
    async getPlan(id: string, init?: RequestInit): Promise<{ "plan"?: Plan }> {
      return this.request("GET", `/v1/plans/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Delete a plan and detach its tasks */
    async deletePlan(id: string, init?: RequestInit): Promise<{ "deleted"?: boolean; "id"?: string }> {
      return this.request("DELETE", `/v1/plans/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Update a plan */
    async updatePlan(id: string, body: UpdatePlanInput, init?: RequestInit): Promise<{ "plan"?: Plan }> {
      return this.request("PATCH", `/v1/plans/${encodeURIComponent(String(id))}`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Plan atomic linkage of an existing plan and every current member task to a project */
    async planPlanProjectLink(id: string, query?: { "project_id": string }, init?: RequestInit): Promise<PlanProjectLinkResult> {
      return this.request("GET", `/v1/plans/${encodeURIComponent(String(id))}/project-link`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Atomically and idempotently link an existing plan and every current member task to a project */
    async applyPlanProjectLink(id: string, body: PlanProjectLinkApplyInput, init?: RequestInit): Promise<PlanProjectLinkResult> {
      return this.request("POST", `/v1/plans/${encodeURIComponent(String(id))}/project-link`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Conditionally restore every exact prior project link from an accepted receipt */
    async rollbackPlanProjectLink(id: string, body: PlanProjectLinkRollbackInput, init?: RequestInit): Promise<PlanProjectLinkRollbackResult> {
      return this.request("POST", `/v1/plans/${encodeURIComponent(String(id))}/project-link/rollback`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Create or idempotently adopt a deterministic PR group attempt */
    async admitPrGroup(body: AdmitPrGroupInput, init?: RequestInit): Promise<PrGroupMutationResult> {
      return this.request("POST", `/v1/pr-groups/admit`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get the authoritative current state of a PR group */
    async getPrGroupState(id: string, init?: RequestInit): Promise<PrGroupStateResponse> {
      return this.request("GET", `/v1/pr-groups/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Get a bounded page of authoritative PR group events */
    async getPrGroupEvents(id: string, query?: { "after_sequence"?: number; "limit"?: number }, init?: RequestInit): Promise<PrGroupEventHistoryResponse> {
      return this.request("GET", `/v1/pr-groups/${encodeURIComponent(String(id))}/events`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Append a fenced lifecycle event or receipt */
    async appendPrGroupEvent(id: string, body: AppendPrGroupEventInput, init?: RequestInit): Promise<PrGroupMutationResult> {
      return this.request("POST", `/v1/pr-groups/${encodeURIComponent(String(id))}/events`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Fence the prior attempt and create or adopt a recovery generation */
    async recoverPrGroup(id: string, body: RecoverPrGroupInput, init?: RequestInit): Promise<PrGroupMutationResult> {
      return this.request("POST", `/v1/pr-groups/${encodeURIComponent(String(id))}/recover`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Read the live package-owned Projects to Todos registration capability */
    async getProjectRegistrationCapability(init?: RequestInit): Promise<{ "capability": ProjectRegistrationCapability }> {
      return this.request("GET", `/v1/project-registration/capability`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Conditionally remove an unchanged receipt-owned registration resource */
    async compensateProjectRegistrationResource(body: ProjectRegistrationRequest, init?: RequestInit): Promise<{ "receipt": ProjectRegistrationReceipt }> {
      return this.request("POST", `/v1/project-registration/compensate`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Create or deterministically bind one Projects to Todos resource */
    async createProjectRegistrationResource(body: ProjectRegistrationRequest, init?: RequestInit): Promise<{ "receipt": ProjectRegistrationReceipt }> {
      return this.request("POST", `/v1/project-registration/create`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Read one registered project or task list by exact full UUID */
    async readExactProjectRegistrationResource(body: { "resource_kind": "project" | "task_list"; "target_id": string; "response_byte_limit": number; "time_budget_ms": number }, init?: RequestInit): Promise<{ "record": { "target_id": string; "revision": string; "digest": string } }> {
      return this.request("POST", `/v1/project-registration/read-exact`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Recover one exact immutable terminal registration receipt */
    async lookupProjectRegistrationReceipt(body: ProjectRegistrationLookupRequest, init?: RequestInit): Promise<{ "receipt": ProjectRegistrationReceipt; "response_control": { "response_byte_limit": number; "time_budget_ms": number; "response_bytes": number; "elapsed_ms": number; "complete": true; "truncated": false } }> {
      return this.request("POST", `/v1/project-registration/receipts/lookup`, {
        body,
        query: undefined,
        init,
      });
    }

    /** List one bounded page of stable Todos identities for an exact Projects workspace id */
    async listProjectRegistrationResources(query?: { "source_project_id": string; "include_anchors"?: boolean; "limit"?: number; "cursor"?: string }, init?: RequestInit): Promise<{ "page": ProjectResourcePage }> {
      return this.request("GET", `/v1/project-registration/resources`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Fail closed unless one prior accepted registration still matches its exact current resource */
    async validatePriorRegistrationAdoption(body: { "source_request": ProjectRegistrationRequest; "source_receipt": ProjectRegistrationReceipt; "current_record": Project | TaskList }, init?: RequestInit): Promise<{ "validation": PriorRegistrationAdoptionValidation }> {
      const response = await this.request<unknown>("POST", `/v1/project-registration/validate-prior-adoption`, {
        body,
        query: undefined,
        init,
      });
      return {
        validation: assertTodosPriorRegistrationAdoptionValidationEnvelope(response, body),
      };
    }

    /** Verify exact absence after conditional registration compensation */
    async verifyInverseProjectRegistrationResource(body: ProjectRegistrationRequest, init?: RequestInit): Promise<{ "verification": { "target_id": string; "accepted_receipt_id": string; "absent": true; "digest": string } }> {
      return this.request("POST", `/v1/project-registration/verify-inverse`, {
        body,
        query: undefined,
        init,
      });
    }

    /** List projects */
    async listProjects(init?: RequestInit): Promise<{ "projects"?: Array<Project>; "count"?: number }> {
      return this.request("GET", `/v1/projects`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Create a project */
    async createProject(body: CreateProjectInput, init?: RequestInit): Promise<{ "project"?: Project }> {
      return this.request("POST", `/v1/projects`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get a project by id */
    async getProject(id: string, init?: RequestInit): Promise<{ "project"?: Project }> {
      return this.request("GET", `/v1/projects/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Delete a project */
    async deleteProject(id: string, init?: RequestInit): Promise<{ "deleted"?: boolean; "id"?: string }> {
      return this.request("DELETE", `/v1/projects/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Update a project */
    async updateProject(id: string, body: UpdateProjectInput, init?: RequestInit): Promise<{ "project"?: Project }> {
      return this.request("PATCH", `/v1/projects/${encodeURIComponent(String(id))}`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Atomically rename a project and its canonical task list */
    async renameProject(id: string, body: RenameProjectInput, init?: RequestInit): Promise<{ "project"?: Project; "task_lists_updated"?: number }> {
      return this.request("POST", `/v1/projects/${encodeURIComponent(String(id))}/rename`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Plan a non-mutating repair of a project's declared task list */
    async planProjectTaskListEnsure(id: string, init?: RequestInit): Promise<ProjectTaskListEnsureResult> {
      return this.request("GET", `/v1/projects/${encodeURIComponent(String(id))}/task-list/ensure`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Idempotently create an existing project's declared task list */
    async ensureProjectTaskList(id: string, body: ProjectTaskListEnsureApplyInput, init?: RequestInit): Promise<ProjectTaskListEnsureResult> {
      return this.request("POST", `/v1/projects/${encodeURIComponent(String(id))}/task-list/ensure`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Conditionally remove an unchanged task list created by an accepted ensure receipt */
    async rollbackProjectTaskListEnsure(id: string, body: ProjectTaskListRollbackInput, init?: RequestInit): Promise<ProjectTaskListRollbackResult> {
      return this.request("POST", `/v1/projects/${encodeURIComponent(String(id))}/task-list/rollback`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Find task links by git branch or pull-request ref */
    async findTaskGitRefs(ref: string, init?: RequestInit): Promise<{ "refs": Array<TaskGitRef>; "count": number }> {
      return this.request("GET", `/v1/refs/${encodeURIComponent(String(ref))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Aggregate counts */
    async getStats(init?: RequestInit): Promise<{ "tasks"?: number; "projects"?: number }> {
      return this.request("GET", `/v1/stats`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** List task lists */
    async listTaskLists(query?: { "project_id"?: string }, init?: RequestInit): Promise<{ "task_lists"?: Array<TaskList>; "count"?: number }> {
      return this.request("GET", `/v1/task-lists`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Create a task list */
    async createTaskList(body: CreateTaskListInput, init?: RequestInit): Promise<{ "task_list"?: TaskList }> {
      return this.request("POST", `/v1/task-lists`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get a task list by id */
    async getTaskList(id: string, init?: RequestInit): Promise<{ "task_list"?: TaskList }> {
      return this.request("GET", `/v1/task-lists/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Delete a task list */
    async deleteTaskList(id: string, init?: RequestInit): Promise<{ "deleted"?: boolean; "id"?: string }> {
      return this.request("DELETE", `/v1/task-lists/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Update a task list */
    async updateTaskList(id: string, body: UpdateTaskListInput, init?: RequestInit): Promise<{ "task_list"?: TaskList }> {
      return this.request("PATCH", `/v1/task-lists/${encodeURIComponent(String(id))}`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Apply one exact task-manifest graph through the Todos authority */
    async applyTaskManifest(body: TaskManifest, init?: RequestInit): Promise<TaskManifestApplyResponse> {
      return this.request("POST", `/v1/task-manifest/apply`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Recover one exact task-manifest apply receipt from its managed plan id */
    async lookupTaskManifestBinding(body: TaskManifestBindingLookupRequest, init?: RequestInit): Promise<TaskManifestBindingLookupResponse> {
      return this.request("POST", `/v1/task-manifest/bindings/lookup`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Read the current task-manifest authority capability and tenant */
    async getTaskManifestCapability(init?: RequestInit): Promise<TaskManifestCapabilityResponse> {
      return this.request("GET", `/v1/task-manifest/capability`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Compensate one exact untouched task-manifest graph with CAS protection */
    async compensateTaskManifest(body: TaskManifestCompensateRequest, init?: RequestInit): Promise<TaskManifestCompensateResponse> {
      return this.request("POST", `/v1/task-manifest/compensate`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Read one exact immutable task-manifest apply receipt */
    async readExactTaskManifest(body: TaskManifestReadExactRequest, init?: RequestInit): Promise<TaskManifestApplyResponse> {
      return this.request("POST", `/v1/task-manifest/read-exact`, {
        body,
        query: undefined,
        init,
      });
    }

    /** List tasks */
    async listTasks(query?: { "status"?: "pending" | "in_progress" | "completed" | "failed" | "cancelled" | Array<"pending" | "in_progress" | "completed" | "failed" | "cancelled">; "priority"?: "low" | "medium" | "high" | "critical" | Array<"low" | "medium" | "high" | "critical">; "project_id"?: string; "parent_id"?: string | null; "include_subtasks"?: boolean; "plan_id"?: string; "task_list_id"?: string; "assigned_to"?: string; "agent_id"?: string; "tags"?: string; "updated_after"?: string; "limit"?: number; "offset"?: number }, init?: RequestInit): Promise<{ "tasks": Array<Task>; "count": number; "total": number }> {
      return this.request("GET", `/v1/tasks`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Create a task */
    async createTask(body: CreateTaskInput, init?: RequestInit): Promise<{ "task"?: Task }> {
      return this.request("POST", `/v1/tasks`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get a task by id */
    async getTask(id: string, init?: RequestInit): Promise<{ "task"?: Task }> {
      return this.request("GET", `/v1/tasks/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Delete a task */
    async deleteTask(id: string, init?: RequestInit): Promise<{ "deleted"?: boolean; "id"?: string }> {
      return this.request("DELETE", `/v1/tasks/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Update a task */
    async updateTask(id: string, body: UpdateTaskInput, init?: RequestInit): Promise<{ "task"?: Task }> {
      return this.request("PATCH", `/v1/tasks/${encodeURIComponent(String(id))}`, {
        body,
        query: undefined,
        init,
      });
    }

    /** List a bounded page of task comments */
    async listTaskComments(id: string, query?: { "limit": number; "cursor"?: string }, init?: RequestInit): Promise<{ "comments": Array<TaskComment>; "count": number; "has_more": boolean; "next_cursor": string | null }> {
      return this.request("GET", `/v1/tasks/${encodeURIComponent(String(id))}/comments`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Create a task comment */
    async createTaskComment(id: string, body: CreateTaskCommentInput, init?: RequestInit): Promise<{ "comment": TaskComment }> {
      return this.request("POST", `/v1/tasks/${encodeURIComponent(String(id))}/comments`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Complete a task */
    async completeTask(id: string, body?: CompleteTaskInput, init?: RequestInit): Promise<{ "task"?: Task }> {
      return this.request("POST", `/v1/tasks/${encodeURIComponent(String(id))}/complete`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Fail a task with an optional reason and retry copy */
    async failTask(id: string, body?: FailTaskInput, init?: RequestInit): Promise<{ "result": TaskFailureResult }> {
      return this.request("POST", `/v1/tasks/${encodeURIComponent(String(id))}/fail`, {
        body,
        query: undefined,
        init,
      });
    }

    /** List git branch and pull-request refs linked to a task */
    async listTaskGitRefs(id: string, init?: RequestInit): Promise<{ "refs": Array<TaskGitRef>; "count": number }> {
      return this.request("GET", `/v1/tasks/${encodeURIComponent(String(id))}/refs`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Link a git branch or pull-request ref to a task */
    async linkTaskGitRef(id: string, body: { "ref_type": "branch" | "pull_request"; "name": string; "url"?: string; "provider"?: string; "metadata"?: Record<string, unknown> }, init?: RequestInit): Promise<{ "ref": TaskGitRef }> {
      return this.request("POST", `/v1/tasks/${encodeURIComponent(String(id))}/refs`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Atomically transfer one exact stale task lock */
    async handoffStaleTaskLock(id: string, body: StaleLockHandoffInput, init?: RequestInit): Promise<{ "receipt": StaleLockHandoffReceipt }> {
      return this.request("POST", `/v1/tasks/${encodeURIComponent(String(id))}/stale-lock-handoff`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Start a task */
    async startTask(id: string, init?: RequestInit): Promise<{ "task"?: Task }> {
      return this.request("POST", `/v1/tasks/${encodeURIComponent(String(id))}/start`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** List reusable task templates */
    async listTemplates(query?: { "project_id"?: string }, init?: RequestInit): Promise<{ "templates"?: Array<Template>; "count"?: number }> {
      return this.request("GET", `/v1/templates`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Create a reusable task template */
    async createTemplate(body: CreateTemplateInput, init?: RequestInit): Promise<{ "template"?: Template }> {
      return this.request("POST", `/v1/templates`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get one reusable task template with its checklist steps */
    async getTemplate(id: string, init?: RequestInit): Promise<{ "template"?: Template }> {
      return this.request("GET", `/v1/templates/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Delete a reusable task template and its checklist steps */
    async deleteTemplate(id: string, init?: RequestInit): Promise<{ "deleted"?: boolean; "id"?: string }> {
      return this.request("DELETE", `/v1/templates/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Update reusable template metadata and defaults */
    async updateTemplate(id: string, body: UpdateTemplateInput, init?: RequestInit): Promise<{ "template"?: Template }> {
      return this.request("PATCH", `/v1/templates/${encodeURIComponent(String(id))}`, {
        body,
        query: undefined,
        init,
      });
    }
}
