import { expect, test } from "bun:test";
import { readFileSync } from "node:fs";

function read(path: string): string {
  return readFileSync(path, "utf8");
}

test("Dockerfile builds a hosted non-root Bun runtime without plaintext secrets", () => {
  const dockerfile = read("Dockerfile");
  const packageDockerfile = read("Dockerfile.package");
  const dockerignore = read(".dockerignore");

  expect(dockerfile).toContain("FROM oven/bun:1.3.13-slim AS build");
  expect(dockerfile).toContain("bun run build");
  expect(dockerfile).toContain("HASNA_UPTIME_MODE=hosted");
  expect(dockerfile).toContain("--uid 10001");
  expect(dockerfile).toContain("USER uptime");
  expect(dockerfile).toContain("HEALTHCHECK");
  expect(packageDockerfile).toContain("FROM public.ecr.aws/docker/library/node:22-alpine AS bun");
  expect(packageDockerfile).toContain("FROM public.ecr.aws/docker/library/alpine:3.22 AS runtime");
  expect(packageDockerfile).toContain("npm install -g bun@1.3.13");
  expect(packageDockerfile).toContain("apk add --no-cache ca-certificates libgcc libstdc++");
  expect(packageDockerfile).toContain("COPY dist ./dist");
  expect(packageDockerfile).toContain("COPY package.json bun.lock ./");
  expect(packageDockerfile).toContain("bun install --production --frozen-lockfile");
  expect(packageDockerfile).toContain("-u 10001");
  expect(packageDockerfile).not.toContain("FROM oven/bun");
  expect(packageDockerfile).not.toContain("node:22-slim");
  expect(dockerignore).not.toMatch(/^dist$/m);
  expect(dockerfile).not.toContain("mkdir -p /data/uptime");
  expect(packageDockerfile).not.toContain("mkdir -p /data/uptime");
  expect(dockerfile).not.toContain("HASNA_UPTIME_HOSTED_TOKEN=");
  expect(dockerfile).not.toContain("DATABASE_URL=");
  expect(dockerfile).not.toContain("AWS_SECRET_ACCESS_KEY");
  expect(packageDockerfile).not.toContain("HASNA_UPTIME_HOSTED_TOKEN=");
  expect(packageDockerfile).not.toContain("DATABASE_URL=");
  expect(packageDockerfile).not.toContain("AWS_SECRET_ACCESS_KEY");
});

test("AWS infra templates use secret refs and keep services scaled down by default", () => {
  const main = read("infra/aws/main.tf");
  const outputs = read("infra/aws/outputs.tf");
  const variables = read("infra/aws/variables.tf");
  const tfvars = read("infra/aws/terraform.tfvars.example");
  const awsRunbook = read("docs/aws-deployment-runbook.md");
  const packageJson = JSON.parse(read("package.json")) as { files?: string[] };
  const deploymentMetadataExample = read("docs/deployment-metadata.example.json");
  const combined = [main, variables, tfvars].join("\n");

  expect(main).toContain('resource "aws_ecs_cluster" "open_uptime"');
  expect(main).toContain('resource "aws_ecs_task_definition" "service"');
  expect(main).toContain("valueFrom");
  expect(main).toContain('image_tag_mutability = "IMMUTABLE"');
  expect(main).toContain('resource "aws_codebuild_project" "image_builder"');
  expect(main).toContain('resource "aws_cloudfront_distribution" "open_uptime"');
  expect(main).toContain('data "aws_ec2_managed_prefix_list" "cloudfront_origin_facing"');
  expect(main).toContain('resource "aws_security_group_rule" "alb_http_from_cloudfront"');
  expect(main).toContain('resource "aws_security_group_rule" "alb_https_from_cloudfront"');
  expect(main).toContain('resource "aws_lb_listener" "http_cloudfront"');
  expect(main).toContain('resource "aws_lb_listener_rule" "http_cloudfront_origin_verify"');
  expect(main).toContain('resource "aws_lb_listener_rule" "https_cloudfront_origin_verify"');
  expect(main).toContain("local.cloudfront_https_origin");
  expect(main).toContain("var.enable_cloudfront_origin_verify_header");
  expect(main).toContain("var.cloudfront_origin_verify_header_name");
  expect(main).toContain("var.cloudfront_origin_verify_header_value");
  expect(main).toContain("var.cloudfront_origin_protocol_policy");
  expect(main).toContain("var.cloudfront_origin_domain_name");
  expect(main).toContain("for_each = local.use_origin_verify ? [] : [1]");
  expect(main).toContain("for_each = local.use_origin_verify ? [1] : []");
  expect(main).toContain("for_each = local.cloudfront_https_origin && local.use_origin_verify ? [] : [1]");
  expect(main).toContain("for_each = local.cloudfront_https_origin && local.use_origin_verify ? [1] : []");
  expect(main).toContain('type = "fixed-response"');
  expect(main).toContain('status_code  = "403"');
  expect(main).toContain("custom_header");
  expect(main).toContain('resource "aws_lb_listener" "https"');
  expect(main).toContain("count             = local.alb_https_listener_enabled ? 1 : 0");
  expect(main).toContain("tags              = local.tags");
  expect(main).toContain('cloudfront_default_certificate = true');
  expect(main).toContain('origin_protocol_policy = var.cloudfront_origin_protocol_policy');
  expect(main).toContain('resource "aws_route53_record" "cloudfront_origin"');
  expect(main).toContain("npm pack @hasna/uptime@");
  expect(main).toContain("EXPECTED_RUNTIME_PACKAGE_INTEGRITY");
  expect(main).toContain("npm view @hasna/uptime@${var.runtime_package_version} dist.integrity");
  expect(main).toContain("runtime package integrity mismatch");
  expect(main).toContain("expected_runtime_package_integrity = coalesce(var.runtime_package_integrity, \"\")");
  expect(main).toContain("Dockerfile.package");
  expect(main).toContain("HASNA_UPTIME_HOSTED_TOKEN");
  expect(main).toContain("HASNA_UPTIME_HOSTED_SQLITE_DB");
  expect(main).not.toContain("HASNA_UPTIME_DATABASE_URL");
  expect(main).toMatch(/efs_enabled_services\s+= toset\(\["web"\]\)/);
  expect(main).toContain('resource "aws_iam_role_policy" "execution_secrets"');
  expect(main).toContain("kms:ViaService");
  expect(main).toContain("secretsmanager.${var.region}.amazonaws.com");
  expect(main).toContain("ssm.${var.region}.amazonaws.com");
  expect(main).toContain("kms:EncryptionContext:SecretARN");
  expect(main).toContain("kms:EncryptionContext:PARAMETER_ARN");
  expect(main).toContain("s3.${var.region}.amazonaws.com");
  expect(main).toContain("kms:EncryptionContext:aws:s3:arn");
  expect(main).toContain('resource "aws_security_group" "worker"');
  expect(main).toContain('key != "web" && key != "migration"');
  expect(main).toContain('each.key == "public-probe" ? ["0.0.0.0/0"] : [data.aws_vpc.target.cidr_block]');
  expect(main).not.toContain('resource "aws_security_group_rule" "efs_from_workers"');
  expect(main).toContain('resource "aws_efs_file_system" "data"');
  expect(main).toContain('resource "aws_efs_access_point" "uptime"');
  expect(main).toContain('resource "aws_backup_plan" "data"');
  expect(main).toContain("efs_volume_configuration");
  expect(main).toContain("transit_encryption = \"ENABLED\"");
  expect(variables).toContain("EFS SQLite bridge requires web desired count 0 or 1");
  expect(variables).toContain("allow_cloudfront_http_origin_live_traffic");
  expect(variables).toContain("web desired count above 0 in cloudfront_default_domain mode requires enable_cloudfront_origin_verify_header=true");
  expect(variables).toContain("web desired count above 0 requires CloudFront HTTPS-origin mode");
  expect(variables).toContain("hosted_token_secret_arn");
  expect(variables).toContain("runtime_package_integrity must be null or an npm sha512 integrity string");
  expect(variables).toContain('"public-probe" = 0');
  expect(variables).toContain("enable_cloudfront_origin_verify_header can only be true when protected_access_mode is cloudfront_default_domain");
  expect(variables).toContain("cloudfront_origin_protocol_policy must be http-only or https-only");
  expect(variables).toContain("cloudfront_origin_domain_name is required when CloudFront HTTPS origin is enabled");
  expect(variables).toContain('default     = "X-Open-Uptime-Origin-Verify"');
  expect(variables).toContain('default     = false');
  expect(variables).toContain('default     = null');
  for (const disallowedHeader of [
    "cache-control",
    "content-length",
    "content-type",
    "host",
    "origin",
    "x-real-ip",
    "x-uptime-hosted-token",
  ]) {
    expect(variables).toContain(`"${disallowedHeader}"`);
  }
  expect(main).toContain("aws_s3_bucket_public_access_block");
  expect(main).toContain("aws_s3_bucket_lifecycle_configuration");
  expect(main).toContain("DenyInsecureTransport");
  expect(main).toContain("deployment_circuit_breaker");
  expect(main).toContain("enable_ecs_managed_tags = true");
  expect(main).toContain('propagate_tags          = "SERVICE"');
  expect(main).toContain("service_health_checks");
  expect(main).toContain("healthCheck = local.service_health_checks[each.key]");
  expect(main).toContain("fetch('http://127.0.0.1:${local.container_port}/health')");
  expect(main).toContain("depends_on = [aws_lb_listener.https, aws_lb_listener.http_cloudfront, aws_lb_listener_rule.http_cloudfront_origin_verify, aws_lb_listener_rule.https_cloudfront_origin_verify, aws_efs_mount_target.data]");
  for (const component of ["scheduler", "public-probe", "reporter", "migration"]) {
    expect(main).toContain(`"cloud", "workers", "run", "--role", "${component}"`);
    expect(main).toContain(`cloud workers preflight --role ${component} --healthcheck --json`);
  }
  expect(main).toContain('resource "aws_cloudwatch_metric_alarm" "web_5xx"');
  expect(main).toContain('resource "aws_cloudwatch_metric_alarm" "web_unhealthy"');
  expect(outputs).toContain('output "log_group_names"');
  expect(outputs).toContain('output "alarm_names"');
  expect(outputs).toContain('output "backup_vault_name"');
  expect(outputs).toContain('output "backup_plan_id"');
  expect(outputs).toContain('output "kms_key_arn"');
  expect(outputs).toContain('output "secret_refs"');
  expect(outputs).toContain('output "cloudfront_origin_verify_header_enabled"');
  expect(outputs).toContain('output "cloudfront_origin_verify_header_name"');
  expect(outputs).toContain('output "cloudfront_origin_protocol_policy"');
  expect(outputs).toContain('output "cloudfront_origin_domain_name"');
  expect(outputs).toContain('output "cloudfront_distribution_id"');
  expect(outputs).toContain('output "alb_security_group_id"');
  expect(outputs).toContain('output "alb_listener_arns"');
  expect(outputs).toContain('output "web_target_group_arn"');
  expect(outputs).not.toContain('output "cloudfront_origin_verify_header_value"');
  expect(outputs).not.toContain("cloudfront_origin_verify_header_value");
  expect(outputs).toContain("var.hosted_token_secret_arn");
  expect(outputs).toContain("aws_cloudwatch_log_group.service");
  expect(outputs).toContain("aws_cloudwatch_metric_alarm.web_5xx.alarm_name");
  expect(outputs).toContain("aws_backup_vault.data.name");
  expect(main).toContain('resource "aws_budgets_budget" "monthly"');
  expect(main).toContain("budget_alert_email_addresses");
  expect(main).toContain('resource "aws_vpc_endpoint" "interface"');
  expect(main).toContain('resource "aws_vpc_endpoint" "gateway"');
  expect(main).toContain('aws_security_group_rule" "web_nat_https_egress"');
  expect(main).toContain('aws_security_group_rule" "worker_nat_https_egress"');
  expect(main).toContain("var.enable_nat_task_egress");
  expect(main).toContain("var.nat_task_egress_cidr_blocks");
  expect(main).toContain('data "aws_iam_policy_document" "vpc_endpoint_s3"');
  expect(main).toContain('data "aws_iam_policy_document" "vpc_endpoint_secretsmanager"');
  expect(main).toContain('data "aws_iam_policy_document" "vpc_endpoint_logs"');
  expect(main).toContain('data "aws_iam_policy_document" "vpc_endpoint_ecr_api"');
  expect(main).toContain('aws_security_group_rule" "web_s3_gateway_egress"');
  expect(main).toContain('aws_security_group_rule" "worker_s3_gateway_egress"');
  expect(main).toContain('aws_vpc_endpoint.gateway["s3"].prefix_list_id');
  expect(main).toContain("additional_vpc_endpoint_source_security_group_ids");
  expect(main).toContain("prod-${var.region}-starport-layer-bucket");
  expect(main).toContain("policy = {");
  expect(main).toContain("var.enable_private_vpc_endpoints");
  expect(main).toContain("com.amazonaws.${var.region}.${each.key}");
  expect(variables).toContain("additional_vpc_endpoint_source_security_group_ids");
  expect(variables).toContain("enable_nat_task_egress");
  expect(variables).toContain("nat_task_egress_cidr_blocks");
  expect(main).toContain("TagKeyValue");
  expect(main).toContain("Project");
  expect(main).toContain("Environment");
  expect(main).toContain("Owner");
  expect(main).toContain("CostCenter");
  expect(main).toContain('required_version = ">= 1.9.0"');
  expect(main).toContain("HASNA_UPTIME_ALLOWED_ORIGINS");
  expect(main).toContain("aws_cloudfront_distribution.open_uptime[0].domain_name");
  expect(variables).toContain("web            = 0");
  expect(tfvars).toContain("container_image");
  expect(tfvars).toContain('protected_access_mode    = "cloudfront_default_domain"');
  expect(tfvars).toContain('cloudfront_origin_protocol_policy = "http-only"');
  expect(tfvars).toContain("allow_cloudfront_http_origin_live_traffic = false");
  expect(tfvars).toContain("cloudfront_origin_domain_name     = null");
  expect(tfvars).toContain("enable_cloudfront_origin_verify_header");
  expect(tfvars).toContain("cloudfront_origin_verify_header_name");
  expect(tfvars).toContain("cloudfront_origin_verify_header_value  = null");
  expect(tfvars).toContain('runtime_package_version   = "0.1.28"');
  expect(tfvars).toContain("runtime_package_integrity = null");
  expect(tfvars).toContain('project_name             = "open-uptime"');
  expect(tfvars).toContain("monthly_budget_limit_usd");
  expect(tfvars).toContain("private_route_table_ids");
  expect(tfvars).toContain("enable_nat_task_egress");
  expect(tfvars).toContain("enable_private_vpc_endpoints = false");
  expect(tfvars).toContain("additional_vpc_endpoint_source_security_group_ids");
  expect(tfvars).toContain("budget_alert_email_addresses");
  expect(outputs).toContain('output "vpc_endpoint_ids"');
  expect(outputs).toContain("aws_vpc_endpoint.interface");
  expect(outputs).toContain("aws_vpc_endpoint.gateway");
  expect(main).toContain("for index, subnet_id in var.private_subnet_ids");
  expect(main).not.toContain("for_each        = toset(var.private_subnet_ids)");
  expect(tfvars).toContain("certificate_arn          = null");
  expect(tfvars).toContain("hosted_zone_id           = null");
  expect(tfvars).toContain("@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
  expect(variables).toContain("certificate_arn is required when protected_access_mode is alb_https_cert or CloudFront HTTPS origin is enabled");
  expect(variables).toContain("certificate ARN in the deployment region");
  expect(variables).toContain("arn:(aws|aws-us-gov|aws-cn):acm:${var.region}");
  expect(awsRunbook).toContain("## Sanitized Origin Evidence");
  expect(awsRunbook).toContain("aws resourcegroupstaggingapi get-resources");
  expect(awsRunbook).toContain("Do not run `aws cloudfront list-distributions`");
  expect(awsRunbook).not.toContain("\naws cloudfront list-distributions \\");
  expect(awsRunbook).toContain("umask 077");
  expect(awsRunbook).toContain("chmod 600 *.tfplan");
  expect(awsRunbook).toContain("ActionsEnabled");
  expect(awsRunbook).toContain("endpointRedacted");
  expect(awsRunbook).toContain("Treat any private");
  expect(awsRunbook).toContain("CloudFront/ELB read that can reveal custom headers as secret-bearing");
  expect(tfvars).toContain("kms_key_arn");
  expect(tfvars).not.toContain("database_secret_arn");
  expect(tfvars).not.toContain("rds_security_group_id");
  expect(tfvars).toContain('"public-probe" = 0');
  expect(tfvars).not.toContain("public_probe = 0");
  expect(packageJson.files).toContain("docs/*.json");
  expect(packageJson.files).toContain("bun.lock");
  expect(deploymentMetadataExample).not.toContain("private-account-label");
  expect(deploymentMetadataExample).not.toContain("private-workspace-id");
  expect(combined).not.toContain("Hasna XYZ");
  expect(combined).not.toContain("private-account-label");
  expect(combined).not.toContain("private-workspace-id");
  expect(combined).not.toContain("vpc-deadbeefdeadbeef0");
  expect(combined).not.toContain("uptime.private.example");
  expect(combined).not.toContain("private/org/path");
  expect(combined).not.toContain("AKIA");
  expect(combined).not.toContain("BEGIN PRIVATE KEY");
  expect(combined).not.toContain("postgres://");
  expect(combined).not.toContain("HASNA_UPTIME_HOSTED_TOKEN=");
  expect(combined).not.toContain('resource "random_');
  expect(combined).not.toContain("hashicorp/random");
});
