import {mkdir,mkdtemp,writeFile,readFile,unlink,readdir} from 'node:fs/promises';
import {join} from 'node:path';import {homedir} from 'node:os';import {fileURLToPath} from 'node:url';import assert from 'node:assert/strict';
const native=process.env.SWITCHER_TEST_AIDER_EXECUTABLE;
if(!native)throw new Error('Set SWITCHER_TEST_AIDER_EXECUTABLE to an installed Aider 0.86.2 executable. No package is installed by this fixture.');
const base=process.env.SWITCHER_TEST_ROOT??join(homedir(),'Workspace/scratch/switcher-native-tests');await mkdir(base,{recursive:true,mode:0o700});const root=await mkdtemp(join(base,'aider-cli-'));
const source=fileURLToPath(new URL('../src/cli.ts',import.meta.url));
const secret='synthetic-'+crypto.randomUUID(),marker='PROOF_'+crypto.randomUUID();const calls:any[]=[],results:any[]=[];let protocol='',phase=0;
let hostileCalls=0;const hostile=Bun.serve({hostname:'127.0.0.1',port:0,fetch(){hostileCalls++;return new Response(null,{status:500});}});
const upstream=Bun.serve({hostname:'127.0.0.1',port:0,async fetch(req){const path=new URL(req.url).pathname;
 if(req.method==='GET'&&path==='/prefix/v1/models')return Response.json({data:[{id:'vendor/fixture',name:'Fixture',context_length:32768,max_output_tokens:4096,supported_parameters:[]},{id:'vendor/second:tag',name:'Second',context_length:32768,max_output_tokens:4096}]});
 if(req.method!=='POST')return new Response(null,{status:404});const b:any=await req.json();const proof=JSON.stringify(b).includes(marker);calls.push({protocol,phase,path,model:b.model,stream:b.stream===true,proof,authMatches:req.headers.get('authorization')==='Bearer '+secret});
 const content=(phase===0||phase===3)?`target.txt\n\`\`\`text\nEDIT_${proof?marker:'MISSING_CONTEXT'}\n\`\`\`\nObserved ${proof?marker:'MISSING_CONTEXT'}`:`RECALLED_${proof?marker:'MISSING_HISTORY'}`;
 if(b.stream){
  const event=(type:string,data:any)=>`event: ${type}\ndata: ${JSON.stringify(data)}\n\n`;
  let text='';
  if(path.endsWith('/messages'))text=[
   ['message_start',{type:'message_start',message:{id:'msg_fixture',type:'message',role:'assistant',model:b.model,content:[],stop_reason:null,stop_sequence:null,usage:{input_tokens:25,output_tokens:0}}}],
   ['content_block_start',{type:'content_block_start',index:0,content_block:{type:'text',text:''}}],['content_block_delta',{type:'content_block_delta',index:0,delta:{type:'text_delta',text:content}}],['content_block_stop',{type:'content_block_stop',index:0}],['message_delta',{type:'message_delta',delta:{stop_reason:'end_turn',stop_sequence:null},usage:{output_tokens:12}}],['message_stop',{type:'message_stop'}],
  ].map(([t,d])=>event(t as string,d)).join('');
  else if(path.endsWith('/responses')){
   const part={type:'output_text',text:content,annotations:[]};const item={id:'msg_fixture',type:'message',role:'assistant',status:'completed',content:[part]};const response={id:'resp_fixture',object:'response',created_at:1,status:'completed',error:null,incomplete_details:null,instructions:null,model:b.model,output:[item],parallel_tool_calls:true,tool_choice:'auto',tools:[],usage:{input_tokens:25,output_tokens:12,total_tokens:37}};
   const events=[['response.created',{response:{...response,status:'in_progress',output:[]}}],['response.output_item.added',{output_index:0,item:{...item,status:'in_progress',content:[]}}],['response.content_part.added',{item_id:item.id,output_index:0,content_index:0,part:{...part,text:''}}],['response.output_text.delta',{item_id:item.id,output_index:0,content_index:0,delta:content}],['response.output_text.done',{item_id:item.id,output_index:0,content_index:0,text:content}],['response.content_part.done',{item_id:item.id,output_index:0,content_index:0,part}],['response.output_item.done',{output_index:0,item}],['response.completed',{response}]];
   text=events.map(([t,d],i)=>event(t as string,{type:t,sequence_number:i,...d as object})).join('');
  }else text=[{id:'chat_fixture',object:'chat.completion.chunk',created:1,model:b.model,choices:[{index:0,delta:{role:'assistant',content},finish_reason:null}]},{id:'chat_fixture',object:'chat.completion.chunk',created:1,model:b.model,choices:[{index:0,delta:{},finish_reason:'stop'}],usage:{prompt_tokens:25,completion_tokens:12,total_tokens:37}}].map(d=>`data: ${JSON.stringify(d)}\n\n`).join('')+'data: [DONE]\n\n';
  return new Response(text,{headers:{'content-type':'text/event-stream'}});
 }
 if(path.endsWith('/messages'))return Response.json({id:'msg_fixture',type:'message',role:'assistant',model:b.model,content:[{type:'text',text:content}],stop_reason:'end_turn',stop_sequence:null,usage:{input_tokens:25,output_tokens:12}});
 if(path.endsWith('/responses'))return Response.json({id:'resp_fixture',object:'response',created_at:1,status:'completed',error:null,incomplete_details:null,instructions:null,model:b.model,output:[{id:'msg_fixture',type:'message',role:'assistant',status:'completed',content:[{type:'output_text',text:content,annotations:[]}]}],parallel_tool_calls:true,tool_choice:'auto',tools:[],usage:{input_tokens:25,output_tokens:12,total_tokens:37}});
 if(path.endsWith('/chat/completions'))return Response.json({id:'chat_fixture',object:'chat.completion',created:1,model:b.model,choices:[{index:0,message:{role:'assistant',content},finish_reason:'stop'}],usage:{prompt_tokens:25,completion_tokens:12,total_tokens:37}});
 return new Response(null,{status:404});
}});
try{for(const wire of ['openai-chat','openai-responses','anthropic-messages']){protocol=wire;const dir=join(root,wire),home=join(dir,'home'),state=join(dir,'state');await mkdir(home,{recursive:true,mode:0o700});await writeFile(join(dir,'proof.txt'),marker);await writeFile(join(dir,'target.txt'),'Before edit\n');await writeFile(join(dir,'--model=literal.txt'),'A literal native filename\n');
 const env={PATH:process.env.PATH,HOME:home,USER:process.env.USER,LOGNAME:process.env.LOGNAME,HASNA_SWITCHER_HOME:join(dir,'switcher'),SWITCHER_PROVIDER_AIDER_FIXTURE:secret,TMPDIR:dir};
 await writeFile(join(home,'.aider.conf.yml'),JSON.stringify({'model':'outside','openai-api-base':hostile.url.origin+'/wrong','openai-api-key':'synthetic-unused','alias':['openai/vendor/fixture:openai/outside'],'dry-run':true}));
 // Ordinary project instructions and native safety preferences remain enabled.
 await writeFile(join(dir,'.aider.conf.yml'),JSON.stringify({'model':'outside','openai-api-base':hostile.url.origin+'/wrong','set-env':['PYTHON_DOTENV_DISABLED=0'],'alias':['openai/vendor/fixture:openai/outside'],'dry-run':false,'read':['proof.txt'],'auto-commits':false,'dirty-commits':false,'auto-lint':false,'auto-test':false,'git':false,'gitignore':false,'pretty':false,'stream':false,'fancy-input':false,'map-tokens':0}));
 let priorLatest="";for(const turn of [0,1,2,...(wire==='openai-chat'?[3]:[]),4,5]){phase=turn;if(phase===1){await unlink(join(dir,'proof.txt'));await writeFile(join(dir,'.aider.conf.yml'),JSON.stringify({'dry-run':false,'git':false,'gitignore':false,'auto-commits':false,'pretty':false,'stream':false,'fancy-input':false,'map-tokens':0}));}
 if(phase===3){await writeFile(join(dir,'target.txt'),'DENIED_EDIT_SENTINEL\n');await writeFile(join(home,'.aider.conf.yml'),JSON.stringify({'dry-run':false}));await writeFile(join(dir,'.aider.conf.yml'),JSON.stringify({'dry-run':true,'git':false,'gitignore':false,'auto-commits':false,'pretty':false,'stream':false,'fancy-input':false,'map-tokens':0}));}
 if(phase===4)await writeFile(join(dir,'.aider.conf.yml'),JSON.stringify({'dry-run':false,'git':false,'gitignore':false,'auto-commits':false,'pretty':false,'stream':true,'fancy-input':false,'map-tokens':0}));
 if(phase===5)await writeFile(join(dir,'second-proof.txt'),marker);
 const args=['launch','aider','--provider','generic-'+wire,'--protocol',wire,'--url',upstream.url.origin+'/prefix/v1','--credential-env','SWITCHER_PROVIDER_AIDER_FIXTURE','--auth-style','bearer','--model',phase===5?'vendor/second:tag':'vendor/fixture','--cwd',dir,'--state-dir',state,'--executable',native,'--timeout','30','--',...(phase===2?['--list-models',(wire==='anthropic-messages'?'anthropic':wire==='openai-responses'?'openai/responses':'openai')+'/vendor/']: [...(phase===0?['--file','target.txt']:phase===3?['--restore-chat-history','--file','target.txt']:phase===5?['--read','second-proof.txt']:['--restore-chat-history']),'--message',(phase===0||phase===3)?'Read the provided proof file and replace target.txt with EDIT_ followed by its unique marker. Report the observed marker.':'Recall the unique marker from the prior conversation. Do not read any file.']),...(phase===0?['--','--model=literal.txt']:[])];
 const child=Bun.spawn([process.execPath,source,...args],{cwd:dir,env,stdin:'ignore',stdout:'pipe',stderr:'pipe',detached:true});let timedOut=false;const timer=setTimeout(()=>{timedOut=true;try{process.kill(-child.pid,'SIGKILL')}catch{}},40000);
 try{const[code,out,err]=await Promise.all([child.exited,new Response(child.stdout).text(),new Response(child.stderr).text()]);await writeFile(join(dir,`phase-${phase}.stdout.log`),out.replaceAll(secret,'[SYNTHETIC]'));await writeFile(join(dir,`phase-${phase}.stderr.log`),err.replaceAll(secret,'[SYNTHETIC]'));const target=await readFile(join(dir,'target.txt'),'utf8'),edited=target.includes('EDIT_'+marker),denied=target==='DENIED_EDIT_SENTINEL\n';const expectedCatalog=['vendor/fixture','vendor/second:tag'].map(id=>(wire==='anthropic-messages'?'anthropic':wire==='openai-responses'?'openai/responses':'openai')+'/'+id);const listed=out.split('\n').map(l=>l.trim()).filter(l=>l.startsWith('- ')).map(l=>l.slice(2));const latestPath=(await readdir(state,{recursive:true})).find(p=>p.endsWith('/latest.json'));const latest=latestPath?await readFile(join(state,latestPath),'utf8'):'';const historyPreserved=phase!==2||latest===priorLatest;if(phase===1)priorLatest=latest;results.push({protocol,phase,expectedModel:phase===5?'vendor/second:tag':'vendor/fixture',code,timedOut,proof:out.includes(marker),edited,denied,expectedCatalog,listed,historyPreserved,calls:calls.filter(c=>c.protocol===wire&&c.phase===phase),launchDirs:(await readdir(state).catch(()=>[])).filter(n=>n.startsWith('launch-'))});}
 finally{clearTimeout(timer);try{process.kill(-child.pid,'SIGKILL')}catch{}}
 }
}}finally{await upstream.stop(true);await hostile.stop(true);}
const keyHits:string[]=[];for(const entry of await readdir(root,{recursive:true,withFileTypes:true}))if(entry.isFile()){const path=join(entry.parentPath,entry.name);if((await readFile(path)).includes(Buffer.from(secret)))keyHits.push(path);}
const result={root,native,results,calls,keyHits,hostileCalls};await writeFile(join(root,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));assert(results.every(x=>x.code===0&&!x.timedOut&&(x.phase===3?x.denied:x.phase>=4?true:x.edited)&&!x.launchDirs.length&&x.historyPreserved&&(x.phase===2?JSON.stringify(x.listed)===JSON.stringify(x.expectedCatalog)&&x.calls.length===0:x.proof&&x.calls.length>0&&x.calls.every((c:any)=>c.proof&&c.authMatches&&(x.phase!==4||c.stream===(x.protocol!=='openai-responses'))&&c.model===x.expectedModel&&c.path==='/prefix/v1'+({'openai-chat':'/chat/completions','openai-responses':'/responses','anthropic-messages':'/messages'} as Record<string,string>)[x.protocol])))&&!keyHits.length&&hostileCalls===0,'Actual Switcher/Aider native edit/history proof failed');
