import assert from "node:assert/strict";
import {mkdir,mkdtemp,readFile,writeFile,readdir} from "node:fs/promises";
import {join} from "node:path";
import {homedir} from "node:os";
import {fileURLToPath} from "node:url";
import {execFileSync} from "node:child_process";
const exe=process.env.SWITCHER_TEST_NATIVE_EXECUTABLE;if(!exe)throw new Error("Set SWITCHER_TEST_NATIVE_EXECUTABLE to installed Kilo.");
const scratch=process.env.SWITCHER_TEST_ROOT??join(homedir(),"Workspace/scratch/switcher-native-tests");await mkdir(scratch,{recursive:true,mode:0o700});const root=await mkdtemp(join(scratch,"kilo-lifecycle-"));
const key="fixture-"+crypto.randomUUID(),cli=fileURLToPath(new URL("../src/cli.ts",import.meta.url));const controllers=new Map<string,ReadableStreamDefaultController<Uint8Array>>(),aborted=new Set<string>(),seen:string[]=[];const calls:any[]=[];
const upstream=Bun.serve({hostname:"127.0.0.1",port:0,async fetch(request){const path=new URL(request.url).pathname;if(path==="/prefix/v1/models")return Response.json({data:["fixture/one","fixture/two"].map(id=>({id,context_length:32000,max_output_tokens:1024}))});if(path!=="/prefix/v1/chat/completions")return new Response("wrong route",{status:404});const body=await request.json() as any;calls.push({model:body.model,path,authMatches:request.headers.get("x-api-key")===key&&!request.headers.has("authorization")});seen.push(body.model);request.signal.addEventListener("abort",()=>aborted.add(body.model),{once:true});return new Response(new ReadableStream({start(controller){controllers.set(body.model,controller);controller.enqueue(new TextEncoder().encode(": fixture holding stream\n\n"));},cancel(){aborted.add(body.model);}}),{headers:{"content-type":"text/event-stream"}});}});
const env={PATH:process.env.PATH!,HOME:join(root,"home"),XDG_CONFIG_HOME:join(root,"config"),XDG_DATA_HOME:join(root,"data"),XDG_STATE_HOME:join(root,"state"),XDG_CACHE_HOME:join(root,"cache"),HASNA_SWITCHER_HOME:join(root,"switcher"),SWITCHER_PROVIDER_FIXTURE:key};await mkdir(env.HOME);await writeFile(join(root,"kilo.json"),JSON.stringify({permission:"deny"}));
const scrub=(s:string)=>s.replaceAll(key,"[fixture key redacted]");const children:ReturnType<typeof Bun.spawn>[]=[];const ownedPids=new Set<number>();
function start(args:string[],label:string){const child=Bun.spawn([process.execPath,cli,...args],{cwd:root,env,stdin:"ignore",stdout:"pipe",stderr:"pipe",detached:true});children.push(child);ownedPids.add(child.pid);const output=Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text()]).then(async([out,err])=>{await writeFile(join(root,label+".stdout"),scrub(out));await writeFile(join(root,label+".stderr"),scrub(err));return {stdout:scrub(out),stderr:scrub(err)};});return {child,output};}
async function until(check:()=>boolean,ms=10000){const end=Date.now()+ms;while(!check()&&Date.now()<end)await Bun.sleep(25);assert(check(),"fixture deadline exceeded");}
const alive=(pid:number)=>{try{process.kill(pid,0);return true;}catch{return false;}};
function descendants(rootPid:number){const text=execFileSync("ps",["-axo","pid=,ppid=,pgid="],{encoding:"utf8",timeout:2000});const rows=text.trim().split("\n").map(line=>line.trim().split(/\s+/).map(Number));const ids=new Set([rootPid]);let size=0;while(ids.size!==size){size=ids.size;for(const[pid,ppid]of rows)if(ids.has(ppid))ids.add(pid);}for(const id of ids)ownedPids.add(id);return rows.filter(([pid])=>ids.has(pid)).map(([pid,ppid,pgid])=>({pid,ppid,pgid}));}
const report:any={root,at:new Date().toISOString(),native:exe,source:cli};const deadline=setTimeout(()=>{for(const child of children)if(child.exitCode===null)try{process.kill(-child.pid,"SIGTERM")}catch{}},30000);
try{
 const add=start(["providers","add","fixture","--name","Fixture","--url",upstream.url.origin+"/prefix/v1","--protocol","openai-chat","--credential-env","SWITCHER_PROVIDER_FIXTURE","--auth-style","x-api-key"],"provider-add");assert.equal(await add.child.exited,0);await add.output;
 const common=["launch","kilo","--provider","fixture","--executable",exe,"--timeout","20"];
 const first=start([...common,"--model","fixture/one","--","run","--format","json","--title","One","Wait for a fixture response."],"one"),second=start([...common,"--model","fixture/two","--","run","--format","json","--title","Two","Wait for another fixture response."],"two");
 await until(()=>seen.includes("fixture/one")&&seen.includes("fixture/two"));report.firstTree=descendants(first.child.pid);report.secondTree=descendants(second.child.pid);assert(report.firstTree.length>1&&report.secondTree.length>1,"must observe native processes before cancellation");
 const startTime=Date.now();process.kill(first.child.pid,"SIGTERM");await until(()=>first.child.exitCode!==null,8000);await first.output;await until(()=>aborted.has("fixture/one"),3000);report.cancelMs=Date.now()-startTime;assert.equal(second.child.exitCode,null,"cancelling one profile killed the other");assert(!aborted.has("fixture/two"));assert(report.firstTree.every(({pid}:{pid:number})=>!alive(pid)),"owned cancelled native process survived");
 const c=controllers.get("fixture/two")!;const event=(delta:unknown,finish_reason:unknown)=>({id:"fixture",object:"chat.completion.chunk",created:1,model:"fixture/two",choices:[{index:0,delta,finish_reason}]});c.enqueue(new TextEncoder().encode([event({role:"assistant",content:"SECOND_PROFILE_SURVIVED"},null),event({},"stop")].map(v=>`data: ${JSON.stringify(v)}\n\n`).join("")+"data: [DONE]\n\n"));
 c.close(); // Kilo consumes stream EOF before completing its native turn.
 await until(()=>second.child.exitCode!==null,8000);const out=await second.output;assert.equal(second.child.exitCode,0);assert(out.stdout.includes("SECOND_PROFILE_SURVIVED"));report.secondCompletedWithEof=true;assert(report.secondTree.every(({pid}:{pid:number})=>!alive(pid)),"owned completed native process survived");
 const runs=start(["runs","list"],"runs");assert.equal(await runs.child.exited,0);const listed=JSON.parse((await runs.output).stdout);const items=listed.items??listed.data??listed;report.runStatuses=items.map((r:any)=>r.status).sort();assert.deepEqual(report.runStatuses,["exited","interrupted"]);assert(!(await readdir(join(root,"switcher/state"))).some(name=>name.startsWith("launch-")));report.passed=true;
}catch(error){report.passed=false;report.error=String(error);process.exitCode=1;}
finally{clearTimeout(deadline);for(const child of children)if(child.exitCode===null){try{process.kill(-child.pid,"SIGTERM")}catch{}await Promise.race([child.exited,Bun.sleep(6000)]);if(child.exitCode===null)try{process.kill(-child.pid,"SIGKILL")}catch{}await child.exited;}for(const pid of ownedPids)if(alive(pid))try{process.kill(pid,"SIGKILL")}catch{}for(const controller of controllers.values())try{controller.close()}catch{}await upstream.stop(true);report.calls=calls;report.aborted=[...aborted];const keyHits:string[]=[];for(const entry of await readdir(root,{recursive:true,withFileTypes:true}))if(entry.isFile()){const path=join(entry.parentPath,entry.name);if((await readFile(path)).includes(Buffer.from(key)))keyHits.push(path);}report.providerKeyFileHits=keyHits;if(keyHits.length||calls.some(c=>!c.authMatches)){report.passed=false;process.exitCode=1;}await writeFile(join(root,"result.json"),JSON.stringify(report,null,2)+"\n");console.log(JSON.stringify(report));}
