import { createHash } from "node:crypto";
import { ArtifactStorage } from "./artifact-storage.js";
import { createArtifactId } from "./store.js";
import { redactForClient } from "./redaction.js";
import type { ServerArtifact, ServerRunRecord, SkillsProductStore } from "./types.js";

const DETERMINISTIC_TEXT_HANDLERS = new Set([
  "audio-transcript-pack",
  "transcript",
  "video-highlight-pack",
]);

export async function executeRun(store: SkillsProductStore, run: ServerRunRecord, storage = new ArtifactStorage()): Promise<ServerRunRecord> {
  try {
    await store.appendLog(run.id, run.orgId, "info", redactForClient(`starting run ${run.skill}`));
    if (!DETERMINISTIC_TEXT_HANDLERS.has(run.skill)) {
      await store.appendLog(run.id, run.orgId, "warn", `${run.skill} has no provider-free handler yet`);
      return await failRun(store, run, "HANDLER_UNAVAILABLE", "This deployment has no safe provider-free handler for that skill yet.");
    }

    const text = extractText(run);
    if (!text.trim()) {
      return await failRun(store, run, "INVALID_INPUT", "Provide transcript text with input.transcript, input.text, --text, --source, or positional text.");
    }

    const title = extractOption(run.args, "--title") || stringInput(run.input, "title") || "Skills run";
    const summary = summarize(text);
    const artifacts = [
      textArtifact(run, "transcript.md", `# ${title}\n\n${text.trim()}\n`),
      textArtifact(run, "summary.md", `# Summary\n\n${summary}\n`),
      textArtifact(run, "show-notes.md", `# Show Notes\n\n- ${summary}\n- Generated by the skills deterministic worker.\n`),
      textArtifact(run, "clips.csv", `start,end,title,summary\n00:00,00:30,\"Opening\",\"${csv(summary)}\"\n`),
      textArtifact(run, "manifest.json", JSON.stringify({
        runId: run.id,
        skill: run.skill,
        requestedSlug: run.requestedSlug,
        generatedAt: new Date().toISOString(),
        artifacts: ["transcript.md", "summary.md", "show-notes.md", "clips.csv"],
      }, null, 2) + "\n", "application/json"),
    ];

    for (const artifact of artifacts) {
      await store.addArtifact(await storage.materialize(run, artifact.meta, artifact.body));
    }
    await store.appendLog(run.id, run.orgId, "info", `generated ${artifacts.length} artifacts`);
    return await completeRun(store, run, summary);
  } catch (error) {
    return await failRun(store, run, "WORKER_ERROR", redactForClient((error as Error).message));
  }
}

function textArtifact(
  run: ServerRunRecord,
  relativePath: string,
  bodyText: string,
  contentType = relativePath.endsWith(".json") ? "application/json" : "text/markdown; charset=utf-8",
): {
  meta: Omit<ServerArtifact, "createdAt" | "storageKind" | "storageKey" | "bodyText">;
  body: { relativePath: string; bodyText: string; contentType: string };
} {
  const bytes = new TextEncoder().encode(bodyText);
  return {
    meta: {
      id: createArtifactId(),
      runId: run.id,
      orgId: run.orgId,
      fileName: relativePath.split("/").pop() || relativePath,
      relativePath,
      contentType,
      byteSize: bytes.byteLength,
      sha256: createHash("sha256").update(bytes).digest("hex"),
      // Run outputs are private by default; a governed writer may widen this at
      // write time, never at read time.
      visibility: "private",
    },
    body: { relativePath, bodyText, contentType },
  };
}

async function completeRun(store: SkillsProductStore, run: ServerRunRecord, preview: string): Promise<ServerRunRecord> {
  const next = await fencedTransition(store, run, {
    status: "succeeded",
    outputType: "artifact_bundle",
    outputPreview: preview,
    completedAt: new Date().toISOString(),
  });
  return next ?? run;
}

async function failRun(
  store: SkillsProductStore,
  run: ServerRunRecord,
  code: string,
  message: string,
): Promise<ServerRunRecord> {
  // Best-effort: the error log must never abort the terminal transition. The
  // failure that lands us here can itself be a log-write failure (SQLITE_BUSY
  // past the finite busy_timeout, a Postgres log-sequence conflict past
  // LOG_SEQUENCE_ATTEMPTS), and a second appendLog rejecting inside this catch
  // would propagate out of executeRun before fencedTransition runs - the run
  // then stays 'running' with locked_by set and is never reclaimed, because
  // claimNextRun selects only queued/retrying rows.
  try {
    await store.appendLog(run.id, run.orgId, "error", message);
  } catch {
    // The run's terminal state is the invariant; the log line is not.
  }
  const next = await fencedTransition(store, run, {
    status: "failed",
    errorCode: code,
    errorMessage: message,
    completedAt: new Date().toISOString(),
  });
  return next ?? run;
}

/**
 * The worker's terminal transition, fenced by the claimed lease generation.
 *
 * A cancellation bumps lease_generation, so a worker that finishes after the
 * cancel was issued no longer matches and its terminal write is refused - the
 * run stays cancelled instead of being moved to succeeded/failed by a worker
 * that no longer owns it. The refusal is visible: the run is logged as a late
 * write rather than silently dropped.
 */
async function fencedTransition(
  store: SkillsProductStore,
  run: ServerRunRecord,
  patch: Parameters<NonNullable<SkillsProductStore["transitionRun"]>>[1],
): Promise<ServerRunRecord | null> {
  if (!store.transitionRun) return store.updateRun(run.id, patch);
  const next = await store.transitionRun(run.id, patch, run.leaseGeneration);
  if (!next) {
    try {
      await store.appendLog(run.id, run.orgId, "warn", `late write rejected: run no longer owned at lease_generation ${run.leaseGeneration}`);
    } catch {
      // Best-effort, same class as failRun: the refusal is already the terminal
      // fact, and a failing warning log must not turn it into a rejection that
      // escapes completeRun/failRun.
    }
  }
  return next;
}

function extractText(run: ServerRunRecord): string {
  return stringInput(run.input, "transcript")
    || stringInput(run.input, "text")
    || extractOption(run.args, "--text")
    || extractOption(run.args, "--source")
    || run.args.filter((arg) => !arg.startsWith("--")).join(" ");
}

function stringInput(input: Record<string, unknown>, key: string): string | undefined {
  const value = input[key];
  return typeof value === "string" && value.trim() ? value : undefined;
}

function extractOption(args: string[], flag: string): string | undefined {
  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg === flag && args[i + 1]) return args[i + 1];
    if (arg.startsWith(`${flag}=`)) return arg.slice(flag.length + 1);
  }
  return undefined;
}

function summarize(text: string): string {
  const normalized = redactForClient(text).replace(/\s+/g, " ").trim();
  if (normalized.length <= 220) return normalized;
  return `${normalized.slice(0, 217)}...`;
}

function csv(value: string): string {
  return value.replace(/"/g, '""');
}
