import type { ConnectorMeta } from "../registry.js";

// AI & ML
export const connectors: ConnectorMeta[] = [
  {
    name: "anthropic",
    displayName: "Anthropic",
    description: "Claude AI models and API",
    category: "AI & ML",
    tags: ["ai", "llm", "claude"],
  },
  {
    name: "openai",
    displayName: "OpenAI",
    description: "GPT models, DALL-E, and Whisper",
    category: "AI & ML",
    tags: ["ai", "llm", "gpt", "dalle"],
  },
  {
    name: "xai",
    displayName: "xAI",
    description: "Grok AI models",
    category: "AI & ML",
    tags: ["ai", "llm", "grok"],
  },
  {
    name: "xai-api-platform",
    displayName: "Xai API Platform",
    description: "Xai API Platform REST API for items, events, and search",
    category: "AI & ML",
    tags: ["ai", "api-platform", "rest"],
  },
  {
    name: "minimax",
    displayName: "Minimax",
    description: "Video, music, image, TTS, and sound effects generation",
    category: "AI & ML",
    tags: ["ai", "video", "music", "tts", "image", "sound-effects"],
  },
  {
    name: "mistral",
    displayName: "Mistral",
    description: "Mistral AI models",
    category: "AI & ML",
    tags: ["ai", "llm"],
  },
  {
    name: "googlegemini",
    displayName: "Google Gemini",
    description: "Gemini AI models",
    category: "AI & ML",
    tags: ["ai", "llm", "google"],
  },
  {
    name: "huggingface",
    displayName: "Hugging Face",
    description: "ML models and datasets hub",
    category: "AI & ML",
    tags: ["ai", "ml", "models"],
  },
  {
    name: "stabilityai",
    displayName: "Stability AI",
    description: "Stable Diffusion image generation",
    category: "AI & ML",
    tags: ["ai", "image", "generation"],
  },
  {
    name: "midjourney",
    displayName: "Midjourney",
    description: "AI image generation",
    category: "AI & ML",
    tags: ["ai", "image", "generation"],
  },
  {
    name: "heygen",
    displayName: "HeyGen",
    description: "AI video generation",
    category: "AI & ML",
    tags: ["ai", "video", "avatar"],
  },
  {
    name: "hedra",
    displayName: "Hedra",
    description: "AI video generation",
    category: "AI & ML",
    tags: ["ai", "video"],
  },
  {
    name: "elevenlabs",
    displayName: "ElevenLabs",
    description: "AI voice synthesis and cloning",
    category: "AI & ML",
    tags: ["ai", "voice", "tts"],
  },
  {
    name: "reducto",
    displayName: "Reducto",
    description: "Document processing and extraction",
    category: "AI & ML",
    tags: ["ai", "document", "ocr"],
  },
  {
    name: "tinker",
    displayName: "Tinker",
    description: "LLM fine-tuning and training API",
    category: "AI & ML",
    tags: ["ai", "llm", "fine-tuning"],
  },
  {
    name: "traverse",
    displayName: "Traverse",
    description: "RL training environments, episodes, judgments, and datasets",
    category: "AI & ML",
    tags: ["ai", "rl", "training", "environments"],
  },
  {
    name: "groq",
    displayName: "Groq",
    description: "Ultra-fast LLM inference",
    category: "AI & ML",
    tags: ["ai", "llm", "inference"],
  },
  {
    name: "replicate",
    displayName: "Replicate",
    description: "Run ML models in the cloud",
    category: "AI & ML",
    tags: ["ai", "ml", "models"],
  },
  {
    name: "together",
    displayName: "Together AI",
    description: "Open-source model inference and fine-tuning",
    category: "AI & ML",
    tags: ["ai", "llm", "open-source"],
  },
  {
    name: "zatanna",
    displayName: "Zatanna",
    description: "AI workflow automation and orchestration",
    category: "AI & ML",
    tags: ["ai", "workflows", "automation"],
  },
  {
    name: "cohere",
    displayName: "Cohere",
    description: "Enterprise NLP and embeddings",
    category: "AI & ML",
    tags: ["ai", "nlp", "embeddings"],
  },
  {
    name: "deepseek",
    displayName: "DeepSeek",
    description: "AI coding and reasoning models",
    category: "AI & ML",
    tags: ["ai", "llm", "coding"],
  },
  {
    name: "perplexity",
    displayName: "Perplexity",
    description: "AI search and answer engine",
    category: "AI & ML",
    tags: ["ai", "search", "llm"],
  },
  {
    name: "fal",
    displayName: "fal.ai",
    description: "Fast image and video generation",
    category: "AI & ML",
    tags: ["ai", "image", "video"],
  },
  {
    name: "baseten",
    displayName: "Baseten",
    description: "ML model deployment and inference",
    category: "AI & ML",
    tags: ["ai", "ml", "deployment"],
  },
  {
    name: "fireworks",
    displayName: "Fireworks AI",
    description: "Fast generative AI inference",
    category: "AI & ML",
    tags: ["ai", "llm", "inference"],
  },
  {
    name: "cerebras",
    displayName: "Cerebras",
    description: "Ultra-fast AI inference",
    category: "AI & ML",
    tags: ["ai", "llm", "inference"],
  },
  {
    name: "modal",
    displayName: "Modal",
    description: "Serverless GPU compute for AI",
    category: "AI & ML",
    tags: ["ai", "gpu", "serverless"],
  },
  {
    name: "deepgram",
    displayName: "Deepgram",
    description: "Speech-to-text and audio intelligence",
    category: "AI & ML",
    tags: ["ai", "speech", "stt"],
  },
  {
    name: "assemblyai",
    displayName: "AssemblyAI",
    description: "Speech recognition and audio intelligence",
    category: "AI & ML",
    tags: ["ai", "speech", "transcription"],
  },
  {
    name: "roboflow",
    displayName: "Roboflow",
    description: "Computer vision models and datasets",
    category: "AI & ML",
    tags: ["ai", "vision", "cv"],
  },
  {
    name: "runway",
    displayName: "Runway",
    description: "AI video generation and editing",
    category: "AI & ML",
    tags: ["ai", "video", "generation"],
  },
  {
    name: "luma",
    displayName: "Luma AI",
    description: "AI video and 3D generation",
    category: "AI & ML",
    tags: ["ai", "video", "3d"],
  },
  {
    name: "3scribe",
    displayName: "3Scribe",
    description: "Audio and video transcription",
    category: "AI & ML",
    tags: ["transcription", "audio", "speech"],
  },
  {
    name: "accurai",
    displayName: "AccurAI",
    description: "AI-powered document data extraction and processing",
    category: "AI & ML",
    tags: ["ai", "document", "extraction"],
  },
  {
    name: "agent",
    displayName: "Agent.ai",
    description: "AI agent platform with web extraction and content generation",
    category: "AI & ML",
    tags: ["ai", "agents", "automation"],
  },
  {
    name: "aiagenttool",
    displayName: "AI Agent Tool",
    description: "AI agent tooling and orchestration",
    category: "AI & ML",
    tags: ["ai", "agents", "tools"],
  },
  {
    name: "alphamoon",
    displayName: "Alphamoon",
    description: "AI document processing and intelligent data extraction",
    category: "AI & ML",
    tags: ["ai", "document", "ocr"],
  },
  {
    name: "alttextai",
    displayName: "AltText.ai",
    description: "AI-generated alt text for images",
    category: "AI & ML",
    tags: ["ai", "accessibility", "images"],
  },
  {
    name: "anyscale",
    displayName: "Anyscale",
    description: "Enterprise LLM endpoints and Ray-based ML infrastructure",
    category: "AI & ML",
    tags: ["ai", "llm", "inference"],
  },
  {
    name: "azureaisearchvectorstore",
    displayName: "Azure AI Search Vector Store",
    description: "Vector search and indexing for AI applications",
    category: "AI & ML",
    tags: ["ai", "vector", "search", "azure"],
  },
  {
    name: "azureopenaichatmodel",
    displayName: "Azure OpenAI Chat Model",
    description: "OpenAI models hosted on Azure",
    category: "AI & ML",
    tags: ["ai", "llm", "openai", "azure"],
  },
  {
    name: "bigml",
    displayName: "BigML",
    description: "Machine learning models and predictions",
    category: "AI & ML",
    tags: ["ml", "predictions", "models"],
  },
  {
    name: "bot9",
    displayName: "Bot9",
    description: "AI chatbot builder for customer support",
    category: "AI & ML",
    tags: ["ai", "chatbot", "support"],
  },
  {
    name: "botsonic",
    displayName: "Botsonic",
    description: "AI-powered custom chatbots trained on your data",
    category: "AI & ML",
    tags: ["ai", "chatbot", "custom"],
  },
  {
    name: "brainpodai",
    displayName: "BrainPod AI",
    description: "AI content generation and writing assistant",
    category: "AI & ML",
    tags: ["ai", "content", "writing"],
  },
  {
    name: "chaindesk",
    displayName: "Chaindesk",
    description: "No-code AI chatbot platform for custom data",
    category: "AI & ML",
    tags: ["ai", "chatbot", "no-code"],
  },
  {
    name: "chatbase",
    displayName: "Chatbase",
    description: "Custom AI chatbots trained on your data",
    category: "AI & ML",
    tags: ["ai", "chatbot", "custom"],
  },
  {
    name: "chatling",
    displayName: "Chatling",
    description: "AI chatbot builder for websites",
    category: "AI & ML",
    tags: ["ai", "chatbot", "website"],
  },
  {
    name: "chatmasters",
    displayName: "Chatmasters",
    description: "AI-powered customer service chatbots",
    category: "AI & ML",
    tags: ["ai", "chatbot", "support"],
  },
  {
    name: "chatsonic",
    displayName: "ChatSonic",
    description: "AI content generation and conversational AI",
    category: "AI & ML",
    tags: ["ai", "content", "chat"],
  },
  {
    name: "chromavectorstore",
    displayName: "Chroma Vector Store",
    description: "Open-source vector database for AI embeddings",
    category: "AI & ML",
    tags: ["ai", "vector", "embeddings", "database"],
  },
  {
    name: "clarifai",
    displayName: "Clarifai",
    description: "AI platform for computer vision and NLP",
    category: "AI & ML",
    tags: ["ai", "vision", "nlp"],
  },
  {
    name: "cloozo",
    displayName: "Cloozo",
    description: "AI chatbot builder with knowledge base integration",
    category: "AI & ML",
    tags: ["ai", "chatbot", "knowledge-base"],
  },
  {
    name: "browseruse",
    displayName: "Browser Use",
    description: "AI-powered browser automation tasks and sessions",
    category: "AI & ML",
    tags: ["ai", "browser", "automation"],
  },
  {
    name: "stablebrowse",
    displayName: "StableBrowse",
    description: "AI browser automation tasks, sessions, and design extraction",
    category: "AI & ML",
    tags: ["ai", "browser", "automation", "agent"],
  },
  {
    name: "cody",
    displayName: "Cody",
    description: "AI coding assistant by Sourcegraph",
    category: "AI & ML",
    tags: ["ai", "coding", "assistant"],
  },
  {
    name: "convi",
    displayName: "Convi",
    description: "Conversational AI and chatbot platform",
    category: "AI & ML",
    tags: ["ai", "chatbot", "conversational"],
  },
  {
    name: "copyai",
    displayName: "Copy.ai",
    description: "AI-powered copywriting and content generation",
    category: "AI & ML",
    tags: ["ai", "copywriting", "content"],
  },
  {
    name: "cradlai",
    displayName: "Cradl AI",
    description: "AI document parsing and data extraction",
    category: "AI & ML",
    tags: ["ai", "document", "extraction"],
  },
  {
    name: "customeriq",
    displayName: "CustomerIQ",
    description: "AI-powered customer feedback analysis",
    category: "AI & ML",
    tags: ["ai", "feedback", "customer-insights"],
  },
  {
    name: "danteai",
    displayName: "Dante AI",
    description: "AI chatbot platform with custom knowledge bases",
    category: "AI & ML",
    tags: ["ai", "chatbot", "knowledge-base"],
  },
  {
    name: "dasha",
    displayName: "Dasha",
    description: "Conversational AI for voice and text applications",
    category: "AI & ML",
    tags: ["ai", "voice", "conversational"],
  },
  {
    name: "datarobot",
    displayName: "DataRobot",
    description: "Enterprise AI platform for automated machine learning",
    category: "AI & ML",
    tags: ["ai", "ml", "automl", "enterprise"],
  },
  {
    name: "datumbox",
    displayName: "Datumbox",
    description: "Machine learning and NLP services for text analysis and sentiment detection",
    category: "AI & ML",
    tags: ["ai", "nlp", "sentiment", "text-analysis"],
  },
  {
    name: "deepinfra",
    displayName: "DeepInfra",
    description: "Scalable AI inference for LLMs, text-to-image, and embeddings",
    category: "AI & ML",
    tags: ["ai", "inference", "llm", "embeddings"],
  },
  {
    name: "deepl",
    displayName: "DeepL",
    description: "Neural machine translation, document translation, and glossary management",
    category: "AI & ML",
    tags: ["ai", "translation", "nlp", "languages"],
  },
  {
    name: "diddoai",
    displayName: "Diddo AI",
    description: "AI chatbot builder and conversational AI platform",
    category: "AI & ML",
    tags: ["ai", "chatbot", "conversational"],
  },
  {
    name: "docsbotai",
    displayName: "DocsBot AI",
    description: "AI-powered documentation chatbot and knowledge base assistant",
    category: "AI & ML",
    tags: ["ai", "chatbot", "documentation", "knowledge-base"],
  },
  {
    name: "droxy",
    displayName: "Droxy",
    description: "AI chatbot platform for customer support and engagement",
    category: "AI & ML",
    tags: ["ai", "chatbot", "customer-support"],
  },
  {
    name: "edenai",
    displayName: "Eden AI",
    description: "Unified AI API for NLP, vision, speech, and translation",
    category: "AI & ML",
    tags: ["ai", "nlp", "vision", "speech", "unified-api"],
  },
  {
    name: "embedai",
    displayName: "EmbedAI",
    description: "AI embedding generation and management platform",
    category: "AI & ML",
    tags: ["ai", "embedding", "vectors"],
  },
  {
    name: "engati",
    displayName: "Engati",
    description: "Conversational AI chatbot and automation platform",
    category: "AI & ML",
    tags: ["ai", "chatbot", "conversational-ai"],
  },
  {
    name: "faraday",
    displayName: "Faraday",
    description: "Predictive analytics and customer AI platform",
    category: "AI & ML",
    tags: ["ai", "predictions", "analytics", "customer"],
  },
  {
    name: "fastbots",
    displayName: "Fastbots",
    description: "AI chatbot builder for websites and customer support",
    category: "AI & ML",
    tags: ["ai", "chatbot", "support", "website"],
  },
  {
    name: "gali",
    displayName: "Gali",
    description: "AI-powered chatbot and lead qualification",
    category: "AI & ML",
    tags: ["chatbot", "ai", "lead-generation"],
  },
  {
    name: "googleperspective",
    displayName: "Google Perspective",
    description: "Content toxicity and abuse detection API",
    category: "AI & ML",
    tags: ["google", "moderation", "toxicity", "ai"],
  },
  {
    name: "googlevertexai",
    displayName: "Google Vertex AI",
    description: "Google Cloud AI and ML platform",
    category: "AI & ML",
    tags: ["google", "ai", "ml", "vertex"],
  },
  {
    name: "gptea",
    displayName: "GPTea",
    description: "GPT-powered AI assistant API",
    category: "AI & ML",
    tags: ["ai", "gpt", "assistant"],
  },
  {
    name: "hansei",
    displayName: "Hansei",
    description: "AI-powered knowledge base and chat",
    category: "AI & ML",
    tags: ["ai", "knowledge", "chatbot"],
  },
  {
    name: "humanticai",
    displayName: "Humantic AI",
    description: "Buyer intelligence and personality AI",
    category: "AI & ML",
    tags: ["ai", "personality", "sales"],
  },
  {
    name: "ideogram",
    displayName: "Ideogram",
    description: "AI image generation with text rendering",
    category: "AI & ML",
    tags: ["ai", "image-generation", "text-to-image"],
  },
  {
    name: "ideta",
    displayName: "Ideta",
    description: "No-code chatbot builder",
    category: "AI & ML",
    tags: ["chatbot", "no-code", "automation"],
  },
  {
    name: "impira",
    displayName: "Impira",
    description: "AI-powered document data extraction",
    category: "AI & ML",
    tags: ["ai", "document", "ocr", "extraction"],
  },
  {
    name: "jasper",
    displayName: "Jasper",
    description: "AI content generation and marketing copy",
    category: "AI & ML",
    tags: ["ai", "content", "copywriting", "marketing"],
  },
  {
    name: "jinaai",
    displayName: "Jina AI",
    description: "Neural search and embedding models",
    category: "AI & ML",
    tags: ["ai", "search", "embeddings", "neural"],
  },
  {
    name: "kling",
    displayName: "Kling AI",
    description: "AI video generation and editing",
    category: "AI & ML",
    tags: ["ai", "video", "generation"],
  },
  {
    name: "kraftful",
    displayName: "Kraftful",
    description: "AI-powered product feedback analysis",
    category: "AI & ML",
    tags: ["ai", "product", "feedback", "analytics"],
  },
  {
    name: "leonardo",
    displayName: "Leonardo AI",
    description: "AI image generation and creative tools",
    category: "AI & ML",
    tags: ["ai", "image-generation", "creative"],
  },
  {
    name: "lepton",
    displayName: "Lepton AI",
    description: "Serverless AI model deployment infrastructure",
    category: "AI & ML",
    tags: ["ai", "serverless", "infrastructure", "deployment"],
  },
  {
    name: "letsenhance",
    displayName: "Let's Enhance",
    description: "AI-powered image upscaling and enhancement",
    category: "AI & ML",
    tags: ["ai", "image", "upscaling", "enhancement"],
  },
  {
    name: "libraria",
    displayName: "Libraria",
    description: "AI chatbot and knowledge base builder",
    category: "AI & ML",
    tags: ["ai", "chatbot", "knowledge-base"],
  },
  {
    name: "lingvanex",
    displayName: "Lingvanex",
    description: "Machine translation and language detection API",
    category: "AI & ML",
    tags: ["translation", "language", "nlp"],
  },
  {
    name: "mindee",
    displayName: "Mindee",
    description: "Document parsing and OCR with AI-powered data extraction",
    category: "AI & ML",
    tags: ["ocr", "document", "parsing", "ai", "extraction"],
  },
  {
    name: "mubert",
    displayName: "Mubert",
    description: "AI-powered music generation and royalty-free audio",
    category: "AI & ML",
    tags: ["music", "ai", "audio", "generation"],
  },
  {
    name: "murf",
    displayName: "Murf",
    description: "AI text-to-speech with natural-sounding voices",
    category: "AI & ML",
    tags: ["tts", "voice", "ai", "speech"],
  },
  {
    name: "myaskai",
    displayName: "My AskAI",
    description: "Custom AI assistant builder for knowledge bases",
    category: "AI & ML",
    tags: ["ai", "chatbot", "knowledge-base", "assistant"],
  },
  {
    name: "nanonetsocr",
    displayName: "Nanonets OCR",
    description: "AI-powered OCR and intelligent document processing",
    category: "AI & ML",
    tags: ["ocr", "ai", "document", "extraction"],
  },
  {
    name: "nuclia",
    displayName: "Nuclia",
    description: "AI-powered search and knowledge base API",
    category: "AI & ML",
    tags: ["search", "ai", "knowledge-base", "rag", "nlp"],
  },
  {
    name: "nyckel",
    displayName: "Nyckel",
    description: "Machine learning API for image and text classification",
    category: "AI & ML",
    tags: ["ml", "classification", "image", "text", "ai"],
  },
  {
    name: "nyota",
    displayName: "Nyota",
    description: "AI meeting notes and action item tracking platform",
    category: "AI & ML",
    tags: ["meetings", "ai", "notes", "productivity", "transcription"],
  },
  {
    name: "octoai",
    displayName: "OctoAI",
    description: "Fast AI inference platform for generative AI models",
    category: "AI & ML",
    tags: ["ai", "inference", "llm", "generative", "gpu"],
  },
  {
    name: "ollama",
    displayName: "Ollama",
    description: "Run large language models locally on your machine",
    category: "AI & ML",
    tags: ["llm", "local", "ai", "open-source", "inference"],
  },
  {
    name: "omnimind",
    displayName: "OmniMind",
    description: "No-code AI assistant builder with custom knowledge bases",
    category: "AI & ML",
    tags: ["ai", "chatbot", "no-code", "knowledge-base", "assistant"],
  },
  {
    name: "oneai",
    displayName: "One AI",
    description: "Language AI API for text analysis, summarization, and extraction",
    category: "AI & ML",
    tags: ["nlp", "ai", "text-analysis", "summarization", "extraction"],
  },
  {
    name: "parseprompt",
    displayName: "ParsePrompt",
    description: "AI-powered document parsing and data extraction API",
    category: "AI & ML",
    tags: ["ai", "parsing", "documents", "extraction", "ocr"],
  },
  {
    name: "personalai",
    displayName: "Personal AI",
    description: "Personal AI assistant with memory and custom knowledge base",
    category: "AI & ML",
    tags: ["ai", "personal", "memory", "assistant", "knowledge"],
  },
  {
    name: "pika",
    displayName: "Pika",
    description: "AI video generation platform API",
    category: "AI & ML",
    tags: ["ai", "video", "generation", "creative", "media"],
  },
  {
    name: "playht",
    displayName: "PlayHT",
    description: "AI text-to-speech and voice cloning API",
    category: "AI & ML",
    tags: ["tts", "text-to-speech", "voice", "cloning", "audio"],
  },
  {
    name: "predisai",
    displayName: "Predis AI",
    description: "AI-powered social media content creation and scheduling",
    category: "AI & ML",
    tags: ["ai", "social-media", "content", "scheduling", "marketing"],
  },
  {
    name: "prodia",
    displayName: "Prodia",
    description: "Fast AI image generation API using Stable Diffusion",
    category: "AI & ML",
    tags: ["ai", "image-generation", "stable-diffusion", "art", "creative"],
  },
  {
    name: "prompthub",
    displayName: "PromptHub",
    description: "Prompt management and versioning platform for AI applications",
    category: "AI & ML",
    tags: ["prompts", "ai", "versioning", "management", "llm"],
  },
  {
    name: "readai",
    displayName: "Read AI",
    description: "AI meeting assistant for transcription, summaries, and insights",
    category: "AI & ML",
    tags: ["meetings", "transcription", "ai", "summaries", "productivity"],
  },
  {
    name: "relevanceai",
    displayName: "Relevance AI",
    description: "AI platform for building and deploying custom AI agents and workflows",
    category: "AI & ML",
    tags: ["ai-agents", "workflows", "automation", "llm", "platform"],
  },
  {
    name: "resemble",
    displayName: "Resemble AI",
    description: "Voice cloning and AI text-to-speech generation platform",
    category: "AI & ML",
    tags: ["voice-cloning", "text-to-speech", "ai", "audio", "synthesis"],
  },
  {
    name: "roboresponseai",
    displayName: "RoboResponseAI",
    description: "AI-powered chatbot and customer engagement automation platform",
    category: "AI & ML",
    tags: ["chatbot", "ai", "customer-engagement", "automation", "support"],
  },
  {
    name: "semblyai",
    displayName: "Sembly AI",
    description: "AI meeting assistant for transcription and smart summaries",
    category: "AI & ML",
    tags: ["ai", "meetings", "transcription", "summaries", "productivity"],
  },
  {
    name: "sharlyai",
    displayName: "Sharly AI",
    description: "AI document summarization and Q&A platform",
    category: "AI & ML",
    tags: ["ai", "documents", "summarization", "qa", "productivity"],
  },
  {
    name: "simpleem",
    displayName: "Simpleem",
    description: "AI-powered video meeting analysis and engagement insights",
    category: "AI & ML",
    tags: ["ai", "video", "meetings", "analytics", "engagement"],
  },
  {
    name: "sitespeakai",
    displayName: "SiteSpeak AI",
    description: "AI-powered chatbot and customer support automation for websites",
    category: "AI & ML",
    tags: ["ai", "chatbot", "customer support", "automation", "website"],
  },
  {
    name: "snatchbot",
    displayName: "SnatchBot",
    description: "Multi-channel chatbot building and automation platform",
    category: "AI & ML",
    tags: ["chatbot", "automation", "multi-channel", "bot builder", "messaging"],
  },
  {
    name: "speechify",
    displayName: "Speechify",
    description: "Text-to-speech API for converting text content to natural audio",
    category: "AI & ML",
    tags: ["text-to-speech", "tts", "audio", "accessibility", "ai"],
  },
  {
    name: "stammerai",
    displayName: "Stammer AI",
    description: "White-label AI chatbot platform for agencies and businesses",
    category: "AI & ML",
    tags: ["ai", "chatbot", "white-label", "agencies", "automation"],
  },
  {
    name: "strand-ai",
    displayName: "Strand AI",
    description: "Multimodal bio-data: WSI uploads, Lattice inference jobs, imputation results",
    category: "AI & ML",
    tags: ["ai", "biology", "imputation", "research"],
  },
  {
    name: "stagehand",
    displayName: "Stagehand",
    description: "Browserbase-hosted AI browser automation sessions",
    category: "AI & ML",
    tags: ["ai", "browser-automation", "agents", "browserbase"],
  },
  {
    name: "studiobyai21labs",
    displayName: "Studio by AI21 Labs",
    description: "AI writing and language models API by AI21 Labs",
    category: "AI & ML",
    tags: ["ai", "writing", "llm", "nlp", "language models"],
  },
  {
    name: "suno",
    displayName: "Suno",
    description: "AI music generation platform for creating songs from text prompts",
    category: "AI & ML",
    tags: ["ai", "music", "generation", "audio", "creative"],
  },
  {
    name: "supernormal",
    displayName: "Supernormal",
    description: "AI meeting notes and transcription tool for automatic summaries",
    category: "AI & ML",
    tags: ["ai", "meeting notes", "transcription", "summaries", "productivity"],
  },
  {
    name: "superpowered",
    displayName: "Superpowered",
    description: "Knowledge base API for AI applications with retrieval-augmented generation",
    category: "AI & ML",
    tags: ["ai", "knowledge base", "rag", "retrieval", "embeddings"],
  },
  {
    name: "synthesia",
    displayName: "Synthesia",
    description: "AI video generation platform for creating professional videos with AI avatars",
    category: "AI & ML",
    tags: ["ai", "video generation", "avatars", "synthetic media", "content creation"],
  },
  {
    name: "talknotes",
    displayName: "TalkNotes",
    description: "AI-powered voice-to-text note-taking app for converting speech to structured notes",
    category: "AI & ML",
    tags: ["ai", "voice", "transcription", "notes", "productivity"],
  },
  {
    name: "teknoir",
    displayName: "Teknoir",
    description: "Edge AI platform for deploying and managing AI models on edge devices",
    category: "AI & ML",
    tags: ["ai", "edge computing", "iot", "deployment", "models"],
  },
  {
    name: "textcortex",
    displayName: "TextCortex",
    description: "AI writing assistant API for text generation, summarization, rewriting, and classification",
    category: "AI & ML",
    tags: ["ai", "writing", "content generation", "nlp", "text"],
  },
  {
    name: "terminal-use",
    displayName: "Terminal Use",
    description: "Agent deployment runtime API with tasks, events, and persistent filesystems",
    category: "AI & ML",
    tags: ["agents", "runtime", "deployment", "filesystem"],
  },
  {
    name: "textcortexai",
    displayName: "TextCortex AI",
    description: "AI writing assistant for generating and rewriting content across platforms",
    category: "AI & ML",
    tags: ["ai", "writing", "content generation", "copywriting", "assistant"],
  },
  {
    name: "textgain",
    displayName: "Textgain",
    description: "Text analytics API for language detection, sentiment analysis, and NLP",
    category: "AI & ML",
    tags: ["nlp", "text analytics", "sentiment", "language detection", "api"],
  },
  {
    name: "textrazor",
    displayName: "TextRazor",
    description: "NLP API for entity extraction, topic detection, sentiment analysis, and text understanding",
    category: "AI & ML",
    tags: ["nlp", "entities", "topics", "sentiment", "text-analysis"],
  },
  {
    name: "the-company-company",
    displayName: "The Company Company",
    description: "Business agent platform",
    category: "AI & ML",
    tags: ["ai", "agents", "business-automation", "integrations"],
  },
  {
    name: "the-token-company",
    displayName: "The Token Company",
    description: "LLM prompt compression",
    category: "AI & ML",
    tags: ["ai", "llm", "compression", "tokens", "middleware"],
  },
  {
    name: "thoughtfulgpt",
    displayName: "Thoughtful GPT",
    description: "AI-powered healthcare automation platform for revenue cycle and patient management",
    category: "AI & ML",
    tags: ["ai", "healthcare", "automation", "revenue cycle", "medical"],
  },
  {
    name: "tisanelabs",
    displayName: "Tisane Labs",
    description: "NLP API for content moderation, sentiment analysis, and language understanding",
    category: "AI & ML",
    tags: ["nlp", "content moderation", "sentiment", "language understanding", "api"],
  },
  {
    name: "typless",
    displayName: "Typless",
    description: "AI-powered document data extraction and OCR for invoices and custom documents",
    category: "AI & ML",
    tags: ["ai", "document", "extraction", "ocr"],
  },
  {
    name: "udio",
    displayName: "Udio",
    description: "AI music generation platform",
    category: "AI & ML",
    tags: ["ai", "music", "generation"],
  },
  {
    name: "voicit",
    displayName: "Voicit",
    description: "AI meeting transcription and note-taking",
    category: "AI & ML",
    tags: ["transcription", "meetings", "ai"],
  },
  {
    name: "wato",
    displayName: "Wato",
    description: "Shared agent memories, workflows, tools, and artifacts",
    category: "AI & ML",
    tags: ["ai", "agents", "memory", "workflows"],
  },
  {
    name: "wavelineextract",
    displayName: "Waveline Extract",
    description: "Document data extraction and parsing",
    category: "AI & ML",
    tags: ["extraction", "documents", "parsing"],
  },
  {
    name: "wayco",
    displayName: "Wayco",
    description: "Med-legal case management, lead intake, medical records, provider matching, and voice calls",
    category: "AI & ML",
    tags: ["ai", "med-legal", "healthcare"],
  },
  {
    name: "weaviate",
    displayName: "Weaviate",
    description: "Open-source vector database for AI embeddings",
    category: "AI & ML",
    tags: ["ai", "vector", "embeddings", "database"],
  },
  {
    name: "wonderchat",
    displayName: "Wonderchat",
    description: "AI chatbot builder from website content",
    category: "AI & ML",
    tags: ["chatbot", "ai", "knowledge-base"],
  },
  {
    name: "wildcard",
    displayName: "Wildcard",
    description: "AI tool discovery, endpoint search, and agents.json flow execution",
    category: "AI & ML",
    tags: ["ai", "agents", "api-discovery", "tools"],
  },
  {
    name: "wondercraft",
    displayName: "Wondercraft",
    description: "AI-powered podcast and audio content creation",
    category: "AI & ML",
    tags: ["ai", "podcast", "audio"],
  },
  {
    name: "woxo",
    displayName: "WOXO",
    description: "AI video creation from text and templates",
    category: "AI & ML",
    tags: ["ai", "video", "generation"],
  },
  {
    name: "writesonic",
    displayName: "Writesonic",
    description: "AI writing and content generation platform",
    category: "AI & ML",
    tags: ["ai", "writing", "content"],
  },
  {
    name: "xtractly",
    displayName: "Xtractly",
    description: "AI document data extraction and automation",
    category: "AI & ML",
    tags: ["ai", "extraction", "documents"],
  },
  {
    name: "yousearch",
    displayName: "You.com Search",
    description: "You.com web search and research API",
    category: "AI & ML",
    tags: ["ai", "search", "research"],
  },
  {
    name: "tensorboard",
    displayName: "TensorBoard",
    description: "TensorBoard training run metrics and scalars",
    category: "AI & ML",
    tags: ["ai", "ml", "metrics", "visualization"],
  },
  {
    name: "zhipu-ai",
    displayName: "Zhipu AI",
    description: "GLM large language models via Zhipu Open Platform",
    category: "AI & ML",
    tags: ["ai", "llm", "glm", "zhipu"],
  },
  {
    name: "youart",
    displayName: "YouArt",
    description: "AI originals funding and creator economy",
    category: "AI & ML",
    tags: ["ai", "creator-economy", "funding"],
  },
];
