import type { ConnectorMeta } from "../registry.js";

// Business Tools
export const connectors: ConnectorMeta[] = [
  {
    name: "notion",
    displayName: "Notion",
    description: "Pages, databases, blocks, and property management",
    category: "Business Tools",
    tags: ["productivity", "databases", "wiki", "notes"],
  },
  {
    name: "quo",
    displayName: "Quo",
    description: "Business quotes and invoices",
    category: "Business Tools",
    tags: ["invoices", "quotes"],
  },
  {
    name: "sedo",
    displayName: "Sedo",
    description: "Domain marketplace",
    category: "Business Tools",
    tags: ["domains", "marketplace"],
  },
  {
    name: "linear",
    displayName: "Linear",
    description: "Issue tracking and project management",
    category: "Business Tools",
    tags: ["issues", "project-management"],
  },
  {
    name: "jira",
    displayName: "Jira",
    description: "Issue tracking, projects, and agile boards",
    category: "Business Tools",
    tags: ["issues", "project-management", "agile"],
  },
  {
    name: "confluence",
    displayName: "Confluence",
    description: "Pages, spaces, and content management",
    category: "Business Tools",
    tags: ["wiki", "documentation"],
  },
  {
    name: "asana",
    displayName: "Asana",
    description: "Projects, tasks, and team workflows",
    category: "Business Tools",
    tags: ["tasks", "project-management"],
  },
  {
    name: "trello",
    displayName: "Trello",
    description: "Boards, lists, and cards",
    category: "Business Tools",
    tags: ["kanban", "project-management"],
  },
  {
    name: "clickup",
    displayName: "ClickUp",
    description: "Tasks, docs, and project management",
    category: "Business Tools",
    tags: ["tasks", "project-management"],
  },
  {
    name: "todoist",
    displayName: "Todoist",
    description: "Task management and to-do lists",
    category: "Business Tools",
    tags: ["tasks", "todo"],
  },
  {
    name: "hubspot",
    displayName: "HubSpot",
    description: "CRM contacts, companies, deals, and tickets",
    category: "Business Tools",
    tags: ["crm", "sales", "marketing"],
  },
  {
    name: "salesforce",
    displayName: "Salesforce",
    description: "CRM accounts, contacts, leads, and opportunities",
    category: "Business Tools",
    tags: ["crm", "sales", "enterprise"],
  },
  {
    name: "zendesk",
    displayName: "Zendesk",
    description: "Support tickets and helpdesk",
    category: "Business Tools",
    tags: ["support", "helpdesk", "tickets"],
  },
  {
    name: "freshdesk",
    displayName: "Freshdesk",
    description: "Helpdesk and customer support",
    category: "Business Tools",
    tags: ["support", "helpdesk"],
  },
  {
    name: "calendly",
    displayName: "Calendly",
    description: "Scheduling and appointment booking",
    category: "Business Tools",
    tags: ["scheduling", "calendar"],
  },
  {
    name: "docusign",
    displayName: "DocuSign",
    description: "Electronic signatures and agreements",
    category: "Business Tools",
    tags: ["esign", "documents", "contracts"],
  },
  {
    name: "pipedrive",
    displayName: "Pipedrive",
    description: "Sales CRM and pipeline management",
    category: "Business Tools",
    tags: ["crm", "sales", "pipeline"],
  },
  {
    name: "coda",
    displayName: "Coda",
    description: "Docs, tables, and automations",
    category: "Business Tools",
    tags: ["docs", "tables", "automation"],
  },
  {
    name: "monday",
    displayName: "Monday.com",
    description: "Work management and project tracking",
    category: "Business Tools",
    tags: ["project-management", "workflow"],
  },
  {
    name: "dropbox",
    displayName: "Dropbox",
    description: "Cloud file storage and sharing",
    category: "Business Tools",
    tags: ["storage", "files", "sharing"],
  },
  {
    name: "box",
    displayName: "Box",
    description: "Enterprise content management",
    category: "Business Tools",
    tags: ["storage", "enterprise", "content"],
  },
  {
    name: "miro",
    displayName: "Miro",
    description: "Visual collaboration and whiteboarding",
    category: "Business Tools",
    tags: ["whiteboard", "collaboration", "design"],
  },
  {
    name: "bamboohr",
    displayName: "BambooHR",
    description: "HR management and employee data",
    category: "Business Tools",
    tags: ["hr", "employees", "management"],
  },
  {
    name: "7todos",
    displayName: "7todos",
    description: "Task management and to-do lists",
    category: "Business Tools",
    tags: ["tasks", "todo", "productivity"],
  },
  {
    name: "accelo",
    displayName: "Accelo",
    description: "Professional services automation, projects, tickets, and CRM",
    category: "Business Tools",
    tags: ["psa", "projects", "crm"],
  },
  {
    name: "accredible",
    displayName: "Accredible",
    description: "Digital credentials, certificates, and badges",
    category: "Business Tools",
    tags: ["credentials", "certificates", "badges"],
  },
  {
    name: "actionnetwork",
    displayName: "Action Network",
    description: "Progressive organizing for petitions, events, and campaigns",
    category: "Business Tools",
    tags: ["organizing", "petitions", "campaigns"],
  },
  {
    name: "affinity",
    displayName: "Affinity",
    description: "Relationship intelligence CRM",
    category: "Business Tools",
    tags: ["crm", "relationships", "deals"],
  },
  {
    name: "agilecrm",
    displayName: "Agile CRM",
    description: "CRM with contacts, deals, tasks, and marketing automation",
    category: "Business Tools",
    tags: ["crm", "sales", "marketing"],
  },
  {
    name: "amilia",
    displayName: "Amilia",
    description: "Activity registration and recreation management",
    category: "Business Tools",
    tags: ["registration", "recreation", "scheduling"],
  },
  {
    name: "announcekit",
    displayName: "AnnounceKit",
    description: "Product changelog and release notes",
    category: "Business Tools",
    tags: ["changelog", "announcements", "product"],
  },
  {
    name: "autom",
    displayName: "Autom",
    description: "Workflow automation and integration platform",
    category: "Business Tools",
    tags: ["automation", "workflows", "integration"],
  },
  {
    name: "badgermaps",
    displayName: "Badger Maps",
    description: "Field sales route planning and optimization",
    category: "Business Tools",
    tags: ["sales", "maps", "routing"],
  },
  {
    name: "beeminder",
    displayName: "Beeminder",
    description: "Goal tracking with commitment contracts",
    category: "Business Tools",
    tags: ["goals", "tracking", "productivity"],
  },
  {
    name: "betterproposals",
    displayName: "Better Proposals",
    description: "Online proposal creation and tracking",
    category: "Business Tools",
    tags: ["proposals", "sales", "documents"],
  },
  {
    name: "bitrix24",
    displayName: "Bitrix24",
    description: "CRM, project management, and collaboration suite",
    category: "Business Tools",
    tags: ["crm", "project-management", "collaboration"],
  },
  {
    name: "breezyhr",
    displayName: "Breezy HR",
    description: "Recruiting and applicant tracking system",
    category: "Business Tools",
    tags: ["hr", "recruiting", "ats"],
  },
  {
    name: "calendarhero",
    displayName: "CalendarHero",
    description: "AI-powered scheduling and meeting automation",
    category: "Business Tools",
    tags: ["scheduling", "calendar", "meetings"],
  },
  {
    name: "canvas",
    displayName: "Canvas LMS",
    description: "Learning management system for courses and assignments",
    category: "Business Tools",
    tags: ["lms", "education", "courses"],
  },
  {
    name: "capsule",
    displayName: "Capsule CRM",
    description: "Simple CRM for contacts, sales, and tasks",
    category: "Business Tools",
    tags: ["crm", "contacts", "sales"],
  },
  {
    name: "chekhub",
    displayName: "Chekhub",
    description: "Field service management and work order tracking",
    category: "Business Tools",
    tags: ["field-service", "work-orders", "maintenance"],
  },
  {
    name: "clockify",
    displayName: "Clockify",
    description: "Time tracking and timesheet management",
    category: "Business Tools",
    tags: ["time-tracking", "timesheets", "productivity"],
  },
  {
    name: "cloze",
    displayName: "Cloze",
    description: "AI-powered relationship management CRM",
    category: "Business Tools",
    tags: ["crm", "relationships", "ai"],
  },
  {
    name: "copper",
    displayName: "Copper",
    description: "CRM built for Google Workspace",
    category: "Business Tools",
    tags: ["crm", "google", "sales"],
  },
  {
    name: "corsizio",
    displayName: "Corsizio",
    description: "Online course and class registration platform",
    category: "Business Tools",
    tags: ["courses", "registration", "education"],
  },
  {
    name: "dayschedule",
    displayName: "DaySchedule",
    description: "Appointment scheduling, booking pages, and calendar management",
    category: "Business Tools",
    tags: ["scheduling", "booking", "calendar"],
  },
  {
    name: "docparser",
    displayName: "Docparser",
    description: "Document data extraction and PDF parsing automation",
    category: "Business Tools",
    tags: ["document", "parsing", "extraction", "pdf"],
  },
  {
    name: "docupilot",
    displayName: "Docupilot",
    description: "Document generation and template automation",
    category: "Business Tools",
    tags: ["documents", "templates", "automation", "generation"],
  },
  {
    name: "draftable",
    displayName: "Draftable",
    description: "Document comparison and diff detection",
    category: "Business Tools",
    tags: ["documents", "comparison", "diff"],
  },
  {
    name: "empsing",
    displayName: "Empsing",
    description: "Employee engagement and workforce management",
    category: "Business Tools",
    tags: ["hr", "employee", "engagement"],
  },
  {
    name: "envoy",
    displayName: "Envoy",
    description: "Visitor management and workplace platform",
    category: "Business Tools",
    tags: ["visitor", "workplace", "office"],
  },
  {
    name: "erpnext",
    displayName: "ERPNext",
    description: "Open-source ERP for accounting, inventory, and business management",
    category: "Business Tools",
    tags: ["erp", "accounting", "inventory", "frappe"],
  },
  {
    name: "firmao",
    displayName: "Firmao",
    description: "CRM and ERP platform for business management",
    category: "Business Tools",
    tags: ["crm", "erp", "business", "management"],
  },
  {
    name: "float",
    displayName: "Float",
    description: "Resource management and team scheduling",
    category: "Business Tools",
    tags: ["resource-management", "scheduling", "planning"],
  },
  {
    name: "flow",
    displayName: "Flow",
    description: "Workflow automation and task management",
    category: "Business Tools",
    tags: ["workflow", "automation", "tasks"],
  },
  {
    name: "fluentsupport",
    displayName: "Fluent Support",
    description: "Help desk and customer support ticket management",
    category: "Business Tools",
    tags: ["helpdesk", "support", "tickets", "customer-service"],
  },
  {
    name: "focuster",
    displayName: "Focuster",
    description: "AI-powered task scheduling and focus management",
    category: "Business Tools",
    tags: ["productivity", "tasks", "scheduling", "focus"],
  },
  {
    name: "formcarry",
    displayName: "Formcarry",
    description: "Form backend for static sites and apps",
    category: "Business Tools",
    tags: ["forms", "backend", "submissions"],
  },
  {
    name: "formdesk",
    displayName: "Formdesk",
    description: "Online form builder and data collection",
    category: "Business Tools",
    tags: ["forms", "surveys", "data-collection"],
  },
  {
    name: "formsite",
    displayName: "Formsite",
    description: "Online form builder with workflows and integrations",
    category: "Business Tools",
    tags: ["forms", "workflows", "surveys"],
  },
  {
    name: "formsonfire",
    displayName: "Forms On Fire",
    description: "Mobile forms and data collection platform",
    category: "Business Tools",
    tags: ["forms", "mobile", "data-collection"],
  },
  {
    name: "formstackdocuments",
    displayName: "Formstack Documents",
    description: "Document generation and automation",
    category: "Business Tools",
    tags: ["documents", "automation", "generation"],
  },
  {
    name: "freshservice",
    displayName: "Freshservice",
    description: "IT service management and helpdesk",
    category: "Business Tools",
    tags: ["itsm", "helpdesk", "it-management"],
  },
  {
    name: "freshworkscrm",
    displayName: "Freshworks CRM",
    description: "Sales CRM with AI-powered lead scoring",
    category: "Business Tools",
    tags: ["crm", "sales", "leads"],
  },
  {
    name: "fusioo",
    displayName: "Fusioo",
    description: "Custom business apps and database management",
    category: "Business Tools",
    tags: ["database", "custom-apps", "business"],
  },
  {
    name: "gatekeeper",
    displayName: "Gatekeeper",
    description: "Vendor and contract management platform",
    category: "Business Tools",
    tags: ["vendor-management", "contracts", "procurement"],
  },
  {
    name: "gocanvas",
    displayName: "GoCanvas",
    description: "Mobile forms and workflow automation",
    category: "Business Tools",
    tags: ["forms", "mobile", "workflow"],
  },
  {
    name: "gong",
    displayName: "Gong",
    description: "Revenue intelligence and conversation analytics",
    category: "Business Tools",
    tags: ["sales", "analytics", "conversations"],
  },
  {
    name: "grain",
    displayName: "Grain",
    description: "Meeting recording and highlights",
    category: "Business Tools",
    tags: ["meetings", "recording", "notes"],
  },
  {
    name: "gravityforms",
    displayName: "Gravity Forms",
    description: "WordPress form builder and submissions",
    category: "Business Tools",
    tags: ["forms", "wordpress", "surveys"],
  },
  {
    name: "growbots",
    displayName: "Growbots",
    description: "Outbound sales automation platform",
    category: "Business Tools",
    tags: ["sales", "outreach", "automation"],
  },
  {
    name: "guru",
    displayName: "Guru",
    description: "Knowledge management and wiki",
    category: "Business Tools",
    tags: ["knowledge", "wiki", "documentation"],
  },
  {
    name: "halopsa",
    displayName: "HaloPSA",
    description: "Professional services automation and IT management",
    category: "Business Tools",
    tags: ["psa", "it", "ticketing", "management"],
  },
  {
    name: "harvest",
    displayName: "Harvest",
    description: "Time tracking and invoicing",
    category: "Business Tools",
    tags: ["time-tracking", "invoicing", "projects"],
  },
  {
    name: "hellosign",
    displayName: "HelloSign",
    description: "Electronic signatures and document signing",
    category: "Business Tools",
    tags: ["esign", "documents", "signatures"],
  },
  {
    name: "heysummit",
    displayName: "HeySummit",
    description: "Virtual summit and event management",
    category: "Business Tools",
    tags: ["events", "summit", "conferences"],
  },
  {
    name: "highlevel",
    displayName: "HighLevel",
    description: "All-in-one CRM and marketing platform",
    category: "Business Tools",
    tags: ["crm", "marketing", "automation"],
  },
  {
    name: "hubplanner",
    displayName: "Hub Planner",
    description: "Resource scheduling and project planning",
    category: "Business Tools",
    tags: ["resource-planning", "scheduling", "projects"],
  },
  {
    name: "hunter",
    displayName: "Hunter",
    description: "Email finder and verification",
    category: "Business Tools",
    tags: ["email", "leads", "verification"],
  },
  {
    name: "iauditorbysafetyculture",
    displayName: "iAuditor by SafetyCulture",
    description: "Safety inspections and audit management",
    category: "Business Tools",
    tags: ["audits", "safety", "inspections"],
  },
  {
    name: "infolobby",
    displayName: "InfoLobby",
    description: "Cloud database and business applications platform",
    category: "Business Tools",
    tags: ["database", "business", "applications"],
  },
  {
    name: "intakeq",
    displayName: "IntakeQ",
    description: "Online intake forms and practice management for health professionals",
    category: "Business Tools",
    tags: ["healthcare", "forms", "intake", "practice-management"],
  },
  {
    name: "isn",
    displayName: "ISN",
    description: "ISNetworld contractor management and compliance",
    category: "Business Tools",
    tags: ["compliance", "contractor", "safety"],
  },
  {
    name: "kanbantool",
    displayName: "Kanban Tool",
    description: "Visual project management with Kanban boards",
    category: "Business Tools",
    tags: ["kanban", "project-management", "boards"],
  },
  {
    name: "karbon",
    displayName: "Karbon",
    description: "Practice management for accounting firms",
    category: "Business Tools",
    tags: ["accounting", "practice-management", "workflow"],
  },
  {
    name: "knack",
    displayName: "Knack",
    description: "No-code online database and web app builder",
    category: "Business Tools",
    tags: ["no-code", "database", "web-apps"],
  },
  {
    name: "launch27",
    displayName: "Launch27",
    description: "Online booking and scheduling for service businesses",
    category: "Business Tools",
    tags: ["booking", "scheduling", "services"],
  },
  {
    name: "lighthouse",
    displayName: "Lighthouse",
    description: "Property management software for landlords",
    category: "Business Tools",
    tags: ["property", "management", "landlord", "real-estate"],
  },
  {
    name: "linkish",
    displayName: "Linkish",
    description: "Bookmark management and link organization",
    category: "Business Tools",
    tags: ["bookmarks", "links", "organization"],
  },
  {
    name: "mem",
    displayName: "Mem",
    description: "AI-powered note-taking and knowledge management",
    category: "Business Tools",
    tags: ["notes", "ai", "knowledge", "productivity"],
  },
  {
    name: "microsoftdynamics365businesscentralapi",
    displayName: "Microsoft Dynamics 365 Business Central",
    description: "ERP and business management for small and mid-size organizations",
    category: "Business Tools",
    tags: ["erp", "accounting", "finance", "microsoft", "dynamics"],
  },
  {
    name: "microsoftexcel",
    displayName: "Microsoft Excel",
    description: "Spreadsheet creation, editing, and data analysis via Graph API",
    category: "Business Tools",
    tags: ["spreadsheet", "excel", "office", "microsoft"],
  },
  {
    name: "microsoftonedrive",
    displayName: "Microsoft OneDrive",
    description: "Cloud file storage and sharing via Microsoft Graph",
    category: "Business Tools",
    tags: ["storage", "files", "cloud", "microsoft", "onedrive"],
  },
  {
    name: "microsoftsharepoint",
    displayName: "Microsoft SharePoint",
    description: "Document management and team collaboration platform",
    category: "Business Tools",
    tags: ["documents", "collaboration", "intranet", "microsoft"],
  },
  {
    name: "microsofttodo",
    displayName: "Microsoft To Do",
    description: "Task management and to-do lists via Microsoft Graph",
    category: "Business Tools",
    tags: ["tasks", "todo", "productivity", "microsoft"],
  },
  {
    name: "miestro",
    displayName: "Miestro",
    description: "Online course and membership platform",
    category: "Business Tools",
    tags: ["courses", "membership", "e-learning", "platform"],
  },
  {
    name: "nextcloud",
    displayName: "Nextcloud",
    description: "Self-hosted file sync, share, and collaboration platform",
    category: "Business Tools",
    tags: ["files", "storage", "collaboration", "self-hosted", "cloud"],
  },
  {
    name: "ninox",
    displayName: "Ninox",
    description: "No-code database and business application builder",
    category: "Business Tools",
    tags: ["no-code", "database", "app-builder", "workflow"],
  },
  {
    name: "nusiiproposals",
    displayName: "Nusii Proposals",
    description: "Online proposal software for agencies and freelancers",
    category: "Business Tools",
    tags: ["proposals", "freelance", "agency", "sales", "documents"],
  },
  {
    name: "occasion",
    displayName: "Occasion",
    description: "Online booking and reservation management for experiences",
    category: "Business Tools",
    tags: ["booking", "reservations", "experiences", "scheduling", "events"],
  },
  {
    name: "odoo",
    displayName: "Odoo",
    description: "Open-source ERP and business management suite",
    category: "Business Tools",
    tags: ["erp", "crm", "accounting", "open-source", "business"],
  },
  {
    name: "on2air",
    displayName: "On2Air",
    description: "Airtable backup, forms, and automation tools",
    category: "Business Tools",
    tags: ["airtable", "backup", "automation", "forms", "database"],
  },
  {
    name: "onfleet",
    displayName: "Onfleet",
    description: "Last-mile delivery management and route optimization platform",
    category: "Business Tools",
    tags: ["delivery", "logistics", "routing", "tracking", "fleet"],
  },
  {
    name: "paperform",
    displayName: "Paperform",
    description: "Online form builder and payment collection platform",
    category: "Business Tools",
    tags: ["forms", "payments", "surveys", "builder", "no-code"],
  },
  {
    name: "papyrs",
    displayName: "Papyrs",
    description: "Intranet and internal wiki platform for teams",
    category: "Business Tools",
    tags: ["wiki", "intranet", "knowledge-base", "collaboration", "documentation"],
  },
  {
    name: "passcreator",
    displayName: "Passcreator",
    description: "Digital wallet passes creation and management platform",
    category: "Business Tools",
    tags: ["wallet", "passes", "mobile", "loyalty", "apple-wallet"],
  },
  {
    name: "passslot",
    displayName: "PassSlot",
    description: "Apple Wallet and Google Pay pass management API",
    category: "Business Tools",
    tags: ["wallet", "passes", "apple-wallet", "google-pay", "mobile"],
  },
  {
    name: "paymo",
    displayName: "Paymo",
    description: "Project management, time tracking, and invoicing platform",
    category: "Business Tools",
    tags: ["project-management", "time-tracking", "invoicing", "freelance", "billing"],
  },
  {
    name: "phrase",
    displayName: "Phrase",
    description: "Localization and translation management platform",
    category: "Business Tools",
    tags: ["localization", "translation", "i18n", "l10n", "strings"],
  },
  {
    name: "pipefy",
    displayName: "Pipefy",
    description: "No-code workflow automation and process management platform",
    category: "Business Tools",
    tags: ["workflow", "automation", "process", "no-code", "bpm"],
  },
  {
    name: "planviewleankit",
    displayName: "Planview LeanKit",
    description: "Enterprise kanban and lean portfolio management platform",
    category: "Business Tools",
    tags: ["kanban", "lean", "portfolio", "enterprise", "agile"],
  },
  {
    name: "projectbubbleproprofsproject",
    displayName: "ProProfs Project",
    description: "Project management and task tracking platform",
    category: "Business Tools",
    tags: ["project-management", "tasks", "collaboration", "tracking", "teams"],
  },
  {
    name: "quickbase",
    displayName: "Quickbase",
    description: "No-code application platform for building business apps and workflows",
    category: "Business Tools",
    tags: ["no-code", "database", "workflows", "apps", "business"],
  },
  {
    name: "realphonevalidation",
    displayName: "Real Phone Validation",
    description: "Phone number validation and carrier lookup API",
    category: "Business Tools",
    tags: ["phone-validation", "carrier-lookup", "sms", "verification", "data"],
  },
  {
    name: "retable",
    displayName: "Retable",
    description: "Online spreadsheet and database tool for team collaboration",
    category: "Business Tools",
    tags: ["spreadsheet", "database", "collaboration", "no-code", "tables"],
  },
  {
    name: "robolytix",
    displayName: "Robolytix",
    description: "RPA process monitoring and analytics platform",
    category: "Business Tools",
    tags: ["rpa", "automation", "monitoring", "analytics", "process"],
  },
  {
    name: "route4me",
    displayName: "Route4Me",
    description: "Route optimization and last-mile delivery management platform",
    category: "Business Tools",
    tags: ["routing", "logistics", "delivery", "optimization", "fleet"],
  },
  {
    name: "servicenow",
    displayName: "ServiceNow",
    description: "Enterprise IT service management and workflow automation platform",
    category: "Business Tools",
    tags: ["itsm", "workflow", "enterprise", "service-management", "automation"],
  },
  {
    name: "signaturit",
    displayName: "Signaturit",
    description: "Electronic signature and digital contract management platform",
    category: "Business Tools",
    tags: ["e-signature", "contracts", "digital", "documents", "legal"],
  },
  {
    name: "smartsuite",
    displayName: "SmartSuite",
    description: "Work management platform for projects, tasks, and workflows",
    category: "Business Tools",
    tags: ["project management", "tasks", "workflows", "collaboration", "productivity"],
  },
  {
    name: "snapdocs",
    displayName: "Snapdocs",
    description: "Digital closing platform for mortgage and real estate transactions",
    category: "Business Tools",
    tags: ["mortgage", "real estate", "closing", "documents", "fintech"],
  },
  {
    name: "spondyr",
    displayName: "Spondyr",
    description: "Automated proposal and document generation platform",
    category: "Business Tools",
    tags: ["proposals", "documents", "automation", "sales", "crm"],
  },
  {
    name: "stackby",
    displayName: "Stackby",
    description: "Spreadsheet-database hybrid with API integrations and no-code automations",
    category: "Business Tools",
    tags: ["spreadsheet", "database", "no-code", "automation", "collaboration"],
  },
  {
    name: "suitedash",
    displayName: "SuiteDash",
    description: "All-in-one business management platform with CRM, billing, and portals",
    category: "Business Tools",
    tags: ["crm", "billing", "client portal", "project management", "business"],
  },
  {
    name: "swagup",
    displayName: "SwagUp",
    description: "Corporate swag and branded merchandise management platform",
    category: "Business Tools",
    tags: ["swag", "merchandise", "branded", "gifting", "corporate"],
  },
  {
    name: "switchboard",
    displayName: "Switchboard",
    description: "Collaborative canvas platform for async team meetings and planning",
    category: "Business Tools",
    tags: ["collaboration", "canvas", "async", "meetings", "planning"],
  },
  {
    name: "syncromsp",
    displayName: "SyncroMSP",
    description: "All-in-one MSP platform with RMM, PSA, and ticketing for managed service providers",
    category: "Business Tools",
    tags: ["msp", "rmm", "psa", "ticketing", "managed services"],
  },
  {
    name: "talentlms",
    displayName: "TalentLMS",
    description: "Cloud-based learning management system for employee training and eLearning",
    category: "Business Tools",
    tags: ["lms", "elearning", "training", "courses", "hr"],
  },
  {
    name: "teachable",
    displayName: "Teachable",
    description: "Online course and coaching platform for creators to sell knowledge products",
    category: "Business Tools",
    tags: ["courses", "elearning", "coaching", "creators", "membership"],
  },
  {
    name: "teamdeck",
    displayName: "Teamdeck",
    description: "Resource management and time tracking tool for agencies and software teams",
    category: "Business Tools",
    tags: ["resource management", "time tracking", "scheduling", "agencies", "teams"],
  },
  {
    name: "teamup",
    displayName: "Teamup",
    description: "Shared calendar and scheduling platform for teams and organizations",
    category: "Business Tools",
    tags: ["calendar", "scheduling", "shared", "teams", "planning"],
  },
  {
    name: "thecustomerfactor",
    displayName: "The Customer Factor",
    description: "CRM and scheduling software for service businesses and field service management",
    category: "Business Tools",
    tags: ["crm", "scheduling", "field service", "small business", "invoicing"],
  },
  {
    name: "timetonic",
    displayName: "TimeTonic",
    description: "Visual database and project management platform with table and kanban views",
    category: "Business Tools",
    tags: ["database", "project management", "kanban", "no-code", "collaboration"],
  },
  {
    name: "trackvia",
    displayName: "TrackVia",
    description: "Low-code workflow and database platform for building operational apps",
    category: "Business Tools",
    tags: ["low-code", "workflow", "database", "operations", "apps"],
  },
  {
    name: "trevorio",
    displayName: "Trevorio",
    description: "Project management and team collaboration platform",
    category: "Business Tools",
    tags: ["project-management", "tasks", "collaboration"],
  },
  {
    name: "turbohire",
    displayName: "TurboHire",
    description: "AI-powered recruitment and applicant tracking system",
    category: "Business Tools",
    tags: ["hr", "recruiting", "ats", "ai"],
  },
  {
    name: "unleashedsoftware",
    displayName: "Unleashed Software",
    description: "Inventory management and manufacturing software",
    category: "Business Tools",
    tags: ["inventory", "manufacturing", "erp"],
  },
  {
    name: "upkeep",
    displayName: "UpKeep",
    description: "Asset and maintenance management (CMMS)",
    category: "Business Tools",
    tags: ["maintenance", "assets", "cmms"],
  },
  {
    name: "uservoice",
    displayName: "UserVoice",
    description: "Product feedback and customer insight platform",
    category: "Business Tools",
    tags: ["feedback", "product", "customer-insights"],
  },
  {
    name: "vivifyscrum",
    displayName: "VivifyScrum",
    description: "Agile project management with Scrum and Kanban boards",
    category: "Business Tools",
    tags: ["agile", "scrum", "kanban"],
  },
  {
    name: "wekan",
    displayName: "Wekan",
    description: "Open-source Kanban board for task management",
    category: "Business Tools",
    tags: ["kanban", "open-source", "tasks"],
  },
  {
    name: "workast",
    displayName: "Workast",
    description: "Task management integrated with Slack",
    category: "Business Tools",
    tags: ["tasks", "slack", "productivity"],
  },
  {
    name: "workboard",
    displayName: "Workboard",
    description: "OKR and strategy execution platform",
    category: "Business Tools",
    tags: ["okr", "strategy", "goals"],
  },
  {
    name: "yodiz",
    displayName: "Yodiz",
    description: "Agile project management and issue tracking",
    category: "Business Tools",
    tags: ["agile", "issues", "project-management"],
  },
  {
    name: "zammad",
    displayName: "Zammad",
    description: "Open-source helpdesk and customer support ticketing",
    category: "Business Tools",
    tags: ["helpdesk", "tickets", "support", "open-source"],
  },
  {
    name: "zoho",
    displayName: "Zoho CRM",
    description: "CRM contacts, leads, accounts, and deals (v8 API)",
    category: "Business Tools",
    tags: ["crm", "sales", "zoho"],
  },
  {
    name: "zoho-bigin",
    displayName: "Zoho Bigin",
    description: "Lightweight CRM and pipeline management for small teams",
    category: "Business Tools",
    tags: ["crm", "pipeline", "sales", "zoho"],
  },
  {
    name: "zoho-sign",
    displayName: "Zoho Sign",
    description: "Electronic signature and document signing platform",
    category: "Business Tools",
    tags: ["esign", "documents", "zoho"],
  },
  {
    name: "zohocrm",
    displayName: "Zoho CRM",
    description: "CRM for sales, marketing, and customer support",
    category: "Business Tools",
    tags: ["crm", "sales", "zoho"],
  },
  {
    name: "zohoforms",
    displayName: "Zoho Forms",
    description: "Online form builder, surveys, and approval workflows",
    category: "Business Tools",
    tags: ["forms", "surveys", "zoho"],
  },
  {
    name: "zohodesk",
    displayName: "Zoho Desk",
    description: "Customer support and helpdesk platform",
    category: "Business Tools",
    tags: ["helpdesk", "support", "zoho"],
  },
  {
    name: "zohobookings",
    displayName: "Zoho Bookings",
    description: "Online appointment scheduling and booking management",
    category: "Business Tools",
    tags: ["scheduling", "appointments", "zoho"],
  },
  {
    name: "zoho-survey",
    displayName: "Zoho Survey",
    description: "Online survey and feedback collection platform",
    category: "Business Tools",
    tags: ["surveys", "feedback", "zoho"],
  },
  {
    name: "zoho-creator",
    displayName: "Zoho Creator",
    description: "Low-code business apps and databases",
    category: "Business Tools",
    tags: ["low-code", "apps", "zoho"],
  },
  {
    name: "zohoworkdrive",
    displayName: "Zoho WorkDrive",
    description: "Team file storage and collaboration",
    category: "Business Tools",
    tags: ["storage", "files", "zoho"],
  },
  {
    name: "zonkafeedback",
    displayName: "Zonka Feedback",
    description: "Customer feedback and survey platform",
    category: "Business Tools",
    tags: ["feedback", "surveys", "cx"],
  },
];
