import type { ConnectorMeta } from "../registry.js";

// Communication
export const connectors: ConnectorMeta[] = [
  {
    name: "gmail",
    displayName: "Gmail",
    description: "Email sending and management",
    category: "Communication",
    tags: ["email", "google"],
  },
  {
    name: "discord",
    displayName: "Discord",
    description: "Messaging and communities",
    category: "Communication",
    tags: ["chat", "community"],
  },
  {
    name: "twilio",
    displayName: "Twilio",
    description: "SMS, voice, and messaging",
    category: "Communication",
    tags: ["sms", "voice"],
  },
  {
    name: "telnyx",
    displayName: "Telnyx",
    description: "Messaging, phone numbers, and carrier lookup APIs",
    category: "Communication",
    tags: ["sms", "voice", "messaging"],
  },
  {
    name: "resend",
    displayName: "Resend",
    description: "Email API for developers",
    category: "Communication",
    tags: ["email", "api"],
  },
  {
    name: "zoom",
    displayName: "Zoom",
    description: "Video meetings and webinars",
    category: "Communication",
    tags: ["video", "meetings"],
  },
  {
    name: "zoho-meeting",
    displayName: "Zoho Meeting",
    description: "Video meetings, webinars, recordings, and reports",
    category: "Communication",
    tags: ["video", "meetings", "webinar", "zoho"],
  },
  {
    name: "maropost",
    displayName: "Maropost",
    description: "Email marketing automation",
    category: "Communication",
    tags: ["email", "marketing"],
  },
  {
    name: "slack",
    displayName: "Slack",
    description: "Channels, messages, and workspace management",
    category: "Communication",
    tags: ["chat", "messaging", "workspace"],
  },
  {
    name: "telegram",
    displayName: "Telegram",
    description: "Bot API for messages, chats, and updates",
    category: "Communication",
    tags: ["chat", "bot", "messaging"],
  },
  {
    name: "imessage",
    displayName: "iMessage",
    description: "Bridge-based access to Apple Messages conversations and send/reply flows",
    category: "Communication",
    tags: ["messaging", "apple", "bridge", "sms"],
  },
  {
    name: "whatsapp",
    displayName: "WhatsApp",
    description: "Business Cloud API for messages and templates",
    category: "Communication",
    tags: ["messaging", "business"],
  },
  {
    name: "intercom",
    displayName: "Intercom",
    description: "Contacts, conversations, and customer engagement",
    category: "Communication",
    tags: ["support", "messaging", "crm"],
  },
  {
    name: "crisp",
    displayName: "Crisp",
    description: "Customer messaging and live chat",
    category: "Communication",
    tags: ["chat", "support", "messaging"],
  },
  {
    name: "drift",
    displayName: "Drift",
    description: "Conversational marketing and sales",
    category: "Communication",
    tags: ["chat", "marketing", "sales"],
  },
  {
    name: "mailchimp",
    displayName: "Mailchimp",
    description: "Email marketing and automation",
    category: "Communication",
    tags: ["email", "marketing", "automation"],
  },
  {
    name: "convertkit",
    displayName: "ConvertKit",
    description: "Email marketing for creators",
    category: "Communication",
    tags: ["email", "marketing", "creators"],
  },
  {
    name: "sendgrid",
    displayName: "SendGrid",
    description: "Email delivery and marketing",
    category: "Communication",
    tags: ["email", "api", "transactional"],
  },
  {
    name: "sparkpost",
    displayName: "SparkPost",
    description: "Transactional email delivery and analytics",
    category: "Communication",
    tags: ["email", "api", "transactional"],
  },
  {
    name: "mailgun",
    displayName: "Mailgun",
    description: "Email delivery API",
    category: "Communication",
    tags: ["email", "api", "transactional"],
  },
  {
    name: "pusher",
    displayName: "Pusher",
    description: "Realtime messaging and channels",
    category: "Communication",
    tags: ["realtime", "websockets", "messaging"],
  },
  {
    name: "ably",
    displayName: "Ably",
    description: "Realtime messaging infrastructure",
    category: "Communication",
    tags: ["realtime", "messaging", "pubsub"],
  },
  {
    name: "vonage",
    displayName: "Vonage",
    description: "SMS, voice, and messaging APIs",
    category: "Communication",
    tags: ["sms", "voice", "messaging"],
  },
  {
    name: "messagebird",
    displayName: "MessageBird",
    description: "Omnichannel messaging platform",
    category: "Communication",
    tags: ["sms", "messaging", "omnichannel"],
  },
  {
    name: "activecampaign",
    displayName: "ActiveCampaign",
    description: "Marketing automation and CRM",
    category: "Communication",
    tags: ["email", "marketing", "automation"],
  },
  {
    name: "brevo",
    displayName: "Brevo",
    description: "Email marketing and transactional emails",
    category: "Communication",
    tags: ["email", "marketing", "transactional"],
  },
  {
    name: "klaviyo",
    displayName: "Klaviyo",
    description: "E-commerce email and SMS marketing",
    category: "Communication",
    tags: ["email", "sms", "ecommerce"],
  },
  {
    name: "customerio",
    displayName: "Customer.io",
    description: "Messaging automation platform",
    category: "Communication",
    tags: ["messaging", "automation", "engagement"],
  },
  {
    name: "acquire",
    displayName: "Acquire",
    description: "Customer support with live chat, video, and co-browsing",
    category: "Communication",
    tags: ["chat", "support", "video"],
  },
  {
    name: "activetrail",
    displayName: "ActiveTrail",
    description: "Email marketing and automation",
    category: "Communication",
    tags: ["email", "marketing", "automation"],
  },
  {
    name: "automizy",
    displayName: "Automizy",
    description: "Email marketing automation",
    category: "Communication",
    tags: ["email", "marketing", "automation"],
  },
  {
    name: "autopilot",
    displayName: "Autopilot",
    description: "Marketing automation and customer journey mapping",
    category: "Communication",
    tags: ["marketing", "automation", "journeys"],
  },
  {
    name: "bandwidth",
    displayName: "Bandwidth",
    description: "Voice, messaging, and emergency services APIs",
    category: "Communication",
    tags: ["voice", "sms", "messaging"],
  },
  {
    name: "benchmarkemail",
    displayName: "Benchmark Email",
    description: "Email marketing campaigns and automation",
    category: "Communication",
    tags: ["email", "marketing", "campaigns"],
  },
  {
    name: "blaze",
    displayName: "Blaze",
    description: "Community engagement and membership platform",
    category: "Communication",
    tags: ["community", "engagement", "membership"],
  },
  {
    name: "botbaba",
    displayName: "BotBaba",
    description: "No-code chatbot builder for websites",
    category: "Communication",
    tags: ["chatbot", "no-code", "messaging"],
  },
  {
    name: "botifier",
    displayName: "Botifier",
    description: "Notification bots and alert automation",
    category: "Communication",
    tags: ["bots", "notifications", "alerts"],
  },
  {
    name: "botstar",
    displayName: "BotStar",
    description: "Visual chatbot builder and automation",
    category: "Communication",
    tags: ["chatbot", "automation", "visual"],
  },
  {
    name: "chatrace",
    displayName: "Chatrace",
    description: "Chatbot marketing and lead generation",
    category: "Communication",
    tags: ["chatbot", "marketing", "leads"],
  },
  {
    name: "ciscowebex",
    displayName: "Cisco Webex",
    description: "Video conferencing, messaging, and collaboration",
    category: "Communication",
    tags: ["video", "meetings", "cisco"],
  },
  {
    name: "cleverreach",
    displayName: "CleverReach",
    description: "Email marketing and newsletter automation",
    category: "Communication",
    tags: ["email", "marketing", "newsletters"],
  },
  {
    name: "clicksendsms",
    displayName: "ClickSend SMS",
    description: "SMS, MMS, and communication APIs",
    category: "Communication",
    tags: ["sms", "mms", "messaging"],
  },
  {
    name: "crowdpower",
    displayName: "CrowdPower",
    description: "Customer engagement and lifecycle automation",
    category: "Communication",
    tags: ["engagement", "automation", "lifecycle"],
  },
  {
    name: "demio",
    displayName: "Demio",
    description: "Webinar platform for events, registrations, and attendee management",
    category: "Communication",
    tags: ["webinar", "events", "video"],
  },
  {
    name: "dialzara",
    displayName: "Dialzara",
    description: "AI-powered virtual receptionist and phone answering service",
    category: "Communication",
    tags: ["ai", "phone", "receptionist", "voice"],
  },
  {
    name: "discourse",
    displayName: "Discourse",
    description: "Community forum platform and discussion management",
    category: "Communication",
    tags: ["forum", "community", "discussion"],
  },
  {
    name: "echowin",
    displayName: "Echowin",
    description: "AI-powered phone answering and call management",
    category: "Communication",
    tags: ["ai", "phone", "call-management", "voice"],
  },
  {
    name: "egoi",
    displayName: "E-goi",
    description: "Multichannel marketing automation for email, SMS, and push notifications",
    category: "Communication",
    tags: ["marketing", "email", "sms", "automation"],
  },
  {
    name: "emelia",
    displayName: "Emelia",
    description: "Email outreach and cold email automation",
    category: "Communication",
    tags: ["email", "outreach", "automation"],
  },
  {
    name: "enormail",
    displayName: "Enormail",
    description: "Email marketing campaigns and subscriber management",
    category: "Communication",
    tags: ["email", "marketing", "campaigns"],
  },
  {
    name: "esendex",
    displayName: "Esendex",
    description: "Business SMS messaging and communication APIs",
    category: "Communication",
    tags: ["sms", "messaging", "business"],
  },
  {
    name: "getresponse",
    displayName: "GetResponse",
    description: "Email marketing and automation platform",
    category: "Communication",
    tags: ["email", "marketing", "automation"],
  },
  {
    name: "gotify",
    displayName: "Gotify",
    description: "Self-hosted push notification server",
    category: "Communication",
    tags: ["notifications", "push", "self-hosted"],
  },
  {
    name: "gotowebinar",
    displayName: "GoTo Webinar",
    description: "Webinar hosting and management",
    category: "Communication",
    tags: ["webinar", "video", "events"],
  },
  {
    name: "gupshup",
    displayName: "Gupshup",
    description: "Conversational messaging platform",
    category: "Communication",
    tags: ["messaging", "chatbot", "whatsapp"],
  },
  {
    name: "handwrytten",
    displayName: "Handwrytten",
    description: "Handwritten notes and cards via robot",
    category: "Communication",
    tags: ["handwritten", "cards", "mail"],
  },
  {
    name: "helpscout",
    displayName: "Help Scout",
    description: "Help desk and customer support",
    category: "Communication",
    tags: ["helpdesk", "support", "tickets"],
  },
  {
    name: "line",
    displayName: "LINE",
    description: "LINE messaging platform and bot API",
    category: "Communication",
    tags: ["messaging", "chat", "bot", "japan"],
  },
  {
    name: "liveagent",
    displayName: "LiveAgent",
    description: "Help desk and live chat customer support",
    category: "Communication",
    tags: ["helpdesk", "live-chat", "support", "ticketing"],
  },
  {
    name: "mailersend",
    displayName: "MailerSend",
    description: "Transactional email and SMS delivery service",
    category: "Communication",
    tags: ["email", "transactional", "sms", "delivery"],
  },
  {
    name: "mailjet",
    displayName: "Mailjet",
    description: "Email delivery and marketing API",
    category: "Communication",
    tags: ["email", "delivery", "marketing", "api"],
  },
  {
    name: "smtp2go",
    displayName: "SMTP2GO",
    description: "Email delivery API and SMTP relay",
    category: "Communication",
    tags: ["email", "smtp", "api"],
  },
  {
    name: "mandrill",
    displayName: "Mandrill",
    description: "Transactional email API by Mailchimp",
    category: "Communication",
    tags: ["email", "transactional", "mailchimp"],
  },
  {
    name: "matrix",
    displayName: "Matrix",
    description: "Open network for decentralized communication",
    category: "Communication",
    tags: ["messaging", "decentralized", "open-source", "federation"],
  },
  {
    name: "mattermost",
    displayName: "Mattermost",
    description: "Open-source team messaging and collaboration",
    category: "Communication",
    tags: ["messaging", "team-chat", "open-source", "collaboration"],
  },
  {
    name: "microsoftoutlook",
    displayName: "Microsoft Outlook",
    description: "Email, calendar, and contacts via Microsoft Graph",
    category: "Communication",
    tags: ["email", "calendar", "contacts", "microsoft", "outlook"],
  },
  {
    name: "microsoftteams",
    displayName: "Microsoft Teams",
    description: "Team messaging, channels, and collaboration",
    category: "Communication",
    tags: ["chat", "teams", "collaboration", "microsoft"],
  },
  {
    name: "microsoftteamsadmin",
    displayName: "Microsoft Teams Admin",
    description: "Teams administration, policies, and tenant management",
    category: "Communication",
    tags: ["admin", "teams", "management", "microsoft"],
  },
  {
    name: "missive",
    displayName: "Missive",
    description: "Team inbox and collaborative email platform",
    category: "Communication",
    tags: ["email", "inbox", "collaboration", "team"],
  },
  {
    name: "mocean",
    displayName: "Mocean",
    description: "SMS, voice, and messaging API platform",
    category: "Communication",
    tags: ["sms", "voice", "messaging", "api"],
  },
  {
    name: "msg91",
    displayName: "MSG91",
    description: "SMS, email, and communication APIs for businesses",
    category: "Communication",
    tags: ["sms", "email", "otp", "communication"],
  },
  {
    name: "plivo",
    displayName: "Plivo",
    description: "Cloud communications platform for voice and SMS",
    category: "Communication",
    tags: ["sms", "voice", "telephony", "cloud", "messaging"],
  },
  {
    name: "rocketchat",
    displayName: "Rocket.Chat",
    description: "Open-source team messaging and collaboration platform",
    category: "Communication",
    tags: ["chat", "messaging", "team", "collaboration", "open-source"],
  },
  {
    name: "signl4",
    displayName: "SIGNL4",
    description: "Mobile alerting and incident management for field teams",
    category: "Communication",
    tags: ["alerting", "incidents", "mobile", "notifications", "on-call"],
  },
  {
    name: "textmagic",
    displayName: "Textmagic",
    description: "Business SMS platform for sending bulk text messages and two-way communication",
    category: "Communication",
    tags: ["sms", "text messaging", "bulk sms", "two-way messaging", "notifications"],
  },
  {
    name: "timelinesai",
    displayName: "TimelinesAI",
    description: "WhatsApp team inbox API for chats, messages, and connected accounts",
    category: "Communication",
    tags: ["whatsapp", "messaging", "api"],
  },
  {
    name: "trengo",
    displayName: "Trengo",
    description: "Multi-channel customer communication platform for managing conversations at scale",
    category: "Communication",
    tags: ["customer communication", "multi-channel", "inbox", "support", "messaging"],
  },
  {
    name: "tuulio",
    displayName: "Tuulio",
    description: "AI chatbot and customer engagement platform",
    category: "Communication",
    tags: ["chatbot", "ai", "engagement"],
  },
  {
    name: "twake",
    displayName: "Twake",
    description: "Open-source collaborative workspace with chat and file sharing",
    category: "Communication",
    tags: ["collaboration", "chat", "open-source"],
  },
  {
    name: "twist",
    displayName: "Twist",
    description: "Async team communication with threads and channels",
    category: "Communication",
    tags: ["async", "messaging", "threads"],
  },
  {
    name: "unisender",
    displayName: "UniSender",
    description: "Email and SMS marketing platform",
    category: "Communication",
    tags: ["email", "sms", "marketing"],
  },
  {
    name: "userlist",
    displayName: "Userlist",
    description: "Behavioral email marketing and lifecycle messaging platform",
    category: "Communication",
    tags: ["email", "marketing", "automation", "lifecycle"],
  },
  {
    name: "vero",
    displayName: "Vero",
    description: "Behavioral email marketing and automation",
    category: "Communication",
    tags: ["email", "marketing", "automation"],
  },
  {
    name: "vowel",
    displayName: "Vowel",
    description: "Video meetings with built-in transcription and summaries",
    category: "Communication",
    tags: ["meetings", "video", "transcription"],
  },
  {
    name: "webex",
    displayName: "Webex",
    description: "Video conferencing, messaging, and collaboration",
    category: "Communication",
    tags: ["video", "meetings", "cisco"],
  },
  {
    name: "webexbycisco",
    displayName: "Webex by Cisco",
    description: "Video conferencing, messaging, and team collaboration",
    category: "Communication",
    tags: ["video", "conferencing", "collaboration"],
  },
  {
    name: "webinarjam",
    displayName: "WebinarJam",
    description: "Live webinar hosting and streaming platform",
    category: "Communication",
    tags: ["webinar", "streaming", "events"],
  },
  {
    name: "wizychat",
    displayName: "WizyChat",
    description: "AI chatbot builder for customer support",
    category: "Communication",
    tags: ["chatbot", "ai", "support"],
  },
  {
    name: "zoho-cliq",
    displayName: "Zoho Cliq",
    description: "Team chat, channels, and messaging for business collaboration",
    category: "Communication",
    tags: ["zoho", "chat", "messaging"],
  },
  {
    name: "zulip",
    displayName: "Zulip",
    description: "Open-source team chat with threaded conversations",
    category: "Communication",
    tags: ["chat", "messaging", "open-source", "threads"],
  },
];
