import type { ConnectorMeta } from "../registry.js";

// Commerce & Finance
export const connectors: ConnectorMeta[] = [
  {
    name: "stripe",
    displayName: "Stripe",
    description: "Payments, subscriptions, and billing",
    category: "Commerce & Finance",
    tags: ["payments", "billing"],
  },
  {
    name: "stripeatlas",
    displayName: "Stripe Atlas",
    description: "Company incorporation",
    category: "Commerce & Finance",
    tags: ["incorporation", "business"],
  },
  {
    name: "shopify",
    displayName: "Shopify",
    description: "E-commerce platform",
    category: "Commerce & Finance",
    tags: ["ecommerce", "store"],
  },
  {
    name: "revolut",
    displayName: "Revolut",
    description: "Banking and payments",
    category: "Commerce & Finance",
    tags: ["banking", "fintech"],
  },
  {
    name: "mercury",
    displayName: "Mercury",
    description: "Startup banking",
    category: "Commerce & Finance",
    tags: ["banking", "startup"],
  },
  {
    name: "pandadoc",
    displayName: "PandaDoc",
    description: "Document signing and proposals",
    category: "Commerce & Finance",
    tags: ["documents", "esign"],
  },
  {
    name: "paypal",
    displayName: "PayPal",
    description: "Payments and checkout",
    category: "Commerce & Finance",
    tags: ["payments", "checkout"],
  },
  {
    name: "lemonsqueezy",
    displayName: "Lemon Squeezy",
    description: "Payments for digital products",
    category: "Commerce & Finance",
    tags: ["payments", "digital", "saas"],
  },
  {
    name: "gumroad",
    displayName: "Gumroad",
    description: "Sell digital products and memberships",
    category: "Commerce & Finance",
    tags: ["ecommerce", "digital", "creators"],
  },
  {
    name: "square",
    displayName: "Square",
    description: "Payments, POS, and commerce",
    category: "Commerce & Finance",
    tags: ["payments", "pos", "commerce"],
  },
  {
    name: "paddle",
    displayName: "Paddle",
    description: "SaaS billing and payments",
    category: "Commerce & Finance",
    tags: ["payments", "billing", "saas"],
  },
  {
    name: "chargebee",
    displayName: "Chargebee",
    description: "Subscription billing and revenue management",
    category: "Commerce & Finance",
    tags: ["billing", "subscriptions"],
  },
  {
    name: "plaid",
    displayName: "Plaid",
    description: "Banking and financial data",
    category: "Commerce & Finance",
    tags: ["banking", "fintech", "data"],
  },
  {
    name: "wise",
    displayName: "Wise",
    description: "International money transfers",
    category: "Commerce & Finance",
    tags: ["payments", "transfers", "forex"],
  },
  {
    name: "amazon",
    displayName: "Amazon",
    description: "Amazon product and marketplace APIs",
    category: "Commerce & Finance",
    tags: ["ecommerce", "marketplace", "products"],
  },
  {
    name: "bigcartel",
    displayName: "Big Cartel",
    description: "E-commerce platform for artists and makers",
    category: "Commerce & Finance",
    tags: ["ecommerce", "store", "artists"],
  },
  {
    name: "blockchainexchange",
    displayName: "Blockchain Exchange",
    description: "Cryptocurrency trading and exchange",
    category: "Commerce & Finance",
    tags: ["crypto", "exchange", "trading"],
  },
  {
    name: "brex",
    displayName: "Brex",
    description: "Business credit cards and spend management",
    category: "Commerce & Finance",
    tags: ["finance", "cards", "expense"],
  },
  {
    name: "chargeover",
    displayName: "ChargeOver",
    description: "Recurring billing and invoicing automation",
    category: "Commerce & Finance",
    tags: ["billing", "invoicing", "subscriptions"],
  },
  {
    name: "chargify",
    displayName: "Chargify",
    description: "Subscription billing and revenue management",
    category: "Commerce & Finance",
    tags: ["billing", "subscriptions", "saas"],
  },
  {
    name: "clickbank",
    displayName: "ClickBank",
    description: "Affiliate marketplace and digital product sales",
    category: "Commerce & Finance",
    tags: ["affiliate", "marketplace", "digital"],
  },
  {
    name: "coinbase",
    displayName: "Coinbase",
    description: "Cryptocurrency accounts, prices, and transactions",
    category: "Commerce & Finance",
    tags: ["crypto", "exchange", "payments"],
  },
  {
    name: "daffy",
    displayName: "Daffy",
    description: "Donor-advised fund and charitable giving platform",
    category: "Commerce & Finance",
    tags: ["donations", "charity", "giving"],
  },
  {
    name: "detrack",
    displayName: "Detrack",
    description: "Delivery tracking, proof of delivery, and fleet management",
    category: "Commerce & Finance",
    tags: ["delivery", "tracking", "logistics", "fleet"],
  },
  {
    name: "dhl",
    displayName: "DHL",
    description: "Shipment tracking, rate calculation, and logistics services",
    category: "Commerce & Finance",
    tags: ["shipping", "tracking", "logistics"],
  },
  {
    name: "dokan",
    displayName: "Dokan",
    description: "Multi-vendor marketplace platform and store management",
    category: "Commerce & Finance",
    tags: ["marketplace", "ecommerce", "multi-vendor"],
  },
  {
    name: "easyship",
    displayName: "Easyship",
    description: "Shipping automation, rate comparison, and fulfillment",
    category: "Commerce & Finance",
    tags: ["shipping", "fulfillment", "logistics", "rates"],
  },
  {
    name: "ecwid",
    displayName: "Ecwid",
    description: "E-commerce platform for online store management",
    category: "Commerce & Finance",
    tags: ["ecommerce", "store", "shopping"],
  },
  {
    name: "helcim",
    displayName: "Helcim",
    description: "Payment processing and merchant services",
    category: "Commerce & Finance",
    tags: ["payments", "merchant", "pos"],
  },
  {
    name: "invoiced",
    displayName: "Invoiced",
    description: "Accounts receivable automation and invoicing",
    category: "Commerce & Finance",
    tags: ["invoicing", "billing", "accounts-receivable"],
  },
  {
    name: "invoiceninja",
    displayName: "Invoice Ninja",
    description: "Open-source invoicing, payments, and accounting",
    category: "Commerce & Finance",
    tags: ["invoicing", "payments", "accounting", "open-source"],
  },
  {
    name: "keyzy",
    displayName: "Keyzy",
    description: "Rent-to-own property platform",
    category: "Commerce & Finance",
    tags: ["property", "rent-to-own", "real-estate"],
  },
  {
    name: "magento2",
    displayName: "Magento 2",
    description: "Adobe Commerce e-commerce platform API",
    category: "Commerce & Finance",
    tags: ["ecommerce", "adobe", "store", "catalog"],
  },
  {
    name: "marketplacer",
    displayName: "Marketplacer",
    description: "Online marketplace platform and management",
    category: "Commerce & Finance",
    tags: ["marketplace", "ecommerce", "platform"],
  },
  {
    name: "moonclerk",
    displayName: "MoonClerk",
    description: "Recurring and one-time online payment platform",
    category: "Commerce & Finance",
    tags: ["payments", "recurring", "billing", "stripe"],
  },
  {
    name: "offalerts",
    displayName: "Off Alerts",
    description: "Price drop and deal alerts for online shopping",
    category: "Commerce & Finance",
    tags: ["alerts", "deals", "price-tracking", "shopping", "ecommerce"],
  },
  {
    name: "opnformerlyomise",
    displayName: "Opn (formerly Omise)",
    description: "Payment gateway and financial services for Southeast Asia",
    category: "Commerce & Finance",
    tags: ["payments", "gateway", "fintech", "southeast-asia", "ecommerce"],
  },
  {
    name: "orderdesk",
    displayName: "Order Desk",
    description: "Order management and fulfillment automation for ecommerce",
    category: "Commerce & Finance",
    tags: ["orders", "fulfillment", "ecommerce", "automation", "inventory"],
  },
  {
    name: "patreon",
    displayName: "Patreon",
    description: "Creator membership and subscription platform API",
    category: "Commerce & Finance",
    tags: ["creator", "membership", "subscriptions", "monetization", "community"],
  },
  {
    name: "pitchly",
    displayName: "Pitchly",
    description: "Deal tombstone and document automation platform for finance",
    category: "Commerce & Finance",
    tags: ["finance", "tombstone", "documents", "automation", "dealmaking"],
  },
  {
    name: "profitwell",
    displayName: "ProfitWell",
    description: "Subscription financial metrics and revenue reporting API",
    category: "Commerce & Finance",
    tags: ["subscription", "metrics", "revenue", "saas", "finance"],
  },
  {
    name: "quickbooksonline",
    displayName: "QuickBooks Online",
    description: "Cloud accounting software for invoicing, expenses, and bookkeeping",
    category: "Commerce & Finance",
    tags: ["accounting", "invoicing", "finance", "bookkeeping", "expenses"],
  },
  {
    name: "recharge",
    displayName: "Recharge",
    description: "Subscription billing and recurring payments platform for e-commerce",
    category: "Commerce & Finance",
    tags: ["subscriptions", "billing", "recurring-payments", "ecommerce", "shopify"],
  },
  {
    name: "relysia",
    displayName: "Relysia",
    description: "Bitcoin SV blockchain wallet and payment API",
    category: "Commerce & Finance",
    tags: ["blockchain", "bitcoin-sv", "payments", "wallet", "crypto"],
  },
  {
    name: "sellix",
    displayName: "Sellix",
    description: "Digital products and subscription e-commerce platform",
    category: "Commerce & Finance",
    tags: ["ecommerce", "digital-products", "subscriptions", "payments", "storefront"],
  },
  {
    name: "shiphero",
    displayName: "ShipHero",
    description: "Warehouse management and order fulfillment platform",
    category: "Commerce & Finance",
    tags: ["warehouse", "fulfillment", "shipping", "inventory", "ecommerce"],
  },
  {
    name: "shipstation",
    displayName: "ShipStation",
    description: "Multi-carrier shipping and order management platform",
    category: "Commerce & Finance",
    tags: ["shipping", "carriers", "orders", "fulfillment", "ecommerce"],
  },
  {
    name: "simplehash",
    displayName: "SimpleHash",
    description: "NFT and blockchain data API for multi-chain digital assets",
    category: "Commerce & Finance",
    tags: ["nft", "blockchain", "crypto", "web3", "digital-assets"],
  },
  {
    name: "snipcart",
    displayName: "Snipcart",
    description: "Developer-first shopping cart and e-commerce API",
    category: "Commerce & Finance",
    tags: ["ecommerce", "shopping cart", "payments", "developer", "api"],
  },
  {
    name: "spydra",
    displayName: "Spydra",
    description: "Blockchain-as-a-service platform for enterprise tokenization",
    category: "Commerce & Finance",
    tags: ["blockchain", "tokenization", "enterprise", "web3", "assets"],
  },
  {
    name: "tdameritrade",
    displayName: "TD Ameritrade",
    description: "Brokerage and trading platform API for market data, orders, and account management",
    category: "Commerce & Finance",
    tags: ["trading", "brokerage", "stocks", "finance", "market data"],
  },
  {
    name: "theleap",
    displayName: "The Leap",
    description: "Digital product creation and selling platform for creators and influencers",
    category: "Commerce & Finance",
    tags: ["digital products", "creators", "ecommerce", "monetization", "influencers"],
  },
  {
    name: "thrivecart",
    displayName: "ThriveCart",
    description: "High-converting shopping cart and affiliate management platform for digital products",
    category: "Commerce & Finance",
    tags: ["shopping cart", "ecommerce", "affiliate", "digital products", "checkout"],
  },
  {
    name: "tokenmetrics",
    displayName: "Token Metrics",
    description: "AI-powered crypto analytics and investment research platform",
    category: "Commerce & Finance",
    tags: ["crypto", "analytics", "ai", "investment", "blockchain"],
  },
  {
    name: "toket",
    displayName: "Toket",
    description: "NFT and digital collectible platform for creating and managing token-based experiences",
    category: "Commerce & Finance",
    tags: ["nft", "blockchain", "digital collectibles", "tokens", "web3"],
  },
  {
    name: "truelayer",
    displayName: "TrueLayer",
    description: "Open banking platform",
    category: "Commerce & Finance",
    tags: ["banking", "fintech", "open-banking", "payments"],
  },
  {
    name: "whal3s",
    displayName: "Whal3s",
    description: "NFT utility and Web3 engagement platform",
    category: "Commerce & Finance",
    tags: ["nft", "web3", "blockchain"],
  },
  {
    name: "wave-accounting",
    displayName: "Wave Accounting",
    description: "Accounting, invoicing, and financial management via GraphQL API",
    category: "Commerce & Finance",
    tags: ["accounting", "invoicing", "finance", "graphql"],
  },
  {
    name: "woocommerce",
    displayName: "WooCommerce",
    description: "WordPress e-commerce plugin for orders, products, and customers",
    category: "Commerce & Finance",
    tags: ["ecommerce", "wordpress", "orders"],
  },
  {
    name: "zerosettle",
    displayName: "ZeroSettle",
    description: "Direct IAP billing",
    category: "Commerce & Finance",
    tags: ["payments", "iap", "billing"],
  },
  {
    name: "xero",
    displayName: "Xero",
    description: "Accounting, invoicing, and financial management",
    category: "Commerce & Finance",
    tags: ["accounting", "invoicing", "finance"],
  },
  {
    name: "zohobooks",
    displayName: "Zoho Books",
    description: "Online accounting and financial management",
    category: "Commerce & Finance",
    tags: ["accounting", "invoicing", "zoho"],
  },
  {
    name: "zoho-inventory",
    displayName: "Zoho Inventory",
    description: "Inventory management for items, orders, and invoices",
    category: "Commerce & Finance",
    tags: ["inventory", "zoho", "orders"],
  },
];
