import type { ConnectorMeta } from "../registry.js";

// Data & Analytics
export const connectors: ConnectorMeta[] = [
  {
    name: "exa",
    displayName: "Exa",
    description: "AI-powered web search",
    category: "Data & Analytics",
    tags: ["search", "ai"],
  },
  {
    name: "mixpanel",
    displayName: "Mixpanel",
    description: "Product analytics",
    category: "Data & Analytics",
    tags: ["analytics", "product"],
  },
  {
    name: "openweathermap",
    displayName: "OpenWeatherMap",
    description: "Weather data and forecasts",
    category: "Data & Analytics",
    tags: ["weather", "data"],
  },
  {
    name: "arxiv",
    displayName: "arXiv",
    description: "Research paper search and retrieval",
    category: "Data & Analytics",
    tags: ["research", "papers", "academic"],
  },
  {
    name: "zenodo",
    displayName: "Zenodo",
    description: "Open research data repository — search records and manage deposits",
    category: "Data & Analytics",
    tags: ["research", "open-access", "datasets"],
  },
  {
    name: "brandsight",
    displayName: "Brandsight",
    description: "Brand monitoring",
    category: "Data & Analytics",
    tags: ["brand", "monitoring"],
  },
  {
    name: "airtable",
    displayName: "Airtable",
    description: "Spreadsheet-database hybrid",
    category: "Data & Analytics",
    tags: ["database", "spreadsheet"],
  },
  {
    name: "segment",
    displayName: "Segment",
    description: "Customer data platform",
    category: "Data & Analytics",
    tags: ["analytics", "cdp", "data"],
  },
  {
    name: "amplitude",
    displayName: "Amplitude",
    description: "Product analytics platform",
    category: "Data & Analytics",
    tags: ["analytics", "product"],
  },
  {
    name: "posthog",
    displayName: "PostHog",
    description: "Product analytics and feature flags",
    category: "Data & Analytics",
    tags: ["analytics", "feature-flags"],
  },
  {
    name: "clearbit",
    displayName: "Clearbit",
    description: "Business intelligence and data enrichment",
    category: "Data & Analytics",
    tags: ["enrichment", "data", "b2b"],
  },
  {
    name: "fathom",
    displayName: "Fathom Analytics",
    description: "Privacy-first website analytics",
    category: "Data & Analytics",
    tags: ["analytics", "privacy"],
  },
  {
    name: "snowflake",
    displayName: "Snowflake",
    description: "Cloud data warehouse",
    category: "Data & Analytics",
    tags: ["data", "warehouse", "sql"],
  },
  {
    name: "databricks",
    displayName: "Databricks",
    description: "Data lakehouse and ML platform",
    category: "Data & Analytics",
    tags: ["data", "ml", "lakehouse"],
  },
  {
    name: "coingecko",
    displayName: "CoinGecko",
    description: "Cryptocurrency data and prices",
    category: "Data & Analytics",
    tags: ["crypto", "prices", "data"],
  },
  {
    name: "abstract",
    displayName: "Abstract API",
    description: "IP geolocation, email validation, and data enrichment APIs",
    category: "Data & Analytics",
    tags: ["geolocation", "validation", "enrichment"],
  },
  {
    name: "accuranker",
    displayName: "AccuRanker",
    description: "SEO keyword rank tracking and SERP monitoring",
    category: "Data & Analytics",
    tags: ["seo", "rank-tracking", "serp"],
  },
  {
    name: "airnow",
    displayName: "AirNow",
    description: "Air quality data and forecasts",
    category: "Data & Analytics",
    tags: ["air-quality", "environment", "data"],
  },
  {
    name: "aitableai",
    displayName: "AITable.ai",
    description: "AI-powered spreadsheet and database platform",
    category: "Data & Analytics",
    tags: ["database", "spreadsheet", "ai"],
  },
  {
    name: "amadeus",
    displayName: "Amadeus",
    description: "Flight search, booking, and travel data",
    category: "Data & Analytics",
    tags: ["travel", "flights", "booking"],
  },
  {
    name: "bigdatacloud",
    displayName: "BigDataCloud",
    description: "IP geolocation and reverse geocoding APIs",
    category: "Data & Analytics",
    tags: ["geolocation", "ip", "geocoding"],
  },
  {
    name: "brandmentions",
    displayName: "BrandMentions",
    description: "Brand monitoring and social listening",
    category: "Data & Analytics",
    tags: ["monitoring", "brand", "social-listening"],
  },
  {
    name: "browseai",
    displayName: "Browse AI",
    description: "No-code web scraping and data extraction",
    category: "Data & Analytics",
    tags: ["scraping", "data-extraction", "no-code"],
  },
  {
    name: "collegefootballdata",
    displayName: "College Football Data",
    description: "College football statistics and game data",
    category: "Data & Analytics",
    tags: ["sports", "football", "statistics"],
  },
  {
    name: "contactout",
    displayName: "ContactOut",
    description: "LinkedIn profile enrichment and contact discovery",
    category: "Data & Analytics",
    tags: ["enrichment", "contacts", "linkedin"],
  },
  {
    name: "crowddev",
    displayName: "Crowd.dev",
    description: "Developer community analytics and engagement",
    category: "Data & Analytics",
    tags: ["community", "analytics", "developer-relations"],
  },
  {
    name: "currents",
    displayName: "Currents",
    description: "News aggregation and current events API",
    category: "Data & Analytics",
    tags: ["news", "articles", "current-events"],
  },
  {
    name: "darkskyapi",
    displayName: "Dark Sky",
    description: "Hyperlocal weather forecasting and historical data",
    category: "Data & Analytics",
    tags: ["weather", "forecasting", "climate"],
  },
  {
    name: "databox",
    displayName: "Databox",
    description: "Business analytics dashboards and KPI tracking",
    category: "Data & Analytics",
    tags: ["analytics", "dashboards", "kpi"],
  },
  {
    name: "datasoap",
    displayName: "DataSoap",
    description: "Data cleansing, email verification, and data validation",
    category: "Data & Analytics",
    tags: ["data", "cleansing", "validation", "email-verification"],
  },
  {
    name: "domo",
    displayName: "Domo",
    description: "Business intelligence platform and data visualization",
    category: "Data & Analytics",
    tags: ["bi", "analytics", "dashboards", "visualization"],
  },
  {
    name: "dropcontact",
    displayName: "Dropcontact",
    description: "B2B contact enrichment and email finder",
    category: "Data & Analytics",
    tags: ["contacts", "enrichment", "b2b", "email"],
  },
  {
    name: "elasticsearch",
    displayName: "Elasticsearch",
    description: "Distributed search and analytics engine",
    category: "Data & Analytics",
    tags: ["search", "analytics", "indexing", "full-text"],
  },
  {
    name: "enterpret",
    displayName: "Enterpret",
    description: "Customer feedback analytics and insights platform",
    category: "Data & Analytics",
    tags: ["feedback", "analytics", "customer-insights"],
  },
  {
    name: "faros",
    displayName: "Faros",
    description: "Engineering intelligence and developer productivity analytics",
    category: "Data & Analytics",
    tags: ["engineering", "analytics", "productivity", "devops"],
  },
  {
    name: "fitbit",
    displayName: "Fitbit",
    description: "Fitness tracking, health data, and wellness metrics",
    category: "Data & Analytics",
    tags: ["fitness", "health", "wearable", "tracking"],
  },
  {
    name: "freedictionary",
    displayName: "Free Dictionary",
    description: "Dictionary definitions, phonetics, and translations",
    category: "Data & Analytics",
    tags: ["dictionary", "language", "definitions"],
  },
  {
    name: "fullcontact",
    displayName: "FullContact",
    description: "Identity resolution and contact enrichment",
    category: "Data & Analytics",
    tags: ["enrichment", "identity", "contacts"],
  },
  {
    name: "genderapi",
    displayName: "Gender API",
    description: "Gender detection from names",
    category: "Data & Analytics",
    tags: ["gender", "names", "demographics"],
  },
  {
    name: "googleanalytics",
    displayName: "Google Analytics",
    description: "Website and app analytics reporting",
    category: "Data & Analytics",
    tags: ["google", "analytics", "web", "reporting"],
  },
  {
    name: "googlebigquery",
    displayName: "Google BigQuery",
    description: "Serverless data warehouse and SQL analytics",
    category: "Data & Analytics",
    tags: ["google", "bigquery", "data-warehouse", "sql"],
  },
  {
    name: "grist",
    displayName: "Grist",
    description: "Relational spreadsheet and database",
    category: "Data & Analytics",
    tags: ["spreadsheet", "database", "tables"],
  },
  {
    name: "hackernews",
    displayName: "Hacker News",
    description: "Y Combinator tech news and stories",
    category: "Data & Analytics",
    tags: ["news", "tech", "community"],
  },
  {
    name: "harrypotterapi",
    displayName: "Harry Potter API",
    description: "Harry Potter universe data and characters",
    category: "Data & Analytics",
    tags: ["harrypotter", "api", "entertainment"],
  },
  {
    name: "idealpostcodes",
    displayName: "Ideal Postcodes",
    description: "UK address lookup and verification",
    category: "Data & Analytics",
    tags: ["address", "postcodes", "uk", "geocoding"],
  },
  {
    name: "idealspot",
    displayName: "IdealSpot",
    description: "Location intelligence and market analytics",
    category: "Data & Analytics",
    tags: ["location", "market", "analytics"],
  },
  {
    name: "industryselect",
    displayName: "IndustrySelect",
    description: "Industry and company database for lead generation",
    category: "Data & Analytics",
    tags: ["leads", "industry", "database"],
  },
  {
    name: "influxdbcloud",
    displayName: "InfluxDB Cloud",
    description: "Time series database and analytics",
    category: "Data & Analytics",
    tags: ["timeseries", "database", "monitoring", "iot"],
  },
  {
    name: "ip2location",
    displayName: "IP2Location",
    description: "IP geolocation and proxy detection",
    category: "Data & Analytics",
    tags: ["ip", "geolocation", "proxy-detection"],
  },
  {
    name: "ipinfo",
    displayName: "IPinfo",
    description: "IP address data and geolocation API",
    category: "Data & Analytics",
    tags: ["ip", "geolocation", "network"],
  },
  {
    name: "ipregistry",
    displayName: "ipregistry",
    description: "IP geolocation and threat detection API",
    category: "Data & Analytics",
    tags: ["ip", "geolocation", "threat-detection"],
  },
  {
    name: "kadoa",
    displayName: "Kadoa",
    description: "AI-powered web scraping and data extraction",
    category: "Data & Analytics",
    tags: ["scraping", "data-extraction", "ai"],
  },
  {
    name: "kaggle",
    displayName: "Kaggle",
    description: "Data science competitions, datasets, and notebooks",
    category: "Data & Analytics",
    tags: ["data-science", "datasets", "ml", "competitions"],
  },
  {
    name: "kibana",
    displayName: "Kibana",
    description: "Data visualization and exploration for Elasticsearch",
    category: "Data & Analytics",
    tags: ["visualization", "elasticsearch", "dashboards", "logging"],
  },
  {
    name: "klazify",
    displayName: "Klazify",
    description: "Website categorization and logo detection API",
    category: "Data & Analytics",
    tags: ["categorization", "website", "logo-detection"],
  },
  {
    name: "kobotoolbox",
    displayName: "KoboToolbox",
    description: "Data collection and survey tools for field research",
    category: "Data & Analytics",
    tags: ["surveys", "data-collection", "field-research", "humanitarian"],
  },
  {
    name: "marketstack",
    displayName: "Marketstack",
    description: "Real-time and historical stock market data API",
    category: "Data & Analytics",
    tags: ["stocks", "market-data", "finance", "api"],
  },
  {
    name: "twelve-data",
    displayName: "Twelve Data",
    description: "Real-time and historical stock, forex, and crypto market data",
    category: "Data & Analytics",
    tags: ["stocks", "forex", "crypto", "market-data", "finance"],
  },
  {
    name: "metabase",
    displayName: "Metabase",
    description: "Open-source business intelligence and analytics",
    category: "Data & Analytics",
    tags: ["bi", "analytics", "dashboards", "sql", "open-source"],
  },
  {
    name: "morph",
    displayName: "Morph",
    description: "Data transformation and workflow automation",
    category: "Data & Analytics",
    tags: ["data", "transformation", "etl", "automation"],
  },
  {
    name: "nasa",
    displayName: "NASA",
    description: "NASA open APIs for space data, imagery, and astronomy",
    category: "Data & Analytics",
    tags: ["space", "astronomy", "science", "imagery", "api"],
  },
  {
    name: "parsehub",
    displayName: "ParseHub",
    description: "Web scraping and data extraction platform",
    category: "Data & Analytics",
    tags: ["scraping", "data-extraction", "web", "automation", "no-code"],
  },
  {
    name: "phantombuster",
    displayName: "PhantomBuster",
    description: "Cloud-based web automation and data extraction platform",
    category: "Data & Analytics",
    tags: ["automation", "scraping", "lead-generation", "linkedin", "social"],
  },
  {
    name: "pirateweather",
    displayName: "Pirate Weather",
    description: "Weather forecast API compatible with Dark Sky",
    category: "Data & Analytics",
    tags: ["weather", "forecast", "meteorology", "dark-sky", "api"],
  },
  {
    name: "plecto",
    displayName: "Plecto",
    description: "Real-time performance dashboards and KPI tracking platform",
    category: "Data & Analytics",
    tags: ["dashboards", "kpi", "performance", "real-time", "visualization"],
  },
  {
    name: "redash",
    displayName: "Redash",
    description: "Open-source data visualization and dashboard platform",
    category: "Data & Analytics",
    tags: ["dashboards", "visualization", "sql", "analytics", "reporting"],
  },
  {
    name: "scrapeitcloud",
    displayName: "ScrapeIt Cloud",
    description: "Cloud-based web scraping and data extraction service",
    category: "Data & Analytics",
    tags: ["scraping", "web-scraping", "data-extraction", "cloud", "automation"],
  },
  {
    name: "scrapeninja",
    displayName: "ScrapeNinja",
    description: "Web scraping API with proxy rotation and anti-bot bypass",
    category: "Data & Analytics",
    tags: ["scraping", "web-scraping", "proxy", "api", "data-extraction"],
  },
  {
    name: "searchandsave",
    displayName: "Search And Save",
    description: "Search aggregation and content saving platform",
    category: "Data & Analytics",
    tags: ["search", "aggregation", "content", "saving", "data"],
  },
  {
    name: "simplekpi",
    displayName: "SimpleKPI",
    description: "KPI tracking and business performance dashboard platform",
    category: "Data & Analytics",
    tags: ["kpi", "metrics", "dashboard", "performance", "analytics"],
  },
  {
    name: "solvedata",
    displayName: "Solve.io",
    description: "Customer data platform for retail analytics and personalization",
    category: "Data & Analytics",
    tags: ["customer data", "retail", "analytics", "personalization", "cdp"],
  },
  {
    name: "specter",
    displayName: "Specter",
    description: "Game intelligence platform for game studios and developers",
    category: "Data & Analytics",
    tags: ["gaming", "analytics", "game development", "intelligence", "data"],
  },
  {
    name: "splunk",
    displayName: "Splunk",
    description: "Platform for searching, monitoring, and analyzing machine-generated data",
    category: "Data & Analytics",
    tags: ["logs", "monitoring", "security", "analytics", "siem"],
  },
  {
    name: "sportsdata",
    displayName: "SportsData",
    description: "Real-time sports data, scores, and statistics API",
    category: "Data & Analytics",
    tags: ["sports", "data", "scores", "statistics", "real-time"],
  },
  {
    name: "strava",
    displayName: "Strava",
    description: "Fitness tracking and social platform for athletes and activities",
    category: "Data & Analytics",
    tags: ["fitness", "running", "cycling", "activities", "sports"],
  },
  {
    name: "triple-whale",
    displayName: "Triple Whale",
    description: "Ecommerce analytics - summary, attribution, data-in, SQL, Moby",
    category: "Data & Analytics",
    tags: ["ecommerce", "analytics", "attribution", "marketing"],
  },
  {
    name: "typesense",
    displayName: "Typesense",
    description: "Open-source search engine for full-text, faceted, and vector search",
    category: "Data & Analytics",
    tags: ["search", "indexing", "vector", "full-text"],
  },
  {
    name: "uproc",
    displayName: "uProc",
    description: "Data processing and enrichment tools",
    category: "Data & Analytics",
    tags: ["data", "enrichment", "processing"],
  },
  {
    name: "watchsignals",
    displayName: "WatchSignals",
    description: "Luxury watch market data and price tracking",
    category: "Data & Analytics",
    tags: ["watches", "market-data", "prices"],
  },
  {
    name: "webscraperio",
    displayName: "WebScraper.io",
    description: "Web scraping and data extraction cloud service",
    category: "Data & Analytics",
    tags: ["scraping", "data", "extraction"],
  },
  {
    name: "wikipedia",
    displayName: "Wikipedia",
    description: "Free encyclopedia with article search and content retrieval",
    category: "Data & Analytics",
    tags: ["encyclopedia", "knowledge", "search"],
  },
  {
    name: "wolframoralpha",
    displayName: "Wolfram Alpha",
    description: "Computational knowledge engine and math solver",
    category: "Data & Analytics",
    tags: ["knowledge", "math", "computation"],
  },
  {
    name: "wubookratechecker",
    displayName: "Wu Bookrate Checker",
    description: "Book rating and review data lookup",
    category: "Data & Analytics",
    tags: ["books", "ratings", "data"],
  },
  {
    name: "zenrows",
    displayName: "ZenRows",
    description: "Web scraping API with anti-bot bypass",
    category: "Data & Analytics",
    tags: ["scraping", "data", "api"],
  },
];
