import type { ConnectorMeta } from "../registry.js";

// Design & Content
export const connectors: ConnectorMeta[] = [
  {
    name: "figma",
    displayName: "Figma",
    description: "Design files, components, and comments",
    category: "Design & Content",
    tags: ["design", "ui"],
  },
  {
    name: "webflow",
    displayName: "Webflow",
    description: "Website builder and CMS",
    category: "Design & Content",
    tags: ["website", "cms"],
  },
  {
    name: "wix",
    displayName: "Wix",
    description: "Website builder",
    category: "Design & Content",
    tags: ["website"],
  },
  {
    name: "icons8",
    displayName: "Icons8",
    description: "Icons and illustrations",
    category: "Design & Content",
    tags: ["icons", "assets"],
  },
  {
    name: "bannerbear",
    displayName: "Bannerbear",
    description: "Auto-generate images and videos",
    category: "Design & Content",
    tags: ["images", "automation", "templates"],
  },
  {
    name: "adobe",
    displayName: "Adobe",
    description: "Creative Cloud APIs",
    category: "Design & Content",
    tags: ["design", "creative", "pdf"],
  },
  {
    name: "apitemplateio",
    displayName: "APITemplate.io",
    description: "PDF and image generation from templates",
    category: "Design & Content",
    tags: ["pdf", "images", "templates"],
  },
  {
    name: "brandfetch",
    displayName: "Brandfetch",
    description: "Brand logos, colors, and asset retrieval API",
    category: "Design & Content",
    tags: ["branding", "logos", "assets"],
  },
  {
    name: "cockpit",
    displayName: "Cockpit",
    description: "Headless CMS for structured content management",
    category: "Design & Content",
    tags: ["cms", "headless", "content"],
  },
  {
    name: "contentful",
    displayName: "Contentful",
    description: "Headless CMS for content management and delivery",
    category: "Design & Content",
    tags: ["cms", "headless", "content"],
  },
  {
    name: "craftdraft",
    displayName: "CraftDraft",
    description: "Document drafting and template management",
    category: "Design & Content",
    tags: ["documents", "templates", "drafting"],
  },
  {
    name: "descript",
    displayName: "Descript",
    description: "Audio/video editing, transcription, and media collaboration",
    category: "Design & Content",
    tags: ["audio", "video", "transcription", "editing"],
  },
  {
    name: "evolphinzoom",
    displayName: "Evolphin Zoom",
    description: "Media asset management and digital asset workflows",
    category: "Design & Content",
    tags: ["dam", "media", "assets", "management"],
  },
  {
    name: "flotiq",
    displayName: "Flotiq",
    description: "Headless CMS and content management API",
    category: "Design & Content",
    tags: ["cms", "headless", "content", "api"],
  },
  {
    name: "ghost",
    displayName: "Ghost",
    description: "Headless CMS and publishing platform",
    category: "Design & Content",
    tags: ["cms", "blog", "publishing"],
  },
  {
    name: "lucidchart",
    displayName: "Lucidchart",
    description: "Diagramming and visual collaboration platform",
    category: "Design & Content",
    tags: ["diagrams", "flowcharts", "collaboration", "visual"],
  },
  {
    name: "sitecreatorio",
    displayName: "Sitecreator.io",
    description: "Website builder and landing page creation platform",
    category: "Design & Content",
    tags: ["website builder", "landing pages", "no-code", "design"],
  },
  {
    name: "storyblok",
    displayName: "Storyblok",
    description: "Headless CMS with visual editor for content management",
    category: "Design & Content",
    tags: ["cms", "headless", "content", "visual editor", "api"],
  },
  {
    name: "supportivekoala",
    displayName: "Supportive Koala",
    description: "Automated image generation API for personalized visuals",
    category: "Design & Content",
    tags: ["image generation", "automation", "personalization", "api", "graphics"],
  },
  {
    name: "tilda",
    displayName: "Tilda",
    description: "Website builder and publishing platform with block-based design tools",
    category: "Design & Content",
    tags: ["website builder", "landing pages", "design", "publishing", "no-code"],
  },
  {
    name: "tinypng",
    displayName: "TinyPNG",
    description: "Image compression and optimization for AVIF, WebP, JPEG, and PNG",
    category: "Design & Content",
    tags: ["images", "optimization", "compression"],
  },
  {
    name: "vimeo",
    displayName: "Vimeo",
    description: "Video hosting, management, and streaming",
    category: "Design & Content",
    tags: ["video", "hosting", "streaming"],
  },
  {
    name: "wordpress",
    displayName: "WordPress",
    description: "CMS posts, pages, media, and site management",
    category: "Design & Content",
    tags: ["cms", "blogging", "website"],
  },
];
