import type { ConnectorMeta } from "../registry.js";

// Developer Tools
export const connectors: ConnectorMeta[] = [
  {
    name: "github",
    displayName: "GitHub",
    description: "Repositories, issues, PRs, and actions",
    category: "Developer Tools",
    tags: ["git", "code", "vcs"],
  },
  {
    name: "docker",
    displayName: "Docker",
    description: "Container management and registry",
    category: "Developer Tools",
    tags: ["containers", "devops"],
  },
  {
    name: "sentry",
    displayName: "Sentry",
    description: "Error tracking and monitoring",
    category: "Developer Tools",
    tags: ["monitoring", "errors"],
  },
  {
    name: "stage",
    displayName: "Stage",
    description: "Structured code reviews, chapters, comments, and pull requests",
    category: "Developer Tools",
    tags: ["code-review", "git", "development"],
  },
  {
    name: "cloudflare",
    displayName: "Cloudflare",
    description: "DNS, CDN, and edge computing",
    category: "Developer Tools",
    tags: ["cdn", "dns", "edge"],
  },
  {
    name: "googlecloud",
    displayName: "Google Cloud",
    description: "GCP services and APIs",
    category: "Developer Tools",
    tags: ["cloud", "gcp"],
  },
  {
    name: "aws",
    displayName: "AWS",
    description: "Amazon Web Services",
    category: "Developer Tools",
    tags: ["cloud", "aws"],
  },
  {
    name: "e2b",
    displayName: "E2B",
    description: "Code interpreter sandboxes",
    category: "Developer Tools",
    tags: ["sandbox", "code"],
  },
  {
    name: "firecrawl",
    displayName: "Firecrawl",
    description: "Web scraping and crawling",
    category: "Developer Tools",
    tags: ["scraping", "web"],
  },
  {
    name: "shadcn",
    displayName: "shadcn/ui",
    description: "UI component registry",
    category: "Developer Tools",
    tags: ["ui", "components", "react"],
  },
  {
    name: "vercel",
    displayName: "Vercel",
    description: "Deployment and hosting platform",
    category: "Developer Tools",
    tags: ["hosting", "deployment", "serverless"],
  },
  {
    name: "wakatime",
    displayName: "WakaTime",
    description: "Coding time analytics and developer productivity tracking",
    category: "Developer Tools",
    tags: ["time-tracking", "productivity", "developer-analytics"],
  },
  {
    name: "netlify",
    displayName: "Netlify",
    description: "Web hosting and deployment",
    category: "Developer Tools",
    tags: ["hosting", "deployment", "jamstack"],
  },
  {
    name: "supabase",
    displayName: "Supabase",
    description: "PostgreSQL database and auth",
    category: "Developer Tools",
    tags: ["database", "auth", "postgres"],
  },
  {
    name: "sucuri-api-platform",
    displayName: "Sucuri API Platform",
    description: "Sucuri API Platform resources and events",
    category: "Developer Tools",
    tags: ["security", "waf", "api-platform", "sucuri"],
  },
  {
    name: "mongodb",
    displayName: "MongoDB",
    description: "Document database and Atlas",
    category: "Developer Tools",
    tags: ["database", "nosql"],
  },
  {
    name: "linode",
    displayName: "Linode",
    description: "Cloud computing and hosting",
    category: "Developer Tools",
    tags: ["cloud", "hosting", "vps"],
  },
  {
    name: "vultr",
    displayName: "Vultr",
    description: "Cloud infrastructure for instances, block storage, firewalls, and snapshots",
    category: "Developer Tools",
    tags: ["cloud", "hosting", "vps", "infrastructure"],
  },
  {
    name: "datadog",
    displayName: "Datadog",
    description: "Monitoring and observability",
    category: "Developer Tools",
    tags: ["monitoring", "observability", "apm"],
  },
  {
    name: "grafana",
    displayName: "Grafana",
    description: "Dashboards and observability",
    category: "Developer Tools",
    tags: ["monitoring", "dashboards", "observability"],
  },
  {
    name: "zipkin",
    displayName: "Zipkin",
    description: "Distributed tracing platform",
    category: "Developer Tools",
    tags: ["monitoring", "tracing", "observability"],
  },
  {
    name: "okta",
    displayName: "Okta",
    description: "Identity and access management",
    category: "Developer Tools",
    tags: ["auth", "identity", "sso"],
  },
  {
    name: "auth0",
    displayName: "Auth0",
    description: "Authentication and authorization platform",
    category: "Developer Tools",
    tags: ["auth", "identity", "oauth"],
  },
  {
    name: "stytch",
    displayName: "Stytch",
    description: "Passwordless authentication and identity platform",
    category: "Developer Tools",
    tags: ["auth", "identity", "mfa"],
  },
  {
    name: "homeassistant",
    displayName: "Home Assistant",
    description: "Smart home automation",
    category: "Developer Tools",
    tags: ["iot", "smart-home", "automation"],
  },
  {
    name: "gitlab",
    displayName: "GitLab",
    description: "DevOps platform with git repos and CI/CD",
    category: "Developer Tools",
    tags: ["git", "cicd", "devops"],
  },
  {
    name: "uptimerobot",
    displayName: "UptimeRobot",
    description: "Website uptime monitoring",
    category: "Developer Tools",
    tags: ["monitoring", "uptime", "alerts"],
  },
  {
    name: "pagerduty",
    displayName: "PagerDuty",
    description: "Incident management and on-call",
    category: "Developer Tools",
    tags: ["incidents", "oncall", "alerts"],
  },
  {
    name: "launchdarkly",
    displayName: "LaunchDarkly",
    description: "Feature flags and experimentation",
    category: "Developer Tools",
    tags: ["feature-flags", "experimentation"],
  },
  {
    name: "split-io",
    displayName: "Split.io",
    description: "Feature flags, segments, and experimentation",
    category: "Developer Tools",
    tags: ["feature-flags", "experimentation"],
  },
  {
    name: "abuselpdb",
    displayName: "AbuseIPDB",
    description: "IP abuse checking and threat intelligence",
    category: "Developer Tools",
    tags: ["security", "ip", "threat-intelligence"],
  },
  {
    name: "adalo",
    displayName: "Adalo",
    description: "No-code app platform with collection and record management",
    category: "Developer Tools",
    tags: ["no-code", "app-builder", "mobile"],
  },
  {
    name: "airbrake",
    displayName: "Airbrake",
    description: "Error and performance monitoring",
    category: "Developer Tools",
    tags: ["monitoring", "errors", "performance"],
  },
  {
    name: "airtop",
    displayName: "Airtop",
    description: "Cloud browser automation and web interaction",
    category: "Developer Tools",
    tags: ["browser", "automation", "cloud"],
  },
  {
    name: "alchemy",
    displayName: "Alchemy",
    description: "Web3 and blockchain development platform",
    category: "Developer Tools",
    tags: ["blockchain", "web3", "ethereum"],
  },
  {
    name: "alerty",
    displayName: "Alerty",
    description: "Website and API monitoring with alerts",
    category: "Developer Tools",
    tags: ["monitoring", "alerts", "uptime"],
  },
  {
    name: "alienvault",
    displayName: "AlienVault OTX",
    description: "Open threat intelligence and security data",
    category: "Developer Tools",
    tags: ["security", "threat-intelligence", "otx"],
  },
  {
    name: "amqpsender",
    displayName: "AMQP Sender",
    description: "AMQP message queue producer",
    category: "Developer Tools",
    tags: ["amqp", "messaging", "queue"],
  },
  {
    name: "apiary",
    displayName: "Apiary",
    description: "API design, documentation, and testing",
    category: "Developer Tools",
    tags: ["api", "documentation", "testing"],
  },
  {
    name: "apiflash",
    displayName: "ApiFlash",
    description: "Website screenshot capture API",
    category: "Developer Tools",
    tags: ["screenshots", "web", "api"],
  },
  {
    name: "apptivegrid",
    displayName: "Apptivegrid",
    description: "Low-code database and business application platform",
    category: "Developer Tools",
    tags: ["low-code", "database", "apps"],
  },
  {
    name: "awscognito",
    displayName: "AWS Cognito",
    description: "User authentication and identity management",
    category: "Developer Tools",
    tags: ["auth", "identity", "aws"],
  },
  {
    name: "azurecosmosdb",
    displayName: "Azure Cosmos DB",
    description: "Globally distributed multi-model database",
    category: "Developer Tools",
    tags: ["database", "nosql", "azure"],
  },
  {
    name: "azurestorage",
    displayName: "Azure Storage",
    description: "Blob, file, queue, and table cloud storage",
    category: "Developer Tools",
    tags: ["storage", "cloud", "azure"],
  },
  {
    name: "baserow",
    displayName: "Baserow",
    description: "Open-source no-code database platform",
    category: "Developer Tools",
    tags: ["database", "no-code", "open-source"],
  },
  {
    name: "bitly",
    displayName: "Bitly",
    description: "URL shortening and link management",
    category: "Developer Tools",
    tags: ["urls", "links", "shortener"],
  },
  {
    name: "bitwarden",
    displayName: "Bitwarden",
    description: "Password management and secrets vault",
    category: "Developer Tools",
    tags: ["passwords", "security", "vault"],
  },
  {
    name: "zohovault",
    displayName: "Zoho Vault",
    description: "Password and secrets manager with chambers, sharing, and audit",
    category: "Developer Tools",
    tags: ["passwords", "security", "vault", "zoho"],
  },
  {
    name: "bloock",
    displayName: "Bloock",
    description: "Blockchain-based data integrity and verification",
    category: "Developer Tools",
    tags: ["blockchain", "integrity", "verification"],
  },
  {
    name: "botiumbox",
    displayName: "Botium Box",
    description: "Chatbot testing and quality assurance",
    category: "Developer Tools",
    tags: ["testing", "chatbot", "qa"],
  },
  {
    name: "browserless",
    displayName: "Browserless",
    description: "Headless browser automation as a service",
    category: "Developer Tools",
    tags: ["browser", "automation", "headless"],
  },
  {
    name: "browserstack",
    displayName: "BrowserStack",
    description: "Cross-browser testing and mobile app testing",
    category: "Developer Tools",
    tags: ["testing", "browser", "mobile"],
  },
  {
    name: "bubble",
    displayName: "Bubble",
    description: "No-code web application builder",
    category: "Developer Tools",
    tags: ["no-code", "app-builder", "web"],
  },
  {
    name: "bugbug",
    displayName: "BugBug",
    description: "Browser-based automated testing",
    category: "Developer Tools",
    tags: ["testing", "automation", "browser"],
  },
  {
    name: "bugfender",
    displayName: "Bugfender",
    description: "Remote logging and crash reporting for apps",
    category: "Developer Tools",
    tags: ["logging", "crash-reporting", "mobile"],
  },
  {
    name: "bugherd",
    displayName: "BugHerd",
    description: "Visual bug tracking and website feedback",
    category: "Developer Tools",
    tags: ["bugs", "feedback", "testing"],
  },
  {
    name: "bugpilot",
    displayName: "Bugpilot",
    description: "AI-powered bug reporting and session replay",
    category: "Developer Tools",
    tags: ["bugs", "monitoring", "ai"],
  },
  {
    name: "bugreplay",
    displayName: "BugReplay",
    description: "Screen recording and bug reporting for QA",
    category: "Developer Tools",
    tags: ["bugs", "recording", "qa"],
  },
  {
    name: "bugshot",
    displayName: "Bugshot",
    description: "Screenshot-based bug reporting and annotation",
    category: "Developer Tools",
    tags: ["bugs", "screenshots", "annotation"],
  },
  {
    name: "buildkite",
    displayName: "Buildkite",
    description: "CI/CD pipelines and build automation",
    category: "Developer Tools",
    tags: ["cicd", "builds", "pipelines"],
  },
  {
    name: "bunnycdn",
    displayName: "Bunny CDN",
    description: "Content delivery network and edge storage",
    category: "Developer Tools",
    tags: ["cdn", "storage", "edge"],
  },
  {
    name: "carbonblack",
    displayName: "Carbon Black",
    description: "Endpoint security and threat detection",
    category: "Developer Tools",
    tags: ["security", "endpoint", "threat-detection"],
  },
  {
    name: "circleci",
    displayName: "CircleCI",
    description: "Continuous integration and delivery platform",
    category: "Developer Tools",
    tags: ["cicd", "builds", "devops"],
  },
  {
    name: "ciscomeraki",
    displayName: "Cisco Meraki",
    description: "Cloud-managed networking and WiFi",
    category: "Developer Tools",
    tags: ["networking", "wifi", "cisco"],
  },
  {
    name: "ciscosecureendpoint",
    displayName: "Cisco Secure Endpoint",
    description: "Endpoint protection and threat response",
    category: "Developer Tools",
    tags: ["security", "endpoint", "cisco"],
  },
  {
    name: "ciscoumbrella",
    displayName: "Cisco Umbrella",
    description: "Cloud security and DNS protection",
    category: "Developer Tools",
    tags: ["security", "dns", "cisco"],
  },
  {
    name: "citrixadc",
    displayName: "Citrix ADC",
    description: "Application delivery controller and load balancing",
    category: "Developer Tools",
    tags: ["networking", "load-balancing", "adc"],
  },
  {
    name: "clappia",
    displayName: "Clappia",
    description: "No-code business app builder",
    category: "Developer Tools",
    tags: ["no-code", "app-builder", "business"],
  },
  {
    name: "cloud66",
    displayName: "Cloud 66",
    description: "DevOps and infrastructure management for cloud deployments",
    category: "Developer Tools",
    tags: ["devops", "deployment", "infrastructure"],
  },
  {
    name: "cloudboost",
    displayName: "CloudBoost",
    description: "Backend-as-a-service with database, search, and storage",
    category: "Developer Tools",
    tags: ["baas", "database", "backend"],
  },
  {
    name: "cloudconvert",
    displayName: "CloudConvert",
    description: "File conversion API for 200+ formats",
    category: "Developer Tools",
    tags: ["conversion", "files", "api"],
  },
  {
    name: "cloudlayer",
    displayName: "CloudLayer",
    description: "HTML to PDF and image generation API",
    category: "Developer Tools",
    tags: ["pdf", "images", "html", "generation"],
  },
  {
    name: "cloudshare",
    displayName: "CloudShare",
    description: "Virtual IT labs and training environments",
    category: "Developer Tools",
    tags: ["labs", "training", "virtual-environments"],
  },
  {
    name: "codeclimate",
    displayName: "Code Climate",
    description: "Code quality and automated code review",
    category: "Developer Tools",
    tags: ["code-quality", "review", "analysis"],
  },
  {
    name: "codefresh",
    displayName: "Codefresh",
    description: "CI/CD platform for Kubernetes and GitOps",
    category: "Developer Tools",
    tags: ["cicd", "kubernetes", "gitops"],
  },
  {
    name: "configcat",
    displayName: "ConfigCat",
    description: "Feature flags and remote configuration management",
    category: "Developer Tools",
    tags: ["feature-flags", "configuration", "remote-config"],
  },
  {
    name: "confluent",
    displayName: "Confluent",
    description: "Cloud-native Apache Kafka streaming platform",
    category: "Developer Tools",
    tags: ["kafka", "streaming", "events"],
  },
  {
    name: "convertapi",
    displayName: "ConvertAPI",
    description: "File conversion and document processing API",
    category: "Developer Tools",
    tags: ["conversion", "documents", "files"],
  },
  {
    name: "cortex",
    displayName: "Cortex",
    description: "Internal developer portal and service catalog",
    category: "Developer Tools",
    tags: ["developer-portal", "service-catalog", "microservices"],
  },
  {
    name: "cratedb",
    displayName: "CrateDB",
    description: "Distributed SQL database for time-series and IoT data",
    category: "Developer Tools",
    tags: ["database", "sql", "time-series"],
  },
  {
    name: "cronly",
    displayName: "Cronly",
    description: "Cron job monitoring and scheduling",
    category: "Developer Tools",
    tags: ["cron", "monitoring", "scheduling"],
  },
  {
    name: "crossmint",
    displayName: "Crossmint",
    description: "NFT minting and Web3 wallet infrastructure",
    category: "Developer Tools",
    tags: ["nft", "web3", "blockchain"],
  },
  {
    name: "crowdin",
    displayName: "Crowdin",
    description: "Localization and translation management platform",
    category: "Developer Tools",
    tags: ["localization", "translation", "i18n"],
  },
  {
    name: "crowdstrike",
    displayName: "CrowdStrike",
    description: "Endpoint security and threat intelligence platform",
    category: "Developer Tools",
    tags: ["security", "endpoint", "threat-intelligence"],
  },
  {
    name: "cryptolens",
    displayName: "Cryptolens",
    description: "Software licensing and key management",
    category: "Developer Tools",
    tags: ["licensing", "keys", "software"],
  },
  {
    name: "devcycle",
    displayName: "DevCycle",
    description: "Feature flags, A/B testing, and feature management",
    category: "Developer Tools",
    tags: ["feature-flags", "ab-testing", "devops"],
  },
  {
    name: "diffy",
    displayName: "Diffy",
    description: "Visual regression testing and screenshot comparison",
    category: "Developer Tools",
    tags: ["testing", "visual-regression", "screenshots"],
  },
  {
    name: "digicert",
    displayName: "DigiCert",
    description: "SSL/TLS certificate management and PKI services",
    category: "Developer Tools",
    tags: ["ssl", "certificates", "security", "pki"],
  },
  {
    name: "digitalocean",
    displayName: "DigitalOcean",
    description: "Cloud infrastructure for droplets, volumes, databases, and Kubernetes",
    category: "Developer Tools",
    tags: ["cloud", "hosting", "infrastructure", "kubernetes"],
  },
  {
    name: "dockcerts",
    displayName: "DockCerts",
    description: "Verifiable credentials and digital certificate issuance",
    category: "Developer Tools",
    tags: ["credentials", "certificates", "blockchain", "verification"],
  },
  {
    name: "docuwriter",
    displayName: "DocuWriter",
    description: "AI-powered technical documentation and code documentation generator",
    category: "Developer Tools",
    tags: ["documentation", "ai", "code-docs", "technical-writing"],
  },
  {
    name: "dynatrace",
    displayName: "Dynatrace",
    description: "Application performance monitoring and observability platform",
    category: "Developer Tools",
    tags: ["monitoring", "apm", "observability", "performance"],
  },
  {
    name: "eartho",
    displayName: "Eartho",
    description: "Universal login and authentication platform",
    category: "Developer Tools",
    tags: ["auth", "identity", "login", "sso"],
  },
  {
    name: "elasticsecurity",
    displayName: "Elastic Security",
    description: "SIEM, threat detection, and endpoint security platform",
    category: "Developer Tools",
    tags: ["security", "siem", "threat-detection", "endpoint"],
  },
  {
    name: "elmah",
    displayName: "Elmah.io",
    description: "Error logging and uptime monitoring for .NET applications",
    category: "Developer Tools",
    tags: ["error-logging", "monitoring", "dotnet", "uptime"],
  },
  {
    name: "evervault",
    displayName: "Evervault",
    description: "Encryption and data security infrastructure",
    category: "Developer Tools",
    tags: ["encryption", "security", "data-protection"],
  },
  {
    name: "f5bigip",
    displayName: "F5 BIG-IP",
    description: "Application delivery controller and load balancing",
    category: "Developer Tools",
    tags: ["networking", "load-balancing", "adc", "f5"],
  },
  {
    name: "filemaker",
    displayName: "FileMaker",
    description: "Claris FileMaker custom app and database platform",
    category: "Developer Tools",
    tags: ["database", "apps", "low-code", "claris"],
  },
  {
    name: "filescan",
    displayName: "FileScan",
    description: "Malware analysis and file scanning security service",
    category: "Developer Tools",
    tags: ["security", "malware", "scanning", "analysis"],
  },
  {
    name: "flagship",
    displayName: "Flagship",
    description: "Feature flagging and experimentation platform",
    category: "Developer Tools",
    tags: ["feature-flags", "experimentation", "ab-testing"],
  },
  {
    name: "fortinetfortigate",
    displayName: "Fortinet FortiGate",
    description: "Network security and firewall management",
    category: "Developer Tools",
    tags: ["security", "firewall", "network"],
  },
  {
    name: "freshping",
    displayName: "Freshping",
    description: "Website and server uptime monitoring",
    category: "Developer Tools",
    tags: ["monitoring", "uptime", "alerts"],
  },
  {
    name: "getscreenshot",
    displayName: "GetScreenshot",
    description: "Website screenshot capture API",
    category: "Developer Tools",
    tags: ["screenshot", "capture", "api"],
  },
  {
    name: "gitea",
    displayName: "Gitea",
    description: "Self-hosted Git service and DevOps platform",
    category: "Developer Tools",
    tags: ["git", "devops", "self-hosted"],
  },
  {
    name: "gleap",
    displayName: "Gleap",
    description: "Bug reporting and customer feedback platform",
    category: "Developer Tools",
    tags: ["bug-reporting", "feedback", "support"],
  },
  {
    name: "godaddy",
    displayName: "GoDaddy",
    description: "Domain registration and DNS management",
    category: "Developer Tools",
    tags: ["domains", "dns", "hosting"],
  },
  {
    name: "headlesstesting",
    displayName: "Headless Testing",
    description: "Cloud browser testing and automation",
    category: "Developer Tools",
    tags: ["testing", "browser", "automation"],
  },
  {
    name: "hybridanalysis",
    displayName: "Hybrid Analysis",
    description: "Malware analysis and threat detection",
    category: "Developer Tools",
    tags: ["security", "malware", "threat-detection"],
  },
  {
    name: "imgbb",
    displayName: "ImgBB",
    description: "Image hosting and sharing",
    category: "Developer Tools",
    tags: ["image", "hosting", "upload"],
  },
  {
    name: "impervawaf",
    displayName: "Imperva WAF",
    description: "Web application firewall and DDoS protection",
    category: "Developer Tools",
    tags: ["security", "waf", "ddos", "firewall"],
  },
  {
    name: "instabug",
    displayName: "Instabug",
    description: "Bug reporting and crash analytics for mobile apps",
    category: "Developer Tools",
    tags: ["bugs", "mobile", "crash-reporting", "analytics"],
  },
  {
    name: "jama",
    displayName: "Jama Software",
    description: "Requirements management and traceability",
    category: "Developer Tools",
    tags: ["requirements", "traceability", "product-development"],
  },
  {
    name: "jenkins",
    displayName: "Jenkins",
    description: "Open-source CI/CD automation server",
    category: "Developer Tools",
    tags: ["ci-cd", "automation", "devops", "open-source"],
  },
  {
    name: "keygen",
    displayName: "Keygen",
    description: "Software licensing and distribution API",
    category: "Developer Tools",
    tags: ["licensing", "software", "distribution", "api"],
  },
  {
    name: "kitemaker",
    displayName: "Kitemaker",
    description: "Issue tracking and project management for product teams",
    category: "Developer Tools",
    tags: ["issue-tracking", "project-management", "product"],
  },
  {
    name: "lambdatest",
    displayName: "LambdaTest",
    description: "Cross-browser testing and test automation platform",
    category: "Developer Tools",
    tags: ["testing", "browser", "automation", "cross-browser"],
  },
  {
    name: "localazy",
    displayName: "Localazy",
    description: "App localization and translation management",
    category: "Developer Tools",
    tags: ["localization", "translation", "i18n"],
  },
  {
    name: "lokalise",
    displayName: "Lokalise",
    description: "Translation and localization management platform",
    category: "Developer Tools",
    tags: ["localization", "translation", "i18n", "l10n"],
  },
  {
    name: "mux",
    displayName: "Mux",
    description: "Video streaming infrastructure and analytics API",
    category: "Developer Tools",
    tags: ["video", "streaming", "api", "analytics"],
  },
  {
    name: "ncscale",
    displayName: "ncScale",
    description: "Database observability and scaling platform for developers",
    category: "Developer Tools",
    tags: ["database", "observability", "scaling", "monitoring"],
  },
  {
    name: "nmkr",
    displayName: "NMKR",
    description: "NFT minting and Cardano blockchain development tools",
    category: "Developer Tools",
    tags: ["nft", "blockchain", "cardano", "crypto", "minting"],
  },
  {
    name: "npm",
    displayName: "npm",
    description: "npm registry API for package search, metadata, and downloads",
    category: "Developer Tools",
    tags: ["npm", "packages", "registry", "javascript", "nodejs"],
  },
  {
    name: "ocrspace",
    displayName: "OCR.space",
    description: "Free and paid OCR API for extracting text from images and PDFs",
    category: "Developer Tools",
    tags: ["ocr", "text-extraction", "images", "pdf", "api"],
  },
  {
    name: "onesimpleapi",
    displayName: "One Simple API",
    description: "Collection of utility APIs for screenshots, PDFs, and web scraping",
    category: "Developer Tools",
    tags: ["screenshot", "pdf", "scraping", "utilities", "api"],
  },
  {
    name: "openthesaurus",
    displayName: "OpenThesaurus",
    description: "German-language thesaurus and synonym lookup API",
    category: "Developer Tools",
    tags: ["thesaurus", "synonyms", "german", "language", "nlp"],
  },
  {
    name: "peekalink",
    displayName: "Peekalink",
    description: "Link preview and metadata extraction API",
    category: "Developer Tools",
    tags: ["link-preview", "metadata", "og-tags", "url", "preview"],
  },
  {
    name: "pivotaltracker",
    displayName: "Pivotal Tracker",
    description: "Agile project management and story tracking tool",
    category: "Developer Tools",
    tags: ["agile", "project-management", "stories", "scrum", "planning"],
  },
  {
    name: "practitest",
    displayName: "PractiTest",
    description: "End-to-end QA and test management platform",
    category: "Developer Tools",
    tags: ["testing", "qa", "test-management", "quality", "bugs"],
  },
  {
    name: "pinboard",
    displayName: "Pinboard",
    description: "Bookmarking service for saving and organizing web links",
    category: "Developer Tools",
    tags: ["bookmarks", "links", "tagging", "reading-list", "web"],
  },
  {
    name: "quickchart",
    displayName: "QuickChart",
    description: "Chart and graph image generation API using Chart.js",
    category: "Developer Tools",
    tags: ["charts", "graphs", "visualization", "images", "chartjs"],
  },
  {
    name: "radar",
    displayName: "Radar",
    description: "Location data platform for geofencing and location-based features",
    category: "Developer Tools",
    tags: ["geolocation", "geofencing", "location", "maps", "tracking"],
  },
  {
    name: "raindrop",
    displayName: "Raindrop.io",
    description: "Bookmark manager for saving and organizing web content",
    category: "Developer Tools",
    tags: ["bookmarks", "reading-list", "organization", "links", "collections"],
  },
  {
    name: "rawgvideogamesdatabase",
    displayName: "RAWG Video Games Database",
    description: "Largest video game database and discovery service API",
    category: "Developer Tools",
    tags: ["games", "video-games", "database", "discovery", "metadata"],
  },
  {
    name: "rollbar",
    displayName: "Rollbar",
    description: "Real-time error tracking and debugging for software teams",
    category: "Developer Tools",
    tags: ["error-tracking", "debugging", "monitoring", "alerts", "logging"],
  },
  {
    name: "rootly",
    displayName: "Rootly",
    description: "Incident management and on-call alerting platform",
    category: "Developer Tools",
    tags: ["incident-management", "on-call", "alerts", "devops", "reliability"],
  },
  {
    name: "rundeck",
    displayName: "Rundeck",
    description: "Operations automation and runbook management platform",
    category: "Developer Tools",
    tags: ["automation", "runbooks", "operations", "devops", "scheduling"],
  },
  {
    name: "screenshotone",
    displayName: "ScreenshotOne",
    description: "Website screenshot and PDF capture API service",
    category: "Developer Tools",
    tags: ["screenshot", "pdf", "capture", "api", "automation"],
  },
  {
    name: "split-in-batches",
    displayName: "Split In Batches",
    description: "Batch workflow splitter",
    category: "Developer Tools",
    tags: ["batches", "workflow", "automation"],
  },
  {
    name: "searxng",
    displayName: "SearXNG",
    description: "Privacy-respecting open-source metasearch engine",
    category: "Developer Tools",
    tags: ["search", "metasearch", "privacy", "open-source", "self-hosted"],
  },
  {
    name: "sifter",
    displayName: "Sifter",
    description: "Hosted bug tracking and issue management tool",
    category: "Developer Tools",
    tags: ["bug-tracking", "issues", "project-management", "development", "qa"],
  },
  {
    name: "smol-machines",
    displayName: "smol machines",
    description: "Portable microVM runtime — smolvm HTTP API lifecycle",
    category: "Developer Tools",
    tags: ["microvm", "smolvm", "infrastructure", "runtime"],
  },
  {
    name: "simplelocalize",
    displayName: "SimpleLocalize",
    description: "Translation management and app localization platform",
    category: "Developer Tools",
    tags: ["localization", "translation", "i18n", "l10n", "multilingual"],
  },
  {
    name: "sonarqube",
    displayName: "SonarQube",
    description: "Code quality, security, and static analysis platform",
    category: "Developer Tools",
    tags: ["code-quality", "sast", "devops"],
  },
  {
    name: "sse-trigger",
    displayName: "SseTrigger",
    description: "SSE workflow trigger",
    category: "Developer Tools",
    tags: ["sse", "triggers", "workflows", "events"],
  },
  {
    name: "stackexchange",
    displayName: "Stack Exchange",
    description: "Q&A search across Stack Overflow and Stack Exchange sites (questions, answers, users, tags)",
    category: "Developer Tools",
    tags: ["q&a", "stackoverflow", "questions", "answers", "community", "api"],
  },
  {
    name: "starton",
    displayName: "Starton",
    description: "Blockchain infrastructure API for deploying and interacting with smart contracts",
    category: "Developer Tools",
    tags: ["blockchain", "smart contracts", "web3", "api", "infrastructure"],
  },
  {
    name: "stop-and-error",
    displayName: "StopAndError",
    description: "Workflow error handler",
    category: "Developer Tools",
    tags: ["workflow", "error-handler", "development"],
  },
  {
    name: "stoplight",
    displayName: "Stoplight",
    description: "API design and documentation platform",
    category: "Developer Tools",
    tags: ["api", "openapi", "documentation", "design"],
  },
  {
    name: "steel-dev",
    displayName: "Steel Dev",
    description: "Browser automation platform and cloud browser sessions API",
    category: "Developer Tools",
    tags: ["browser", "automation", "sessions"],
  },
  {
    name: "strapi",
    displayName: "Strapi",
    description: "Open-source headless CMS and content API platform",
    category: "Developer Tools",
    tags: ["cms", "headless", "open-source", "api", "content"],
  },
  {
    name: "taiga",
    displayName: "Taiga",
    description: "Open-source agile project management platform for cross-functional teams",
    category: "Developer Tools",
    tags: ["project management", "agile", "scrum", "kanban", "open source"],
  },
  {
    name: "testim",
    displayName: "Testim",
    description: "AI-powered test automation platform",
    category: "Developer Tools",
    tags: ["testing", "qa", "automation"],
  },
  {
    name: "testmonitor",
    displayName: "TestMonitor",
    description: "Test management tool for organizing, running, and reporting on software tests",
    category: "Developer Tools",
    tags: ["testing", "test management", "qa", "reporting", "software quality"],
  },
  {
    name: "testerarmy",
    displayName: "TesterArmy",
    description: "Agent-first QA automation",
    category: "Developer Tools",
    tags: ["qa", "testing", "automation"],
  },
  {
    name: "textkit",
    displayName: "TextKit",
    description: "Text processing and manipulation API for formatting and transforming text",
    category: "Developer Tools",
    tags: ["text processing", "formatting", "api", "utilities", "content"],
  },
  {
    name: "tierion",
    displayName: "Tierion",
    description: "Blockchain-based data anchoring and verification platform",
    category: "Developer Tools",
    tags: ["blockchain", "data anchoring", "verification", "proof", "decentralized"],
  },
  {
    name: "tinyurl",
    displayName: "TinyURL",
    description: "URL shortening service for creating and managing shortened links",
    category: "Developer Tools",
    tags: ["url shortener", "links", "redirect", "analytics", "api"],
  },
  {
    name: "tomtom",
    displayName: "TomTom",
    description: "Maps platform for geocoding, POI search, and routing",
    category: "Developer Tools",
    tags: ["maps", "geocoding", "routing", "navigation", "location"],
  },
  {
    name: "trackjs",
    displayName: "TrackJS",
    description: "JavaScript error tracking and monitoring platform",
    category: "Developer Tools",
    tags: ["monitoring", "errors", "error-tracking", "javascript", "frontend"],
  },
  {
    name: "transifex",
    displayName: "Transifex",
    description: "Localization and translation management platform for software and content",
    category: "Developer Tools",
    tags: ["localization", "translation", "i18n", "l10n", "content"],
  },
  {
    name: "trigger-dev-api-platform",
    displayName: "Trigger.dev API Platform",
    description: "Background jobs, workflows, and task run management",
    category: "Developer Tools",
    tags: ["background-jobs", "workflows", "trigger-dev", "automation"],
  },
  {
    name: "travisci",
    displayName: "Travis CI",
    description: "Continuous integration and delivery platform for testing and deploying software",
    category: "Developer Tools",
    tags: ["ci/cd", "continuous integration", "testing", "deployment", "devops"],
  },
  {
    name: "trigger-dev",
    displayName: "Trigger.dev",
    description: "Background job platform",
    category: "Developer Tools",
    tags: ["background-jobs", "workflows", "trigger-dev", "automation"],
  },
  {
    name: "tuskr",
    displayName: "Tuskr",
    description: "Test case management and QA platform",
    category: "Developer Tools",
    tags: ["testing", "qa", "test-management"],
  },
  {
    name: "upstash-api-platform",
    displayName: "Upstash API Platform",
    description: "Upstash Developer API — teams, vector indices, and audit logs",
    category: "Developer Tools",
    tags: ["serverless", "platform", "management-api", "qstash", "vector", "teams"],
  },
  {
    name: "uptimetoolbox",
    displayName: "Uptime Toolbox",
    description: "Website uptime and performance monitoring",
    category: "Developer Tools",
    tags: ["monitoring", "uptime", "performance"],
  },
  {
    name: "workato-api-platform",
    displayName: "Workato API Platform",
    description: "Customer runtime API for items, events, and search",
    category: "Developer Tools",
    tags: ["workato", "api-platform", "integration"],
  },
  {
    name: "webhooks",
    displayName: "Webhooks",
    description: "Generic outbound HTTP webhook delivery with optional HMAC signing",
    category: "Developer Tools",
    tags: ["webhook", "outbound", "http", "integrations"],
  },
  {
    name: "xray",
    displayName: "Xray",
    description: "Test management platform for QA scans, events, and search",
    category: "Developer Tools",
    tags: ["testing", "test-management", "qa", "scans"],
  },
  {
    name: "windmill-api-platform",
    displayName: "Windmill API Platform",
    description: "Tenant-hosted Windmill runtime API integration",
    category: "Developer Tools",
    tags: ["api", "integration", "automation", "windmill"],
  },
  {
    name: "xata",
    displayName: "Xata",
    description: "Serverless database with search and analytics",
    category: "Developer Tools",
    tags: ["database", "search", "serverless"],
  },
  {
    name: "ybug",
    displayName: "Ybug",
    description: "Visual bug reporting and user feedback tool",
    category: "Developer Tools",
    tags: ["bug-reporting", "feedback", "testing"],
  },
  {
    name: "ycode",
    displayName: "Ycode",
    description: "No-code website builder with CMS",
    category: "Developer Tools",
    tags: ["no-code", "website", "cms"],
  },
  {
    name: "yourls",
    displayName: "YOURLS",
    description: "Self-hosted URL shortener and link management",
    category: "Developer Tools",
    tags: ["url-shortener", "links", "self-hosted"],
  },
  {
    name: "zabbix",
    displayName: "Zabbix",
    description: "Enterprise network and infrastructure monitoring",
    category: "Developer Tools",
    tags: ["monitoring", "infrastructure", "network"],
  },
  {
    name: "zapier-api-platform",
    displayName: "Zapier API Platform",
    description: "Zapier API Platform integration for items, events, and search",
    category: "Developer Tools",
    tags: ["zapier", "automation", "api-platform"],
  },
];
