import type { ConnectorMeta } from "../registry.js";

// Google Workspace
export const connectors: ConnectorMeta[] = [
  {
    name: "google",
    displayName: "Google",
    description: "Google OAuth and APIs",
    category: "Google Workspace",
    tags: ["google", "auth"],
  },
  {
    name: "googledrive",
    displayName: "Google Drive",
    description: "File storage and sharing",
    category: "Google Workspace",
    tags: ["storage", "google"],
  },
  {
    name: "googledocs",
    displayName: "Google Docs",
    description: "Document creation and editing",
    category: "Google Workspace",
    tags: ["documents", "google"],
  },
  {
    name: "googlesheets",
    displayName: "Google Sheets",
    description: "Spreadsheets and data",
    category: "Google Workspace",
    tags: ["spreadsheets", "google"],
  },
  {
    name: "googlecalendar",
    displayName: "Google Calendar",
    description: "Calendar and events",
    category: "Google Workspace",
    tags: ["calendar", "google"],
  },
  {
    name: "googletasks",
    displayName: "Google Tasks",
    description: "Task management",
    category: "Google Workspace",
    tags: ["tasks", "google"],
  },
  {
    name: "googlecontacts",
    displayName: "Google Contacts",
    description: "Contact management",
    category: "Google Workspace",
    tags: ["contacts", "google"],
  },
  {
    name: "googlemaps",
    displayName: "Google Maps",
    description: "Maps, places, and directions",
    category: "Google Workspace",
    tags: ["maps", "google"],
  },
  {
    name: "googlebooks",
    displayName: "Google Books",
    description: "Book search, metadata, and library management",
    category: "Google Workspace",
    tags: ["google", "books", "search", "library"],
  },
  {
    name: "googlebusinessprofile",
    displayName: "Google Business Profile",
    description: "Business listings and local search management",
    category: "Google Workspace",
    tags: ["google", "business", "local", "listings"],
  },
  {
    name: "googlechat",
    displayName: "Google Chat",
    description: "Team messaging and collaboration",
    category: "Google Workspace",
    tags: ["google", "chat", "messaging", "collaboration"],
  },
  {
    name: "googleforms",
    displayName: "Google Forms",
    description: "Form creation and response collection",
    category: "Google Workspace",
    tags: ["google", "forms", "surveys", "responses"],
  },
  {
    name: "googlephotos",
    displayName: "Google Photos",
    description: "Photo and video library management",
    category: "Google Workspace",
    tags: ["google", "photos", "media", "albums"],
  },
  {
    name: "googleslides",
    displayName: "Google Slides",
    description: "Presentation creation and editing",
    category: "Google Workspace",
    tags: ["google", "presentations", "slides"],
  },
  {
    name: "googletables",
    displayName: "Google Tables",
    description: "Structured data and workflow automation",
    category: "Google Workspace",
    tags: ["google", "tables", "data", "workflows"],
  },
  {
    name: "googletranslate",
    displayName: "Google Translate",
    description: "Language translation and detection",
    category: "Google Workspace",
    tags: ["google", "translation", "languages"],
  },
];
