import type { ConnectorMeta } from "../registry.js";

// Infrastructure
export const connectors: ConnectorMeta[] = [
  {
    name: "kafka",
    displayName: "Apache Kafka",
    description: "Distributed event streaming platform",
    category: "Infrastructure",
    tags: ["streaming", "messaging", "events", "distributed"],
  },
  {
    name: "ldap",
    displayName: "LDAP",
    description: "Lightweight Directory Access Protocol for directory services",
    category: "Infrastructure",
    tags: ["directory", "authentication", "ldap", "identity"],
  },
  {
    name: "microsoftazuremonitor",
    displayName: "Microsoft Azure Monitor",
    description: "Azure cloud monitoring, metrics, and diagnostics",
    category: "Infrastructure",
    tags: ["azure", "monitoring", "metrics", "cloud", "microsoft"],
  },
  {
    name: "mist",
    displayName: "Mist",
    description: "Juniper Mist AI-driven wireless network management",
    category: "Infrastructure",
    tags: ["wifi", "networking", "juniper", "ai"],
  },
  {
    name: "mxtoolbox",
    displayName: "MXToolbox",
    description: "DNS, email, and network diagnostic tools",
    category: "Infrastructure",
    tags: ["dns", "email", "diagnostics", "network", "mx"],
  },
  {
    name: "pinata",
    displayName: "Pinata",
    description: "IPFS file storage and pinning service for Web3",
    category: "Infrastructure",
    tags: ["ipfs", "web3", "storage", "pinning", "decentralized"],
  },
  {
    name: "pulsetic",
    displayName: "Pulsetic",
    description: "Website uptime monitoring and status page service",
    category: "Infrastructure",
    tags: ["monitoring", "uptime", "status", "alerts", "website"],
  },
  {
    name: "rabbitmq",
    displayName: "RabbitMQ",
    description: "Open-source message broker for reliable asynchronous messaging",
    category: "Infrastructure",
    tags: ["message-queue", "messaging", "amqp", "async", "broker"],
  },
  {
    name: "runpod",
    displayName: "RunPod",
    description: "Cloud GPU infrastructure for AI and machine learning workloads",
    category: "Infrastructure",
    tags: ["gpu", "cloud", "ai", "ml", "compute"],
  },
  {
    name: "s3",
    displayName: "Amazon S3",
    description: "AWS Simple Storage Service for scalable object storage",
    category: "Infrastructure",
    tags: ["storage", "aws", "cloud", "object-storage", "files"],
  },
  {
    name: "vercel-blob",
    displayName: "Vercel Blob",
    description: "Blob storage platform",
    category: "Infrastructure",
    tags: ["blob", "storage", "vercel"],
  },
  {
    name: "spike",
    displayName: "Spike",
    description: "Incident management and on-call alerting platform",
    category: "Infrastructure",
    tags: ["incident management", "alerts", "on-call", "monitoring", "devops"],
  },
  {
    name: "statuspage",
    displayName: "Statuspage",
    description: "Atlassian Statuspage incident and status page management",
    category: "Infrastructure",
    tags: ["status", "incidents", "monitoring", "atlassian", "devops"],
  },
  {
    name: "statuscake",
    displayName: "StatusCake",
    description: "Website uptime monitoring and performance testing platform",
    category: "Infrastructure",
    tags: ["monitoring", "uptime", "performance", "alerts", "website"],
  },
  {
    name: "terraform-cloud",
    displayName: "Terraform Cloud",
    description: "HashiCorp Terraform Cloud infrastructure-as-code platform",
    category: "Infrastructure",
    tags: ["terraform", "hashicorp", "iac", "devops", "infrastructure"],
  },
  {
    name: "thousandeyes",
    displayName: "ThousandEyes",
    description: "Network monitoring platform",
    category: "Infrastructure",
    tags: ["monitoring", "network", "observability", "synthetic", "path-visibility"],
  },
  {
    name: "turbot-pipes",
    displayName: "Turbot Pipes",
    description: "Cloud intelligence platform for SQL queries across cloud APIs",
    category: "Infrastructure",
    tags: ["cloud", "intelligence", "steampipe", "sql", "turbot"],
  },
  {
    name: "zibra-labs",
    displayName: "Zibra Labs",
    description: "Quant backtesting HPC",
    category: "Infrastructure",
    tags: ["quant", "backtesting", "hpc", "datasets", "finance"],
  },
  {
    name: "zerotier",
    displayName: "ZeroTier",
    description: "ZeroTier Central SDN networking — virtual networks, members, and organizations",
    category: "Infrastructure",
    tags: ["networking", "vpn", "sdn", "zerotier"],
  },
  {
    name: "ssh",
    displayName: "SSH.com",
    description: "SSH automation and sessions API",
    category: "Infrastructure",
    tags: ["ssh", "sessions", "security", "privx"],
  },
  {
    name: "surtrdefensesystems",
    displayName: "Surtr Defense Systems",
    description: "Counter-UAS operating system: sensors, threat fusion, situation picture, and engagements",
    category: "Infrastructure",
    tags: ["counter-uas", "defense", "sensors", "threat-detection", "security"],
  },
  {
    name: "tyk",
    displayName: "Tyk",
    description: "API gateway platform",
    category: "Infrastructure",
    tags: ["api-gateway", "api-management", "tyk"],
  },
  {
    name: "upcloud",
    displayName: "UpCloud",
    description: "European cloud infrastructure for servers, storage, and networking",
    category: "Infrastructure",
    tags: ["cloud", "vps", "servers", "storage", "network"],
  },
  {
    name: "updown-io",
    displayName: "updown.io",
    description: "Simple and inexpensive website uptime monitoring",
    category: "Infrastructure",
    tags: ["monitoring", "uptime", "status", "alerts", "website"],
  },
  {
    name: "uploadcare",
    displayName: "Uploadcare",
    description: "CDN and media file storage with upload, delivery, and transformation APIs",
    category: "Infrastructure",
    tags: ["cdn", "media", "storage", "files", "upload"],
  },
  {
    name: "vercel-edge-config",
    displayName: "Vercel Edge Config",
    description: "Edge config platform",
    category: "Infrastructure",
    tags: ["edge", "config", "vercel", "feature-flags"],
  },
  {
    name: "voxel-energy",
    displayName: "Voxel Energy",
    description: "Off-grid data center power / sites, capacity, reservations",
    category: "Infrastructure",
    tags: ["energy", "data-center", "infrastructure", "gpu", "off-grid"],
  },
  {
    name: "whatsapp-cloud-api",
    displayName: "WhatsApp Cloud API",
    description: "Third-party WhatsApp Cloud API (api.whatsappcloudapi.com) for items, events, and search — not Meta Business Cloud",
    category: "Infrastructure",
    tags: ["messaging", "whatsapp", "api", "infrastructure"],
  },
];
