import type { ConnectorMeta } from "../registry.js";

// Marketing & Sales
export const connectors: ConnectorMeta[] = [
  {
    name: "instabot",
    displayName: "Instabot",
    description: "Chatbot and conversational marketing platform",
    category: "Marketing & Sales",
    tags: ["chatbot", "marketing", "automation"],
  },
  {
    name: "iterable",
    displayName: "Iterable",
    description: "Cross-channel marketing automation platform",
    category: "Marketing & Sales",
    tags: ["marketing", "email", "automation", "cross-channel"],
  },
  {
    name: "keap",
    displayName: "Keap",
    description: "CRM, sales, and marketing automation for small business",
    category: "Marketing & Sales",
    tags: ["crm", "marketing", "automation", "small-business"],
  },
  {
    name: "lagrowthmachine",
    displayName: "La Growth Machine",
    description: "Multi-channel sales automation and outreach",
    category: "Marketing & Sales",
    tags: ["sales", "outreach", "automation", "multi-channel"],
  },
  {
    name: "landbot",
    displayName: "Landbot",
    description: "No-code chatbot builder for websites and messaging",
    category: "Marketing & Sales",
    tags: ["chatbot", "no-code", "messaging", "lead-generation"],
  },
  {
    name: "laposta",
    displayName: "Laposta",
    description: "Email marketing and newsletter platform",
    category: "Marketing & Sales",
    tags: ["email", "newsletter", "marketing"],
  },
  {
    name: "leadboxer",
    displayName: "LeadBoxer",
    description: "Lead identification and website visitor tracking",
    category: "Marketing & Sales",
    tags: ["leads", "tracking", "visitor-identification", "b2b"],
  },
  {
    name: "leadpops",
    displayName: "LeadPops",
    description: "Lead generation for mortgage and real estate professionals",
    category: "Marketing & Sales",
    tags: ["leads", "real-estate", "mortgage", "landing-pages"],
  },
  {
    name: "lemlist",
    displayName: "Lemlist",
    description: "Cold email outreach and sales automation",
    category: "Marketing & Sales",
    tags: ["email", "outreach", "sales", "automation"],
  },
  {
    name: "limego",
    displayName: "LimeGo",
    description: "B2B sales intelligence and prospecting platform",
    category: "Marketing & Sales",
    tags: ["sales", "b2b", "prospecting", "intelligence"],
  },
  {
    name: "lonescale",
    displayName: "LoneScale",
    description: "Real-time buying signal detection for sales teams",
    category: "Marketing & Sales",
    tags: ["sales", "signals", "intent", "b2b"],
  },
  {
    name: "mailcheck",
    displayName: "Mailcheck",
    description: "Email verification and validation service",
    category: "Marketing & Sales",
    tags: ["email", "verification", "validation"],
  },
  {
    name: "mailerlite",
    displayName: "MailerLite",
    description: "Email marketing and automation platform",
    category: "Marketing & Sales",
    tags: ["email", "marketing", "automation", "newsletters"],
  },
  {
    name: "mailify",
    displayName: "Mailify",
    description: "Email and SMS marketing campaign platform",
    category: "Marketing & Sales",
    tags: ["email", "sms", "marketing", "campaigns"],
  },
  {
    name: "mailmodo",
    displayName: "Mailmodo",
    description: "Interactive email marketing with AMP emails",
    category: "Marketing & Sales",
    tags: ["email", "marketing", "amp", "interactive"],
  },
  {
    name: "marcomrobot",
    displayName: "Marcom Robot",
    description: "Marketing content compliance and brand management",
    category: "Marketing & Sales",
    tags: ["compliance", "brand", "content", "marketing"],
  },
  {
    name: "marketingmasterio",
    displayName: "Marketing Master IO",
    description: "All-in-one marketing automation platform",
    category: "Marketing & Sales",
    tags: ["marketing", "automation", "all-in-one"],
  },
  {
    name: "mautic",
    displayName: "Mautic",
    description: "Open-source marketing automation platform",
    category: "Marketing & Sales",
    tags: ["marketing", "automation", "open-source", "campaigns"],
  },
  {
    name: "mav",
    displayName: "Mav",
    description: "AI-powered SMS assistant for lead engagement",
    category: "Marketing & Sales",
    tags: ["ai", "sms", "leads", "engagement"],
  },
  {
    name: "maverick",
    displayName: "Maverick",
    description: "AI-generated personalized video for e-commerce",
    category: "Marketing & Sales",
    tags: ["ai", "video", "personalization", "ecommerce"],
  },
  {
    name: "microsoftdynamicscrm",
    displayName: "Microsoft Dynamics CRM",
    description: "Customer relationship management and sales automation",
    category: "Marketing & Sales",
    tags: ["crm", "sales", "microsoft", "dynamics"],
  },
  {
    name: "monicacrm",
    displayName: "Monica CRM",
    description: "Personal relationship management and CRM",
    category: "Marketing & Sales",
    tags: ["crm", "contacts", "relationships", "personal"],
  },
  {
    name: "moonmail",
    displayName: "MoonMail",
    description: "Email marketing and campaign automation",
    category: "Marketing & Sales",
    tags: ["email", "marketing", "campaigns", "automation"],
  },
  {
    name: "myphoner",
    displayName: "Myphoner",
    description: "Lead tracking and cold calling CRM",
    category: "Marketing & Sales",
    tags: ["calling", "leads", "crm", "sales"],
  },
  {
    name: "omeda",
    displayName: "Omeda",
    description: "Audience management and marketing automation for media companies",
    category: "Marketing & Sales",
    tags: ["audience", "marketing", "automation", "media", "crm"],
  },
  {
    name: "omniconvert",
    displayName: "Omniconvert",
    description: "Conversion rate optimization and A/B testing platform",
    category: "Marketing & Sales",
    tags: ["cro", "ab-testing", "optimization", "conversion", "analytics"],
  },
  {
    name: "orbit",
    displayName: "Orbit",
    description: "Community growth and developer relations management platform",
    category: "Marketing & Sales",
    tags: ["community", "devrel", "developer-relations", "growth", "analytics"],
  },
  {
    name: "ortto",
    displayName: "Ortto",
    description: "Customer data platform and marketing automation tool",
    category: "Marketing & Sales",
    tags: ["cdp", "marketing", "automation", "analytics", "email"],
  },
  {
    name: "persio",
    displayName: "Persio",
    description: "Customer engagement and push notification platform",
    category: "Marketing & Sales",
    tags: ["push-notifications", "engagement", "mobile", "marketing", "notifications"],
  },
  {
    name: "platformly",
    displayName: "Platformly",
    description: "Business intelligence and marketing automation platform",
    category: "Marketing & Sales",
    tags: ["marketing", "automation", "analytics", "crm", "email"],
  },
  {
    name: "prospeai",
    displayName: "Prospe AI",
    description: "AI-powered sales prospecting and lead enrichment platform",
    category: "Marketing & Sales",
    tags: ["sales", "prospecting", "leads", "enrichment", "ai"],
  },
  {
    name: "qualaroo",
    displayName: "Qualaroo",
    description: "User feedback and survey platform for websites and apps",
    category: "Marketing & Sales",
    tags: ["surveys", "feedback", "user-research", "analytics", "ux"],
  },
  {
    name: "quentn",
    displayName: "Quentn",
    description: "Marketing automation and CRM platform for email and sales funnels",
    category: "Marketing & Sales",
    tags: ["marketing-automation", "crm", "email", "funnels", "sales"],
  },
  {
    name: "raventools",
    displayName: "Raven Tools",
    description: "SEO and marketing reporting platform with rank tracking",
    category: "Marketing & Sales",
    tags: ["seo", "marketing", "rank-tracking", "reporting", "analytics"],
  },
  {
    name: "rdstationcrm",
    displayName: "RD Station CRM",
    description: "Brazilian CRM platform for managing leads and sales pipelines",
    category: "Marketing & Sales",
    tags: ["crm", "leads", "sales", "pipeline", "brazil"],
  },
  {
    name: "relinkurlshortener",
    displayName: "Relink URL Shortener",
    description: "URL shortening and link management service with analytics",
    category: "Marketing & Sales",
    tags: ["url-shortener", "links", "analytics", "tracking", "redirects"],
  },
  {
    name: "reply",
    displayName: "Reply",
    description: "Sales engagement platform for automating multi-channel outreach",
    category: "Marketing & Sales",
    tags: ["sales-engagement", "outreach", "email", "automation", "sequences"],
  },
  {
    name: "replyio",
    displayName: "Reply.io",
    description: "AI-powered sales engagement and outreach automation platform",
    category: "Marketing & Sales",
    tags: ["sales-engagement", "email-automation", "outreach", "ai", "sequences"],
  },
  {
    name: "reversecontact",
    displayName: "Reverse Contact",
    description: "Email to LinkedIn profile enrichment and reverse contact lookup",
    category: "Marketing & Sales",
    tags: ["enrichment", "linkedin", "email-lookup", "data", "prospecting"],
  },
  {
    name: "rewardful",
    displayName: "Rewardful",
    description: "Affiliate and referral tracking program for SaaS businesses",
    category: "Marketing & Sales",
    tags: ["affiliate", "referrals", "tracking", "saas", "partnerships"],
  },
  {
    name: "salesmaa",
    displayName: "Salesmaa",
    description: "AI-powered sales automation and outreach platform",
    category: "Marketing & Sales",
    tags: ["sales", "ai", "automation", "outreach", "crm"],
  },
  {
    name: "salesmate",
    displayName: "Salesmate",
    description: "CRM and sales automation software for growing businesses",
    category: "Marketing & Sales",
    tags: ["crm", "sales", "automation", "pipeline", "contacts"],
  },
  {
    name: "salesmsg",
    displayName: "Salesmsg",
    description: "Business text messaging and SMS marketing platform",
    category: "Marketing & Sales",
    tags: ["sms", "messaging", "sales", "marketing", "texting"],
  },
  {
    name: "salesrocks",
    displayName: "SalesRocks",
    description: "B2B sales intelligence and prospecting data platform",
    category: "Marketing & Sales",
    tags: ["sales", "b2b", "prospecting", "intelligence", "leads"],
  },
  {
    name: "salessimplify",
    displayName: "SalesSimplify",
    description: "All-in-one CRM and sales management platform",
    category: "Marketing & Sales",
    tags: ["crm", "sales", "pipeline", "contacts", "deals"],
  },
  {
    name: "seamlessai",
    displayName: "Seamless.AI",
    description: "AI-powered B2B sales prospecting and contact data platform",
    category: "Marketing & Sales",
    tags: ["sales", "ai", "b2b", "prospecting", "contacts"],
  },
  {
    name: "sendy",
    displayName: "Sendy",
    description: "Self-hosted email newsletter platform using Amazon SES",
    category: "Marketing & Sales",
    tags: ["email", "newsletter", "self-hosted", "aws-ses", "marketing"],
  },
  {
    name: "shortio",
    displayName: "Short.io",
    description: "Custom domain URL shortener and link management platform",
    category: "Marketing & Sales",
    tags: ["url-shortener", "links", "custom-domain", "analytics", "branding"],
  },
  {
    name: "sierrainteractive",
    displayName: "Sierra Interactive",
    description: "Real estate CRM and lead generation platform",
    category: "Marketing & Sales",
    tags: ["real-estate", "crm", "leads", "marketing", "sales"],
  },
  {
    name: "simplero",
    displayName: "Simplero",
    description: "All-in-one platform for online courses, memberships, and marketing",
    category: "Marketing & Sales",
    tags: ["courses", "memberships", "marketing", "email", "ecommerce"],
  },
  {
    name: "simpletexting",
    displayName: "SimpleTexting",
    description: "SMS marketing and text messaging platform for businesses",
    category: "Marketing & Sales",
    tags: ["sms", "text messaging", "marketing", "campaigns", "mobile"],
  },
  {
    name: "smaily",
    displayName: "Smaily",
    description: "Email marketing automation and newsletter platform",
    category: "Marketing & Sales",
    tags: ["email marketing", "newsletter", "automation", "campaigns"],
  },
  {
    name: "smartreach",
    displayName: "SmartReach",
    description: "Sales engagement and email outreach automation platform",
    category: "Marketing & Sales",
    tags: ["sales", "email outreach", "automation", "sequences", "prospecting"],
  },
  {
    name: "sprig",
    displayName: "Sprig",
    description: "Continuous in-product user research and survey platform",
    category: "Marketing & Sales",
    tags: ["surveys", "feedback", "user-research", "product", "ux"],
  },
  {
    name: "surveysparrow",
    displayName: "SurveySparrow",
    description: "Conversational survey and feedback management platform",
    category: "Marketing & Sales",
    tags: ["surveys", "feedback", "conversational", "nps", "customer experience"],
  },
  {
    name: "survicate",
    displayName: "Survicate",
    description: "Customer feedback and survey platform for product and marketing teams",
    category: "Marketing & Sales",
    tags: ["surveys", "feedback", "customer experience", "nps", "product"],
  },
  {
    name: "syncly",
    displayName: "Syncly",
    description: "Customer feedback intelligence platform for analyzing and centralizing feedback",
    category: "Marketing & Sales",
    tags: ["feedback", "customer intelligence", "analytics", "crm", "insights"],
  },
  {
    name: "tapfiliate",
    displayName: "Tapfiliate",
    description: "Affiliate tracking and management platform for running affiliate programs",
    category: "Marketing & Sales",
    tags: ["affiliate", "tracking", "referral", "marketing", "commissions"],
  },
  {
    name: "teamgate",
    displayName: "Teamgate",
    description: "Sales CRM with pipeline management and analytics for growing sales teams",
    category: "Marketing & Sales",
    tags: ["crm", "sales", "pipeline", "analytics", "leads"],
  },
  {
    name: "thankster",
    displayName: "Thankster",
    description: "Handwritten card automation service for sending personalized thank-you notes",
    category: "Marketing & Sales",
    tags: ["handwritten cards", "direct mail", "personalization", "thank you", "gifting"],
  },
  {
    name: "totango",
    displayName: "Totango",
    description: "Customer success platform for managing customer health and reducing churn",
    category: "Marketing & Sales",
    tags: ["customer success", "churn", "health score", "crm", "saas"],
  },
  {
    name: "unbounce",
    displayName: "Unbounce",
    description: "Landing page builder and conversion optimization",
    category: "Marketing & Sales",
    tags: ["landing-pages", "conversion", "marketing"],
  },
  {
    name: "uplead",
    displayName: "UpLead",
    description: "B2B lead generation and contact data platform",
    category: "Marketing & Sales",
    tags: ["leads", "b2b", "prospecting"],
  },
  {
    name: "verifalia",
    displayName: "Verifalia",
    description: "Email address validation and verification service",
    category: "Marketing & Sales",
    tags: ["email", "validation", "verification"],
  },
  {
    name: "whatconverts",
    displayName: "WhatConverts",
    description: "Lead tracking and marketing attribution platform",
    category: "Marketing & Sales",
    tags: ["leads", "tracking", "attribution"],
  },
  {
    name: "woodpeckerco",
    displayName: "Woodpecker.co",
    description: "Cold email outreach and follow-up automation",
    category: "Marketing & Sales",
    tags: ["email", "outreach", "sales"],
  },
  {
    name: "zerobounce",
    displayName: "ZeroBounce",
    description: "Email validation, verification, and deliverability platform",
    category: "Marketing & Sales",
    tags: ["email", "validation", "verification", "deliverability"],
  },
];
