import type { ConnectorMeta } from "../registry.js";

// Security & Compliance
export const connectors: ConnectorMeta[] = [
  {
    name: "irisdfir",
    displayName: "IRIS DFIR",
    description: "Digital forensics and incident response platform",
    category: "Security & Compliance",
    tags: ["dfir", "forensics", "incident-response", "security"],
  },
  {
    name: "knowbe4",
    displayName: "KnowBe4",
    description: "Security awareness training and phishing simulation",
    category: "Security & Compliance",
    tags: ["security", "training", "phishing", "awareness"],
  },
  {
    name: "loginradius",
    displayName: "LoginRadius",
    description: "Customer identity and access management (CIAM)",
    category: "Security & Compliance",
    tags: ["identity", "authentication", "ciam", "sso"],
  },
  {
    name: "malcore",
    displayName: "Malcore",
    description: "Malware analysis and threat detection API",
    category: "Security & Compliance",
    tags: ["malware", "security", "threat-detection", "analysis"],
  },
  {
    name: "microsoftentraid",
    displayName: "Microsoft Entra ID",
    description: "Identity and access management (formerly Azure AD)",
    category: "Security & Compliance",
    tags: ["identity", "auth", "azure", "microsoft", "iam"],
  },
  {
    name: "microsoftentraidazureactivedirectory",
    displayName: "Microsoft Entra ID (Azure Active Directory)",
    description: "Azure Active Directory identity and directory services",
    category: "Security & Compliance",
    tags: ["identity", "directory", "azure-ad", "microsoft", "iam"],
  },
  {
    name: "microsoftgraphsecurity",
    displayName: "Microsoft Graph Security",
    description: "Unified security alerts, threats, and incidents via Microsoft Graph",
    category: "Security & Compliance",
    tags: ["security", "alerts", "threats", "microsoft", "graph"],
  },
  {
    name: "misp",
    displayName: "MISP",
    description: "Open-source threat intelligence and sharing platform",
    category: "Security & Compliance",
    tags: ["threat-intelligence", "ioc", "security", "sharing"],
  },
  {
    name: "nightfallai",
    displayName: "Nightfall AI",
    description: "AI-powered data loss prevention and sensitive data detection",
    category: "Security & Compliance",
    tags: ["dlp", "ai", "security", "data-loss-prevention", "compliance"],
  },
  {
    name: "opencti",
    displayName: "OpenCTI",
    description: "Open-source cyber threat intelligence platform",
    category: "Security & Compliance",
    tags: ["threat-intelligence", "security", "cti", "open-source", "cyber"],
  },
  {
    name: "qradar",
    displayName: "IBM QRadar",
    description: "IBM SIEM platform for security intelligence and threat detection",
    category: "Security & Compliance",
    tags: ["siem", "security", "threat-detection", "ibm", "analytics"],
  },
  {
    name: "qualys",
    displayName: "Qualys",
    description: "Cloud-based security and compliance platform with vulnerability management",
    category: "Security & Compliance",
    tags: ["vulnerability-management", "compliance", "security", "cloud", "scanning"],
  },
  {
    name: "rapid7insightvm",
    displayName: "Rapid7 InsightVM",
    description: "Vulnerability management and risk assessment platform",
    category: "Security & Compliance",
    tags: ["vulnerability-management", "risk", "security", "scanning", "compliance"],
  },
  {
    name: "recordedfuture",
    displayName: "Recorded Future",
    description: "Threat intelligence platform for real-time cybersecurity insights",
    category: "Security & Compliance",
    tags: ["threat-intelligence", "cybersecurity", "intelligence", "security", "risk"],
  },
  {
    name: "securityscorecard",
    displayName: "SecurityScorecard",
    description: "Cybersecurity risk ratings and supply chain security platform",
    category: "Security & Compliance",
    tags: ["security", "risk", "ratings", "compliance", "cyber"],
  },
  {
    name: "sekoia",
    displayName: "Sekoia",
    description: "Cyber threat intelligence and security operations platform",
    category: "Security & Compliance",
    tags: ["security", "threat-intelligence", "soc", "cyber", "detection"],
  },
  {
    name: "shuffler",
    displayName: "Shuffler",
    description: "Security automation and SOAR workflow orchestration platform",
    category: "Security & Compliance",
    tags: ["security", "soar", "automation", "workflow", "orchestration"],
  },
  {
    name: "sslmatecertspotterapi",
    displayName: "SSLMate CertSpotter API",
    description: "Certificate transparency monitoring and SSL certificate search API",
    category: "Security & Compliance",
    tags: ["ssl", "certificates", "security", "monitoring", "tls"],
  },
  {
    name: "the-hive-project",
    displayName: "TheHiveProject",
    description: "Security case platform for incident response and SOC workflows",
    category: "Security & Compliance",
    tags: ["security", "soc", "cases", "incident-response"],
  },
  {
    name: "thehive",
    displayName: "TheHive",
    description: "Security incident response platform for managing and investigating cyber threats",
    category: "Security & Compliance",
    tags: ["security", "incident response", "soc", "threat intelligence", "cybersecurity"],
  },
  {
    name: "thehive5",
    displayName: "TheHive 5",
    description: "Next-generation security operations platform for incident management and threat analysis",
    category: "Security & Compliance",
    tags: ["security", "incident response", "soc", "threat analysis", "cybersecurity"],
  },
  {
    name: "trellixepo",
    displayName: "Trellix EPO",
    description: "Enterprise security management platform for endpoint protection and threat response",
    category: "Security & Compliance",
    tags: ["endpoint security", "edr", "threat response", "enterprise", "cybersecurity"],
  },
  {
    name: "urlscanio",
    displayName: "urlscan.io",
    description: "Website scanning and threat analysis",
    category: "Security & Compliance",
    tags: ["security", "scanning", "threat-intelligence"],
  },
  {
    name: "virustotal",
    displayName: "VirusTotal",
    description: "File and URL malware scanning and threat intelligence",
    category: "Security & Compliance",
    tags: ["security", "malware", "threat-intelligence"],
  },
  {
    name: "zscalerzia",
    displayName: "Zscaler ZIA",
    description: "Cloud-native internet access and security gateway",
    category: "Security & Compliance",
    tags: ["security", "cloud", "gateway", "zscaler"],
  },
];
