import type { ConnectorMeta } from "../registry.js";

// Social Media
export const connectors: ConnectorMeta[] = [
  {
    name: "x",
    displayName: "X (Twitter)",
    description: "Posts, threads, and engagement",
    category: "Social Media",
    tags: ["social", "twitter"],
  },
  {
    name: "reddit",
    displayName: "Reddit",
    description: "Posts, comments, and subreddits",
    category: "Social Media",
    tags: ["social", "community"],
  },
  {
    name: "substack",
    displayName: "Substack",
    description: "Newsletter publishing",
    category: "Social Media",
    tags: ["newsletter", "writing"],
  },
  {
    name: "meta",
    displayName: "Meta",
    description: "Facebook and Instagram APIs",
    category: "Social Media",
    tags: ["social", "facebook", "instagram"],
  },
  {
    name: "snap",
    displayName: "Snapchat",
    description: "Snapchat marketing API",
    category: "Social Media",
    tags: ["social", "ads"],
  },
  {
    name: "tiktok",
    displayName: "TikTok",
    description: "TikTok content and ads",
    category: "Social Media",
    tags: ["social", "video"],
  },
  {
    name: "twitch",
    displayName: "Twitch",
    description: "Live streaming, channels, chat, and followers",
    category: "Social Media",
    tags: ["streaming", "live", "video"],
  },
  {
    name: "youtube",
    displayName: "YouTube",
    description: "Videos, channels, and analytics",
    category: "Social Media",
    tags: ["video", "google"],
  },
  {
    name: "pinterest",
    displayName: "Pinterest",
    description: "Pins, boards, and visual discovery",
    category: "Social Media",
    tags: ["social", "visual", "marketing"],
  },
  {
    name: "linkedin",
    displayName: "LinkedIn",
    description: "Professional network and marketing",
    category: "Social Media",
    tags: ["social", "professional", "b2b"],
  },
  {
    name: "spotify",
    displayName: "Spotify",
    description: "Music streaming and playlists",
    category: "Social Media",
    tags: ["music", "streaming", "playlists"],
  },
  {
    name: "medium",
    displayName: "Medium",
    description: "Publishing and blogging platform",
    category: "Social Media",
    tags: ["writing", "blogging", "publishing"],
  },
  {
    name: "producthunt",
    displayName: "Product Hunt",
    description: "Product launches and discovery",
    category: "Social Media",
    tags: ["products", "launches", "tech"],
  },
  {
    name: "giphy",
    displayName: "Giphy",
    description: "GIF search and sharing",
    category: "Social Media",
    tags: ["gifs", "media", "search"],
  },
  {
    name: "imgur",
    displayName: "Imgur",
    description: "Image hosting and sharing",
    category: "Social Media",
    tags: ["images", "hosting", "sharing"],
  },
  {
    name: "mastodon",
    displayName: "Mastodon",
    description: "Decentralized social network",
    category: "Social Media",
    tags: ["social", "fediverse", "decentralized"],
  },
  {
    name: "bluesky",
    displayName: "Bluesky",
    description: "AT Protocol social network - posts, threads, mentions",
    category: "Social Media",
    tags: ["social", "atproto", "decentralized"],
  },
  {
    name: "brandblast",
    displayName: "BrandBlast",
    description: "AI-powered social media content management",
    category: "Social Media",
    tags: ["social", "content", "ai"],
  },
  {
    name: "disqus",
    displayName: "Disqus",
    description: "Comment hosting and community engagement platform",
    category: "Social Media",
    tags: ["comments", "community", "engagement"],
  },
  {
    name: "foursquare",
    displayName: "Foursquare",
    description: "Location data and place discovery API",
    category: "Social Media",
    tags: ["location", "places", "discovery"],
  },
  {
    name: "ritekit",
    displayName: "RiteKit",
    description: "Social media hashtag suggestions and content optimization API",
    category: "Social Media",
    tags: ["hashtags", "social-media", "content", "optimization", "twitter"],
  },
  {
    name: "tumblr",
    displayName: "Tumblr",
    description: "Microblogging platform — blogs, posts, and social features",
    category: "Social Media",
    tags: ["social", "blogging", "microblog"],
  },
];
