#!/usr/bin/env bun
/**
 * Regenerate the typed @hasna/logs API client from the serve OpenAPI document.
 *
 *   bun scripts/generate-sdk-api.ts
 *
 * Output: src/sdk-api/client.ts (a dependency-free fetch client + interfaces),
 * generated by `@hasna/contracts` `generateSdkFromOpenApi`. Do not hand-edit
 * the generated file — change `src/server/cloud/openapi.ts` and rerun this.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { generateSdkFromOpenApi } from "@hasna/contracts/sdk";
import { PACKAGE_VERSION } from "../src/lib/package-meta.ts";
import { buildOpenApiDocument } from "../src/server/cloud/openapi.ts";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const spec = buildOpenApiDocument(PACKAGE_VERSION);
const generated = generateSdkFromOpenApi(spec, {
  className: "LogsClient",
  apiKeyHeader: "x-api-key",
});

const outDir = join(repoRoot, "src", "sdk-api");
mkdirSync(outDir, { recursive: true });
const header = [
  "// @generated from the @hasna/logs serve OpenAPI by scripts/generate-sdk-api.ts.",
  "// DO NOT EDIT. Regenerate: bun scripts/generate-sdk-api.ts",
  "",
  "",
].join("\n");
writeFileSync(join(outDir, "client.ts"), header + generated.code, "utf8");

console.log(
  `Generated LogsClient with ${generated.operations.length} operations -> src/sdk-api/client.ts`,
);
for (const warning of generated.warnings) console.warn(`  warning: ${warning}`);
