/**
 * Canonical PostgreSQL 17 catalog produced by the package-owned migrations.
 *
 * This manifest is intentionally independent of the migration ledger: re-running
 * an already-applied migration must still prove every column, PK/UNIQUE/CHECK/FK,
 * and package-owned index (including ordered keys and partial predicates).
 */
export type PostgresColumnManifestEntry = readonly [
  tableName: string,
  ordinalPosition: number,
  columnName: string,
  dataType: string,
  notNull: boolean,
  defaultExpression: string | null,
  identityKind: string,
  generatedKind: string,
  collationName: string | null,
];

export type PostgresConstraintManifestEntry = readonly [
  tableName: string,
  constraintName: string,
  constraintType: "p" | "u" | "c" | "f",
  definition: string,
  deferrable: boolean,
  initiallyDeferred: boolean,
  validated: boolean,
];

export type PostgresIndexManifestEntry = readonly [
  tableName: string,
  indexName: string,
  accessMethod: string,
  unique: boolean,
  valid: boolean,
  ready: boolean,
  live: boolean,
  definition: string,
  predicate: string | null,
];

function freezeEntries<T extends readonly unknown[]>(entries: readonly T[]): readonly T[] {
  for (const entry of entries) Object.freeze(entry);
  return Object.freeze(entries);
}

const COLUMNS: PostgresColumnManifestEntry[] = [
  ["account_events",1,"id","uuid",true,null,"","",null],
  ["account_events",2,"owner_ref","text",true,null,"","","pg_catalog.default"],
  ["account_events",3,"aggregate_kind","text",true,null,"","","pg_catalog.default"],
  ["account_events",4,"aggregate_id","uuid",true,null,"","",null],
  ["account_events",5,"aggregate_revision","bigint",true,null,"","",null],
  ["account_events",6,"actor_ref","text",true,null,"","","pg_catalog.default"],
  ["account_events",7,"reason_code","text",true,null,"","","pg_catalog.default"],
  ["account_events",8,"occurred_at","timestamp with time zone",true,null,"","",null],
  ["account_lanes",1,"id","uuid",true,null,"","",null],
  ["account_lanes",2,"owner_ref","text",true,null,"","","pg_catalog.default"],
  ["account_lanes",3,"entitlement_id","uuid",true,null,"","",null],
  ["account_lanes",4,"capacity_pool_id","uuid",true,null,"","",null],
  ["account_lanes",5,"access_transport","text",true,null,"","","pg_catalog.default"],
  ["account_lanes",6,"status","text",true,null,"","","pg_catalog.default"],
  ["account_lanes",7,"revision","bigint",true,null,"","",null],
  ["account_lanes",8,"created_at","timestamp with time zone",true,null,"","",null],
  ["account_lanes",9,"updated_at","timestamp with time zone",true,null,"","",null],
  ["account_lanes",10,"payload_json","text",true,null,"","","pg_catalog.default"],
  ["accounts_installation",1,"singleton","smallint",true,"1","","",null],
  ["accounts_installation",2,"deployment_mode","text",true,null,"","","pg_catalog.default"],
  ["accounts_installation",3,"identity_realm","text",true,null,"","","pg_catalog.default"],
  ["accounts_installation",4,"organization_ref","text",true,null,"","","pg_catalog.default"],
  ["accounts_installation",5,"schema_version","text",true,null,"","","pg_catalog.default"],
  ["accounts_installation",6,"build_digest","text",true,null,"","","pg_catalog.default"],
  ["accounts_installation",7,"configuration_attestation_digest","text",true,null,"","","pg_catalog.default"],
  ["accounts_installation",8,"catalog_incarnation","text",true,null,"","","pg_catalog.default"],
  ["accounts_installation",9,"recovery_frontier_sequence","bigint",true,null,"","",null],
  ["accounts_installation",10,"recovery_frontier_hash","text",true,null,"","","pg_catalog.default"],
  ["accounts_installation",11,"recovery_frontier_signature_digest","text",true,null,"","","pg_catalog.default"],
  ["accounts_installation",12,"database_frontier_sequence","bigint",true,null,"","",null],
  ["accounts_installation",13,"database_frontier_hash","text",true,null,"","","pg_catalog.default"],
  ["accounts_installation",14,"database_frontier_signature_digest","text",true,null,"","","pg_catalog.default"],
  ["accounts_installation",15,"recovery_hold","boolean",true,"true","","",null],
  ["accounts_installation",16,"created_at","timestamp with time zone",true,null,"","",null],
  ["accounts_installation",17,"updated_at","timestamp with time zone",true,null,"","",null],
  ["auth_capsules",1,"id","uuid",true,null,"","",null],
  ["auth_capsules",2,"owner_ref","text",true,null,"","","pg_catalog.default"],
  ["auth_capsules",3,"access_method_id","uuid",true,null,"","",null],
  ["auth_capsules",4,"capacity_pool_id","uuid",true,null,"","",null],
  ["auth_capsules",5,"placement_ref","uuid",true,null,"","",null],
  ["auth_capsules",6,"status","text",true,null,"","","pg_catalog.default"],
  ["auth_capsules",7,"auth_generation","bigint",true,null,"","",null],
  ["auth_capsules",8,"auth_state_revision","bigint",true,null,"","",null],
  ["auth_capsules",9,"revision","bigint",true,null,"","",null],
  ["auth_capsules",10,"created_at","timestamp with time zone",true,null,"","",null],
  ["auth_capsules",11,"updated_at","timestamp with time zone",true,null,"","",null],
  ["auth_capsules",12,"payload_json","text",true,null,"","","pg_catalog.default"],
  ["capability_use_consumptions",1,"owner_ref","text",true,null,"","","pg_catalog.default"],
  ["capability_use_consumptions",2,"consume_request_id","uuid",true,null,"","",null],
  ["capability_use_consumptions",3,"request_digest","text",true,null,"","","pg_catalog.default"],
  ["capability_use_consumptions",4,"capability_id","uuid",true,null,"","",null],
  ["capability_use_consumptions",5,"idempotency_key_digest","text",true,null,"","","pg_catalog.default"],
  ["capability_use_consumptions",6,"receipt_jcs_base64url","text",true,null,"","","pg_catalog.default"],
  ["capability_use_consumptions",7,"committed_at","timestamp with time zone",true,null,"","",null],
  ["capacity_domain_claims",1,"provider_key","text",true,null,"","","pg_catalog.default"],
  ["capacity_domain_claims",2,"capacity_domain_ref","text",true,null,"","","pg_catalog.default"],
  ["capacity_domain_claims",3,"serialization_key","text",true,null,"","","pg_catalog.default"],
  ["capacity_domain_claims",4,"owner_ref","text",true,null,"","","pg_catalog.default"],
  ["capacity_domain_claims",5,"capacity_pool_id","uuid",true,null,"","",null],
  ["capacity_domain_claims",6,"claimed_at","timestamp with time zone",true,null,"","",null],
  ["capacity_pools",1,"id","uuid",true,null,"","",null],
  ["capacity_pools",2,"owner_ref","text",true,null,"","","pg_catalog.default"],
  ["capacity_pools",3,"account_id","uuid",true,null,"","",null],
  ["capacity_pools",4,"provider_key","text",true,null,"","","pg_catalog.default"],
  ["capacity_pools",5,"capacity_domain_ref","text",true,null,"","","pg_catalog.default"],
  ["capacity_pools",6,"serialization_key","text",true,null,"","","pg_catalog.default"],
  ["capacity_pools",7,"status","text",true,null,"","","pg_catalog.default"],
  ["capacity_pools",8,"deny_state","text",true,null,"","","pg_catalog.default"],
  ["capacity_pools",9,"revision","bigint",true,null,"","",null],
  ["capacity_pools",10,"capacity_generation","bigint",true,null,"","",null],
  ["capacity_pools",11,"deny_generation","bigint",true,null,"","",null],
  ["capacity_pools",12,"created_at","timestamp with time zone",true,null,"","",null],
  ["capacity_pools",13,"updated_at","timestamp with time zone",true,null,"","",null],
  ["capacity_pools",14,"payload_json","text",true,null,"","","pg_catalog.default"],
  ["capsule_maintenance_grants",1,"grant_id","uuid",true,null,"","",null],
  ["capsule_maintenance_grants",2,"owner_ref","text",true,null,"","","pg_catalog.default"],
  ["capsule_maintenance_grants",3,"idempotency_key_digest","text",true,null,"","","pg_catalog.default"],
  ["capsule_maintenance_grants",4,"request_digest","text",true,null,"","","pg_catalog.default"],
  ["capsule_maintenance_grants",5,"reservation_key_digest","text",true,null,"","","pg_catalog.default"],
  ["capsule_maintenance_grants",6,"grant_digest","text",true,null,"","","pg_catalog.default"],
  ["capsule_maintenance_grants",7,"grant_jcs_base64url","text",true,null,"","","pg_catalog.default"],
  ["capsule_maintenance_grants",8,"expires_at","timestamp with time zone",true,null,"","",null],
  ["capsule_maintenance_grants",9,"state","text",true,null,"","","pg_catalog.default"],
  ["capsule_maintenance_grants",10,"created_at","timestamp with time zone",true,null,"","",null],
  ["capsule_maintenance_grants",11,"terminal_at","timestamp with time zone",false,null,"","",null],
  ["capsule_maintenance_uses",1,"grant_id","uuid",true,null,"","",null],
  ["capsule_maintenance_uses",2,"owner_ref","text",true,null,"","","pg_catalog.default"],
  ["capsule_maintenance_uses",3,"idempotency_key_digest","text",true,null,"","","pg_catalog.default"],
  ["capsule_maintenance_uses",4,"request_digest","text",true,null,"","","pg_catalog.default"],
  ["capsule_maintenance_uses",5,"maintenance_use_id","text",true,null,"","","pg_catalog.default"],
  ["capsule_maintenance_uses",6,"consume_receipt_digest","text",true,null,"","","pg_catalog.default"],
  ["capsule_maintenance_uses",7,"consume_receipt_jcs_base64url","text",true,null,"","","pg_catalog.default"],
  ["capsule_maintenance_uses",8,"committed_at","timestamp with time zone",true,null,"","",null],
  ["credential_binding_handles",1,"binding_id","uuid",true,null,"","",null],
  ["credential_binding_handles",2,"owner_ref","text",true,null,"","","pg_catalog.default"],
  ["credential_binding_handles",3,"opaque_handle","text",true,null,"","","pg_catalog.default"],
  ["credential_binding_handles",4,"issuer_ref","text",true,null,"","","pg_catalog.default"],
  ["credential_binding_handles",5,"audience","text",true,null,"","","pg_catalog.default"],
  ["credential_binding_handles",6,"catalog_incarnation","text",true,null,"","","pg_catalog.default"],
  ["credential_binding_handles",7,"backend_class","text",true,null,"","","pg_catalog.default"],
  ["credential_binding_handles",8,"audit_digest","text",true,null,"","","pg_catalog.default"],
  ["credential_binding_handles",9,"issued_at","timestamp with time zone",true,null,"","",null],
  ["credential_binding_handles",10,"expires_at","timestamp with time zone",false,null,"","",null],
  ["credential_bindings",1,"id","uuid",true,null,"","",null],
  ["credential_bindings",2,"owner_ref","text",true,null,"","","pg_catalog.default"],
  ["credential_bindings",3,"access_method_id","uuid",true,null,"","",null],
  ["credential_bindings",4,"capacity_pool_id","uuid",true,null,"","",null],
  ["credential_bindings",5,"auth_capsule_id","uuid",false,null,"","",null],
  ["credential_bindings",6,"credential_family_id","text",true,null,"","","pg_catalog.default"],
  ["credential_bindings",7,"resolver","text",true,null,"","","pg_catalog.default"],
  ["credential_bindings",8,"purpose","text",true,null,"","","pg_catalog.default"],
  ["credential_bindings",9,"status","text",true,null,"","","pg_catalog.default"],
  ["credential_bindings",10,"credential_generation","bigint",true,null,"","",null],
  ["credential_bindings",11,"auth_state_revision","bigint",false,null,"","",null],
  ["credential_bindings",12,"revision","bigint",true,null,"","",null],
  ["credential_bindings",13,"created_at","timestamp with time zone",true,null,"","",null],
  ["credential_bindings",14,"updated_at","timestamp with time zone",true,null,"","",null],
  ["credential_bindings",15,"payload_json","text",true,null,"","","pg_catalog.default"],
  ["credential_bindings",16,"terminal_kind","text",false,null,"","","pg_catalog.default"],
  ["credential_bindings",17,"credential_handle_audit_digest","text",false,null,"","","pg_catalog.default"],
  ["credential_bindings",18,"last_usable_credential_generation","bigint",false,null,"","",null],
  ["credential_bindings",19,"revocation_barrier_receipt_digest","text",false,null,"","","pg_catalog.default"],
  ["credential_bindings",20,"revoked_at","timestamp with time zone",false,null,"","",null],
  ["credential_family_claims",1,"credential_family_id","text",true,null,"","","pg_catalog.default"],
  ["credential_family_claims",2,"owner_ref","text",true,null,"","","pg_catalog.default"],
  ["credential_family_claims",3,"capacity_pool_id","uuid",true,null,"","",null],
  ["credential_family_claims",4,"purpose","text",true,null,"","","pg_catalog.default"],
  ["credential_family_claims",5,"resolver","text",true,null,"","","pg_catalog.default"],
  ["credential_family_claims",6,"claimed_at","timestamp with time zone",true,null,"","",null],
  ["credential_operations",1,"id","uuid",true,null,"","",null],
  ["credential_operations",2,"owner_ref","text",true,null,"","","pg_catalog.default"],
  ["credential_operations",3,"kind","text",true,null,"","","pg_catalog.default"],
  ["credential_operations",4,"source_binding_id","uuid",false,null,"","",null],
  ["credential_operations",5,"target_binding_id","uuid",false,null,"","",null],
  ["credential_operations",6,"credential_family_id","text",true,null,"","","pg_catalog.default"],
  ["credential_operations",7,"capacity_pool_id","uuid",true,null,"","",null],
  ["credential_operations",8,"serialization_key","text",true,null,"","","pg_catalog.default"],
  ["credential_operations",9,"expected_source_generation","bigint",true,null,"","",null],
  ["credential_operations",10,"expected_auth_state_revision","bigint",false,null,"","",null],
  ["credential_operations",11,"proposed_target_generation","bigint",true,null,"","",null],
  ["credential_operations",12,"proposed_auth_state_revision","bigint",false,null,"","",null],
  ["credential_operations",13,"state","text",true,null,"","","pg_catalog.default"],
  ["credential_operations",14,"idempotency_request_hash","text",true,null,"","","pg_catalog.default"],
  ["credential_operations",15,"barrier_receipt_digest","text",false,null,"","","pg_catalog.default"],
  ["credential_operations",16,"completion_receipt_digest","text",false,null,"","","pg_catalog.default"],
  ["credential_operations",17,"revision","bigint",true,null,"","",null],
  ["credential_operations",18,"created_at","timestamp with time zone",true,null,"","",null],
  ["credential_operations",19,"updated_at","timestamp with time zone",true,null,"","",null],
  ["entitlements",1,"id","uuid",true,null,"","",null],
  ["entitlements",2,"owner_ref","text",true,null,"","","pg_catalog.default"],
  ["entitlements",3,"account_id","uuid",true,null,"","",null],
  ["entitlements",4,"status","text",true,null,"","","pg_catalog.default"],
  ["entitlements",5,"revision","bigint",true,null,"","",null],
  ["entitlements",6,"created_at","timestamp with time zone",true,null,"","",null],
  ["entitlements",7,"updated_at","timestamp with time zone",true,null,"","",null],
  ["entitlements",8,"payload_json","text",true,null,"","","pg_catalog.default"],
  ["evidence_records",1,"id","text",true,null,"","","pg_catalog.default"],
  ["evidence_records",2,"owner_ref","text",true,null,"","","pg_catalog.default"],
  ["evidence_records",3,"evidence_type","text",true,null,"","","pg_catalog.default"],
  ["evidence_records",4,"subject_ref","text",true,null,"","","pg_catalog.default"],
  ["evidence_records",5,"aggregate_kind","text",true,null,"","","pg_catalog.default"],
  ["evidence_records",6,"aggregate_id","uuid",true,null,"","",null],
  ["evidence_records",7,"aggregate_revision","bigint",true,null,"","",null],
  ["evidence_records",8,"identity_realm","text",true,null,"","","pg_catalog.default"],
  ["evidence_records",9,"issuer_ref","text",true,null,"","","pg_catalog.default"],
  ["evidence_records",10,"issuer_class","text",true,null,"","","pg_catalog.default"],
  ["evidence_records",11,"issuer_incarnation","text",true,null,"","","pg_catalog.default"],
  ["evidence_records",12,"audience","text",true,null,"","","pg_catalog.default"],
  ["evidence_records",13,"key_id","text",true,null,"","","pg_catalog.default"],
  ["evidence_records",14,"issued_at","timestamp with time zone",true,null,"","",null],
  ["evidence_records",15,"expires_at","timestamp with time zone",true,null,"","",null],
  ["evidence_records",16,"nonce","text",true,null,"","","pg_catalog.default"],
  ["evidence_records",17,"evidence_generation","bigint",true,null,"","",null],
  ["evidence_records",18,"payload_digest","text",true,null,"","","pg_catalog.default"],
  ["evidence_records",19,"envelope_digest","text",true,null,"","","pg_catalog.default"],
  ["evidence_records",20,"envelope_json","text",true,null,"","","pg_catalog.default"],
  ["evidence_records",21,"created_at","timestamp with time zone",true,null,"","",null],
  ["idempotency_records",1,"scope","text",true,null,"","","pg_catalog.default"],
  ["idempotency_records",2,"owner_ref","text",true,null,"","","pg_catalog.default"],
  ["idempotency_records",3,"request_hash","text",true,null,"","","pg_catalog.default"],
  ["idempotency_records",4,"aggregate_kind","text",true,null,"","","pg_catalog.default"],
  ["idempotency_records",5,"aggregate_id","uuid",true,null,"","",null],
  ["idempotency_records",6,"event_id","uuid",true,null,"","",null],
  ["idempotency_records",7,"response_json","text",true,null,"","","pg_catalog.default"],
  ["idempotency_records",8,"created_at","timestamp with time zone",true,null,"","",null],
  ["import_candidates",1,"id","uuid",true,null,"","",null],
  ["import_candidates",2,"owner_ref","text",true,null,"","","pg_catalog.default"],
  ["import_candidates",3,"checksum","text",true,null,"","","pg_catalog.default"],
  ["import_candidates",4,"redacted_metadata_json","text",true,null,"","","pg_catalog.default"],
  ["import_candidates",5,"state","text",true,null,"","","pg_catalog.default"],
  ["import_candidates",6,"revision","bigint",true,null,"","",null],
  ["import_candidates",7,"created_at","timestamp with time zone",true,null,"","",null],
  ["import_candidates",8,"updated_at","timestamp with time zone",true,null,"","",null],
  ["outbox",1,"id","uuid",true,null,"","",null],
  ["outbox",2,"owner_ref","text",true,null,"","","pg_catalog.default"],
  ["outbox",3,"topic","text",true,null,"","","pg_catalog.default"],
  ["outbox",4,"aggregate_kind","text",true,null,"","","pg_catalog.default"],
  ["outbox",5,"aggregate_id","text",true,null,"","","pg_catalog.default"],
  ["outbox",6,"event_id","uuid",false,null,"","",null],
  ["outbox",7,"payload_digest","text",true,null,"","","pg_catalog.default"],
  ["outbox",8,"payload_json","text",true,null,"","","pg_catalog.default"],
  ["outbox",9,"status","text",true,null,"","","pg_catalog.default"],
  ["outbox",10,"attempt_count","bigint",true,null,"","",null],
  ["outbox",11,"claim_owner_ref","text",false,null,"","","pg_catalog.default"],
  ["outbox",12,"claim_expires_at","timestamp with time zone",false,null,"","",null],
  ["outbox",13,"created_at","timestamp with time zone",true,null,"","",null],
  ["provider_accounts",1,"id","uuid",true,null,"","",null],
  ["provider_accounts",2,"owner_ref","text",true,null,"","","pg_catalog.default"],
  ["provider_accounts",3,"provider_key","text",true,null,"","","pg_catalog.default"],
  ["provider_accounts",4,"provider_subject_ref","text",false,null,"","","pg_catalog.default"],
  ["provider_accounts",5,"status","text",true,null,"","","pg_catalog.default"],
  ["provider_accounts",6,"revision","bigint",true,null,"","",null],
  ["provider_accounts",7,"created_at","timestamp with time zone",true,null,"","",null],
  ["provider_accounts",8,"updated_at","timestamp with time zone",true,null,"","",null],
  ["provider_accounts",9,"payload_json","text",true,null,"","","pg_catalog.default"],
  ["provider_subject_claims",1,"provider_key","text",true,null,"","","pg_catalog.default"],
  ["provider_subject_claims",2,"provider_subject_ref","text",true,null,"","","pg_catalog.default"],
  ["provider_subject_claims",3,"owner_ref","text",true,null,"","","pg_catalog.default"],
  ["provider_subject_claims",4,"provider_account_id","uuid",true,null,"","",null],
  ["provider_subject_claims",5,"claimed_at","timestamp with time zone",true,null,"","",null],
  ["recovery_ledger_receipts",1,"sequence","bigint",true,null,"","",null],
  ["recovery_ledger_receipts",2,"identity_realm","text",true,null,"","","pg_catalog.default"],
  ["recovery_ledger_receipts",3,"frontier_hash","text",true,null,"","","pg_catalog.default"],
  ["recovery_ledger_receipts",4,"frontier_signature_digest","text",true,null,"","","pg_catalog.default"],
  ["recovery_ledger_receipts",5,"catalog_incarnation","text",true,null,"","","pg_catalog.default"],
  ["recovery_ledger_receipts",6,"receipt_digest","text",true,null,"","","pg_catalog.default"],
  ["recovery_ledger_receipts",7,"entry_kind","text",true,null,"","","pg_catalog.default"],
  ["recovery_ledger_receipts",8,"aggregate_id","text",false,null,"","","pg_catalog.default"],
  ["recovery_ledger_receipts",9,"created_at","timestamp with time zone",true,null,"","",null],
  ["schema_migrations",1,"version","bigint",true,null,"","",null],
  ["schema_migrations",2,"checksum","text",true,null,"","","pg_catalog.default"],
  ["schema_migrations",3,"applied_at","timestamp with time zone",true,"clock_timestamp()","","",null],
  ["slot_eligibility_audit",1,"id","uuid",true,null,"","",null],
  ["slot_eligibility_audit",2,"owner_ref","text",true,null,"","","pg_catalog.default"],
  ["slot_eligibility_audit",3,"access_method_id","uuid",true,null,"","",null],
  ["slot_eligibility_audit",4,"decision","text",true,null,"","","pg_catalog.default"],
  ["slot_eligibility_audit",5,"reason_codes_json","text",true,null,"","","pg_catalog.default"],
  ["slot_eligibility_audit",6,"request_digest","text",true,null,"","","pg_catalog.default"],
  ["slot_eligibility_audit",7,"record_revision_digest","text",true,null,"","","pg_catalog.default"],
  ["slot_eligibility_audit",8,"recovery_frontier_sequence","bigint",true,null,"","",null],
  ["slot_eligibility_audit",9,"recovery_frontier_hash","text",true,null,"","","pg_catalog.default"],
  ["slot_eligibility_audit",10,"created_at","timestamp with time zone",true,null,"","",null],
];

const CONSTRAINTS: PostgresConstraintManifestEntry[] = [
  ["account_events","account_events_aggregate_kind_check","c","CHECK (aggregate_kind = ANY (ARRAY['account'::text, 'entitlement'::text, 'capacity_pool'::text, 'access_method'::text, 'auth_capsule'::text, 'credential_binding'::text]))",false,false,true],
  ["account_events","account_events_aggregate_revision_check","c","CHECK (aggregate_revision >= 0 AND aggregate_revision <= '9223372036854775807'::bigint)",false,false,true],
  ["account_events","account_events_id_owner_ref_key","u","UNIQUE (id, owner_ref)",false,false,true],
  ["account_events","account_events_pkey","p","PRIMARY KEY (id)",false,false,true],
  ["account_events","account_events_reason_code_check","c","CHECK (reason_code ~ '^[A-Z][A-Z0-9_]{0,63}$'::text)",false,false,true],
  ["account_lanes","account_lanes_access_transport_check","c","CHECK (access_transport = ANY (ARRAY['native_session'::text, 'api_key'::text, 'workload_identity'::text]))",false,false,true],
  ["account_lanes","account_lanes_capacity_pool_id_owner_ref_fkey","f","FOREIGN KEY (capacity_pool_id, owner_ref) REFERENCES accounts.capacity_pools(id, owner_ref) ON DELETE RESTRICT",false,false,true],
  ["account_lanes","account_lanes_check","c","CHECK (updated_at >= created_at)",false,false,true],
  ["account_lanes","account_lanes_entitlement_id_owner_ref_fkey","f","FOREIGN KEY (entitlement_id, owner_ref) REFERENCES accounts.entitlements(id, owner_ref) ON DELETE RESTRICT",false,false,true],
  ["account_lanes","account_lanes_id_owner_ref_key","u","UNIQUE (id, owner_ref)",false,false,true],
  ["account_lanes","account_lanes_payload_json_check","c","CHECK (octet_length(payload_json) <= 1048576)",false,false,true],
  ["account_lanes","account_lanes_pkey","p","PRIMARY KEY (id)",false,false,true],
  ["account_lanes","account_lanes_revision_check","c","CHECK (revision >= 0 AND revision <= '9223372036854775807'::bigint)",false,false,true],
  ["account_lanes","account_lanes_status_check","c","CHECK (status = ANY (ARRAY['draft'::text, 'ready'::text, 'draining'::text, 'disabled'::text, 'retired'::text]))",false,false,true],
  ["accounts_installation","accounts_installation_build_digest_check","c","CHECK (build_digest ~ '^sha256:[0-9a-f]{64}$'::text)",false,false,true],
  ["accounts_installation","accounts_installation_catalog_incarnation_key","u","UNIQUE (catalog_incarnation)",false,false,true],
  ["accounts_installation","accounts_installation_check","c","CHECK (updated_at >= created_at)",false,false,true],
  ["accounts_installation","accounts_installation_configuration_attestation_digest_check","c","CHECK (configuration_attestation_digest ~ '^sha256:[0-9a-f]{64}$'::text)",false,false,true],
  ["accounts_installation","accounts_installation_database_frontier_hash_check","c","CHECK (database_frontier_hash ~ '^sha256:[0-9a-f]{64}$'::text)",false,false,true],
  ["accounts_installation","accounts_installation_database_frontier_sequence_check","c","CHECK (database_frontier_sequence >= 0 AND database_frontier_sequence <= '9223372036854775807'::bigint)",false,false,true],
  ["accounts_installation","accounts_installation_database_frontier_signature_digest_check","c","CHECK (database_frontier_signature_digest ~ '^sha256:[0-9a-f]{64}$'::text)",false,false,true],
  ["accounts_installation","accounts_installation_deployment_mode_check","c","CHECK (deployment_mode = 'self_hosted'::text)",false,false,true],
  ["accounts_installation","accounts_installation_identity_realm_check","c","CHECK (identity_realm = 'hasna'::text)",false,false,true],
  ["accounts_installation","accounts_installation_pkey","p","PRIMARY KEY (singleton)",false,false,true],
  ["accounts_installation","accounts_installation_recovery_frontier_hash_check","c","CHECK (recovery_frontier_hash ~ '^sha256:[0-9a-f]{64}$'::text)",false,false,true],
  ["accounts_installation","accounts_installation_recovery_frontier_sequence_check","c","CHECK (recovery_frontier_sequence >= 0 AND recovery_frontier_sequence <= '9223372036854775807'::bigint)",false,false,true],
  ["accounts_installation","accounts_installation_recovery_frontier_signature_digest_check","c","CHECK (recovery_frontier_signature_digest ~ '^sha256:[0-9a-f]{64}$'::text)",false,false,true],
  ["accounts_installation","accounts_installation_singleton_check","c","CHECK (singleton = 1)",false,false,true],
  ["auth_capsules","auth_capsules_access_method_id_owner_ref_fkey","f","FOREIGN KEY (access_method_id, owner_ref) REFERENCES accounts.account_lanes(id, owner_ref) ON DELETE RESTRICT",false,false,true],
  ["auth_capsules","auth_capsules_auth_generation_check","c","CHECK (auth_generation >= 0 AND auth_generation <= '9223372036854775807'::bigint)",false,false,true],
  ["auth_capsules","auth_capsules_auth_state_revision_check","c","CHECK (auth_state_revision >= 0 AND auth_state_revision <= '9223372036854775807'::bigint)",false,false,true],
  ["auth_capsules","auth_capsules_capacity_pool_id_owner_ref_fkey","f","FOREIGN KEY (capacity_pool_id, owner_ref) REFERENCES accounts.capacity_pools(id, owner_ref) ON DELETE RESTRICT",false,false,true],
  ["auth_capsules","auth_capsules_check","c","CHECK (updated_at >= created_at)",false,false,true],
  ["auth_capsules","auth_capsules_id_owner_ref_key","u","UNIQUE (id, owner_ref)",false,false,true],
  ["auth_capsules","auth_capsules_payload_json_check","c","CHECK (octet_length(payload_json) <= 1048576)",false,false,true],
  ["auth_capsules","auth_capsules_pkey","p","PRIMARY KEY (id)",false,false,true],
  ["auth_capsules","auth_capsules_revision_check","c","CHECK (revision >= 0 AND revision <= '9223372036854775807'::bigint)",false,false,true],
  ["auth_capsules","auth_capsules_status_check","c","CHECK (status = ANY (ARRAY['unprovisioned'::text, 'bootstrapping'::text, 'ready'::text, 'degraded'::text, 'revoked'::text]))",false,false,true],
  ["capability_use_consumptions","capability_use_consumptions_idempotency_key_digest_check","c","CHECK (idempotency_key_digest ~ '^sha256:[0-9a-f]{64}$'::text)",false,false,true],
  ["capability_use_consumptions","capability_use_consumptions_owner_ref_capability_id_key","u","UNIQUE (owner_ref, capability_id)",false,false,true],
  ["capability_use_consumptions","capability_use_consumptions_owner_ref_idempotency_key_diges_key","u","UNIQUE (owner_ref, idempotency_key_digest)",false,false,true],
  ["capability_use_consumptions","capability_use_consumptions_pkey","p","PRIMARY KEY (owner_ref, consume_request_id)",false,false,true],
  ["capability_use_consumptions","capability_use_consumptions_receipt_jcs_base64url_check","c","CHECK (receipt_jcs_base64url ~ '^[A-Za-z0-9_-]+$'::text AND octet_length(receipt_jcs_base64url) <= 1398102)",false,false,true],
  ["capability_use_consumptions","capability_use_consumptions_request_digest_check","c","CHECK (request_digest ~ '^sha256:[0-9a-f]{64}$'::text)",false,false,true],
  ["capacity_domain_claims","capacity_domain_claims_capacity_pool_id_key","u","UNIQUE (capacity_pool_id)",false,false,true],
  ["capacity_domain_claims","capacity_domain_claims_capacity_pool_id_owner_ref_fkey","f","FOREIGN KEY (capacity_pool_id, owner_ref) REFERENCES accounts.capacity_pools(id, owner_ref) ON DELETE RESTRICT",false,false,true],
  ["capacity_domain_claims","capacity_domain_claims_pkey","p","PRIMARY KEY (provider_key, capacity_domain_ref)",false,false,true],
  ["capacity_domain_claims","capacity_domain_claims_serialization_key_key","u","UNIQUE (serialization_key)",false,false,true],
  ["capacity_pools","capacity_pools_account_id_owner_ref_fkey","f","FOREIGN KEY (account_id, owner_ref) REFERENCES accounts.provider_accounts(id, owner_ref) ON DELETE RESTRICT",false,false,true],
  ["capacity_pools","capacity_pools_capacity_generation_check","c","CHECK (capacity_generation >= 0 AND capacity_generation <= '9223372036854775807'::bigint)",false,false,true],
  ["capacity_pools","capacity_pools_check","c","CHECK (updated_at >= created_at)",false,false,true],
  ["capacity_pools","capacity_pools_deny_generation_check","c","CHECK (deny_generation >= 0 AND deny_generation <= '9223372036854775807'::bigint)",false,false,true],
  ["capacity_pools","capacity_pools_deny_state_check","c","CHECK (deny_state = ANY (ARRAY['allowed'::text, 'denied'::text]))",false,false,true],
  ["capacity_pools","capacity_pools_id_owner_ref_key","u","UNIQUE (id, owner_ref)",false,false,true],
  ["capacity_pools","capacity_pools_payload_json_check","c","CHECK (octet_length(payload_json) <= 1048576)",false,false,true],
  ["capacity_pools","capacity_pools_pkey","p","PRIMARY KEY (id)",false,false,true],
  ["capacity_pools","capacity_pools_provider_key_capacity_domain_ref_key","u","UNIQUE (provider_key, capacity_domain_ref)",false,false,true],
  ["capacity_pools","capacity_pools_revision_check","c","CHECK (revision >= 0 AND revision <= '9223372036854775807'::bigint)",false,false,true],
  ["capacity_pools","capacity_pools_serialization_key_key","u","UNIQUE (serialization_key)",false,false,true],
  ["capacity_pools","capacity_pools_status_check","c","CHECK (status = ANY (ARRAY['pending'::text, 'active'::text, 'draining'::text, 'denied'::text, 'retired'::text]))",false,false,true],
  ["capsule_maintenance_grants","capsule_maintenance_grants_check","c","CHECK (state = 'live'::text AND terminal_at IS NULL OR (state = ANY (ARRAY['consumed'::text, 'expired'::text])) AND terminal_at IS NOT NULL)",false,false,true],
  ["capsule_maintenance_grants","capsule_maintenance_grants_grant_digest_check","c","CHECK (grant_digest ~ '^sha256:[0-9a-f]{64}$'::text)",false,false,true],
  ["capsule_maintenance_grants","capsule_maintenance_grants_grant_id_owner_ref_key","u","UNIQUE (grant_id, owner_ref)",false,false,true],
  ["capsule_maintenance_grants","capsule_maintenance_grants_grant_jcs_base64url_check","c","CHECK (grant_jcs_base64url ~ '^[A-Za-z0-9_-]+$'::text AND octet_length(grant_jcs_base64url) <= 1398102)",false,false,true],
  ["capsule_maintenance_grants","capsule_maintenance_grants_idempotency_key_digest_check","c","CHECK (idempotency_key_digest ~ '^sha256:[0-9a-f]{64}$'::text)",false,false,true],
  ["capsule_maintenance_grants","capsule_maintenance_grants_owner_ref_grant_digest_key","u","UNIQUE (owner_ref, grant_digest)",false,false,true],
  ["capsule_maintenance_grants","capsule_maintenance_grants_owner_ref_idempotency_key_digest_key","u","UNIQUE (owner_ref, idempotency_key_digest)",false,false,true],
  ["capsule_maintenance_grants","capsule_maintenance_grants_pkey","p","PRIMARY KEY (grant_id)",false,false,true],
  ["capsule_maintenance_grants","capsule_maintenance_grants_request_digest_check","c","CHECK (request_digest ~ '^sha256:[0-9a-f]{64}$'::text)",false,false,true],
  ["capsule_maintenance_grants","capsule_maintenance_grants_reservation_key_digest_check","c","CHECK (reservation_key_digest ~ '^sha256:[0-9a-f]{64}$'::text)",false,false,true],
  ["capsule_maintenance_grants","capsule_maintenance_grants_state_check","c","CHECK (state = ANY (ARRAY['live'::text, 'consumed'::text, 'expired'::text]))",false,false,true],
  ["capsule_maintenance_uses","capsule_maintenance_uses_consume_receipt_digest_check","c","CHECK (consume_receipt_digest ~ '^sha256:[0-9a-f]{64}$'::text)",false,false,true],
  ["capsule_maintenance_uses","capsule_maintenance_uses_consume_receipt_digest_key","u","UNIQUE (consume_receipt_digest)",false,false,true],
  ["capsule_maintenance_uses","capsule_maintenance_uses_consume_receipt_jcs_base64url_check","c","CHECK (consume_receipt_jcs_base64url ~ '^[A-Za-z0-9_-]+$'::text AND octet_length(consume_receipt_jcs_base64url) <= 1398102)",false,false,true],
  ["capsule_maintenance_uses","capsule_maintenance_uses_grant_id_owner_ref_fkey","f","FOREIGN KEY (grant_id, owner_ref) REFERENCES accounts.capsule_maintenance_grants(grant_id, owner_ref) ON DELETE RESTRICT",false,false,true],
  ["capsule_maintenance_uses","capsule_maintenance_uses_idempotency_key_digest_check","c","CHECK (idempotency_key_digest ~ '^sha256:[0-9a-f]{64}$'::text)",false,false,true],
  ["capsule_maintenance_uses","capsule_maintenance_uses_maintenance_use_id_check","c","CHECK (maintenance_use_id ~ '^sha256:[0-9a-f]{64}$'::text)",false,false,true],
  ["capsule_maintenance_uses","capsule_maintenance_uses_maintenance_use_id_key","u","UNIQUE (maintenance_use_id)",false,false,true],
  ["capsule_maintenance_uses","capsule_maintenance_uses_owner_ref_idempotency_key_digest_key","u","UNIQUE (owner_ref, idempotency_key_digest)",false,false,true],
  ["capsule_maintenance_uses","capsule_maintenance_uses_pkey","p","PRIMARY KEY (grant_id)",false,false,true],
  ["capsule_maintenance_uses","capsule_maintenance_uses_request_digest_check","c","CHECK (request_digest ~ '^sha256:[0-9a-f]{64}$'::text)",false,false,true],
  ["credential_binding_handles","credential_binding_handles_audience_check","c","CHECK (audience = 'accounts-self-hosted'::text)",false,false,true],
  ["credential_binding_handles","credential_binding_handles_audit_digest_check","c","CHECK (audit_digest ~ '^(sha256|hmac-sha256):[0-9a-f]{64}$'::text)",false,false,true],
  ["credential_binding_handles","credential_binding_handles_backend_class_check","c","CHECK (backend_class = ANY (ARRAY['secrets_broker'::text, 'workload_identity_broker'::text, 'capsule_protected_state'::text]))",false,false,true],
  ["credential_binding_handles","credential_binding_handles_binding_id_owner_ref_fkey","f","FOREIGN KEY (binding_id, owner_ref) REFERENCES accounts.credential_bindings(id, owner_ref) ON DELETE RESTRICT",false,false,true],
  ["credential_binding_handles","credential_binding_handles_binding_id_owner_ref_key","u","UNIQUE (binding_id, owner_ref)",false,false,true],
  ["credential_binding_handles","credential_binding_handles_check","c","CHECK (expires_at IS NULL OR expires_at > issued_at)",false,false,true],
  ["credential_binding_handles","credential_binding_handles_opaque_handle_check","c","CHECK (length(opaque_handle) >= 64 AND length(opaque_handle) <= 1024)",false,false,true],
  ["credential_binding_handles","credential_binding_handles_pkey","p","PRIMARY KEY (binding_id)",false,false,true],
  ["credential_bindings","credential_binding_resolver_shape","c","CHECK (resolver = 'capsule_local_native'::text AND purpose = 'provider_session'::text AND auth_capsule_id IS NOT NULL AND auth_state_revision IS NOT NULL OR resolver = 'brokered_secret'::text AND purpose = 'api_key'::text AND auth_capsule_id IS NULL AND auth_state_revision IS NULL OR resolver = 'workload_identity'::text AND purpose = 'workload_identity'::text AND auth_capsule_id IS NULL AND auth_state_revision IS NULL)",false,false,true],
  ["credential_bindings","credential_bindings_access_method_id_owner_ref_fkey","f","FOREIGN KEY (access_method_id, owner_ref) REFERENCES accounts.account_lanes(id, owner_ref) ON DELETE RESTRICT",false,false,true],
  ["credential_bindings","credential_bindings_auth_capsule_id_owner_ref_fkey","f","FOREIGN KEY (auth_capsule_id, owner_ref) REFERENCES accounts.auth_capsules(id, owner_ref) ON DELETE RESTRICT",false,false,true],
  ["credential_bindings","credential_bindings_auth_state_revision_check","c","CHECK (auth_state_revision >= 0 AND auth_state_revision <= '9223372036854775807'::bigint)",false,false,true],
  ["credential_bindings","credential_bindings_capacity_pool_id_owner_ref_fkey","f","FOREIGN KEY (capacity_pool_id, owner_ref) REFERENCES accounts.capacity_pools(id, owner_ref) ON DELETE RESTRICT",false,false,true],
  ["credential_bindings","credential_bindings_check","c","CHECK (updated_at >= created_at)",false,false,true],
  ["credential_bindings","credential_bindings_credential_family_id_credential_generat_key","u","UNIQUE (credential_family_id, credential_generation)",false,false,true],
  ["credential_bindings","credential_bindings_credential_generation_check","c","CHECK (credential_generation >= 0 AND credential_generation <= '9223372036854775807'::bigint)",false,false,true],
  ["credential_bindings","credential_bindings_id_owner_ref_key","u","UNIQUE (id, owner_ref)",false,false,true],
  ["credential_bindings","credential_bindings_last_usable_credential_generation_check","c","CHECK (last_usable_credential_generation >= 0 AND last_usable_credential_generation <= '9223372036854775807'::bigint)",false,false,true],
  ["credential_bindings","credential_bindings_payload_json_check","c","CHECK (octet_length(payload_json) <= 1048576)",false,false,true],
  ["credential_bindings","credential_bindings_pkey","p","PRIMARY KEY (id)",false,false,true],
  ["credential_bindings","credential_bindings_purpose_check","c","CHECK (purpose = ANY (ARRAY['provider_session'::text, 'api_key'::text, 'workload_identity'::text]))",false,false,true],
  ["credential_bindings","credential_bindings_resolver_check","c","CHECK (resolver = ANY (ARRAY['brokered_secret'::text, 'workload_identity'::text, 'capsule_local_native'::text]))",false,false,true],
  ["credential_bindings","credential_bindings_revision_check","c","CHECK (revision >= 0 AND revision <= '9223372036854775807'::bigint)",false,false,true],
  ["credential_bindings","credential_bindings_status_check","c","CHECK (status = ANY (ARRAY['pending'::text, 'active'::text, 'retiring'::text, 'revoked'::text]))",false,false,true],
  ["credential_bindings","credential_bindings_terminal_kind_check","c","CHECK (terminal_kind = ANY (ARRAY['retired_handle_generation'::text, 'revocation_barrier'::text]))",false,false,true],
  ["credential_bindings","credential_bindings_terminal_shape","c","CHECK (status <> 'revoked'::text AND terminal_kind IS NULL AND credential_handle_audit_digest IS NULL AND last_usable_credential_generation IS NULL AND revocation_barrier_receipt_digest IS NULL AND revoked_at IS NULL OR status = 'revoked'::text AND terminal_kind = 'retired_handle_generation'::text AND credential_handle_audit_digest IS NOT NULL AND last_usable_credential_generation IS NULL AND revocation_barrier_receipt_digest IS NOT NULL AND revoked_at IS NOT NULL OR status = 'revoked'::text AND terminal_kind = 'revocation_barrier'::text AND credential_handle_audit_digest IS NULL AND last_usable_credential_generation IS NOT NULL AND revocation_barrier_receipt_digest IS NOT NULL AND revoked_at IS NOT NULL)",false,false,true],
  ["credential_family_claims","credential_family_claims_capacity_pool_id_owner_ref_fkey","f","FOREIGN KEY (capacity_pool_id, owner_ref) REFERENCES accounts.capacity_pools(id, owner_ref) ON DELETE RESTRICT",false,false,true],
  ["credential_family_claims","credential_family_claims_pkey","p","PRIMARY KEY (credential_family_id)",false,false,true],
  ["credential_family_claims","credential_family_claims_purpose_check","c","CHECK (purpose = ANY (ARRAY['provider_session'::text, 'api_key'::text, 'workload_identity'::text]))",false,false,true],
  ["credential_family_claims","credential_family_claims_resolver_check","c","CHECK (resolver = ANY (ARRAY['brokered_secret'::text, 'workload_identity'::text, 'capsule_local_native'::text]))",false,false,true],
  ["credential_operations","credential_operations_capacity_pool_id_owner_ref_fkey","f","FOREIGN KEY (capacity_pool_id, owner_ref) REFERENCES accounts.capacity_pools(id, owner_ref) ON DELETE RESTRICT",false,false,true],
  ["credential_operations","credential_operations_check","c","CHECK (updated_at >= created_at)",false,false,true],
  ["credential_operations","credential_operations_expected_auth_state_revision_check","c","CHECK (expected_auth_state_revision >= 0 AND expected_auth_state_revision <= '9223372036854775807'::bigint)",false,false,true],
  ["credential_operations","credential_operations_expected_source_generation_check","c","CHECK (expected_source_generation >= 0 AND expected_source_generation <= '9223372036854775807'::bigint)",false,false,true],
  ["credential_operations","credential_operations_id_owner_ref_key","u","UNIQUE (id, owner_ref)",false,false,true],
  ["credential_operations","credential_operations_kind_check","c","CHECK (kind = ANY (ARRAY['refresh'::text, 'reauthentication'::text, 'rotation'::text, 'revocation'::text]))",false,false,true],
  ["credential_operations","credential_operations_pkey","p","PRIMARY KEY (id)",false,false,true],
  ["credential_operations","credential_operations_proposed_auth_state_revision_check","c","CHECK (proposed_auth_state_revision >= 0 AND proposed_auth_state_revision <= '9223372036854775807'::bigint)",false,false,true],
  ["credential_operations","credential_operations_proposed_target_generation_check","c","CHECK (proposed_target_generation >= 0 AND proposed_target_generation <= '9223372036854775807'::bigint)",false,false,true],
  ["credential_operations","credential_operations_revision_check","c","CHECK (revision >= 0 AND revision <= '9223372036854775807'::bigint)",false,false,true],
  ["credential_operations","credential_operations_source_binding_id_owner_ref_fkey","f","FOREIGN KEY (source_binding_id, owner_ref) REFERENCES accounts.credential_bindings(id, owner_ref) ON DELETE RESTRICT",false,false,true],
  ["credential_operations","credential_operations_state_check","c","CHECK (state = ANY (ARRAY['requested'::text, 'quiescing'::text, 'applying'::text, 'verifying'::text, 'completed'::text, 'failed_before_dispatch'::text, 'failed'::text, 'quarantined'::text]))",false,false,true],
  ["credential_operations","credential_operations_target_binding_id_owner_ref_fkey","f","FOREIGN KEY (target_binding_id, owner_ref) REFERENCES accounts.credential_bindings(id, owner_ref) ON DELETE RESTRICT",false,false,true],
  ["entitlements","entitlements_account_id_owner_ref_fkey","f","FOREIGN KEY (account_id, owner_ref) REFERENCES accounts.provider_accounts(id, owner_ref) ON DELETE RESTRICT",false,false,true],
  ["entitlements","entitlements_check","c","CHECK (updated_at >= created_at)",false,false,true],
  ["entitlements","entitlements_id_owner_ref_key","u","UNIQUE (id, owner_ref)",false,false,true],
  ["entitlements","entitlements_payload_json_check","c","CHECK (octet_length(payload_json) <= 1048576)",false,false,true],
  ["entitlements","entitlements_pkey","p","PRIMARY KEY (id)",false,false,true],
  ["entitlements","entitlements_revision_check","c","CHECK (revision >= 0 AND revision <= '9223372036854775807'::bigint)",false,false,true],
  ["entitlements","entitlements_status_check","c","CHECK (status = ANY (ARRAY['pending'::text, 'active'::text, 'paused'::text, 'expired'::text, 'revoked'::text]))",false,false,true],
  ["evidence_records","evidence_records_aggregate_kind_check","c","CHECK (aggregate_kind = ANY (ARRAY['provider_account'::text, 'capacity_pool'::text, 'entitlement'::text, 'account_lane'::text]))",false,false,true],
  ["evidence_records","evidence_records_aggregate_revision_check","c","CHECK (aggregate_revision >= 0 AND aggregate_revision <= '9223372036854775807'::bigint)",false,false,true],
  ["evidence_records","evidence_records_check","c","CHECK (expires_at > issued_at)",false,false,true],
  ["evidence_records","evidence_records_envelope_digest_check","c","CHECK (envelope_digest ~ '^sha256:[0-9a-f]{64}$'::text)",false,false,true],
  ["evidence_records","evidence_records_envelope_digest_key","u","UNIQUE (envelope_digest)",false,false,true],
  ["evidence_records","evidence_records_envelope_json_check","c","CHECK (octet_length(envelope_json) <= 1048576)",false,false,true],
  ["evidence_records","evidence_records_evidence_generation_check","c","CHECK (evidence_generation >= 1 AND evidence_generation <= '9223372036854775807'::bigint)",false,false,true],
  ["evidence_records","evidence_records_identity_realm_check","c","CHECK (identity_realm = 'hasna'::text)",false,false,true],
  ["evidence_records","evidence_records_issuer_class_check","c","CHECK (issuer_class = ANY (ARRAY['provider_ownership_verifier'::text, 'provider_capacity_verifier'::text, 'execution_policy_authority'::text, 'terms_authority'::text, 'adapter_health_reporter'::text]))",false,false,true],
  ["evidence_records","evidence_records_nonce_check","c","CHECK (nonce ~ '^[A-Za-z0-9_-]{22,86}$'::text)",false,false,true],
  ["evidence_records","evidence_records_nonce_key","u","UNIQUE (nonce)",false,false,true],
  ["evidence_records","evidence_records_payload_digest_check","c","CHECK (payload_digest ~ '^sha256:[0-9a-f]{64}$'::text)",false,false,true],
  ["evidence_records","evidence_records_pkey","p","PRIMARY KEY (id)",false,false,true],
  ["idempotency_records","idempotency_records_event_id_owner_ref_fkey","f","FOREIGN KEY (event_id, owner_ref) REFERENCES accounts.account_events(id, owner_ref) ON DELETE RESTRICT",false,false,true],
  ["idempotency_records","idempotency_records_pkey","p","PRIMARY KEY (scope, owner_ref)",false,false,true],
  ["idempotency_records","idempotency_records_request_hash_check","c","CHECK (request_hash ~ '^sha256:[0-9a-f]{64}$'::text)",false,false,true],
  ["idempotency_records","idempotency_records_response_json_check","c","CHECK (octet_length(response_json) <= 1048576)",false,false,true],
  ["import_candidates","import_candidates_check","c","CHECK (updated_at >= created_at)",false,false,true],
  ["import_candidates","import_candidates_pkey","p","PRIMARY KEY (id)",false,false,true],
  ["import_candidates","import_candidates_redacted_metadata_json_check","c","CHECK (octet_length(redacted_metadata_json) <= 1048576)",false,false,true],
  ["import_candidates","import_candidates_revision_check","c","CHECK (revision >= 0 AND revision <= '9223372036854775807'::bigint)",false,false,true],
  ["import_candidates","import_candidates_state_check","c","CHECK (state = ANY (ARRAY['pending'::text, 'confirmed'::text, 'cancelled'::text, 'rejected'::text]))",false,false,true],
  ["outbox","outbox_attempt_count_check","c","CHECK (attempt_count >= 0 AND attempt_count <= '9223372036854775807'::bigint)",false,false,true],
  ["outbox","outbox_check","c","CHECK (status = 'in_flight'::text AND claim_owner_ref IS NOT NULL AND claim_expires_at IS NOT NULL OR status <> 'in_flight'::text AND claim_owner_ref IS NULL AND claim_expires_at IS NULL)",false,false,true],
  ["outbox","outbox_event_id_owner_ref_fkey","f","FOREIGN KEY (event_id, owner_ref) REFERENCES accounts.account_events(id, owner_ref) ON DELETE RESTRICT",false,false,true],
  ["outbox","outbox_payload_digest_check","c","CHECK (payload_digest ~ '^sha256:[0-9a-f]{64}$'::text)",false,false,true],
  ["outbox","outbox_payload_json_check","c","CHECK (octet_length(payload_json) <= 1048576)",false,false,true],
  ["outbox","outbox_pkey","p","PRIMARY KEY (id)",false,false,true],
  ["outbox","outbox_status_check","c","CHECK (status = ANY (ARRAY['pending'::text, 'in_flight'::text, 'delivered'::text, 'dead_letter'::text]))",false,false,true],
  ["outbox","outbox_topic_check","c","CHECK (topic = ANY (ARRAY['accounts.aggregate.changed'::text, 'accounts.capsule.cleanup.requested'::text]))",false,false,true],
  ["provider_accounts","provider_accounts_check","c","CHECK (updated_at >= created_at)",false,false,true],
  ["provider_accounts","provider_accounts_id_owner_ref_key","u","UNIQUE (id, owner_ref)",false,false,true],
  ["provider_accounts","provider_accounts_owner_ref_check","c","CHECK (owner_ref ~ '^principal:(human|service):hasna:[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$'::text)",false,false,true],
  ["provider_accounts","provider_accounts_payload_json_check","c","CHECK (octet_length(payload_json) <= 1048576)",false,false,true],
  ["provider_accounts","provider_accounts_pkey","p","PRIMARY KEY (id)",false,false,true],
  ["provider_accounts","provider_accounts_revision_check","c","CHECK (revision >= 0 AND revision <= '9223372036854775807'::bigint)",false,false,true],
  ["provider_accounts","provider_accounts_status_check","c","CHECK (status = ANY (ARRAY['pending'::text, 'active'::text, 'suspended'::text, 'revoked'::text]))",false,false,true],
  ["provider_subject_claims","provider_subject_claims_pkey","p","PRIMARY KEY (provider_key, provider_subject_ref)",false,false,true],
  ["provider_subject_claims","provider_subject_claims_provider_account_id_key","u","UNIQUE (provider_account_id)",false,false,true],
  ["provider_subject_claims","provider_subject_claims_provider_account_id_owner_ref_fkey","f","FOREIGN KEY (provider_account_id, owner_ref) REFERENCES accounts.provider_accounts(id, owner_ref) ON DELETE RESTRICT",false,false,true],
  ["recovery_ledger_receipts","recovery_ledger_receipts_entry_kind_check","c","CHECK (entry_kind = ANY (ARRAY['catalog_mutation'::text, 'native_revocation_barrier'::text]))",false,false,true],
  ["recovery_ledger_receipts","recovery_ledger_receipts_frontier_hash_check","c","CHECK (frontier_hash ~ '^sha256:[0-9a-f]{64}$'::text)",false,false,true],
  ["recovery_ledger_receipts","recovery_ledger_receipts_frontier_hash_key","u","UNIQUE (frontier_hash)",false,false,true],
  ["recovery_ledger_receipts","recovery_ledger_receipts_frontier_signature_digest_check","c","CHECK (frontier_signature_digest ~ '^sha256:[0-9a-f]{64}$'::text)",false,false,true],
  ["recovery_ledger_receipts","recovery_ledger_receipts_identity_realm_check","c","CHECK (identity_realm = 'hasna'::text)",false,false,true],
  ["recovery_ledger_receipts","recovery_ledger_receipts_pkey","p","PRIMARY KEY (sequence)",false,false,true],
  ["recovery_ledger_receipts","recovery_ledger_receipts_receipt_digest_check","c","CHECK (receipt_digest ~ '^sha256:[0-9a-f]{64}$'::text)",false,false,true],
  ["recovery_ledger_receipts","recovery_ledger_receipts_receipt_digest_key","u","UNIQUE (receipt_digest)",false,false,true],
  ["recovery_ledger_receipts","recovery_ledger_receipts_sequence_check","c","CHECK (sequence >= 0 AND sequence <= '9223372036854775807'::bigint)",false,false,true],
  ["schema_migrations","schema_migrations_checksum_check","c","CHECK (checksum ~ '^sha256:[0-9a-f]{64}$'::text)",false,false,true],
  ["schema_migrations","schema_migrations_pkey","p","PRIMARY KEY (version)",false,false,true],
  ["schema_migrations","schema_migrations_version_check","c","CHECK (version > 0)",false,false,true],
  ["slot_eligibility_audit","slot_eligibility_audit_access_method_id_owner_ref_fkey","f","FOREIGN KEY (access_method_id, owner_ref) REFERENCES accounts.account_lanes(id, owner_ref) ON DELETE RESTRICT",false,false,true],
  ["slot_eligibility_audit","slot_eligibility_audit_decision_check","c","CHECK (decision = ANY (ARRAY['eligible'::text, 'ineligible'::text]))",false,false,true],
  ["slot_eligibility_audit","slot_eligibility_audit_pkey","p","PRIMARY KEY (id)",false,false,true],
  ["slot_eligibility_audit","slot_eligibility_audit_recovery_frontier_hash_check","c","CHECK (recovery_frontier_hash ~ '^sha256:[0-9a-f]{64}$'::text)",false,false,true],
  ["slot_eligibility_audit","slot_eligibility_audit_recovery_frontier_sequence_check","c","CHECK (recovery_frontier_sequence >= 0 AND recovery_frontier_sequence <= '9223372036854775807'::bigint)",false,false,true],
];

const INDEXES: PostgresIndexManifestEntry[] = [
  ["auth_capsules","auth_capsules_one_live_per_pool","btree",true,true,true,true,"CREATE UNIQUE INDEX auth_capsules_one_live_per_pool ON accounts.auth_capsules USING btree (capacity_pool_id) WHERE status <> 'revoked'::text","status <> 'revoked'::text"],
  ["capsule_maintenance_grants","capsule_maintenance_one_live_reservation","btree",true,true,true,true,"CREATE UNIQUE INDEX capsule_maintenance_one_live_reservation ON accounts.capsule_maintenance_grants USING btree (owner_ref, reservation_key_digest) WHERE state = 'live'::text","state = 'live'::text"],
  ["credential_bindings","credential_bindings_one_active_native","btree",true,true,true,true,"CREATE UNIQUE INDEX credential_bindings_one_active_native ON accounts.credential_bindings USING btree (capacity_pool_id, purpose) WHERE resolver = 'capsule_local_native'::text AND status = 'active'::text","resolver = 'capsule_local_native'::text AND status = 'active'::text"],
  ["credential_operations","credential_operations_one_active_family_domain","btree",true,true,true,true,"CREATE UNIQUE INDEX credential_operations_one_active_family_domain ON accounts.credential_operations USING btree (credential_family_id, serialization_key) WHERE state = ANY (ARRAY['requested'::text, 'quiescing'::text, 'applying'::text, 'verifying'::text, 'failed_before_dispatch'::text, 'failed'::text])","state = ANY (ARRAY['requested'::text, 'quiescing'::text, 'applying'::text, 'verifying'::text, 'failed_before_dispatch'::text, 'failed'::text])"],
  ["evidence_records","evidence_records_lookup","btree",false,true,true,true,"CREATE INDEX evidence_records_lookup ON accounts.evidence_records USING btree (owner_ref, aggregate_kind, aggregate_id, aggregate_revision, evidence_type)",null],
  ["outbox","outbox_pending_order","btree",false,true,true,true,"CREATE INDEX outbox_pending_order ON accounts.outbox USING btree (owner_ref, status, created_at, id)",null],
  ["provider_accounts","provider_accounts_active_subject","btree",true,true,true,true,"CREATE UNIQUE INDEX provider_accounts_active_subject ON accounts.provider_accounts USING btree (provider_key, provider_subject_ref) WHERE provider_subject_ref IS NOT NULL AND status <> 'pending'::text","provider_subject_ref IS NOT NULL AND status <> 'pending'::text"],
];

export const POSTGRES_SCHEMA_MANIFEST = Object.freeze({
  columns: freezeEntries(COLUMNS),
  constraints: freezeEntries(CONSTRAINTS),
  indexes: freezeEntries(INDEXES),
});
