// AUTO-GENERATED by `bun run sdk:generate` from src/server/openapi.ts.
// Do not edit by hand — re-run the generator to update.

// @generated from OpenAPI by @hasna/contracts SDK generator — DO NOT EDIT.
// Source: Accounts 1.0.0

export interface HealthResponse { "status": "ok" | "degraded" | "unavailable"; "version": string; "mode": "local" | "cloud" }

export interface ReadyResponse { "ready": boolean; "reason"?: string }

export interface VersionResponse { "version": string }

export interface ErrorResponse { "error": string; "reason"?: string }

export interface Account { "tool": string; "name": string; "email"?: string; "displayName"?: string; "identity"?: string; "cardLast4"?: string; "metadata": Record<string, unknown>; "dir"?: string; "description"?: string; "createdAt": string; "lastUsedAt"?: string }

export interface AccountList { "accounts": Array<Account> }

export interface CreateAccountInput { "name": string; "tool": string; "email"?: string; "displayName"?: string; "identity"?: string; "cardLast4"?: string; "metadata"?: Record<string, unknown>; "dir"?: string; "description"?: string }

export interface UpdateAccountInput { "email"?: string; "displayName"?: string; "identity"?: string; "cardLast4"?: string; "metadata"?: Record<string, unknown>; "dir"?: string; "description"?: string; "lastUsedAt"?: string }

export interface CurrentSelection { "tool": string; "name": string; "updatedAt": string }

export interface CurrentSelectionList { "current": Array<CurrentSelection> }

export interface SetCurrentInput { "name": string }

export interface RenameAccountInput { "name": string }

export interface Tool { "id": string; "label": string; "envVar": string; "extraEnv"?: Record<string, string>; "defaultDir": string; "bin": string; "loginArgs"?: Array<string>; "loginHint"?: string; "resumeArgs"?: Array<string>; "permissionArgs"?: Record<string, Array<string>>; "launchArgs"?: Array<string>; "accountFile"?: string; "emailPath"?: Array<string>; "builtin"?: boolean }

export interface ToolDefInput { "id": string; "label": string; "envVar": string; "extraEnv"?: Record<string, string>; "defaultDir": string; "bin": string; "loginArgs"?: Array<string>; "loginHint"?: string; "resumeArgs"?: Array<string>; "permissionArgs"?: Record<string, Array<string>>; "launchArgs"?: Array<string>; "accountFile"?: string; "emailPath"?: Array<string> }

export interface ToolList { "tools": Array<Tool> }

export interface AccountsClientOptions {
  /** Base URL, e.g. process.env.APP_API_URL. */
  baseUrl: string;
  /** API key, e.g. process.env.APP_API_KEY. Sent as the 'x-api-key' header. */
  apiKey?: string;
  /** Custom fetch (defaults to global fetch). */
  fetch?: typeof fetch;
  /** Extra headers merged into every request. */
  headers?: Record<string, string>;
}

export class ApiError extends Error {
  constructor(readonly status: number, message: string, readonly body: unknown) {
    super(message);
    this.name = "ApiError";
  }
}

export class AccountsClient {
  private readonly baseUrl: string;
  private readonly apiKey: string | undefined;
  private readonly fetchImpl: typeof fetch;
  private readonly baseHeaders: Record<string, string>;

  constructor(options: AccountsClientOptions) {
    if (!options.baseUrl) throw new Error("AccountsClient requires a baseUrl.");
    this.baseUrl = options.baseUrl.replace(/\/$/, "");
    this.apiKey = options.apiKey;
    this.fetchImpl = options.fetch ?? globalThis.fetch;
    this.baseHeaders = options.headers ?? {};
  }

  private async request<T>(method: string, path: string, opts: { body?: unknown; query?: Record<string, unknown>; init?: RequestInit }): Promise<T> {
    const url = new URL(this.baseUrl + path);
    if (opts.query) {
      for (const [key, value] of Object.entries(opts.query)) {
        if (value !== undefined && value !== null) url.searchParams.set(key, String(value));
      }
    }
    const headers: Record<string, string> = { Accept: "application/json", ...this.baseHeaders, ...(opts.init?.headers as Record<string, string> | undefined) };
    if (this.apiKey) headers["x-api-key"] = this.apiKey;
    let payload: BodyInit | undefined;
    if (opts.body !== undefined) {
      headers["Content-Type"] = "application/json";
      payload = JSON.stringify(opts.body);
    }
    const response = await this.fetchImpl(url.toString(), { ...opts.init, method, headers, body: payload });
    const text = await response.text();
    const data = text ? (() => { try { return JSON.parse(text); } catch { return text; } })() : undefined;
    if (!response.ok) {
      throw new ApiError(response.status, `${method} ${path} failed: ${response.status}`, data);
    }
    return data as T;
  }

    /** Liveness + DB reachability probe */
    async getHealth(init?: RequestInit): Promise<HealthResponse> {
      return this.request("GET", `/health`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Readiness probe (reachable AND migrated) */
    async getReady(init?: RequestInit): Promise<ReadyResponse> {
      return this.request("GET", `/ready`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** List accounts (optionally filtered by tool) */
    async listAccounts(query?: { "tool"?: string }, init?: RequestInit): Promise<AccountList> {
      return this.request("GET", `/v1/accounts`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Create an account */
    async createAccount(body: CreateAccountInput, init?: RequestInit): Promise<Account> {
      return this.request("POST", `/v1/accounts`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get one account */
    async getAccount(tool: string, name: string, init?: RequestInit): Promise<Account> {
      return this.request("GET", `/v1/accounts/${encodeURIComponent(String(tool))}/${encodeURIComponent(String(name))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Delete an account */
    async deleteAccount(tool: string, name: string, init?: RequestInit): Promise<void> {
      return this.request("DELETE", `/v1/accounts/${encodeURIComponent(String(tool))}/${encodeURIComponent(String(name))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Update an account */
    async updateAccount(tool: string, name: string, body: UpdateAccountInput, init?: RequestInit): Promise<Account> {
      return this.request("PATCH", `/v1/accounts/${encodeURIComponent(String(tool))}/${encodeURIComponent(String(name))}`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Rename an account */
    async renameAccount(tool: string, name: string, body: RenameAccountInput, init?: RequestInit): Promise<Account> {
      return this.request("POST", `/v1/accounts/${encodeURIComponent(String(tool))}/${encodeURIComponent(String(name))}/rename`, {
        body,
        query: undefined,
        init,
      });
    }

    /** List current active selections per tool */
    async listCurrent(init?: RequestInit): Promise<CurrentSelectionList> {
      return this.request("GET", `/v1/current`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Get the current active account for a tool */
    async getCurrent(tool: string, init?: RequestInit): Promise<CurrentSelection> {
      return this.request("GET", `/v1/current/${encodeURIComponent(String(tool))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Set the current active account for a tool */
    async setCurrent(tool: string, body: SetCurrentInput, init?: RequestInit): Promise<CurrentSelection> {
      return this.request("PUT", `/v1/current/${encodeURIComponent(String(tool))}`, {
        body,
        query: undefined,
        init,
      });
    }

    /** List known tools (builtin + custom) */
    async listTools(init?: RequestInit): Promise<ToolList> {
      return this.request("GET", `/v1/tools`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Register a custom tool */
    async addTool(body: ToolDefInput, init?: RequestInit): Promise<Tool> {
      return this.request("POST", `/v1/tools`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Remove a custom tool */
    async removeTool(id: string, init?: RequestInit): Promise<void> {
      return this.request("DELETE", `/v1/tools/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Service version */
    async getVersion(init?: RequestInit): Promise<VersionResponse> {
      return this.request("GET", `/version`, {
        body: undefined,
        query: undefined,
        init,
      });
    }
}
