#!/usr/bin/env bun
// Generate the typed SDK client from the accounts-serve OpenAPI document.
//
// Source of truth: src/server/openapi.ts. Output: src/sdk/client.ts (a typed,
// dependency-free fetch client). Run `bun run sdk:generate` after changing the
// API. A test (src/sdk.test.ts) fails if client.ts drifts from the spec.

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { generateSdkFromOpenApi, type OpenApiDocument } from "@hasna/contracts/sdk";
import { buildOpenApiDoc } from "../server/openapi.js";

const HEADER = `// AUTO-GENERATED by \`bun run sdk:generate\` from src/server/openapi.ts.
// Do not edit by hand — re-run the generator to update.
`;

/**
 * Stable doc version for SDK codegen so the generated client does not churn on
 * every package version bump (the runtime OpenAPI uses the real version).
 */
export const SDK_DOC_VERSION = "1.0.0";

export function renderSdk(): { code: string; warnings: string[] } {
  const spec = buildOpenApiDoc(SDK_DOC_VERSION) as unknown as OpenApiDocument;
  const result = generateSdkFromOpenApi(spec, { className: "AccountsClient", apiKeyHeader: "x-api-key" });
  return { code: HEADER + "\n" + result.code, warnings: result.warnings };
}

export function sdkClientPath(): string {
  return join(dirname(fileURLToPath(import.meta.url)), "client.ts");
}

if (import.meta.main) {
  const { code, warnings } = renderSdk();
  writeFileSync(sdkClientPath(), code);
  if (warnings.length > 0) {
    console.error("SDK generator warnings:");
    for (const w of warnings) console.error(`  - ${w}`);
  }
  console.log(`wrote ${sdkClientPath()} (${code.length} bytes)`);
}
