import type { MachineCommandRunner } from "./remote.js";
import type { DaemonServicePlan, DaemonServiceRunOptions, DaemonServiceRunResult } from "./commands/daemon.js";
import type { NotificationChannel, NotificationConfig, NotificationDispatchSummary, NotificationTestResult, AppsPlanResult, SetupResult, SyncResult } from "./types.js";
import type { DomainMapping } from "./commands/dns.js";
import { type ClearMachineFriendlyNameInput, type MachineFriendlyNameResult, type SetMachineFriendlyNameInput } from "./commands/manifest.js";
import { type RunAppsInstallOptions } from "./commands/apps.js";
import { type RunClaudeInstallOptions } from "./commands/install-claude.js";
import { type RunSetupOptions } from "./commands/setup.js";
import { type RunSyncOptions } from "./commands/sync.js";
import { type RunTailscaleInstallOptions } from "./commands/install-tailscale.js";
import { type TrustedNotificationApproval } from "./commands/notifications.js";
import { type SdkMutationApprovalOptions } from "./commands/mutation-approval.js";
import type { FleetManifest, MachineManifest } from "./types.js";
import { type AssignMachineProjectInput, type MachineProjectAssignments, type RemoveMachineProjectAssignmentInput } from "./projects.js";
type ApplyOptions = {
    apply?: boolean;
    yes?: boolean;
};
type SdkApplyOptions<T extends ApplyOptions> = T & SdkMutationApprovalOptions;
type NotificationSdkOptions = SdkMutationApprovalOptions & {
    approvalToken?: string;
    trustedApproval?: TrustedNotificationApproval;
};
type NotificationTestSdkOptions = NotificationSdkOptions & ApplyOptions;
export declare function manifestInit(options?: SdkMutationApprovalOptions): string;
export declare function manifestAdd(machine: MachineManifest, options?: SdkMutationApprovalOptions): FleetManifest;
export declare function manifestBootstrapCurrentMachine(options?: SdkMutationApprovalOptions): FleetManifest;
export declare function manifestRemove(machineId: string, options?: SdkMutationApprovalOptions): FleetManifest;
export declare function manifestSetFriendlyName(input: SetMachineFriendlyNameInput, options?: SdkMutationApprovalOptions): MachineFriendlyNameResult;
export declare function manifestClearFriendlyName(input: ClearMachineFriendlyNameInput, options?: SdkMutationApprovalOptions): MachineFriendlyNameResult;
export declare function assignMachineProject(input: AssignMachineProjectInput, options?: SdkMutationApprovalOptions): MachineProjectAssignments;
export declare function removeMachineProjectAssignment(input: RemoveMachineProjectAssignmentInput, options?: SdkMutationApprovalOptions): MachineProjectAssignments;
export declare function runSetup(machineId?: string, options?: SdkApplyOptions<RunSetupOptions>, runner?: MachineCommandRunner): SetupResult;
export declare function runSetupPlan(plan: SetupResult, options?: SdkApplyOptions<RunSetupOptions>, runner?: MachineCommandRunner): SetupResult;
export declare function runSync(machineId?: string, options?: SdkApplyOptions<RunSyncOptions>, runner?: MachineCommandRunner): SyncResult;
export declare function runSyncPlan(plan: SyncResult, options?: SdkApplyOptions<RunSyncOptions>, runner?: MachineCommandRunner): SyncResult;
export declare function runAppsInstall(machineId?: string, options?: SdkApplyOptions<RunAppsInstallOptions>, runner?: MachineCommandRunner): AppsPlanResult;
export declare function runAppsPlan(plan: AppsPlanResult, options?: SdkApplyOptions<RunAppsInstallOptions>, runner?: MachineCommandRunner): AppsPlanResult;
export declare function runClaudeInstall(machineId?: string, tools?: string[], options?: SdkApplyOptions<RunClaudeInstallOptions>, runner?: MachineCommandRunner): SetupResult;
export declare function runClaudeInstallPlan(plan: SetupResult, options?: SdkApplyOptions<RunClaudeInstallOptions>, runner?: MachineCommandRunner): SetupResult;
export declare function runTailscaleInstall(machineId?: string, options?: SdkApplyOptions<RunTailscaleInstallOptions>, runner?: MachineCommandRunner): SetupResult;
export declare function runTailscaleInstallPlan(plan: SetupResult, options?: SdkApplyOptions<RunTailscaleInstallOptions>, runner?: MachineCommandRunner): SetupResult;
export declare function addDomainMapping(domain: string, port: number, targetHost?: string, options?: SdkMutationApprovalOptions): DomainMapping[];
export declare function runCertPlan(domains: string[], options?: SdkApplyOptions<{
    apply?: boolean;
    yes?: boolean;
}>): SetupResult;
export declare function runBackup(bucket?: string, prefix?: string, options?: SdkApplyOptions<{
    apply?: boolean;
    yes?: boolean;
}>): SetupResult;
export declare function runDaemonServicePlan(plan: DaemonServicePlan, options?: SdkApplyOptions<DaemonServiceRunOptions>): DaemonServiceRunResult;
export declare function writeNotificationConfig(config: NotificationConfig, pathOrOptions?: string | SdkMutationApprovalOptions, maybeOptions?: SdkMutationApprovalOptions): NotificationConfig;
export declare function addNotificationChannel(channel: NotificationChannel, options?: NotificationSdkOptions): NotificationConfig;
export declare function removeNotificationChannel(channelId: string, options?: SdkMutationApprovalOptions): NotificationConfig;
export declare function dispatchNotificationEvent(event: string, message: string, options?: NotificationSdkOptions & {
    channelId?: string;
}): Promise<NotificationDispatchSummary>;
export declare function testNotificationChannel(channelId: string, event?: string, message?: string, options?: NotificationTestSdkOptions): Promise<NotificationTestResult>;
export {};
