export { ZohoSurvey, ZohoSurveyClient, DEFAULT_BASE_URL } from './api';
export * from './types';

export {
  getToken,
  setToken,
  getPortalId,
  setPortalId,
  getDepartmentId,
  setDepartmentId,
  getBaseUrl,
  setBaseUrl,
  getCurrentProfile,
  setCurrentProfile,
  listProfiles,
  createProfile,
  deleteProfile,
  loadProfile,
  saveProfile,
  clearConfig,
  getConfigDir,
  setProfileOverride,
  profileExists,
  getOAuthConfig,
  setOAuthConfig,
  loadOAuthTokens,
  saveOAuthTokens,
  clearOAuthTokens,
  getAccessToken,
} from './utils/config';

export {
  getAuthUrl,
  exchangeCodeForTokens,
  refreshAccessToken,
  startCallbackServer,
  getValidAccessToken,
  isAuthenticated,
  getRedirectUri,
  getRedirectPort,
  DEFAULT_AUTH_URL,
  DEFAULT_TOKEN_URL,
  DEFAULT_SCOPES,
  type AuthResult,
  type AuthUrlOptions,
} from './utils/auth';

export {
  formatOutput,
  success,
  error,
  warn,
  info,
  heading,
  print,
  setVerboseMode,
  isVerboseMode,
  debug,
  type OutputFormat,
} from './utils/output';
