-- @generated by scripts/gen-migrations.ts — DO NOT EDIT.
-- id: hasna_auth_0002_api_keys_indexes
-- checksum: sha256:4e646262846e9ae664b5b0d67cb079f788c85d45fcc3a323131df5aa9ba7b777

CREATE INDEX IF NOT EXISTS api_keys_app_idx ON api_keys (app);
            CREATE INDEX IF NOT EXISTS api_keys_token_hash_idx ON api_keys (token_hash);
