-- @generated by scripts/gen-migrations.ts — DO NOT EDIT.
-- id: hasna_auth_0001_api_keys
-- checksum: sha256:95429079245944aa39727486cf92dea0ae8a1bfa889e1940f2d9911eb0b020a5

CREATE TABLE IF NOT EXISTS api_keys (
    kid TEXT PRIMARY KEY,
    app TEXT NOT NULL,
    agent TEXT,
    scopes JSONB NOT NULL,
    token_hash TEXT NOT NULL UNIQUE,
    issued_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    revoked_reason TEXT,
    last_used_at TIMESTAMPTZ,
    created_by TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
  )
