/**
 * Registry of the @hasna/* packages this CLI manages.
 *
 * NOTE (reconstruction provenance, 2026-08-20): this list is the EMBEDDED
 * registry extracted byte-for-byte from the published @hasna/agency@0.3.1
 * bundle. It is STALE BY DESIGN: it covers 45 of ~176 first-party packages
 * and is not updated by any dynamic registry or GitHub lookup. Do not treat
 * it as the package census; the live census of the hasna/apps monorepo is
 * the name-conformance gate there.
 */

export interface PackageEntry {
  name: string;
  npm: string;
  description: string;
  bins: { cli?: string; mcp?: string; serve?: string };
  hasDb: boolean;
  hasMcp: boolean;
  hasHttp: boolean;
  dataDir: string;
}

export const REGISTRY: PackageEntry[] = [
  {
    name: "assistants",
    npm: "@hasna/assistants",
    description: "Personal AI assistant that runs in your terminal — powered by Claude",
    bins: { cli: "assistants" },
    hasDb: true,
    hasMcp: false,
    hasHttp: false,
    dataDir: "assistants",
  },
  {
    name: "attachments",
    npm: "@hasna/attachments",
    description: "File transfer for AI agents — S3-backed upload, shareable links, CLI + MCP + REST API",
    bins: { cli: "attachments", mcp: "attachments-mcp" },
    hasDb: true,
    hasMcp: true,
    hasHttp: false,
    dataDir: "attachments",
  },
  {
    name: "brains",
    npm: "@hasna/brains",
    description: "Fine-tuned model tracker and trainer — wraps OpenAI + Thinker Labs",
    bins: { cli: "brains", mcp: "brains-mcp", serve: "brains-serve" },
    hasDb: true,
    hasMcp: true,
    hasHttp: true,
    dataDir: "brains",
  },
  {
    name: "browser",
    npm: "@hasna/browser",
    description: "General-purpose browser agent toolkit — Playwright, CDP, Lightpanda",
    bins: { cli: "browser", mcp: "browser-mcp", serve: "browser-serve" },
    hasDb: true,
    hasMcp: true,
    hasHttp: true,
    dataDir: "browser",
  },
  {
    name: "cloud",
    npm: "@hasna/cloud",
    description: "Shared cloud infrastructure — database adapter (SQLite + PostgreSQL), sync engine",
    bins: { cli: "cloud", mcp: "cloud-mcp" },
    hasDb: false,
    hasMcp: true,
    hasHttp: false,
    dataDir: "cloud",
  },
  {
    name: "coders",
    npm: "@hasna/coders",
    description: "Open-source coding agent CLI with native @hasna/* ecosystem integration",
    bins: { cli: "coders" },
    hasDb: true,
    hasMcp: false,
    hasHttp: false,
    dataDir: "coders",
  },
  {
    name: "configs",
    npm: "@hasna/configs",
    description: "AI coding agent configuration manager — store, version, apply, share configs",
    bins: { cli: "configs", mcp: "configs-mcp", serve: "configs-serve" },
    hasDb: true,
    hasMcp: true,
    hasHttp: true,
    dataDir: "configs",
  },
  {
    name: "connectors",
    npm: "@hasna/connectors",
    description: "Open source connector library — install API connectors with a single command",
    bins: { cli: "connectors", mcp: "connectors-mcp", serve: "connectors-serve" },
    hasDb: true,
    hasMcp: true,
    hasHttp: true,
    dataDir: "connectors",
  },
  {
    name: "contacts",
    npm: "@hasna/contacts",
    description: "Contact management for AI coding agents — CLI + MCP + Web",
    bins: { cli: "contacts", mcp: "contacts-mcp", serve: "contacts-serve" },
    hasDb: true,
    hasMcp: true,
    hasHttp: true,
    dataDir: "contacts",
  },
  {
    name: "context",
    npm: "@hasna/context",
    description: "Self-hosted documentation context server — crawl, index, query library docs",
    bins: { cli: "context", mcp: "context-mcp", serve: "context-serve" },
    hasDb: true,
    hasMcp: true,
    hasHttp: true,
    dataDir: "context",
  },
  {
    name: "conversations",
    npm: "@hasna/conversations",
    description: "Real-time CLI messaging for AI agents",
    bins: { cli: "conversations", mcp: "conversations-mcp" },
    hasDb: true,
    hasMcp: true,
    hasHttp: false,
    dataDir: "conversations",
  },
  {
    name: "deployment",
    npm: "@hasna/deployment",
    description: "General-purpose deployment orchestration for AI agents",
    bins: { cli: "deployment", mcp: "deployment-mcp", serve: "deployment-serve" },
    hasDb: true,
    hasMcp: true,
    hasHttp: true,
    dataDir: "deployment",
  },
  {
    name: "economy",
    npm: "@hasna/economy",
    description: "AI coding cost tracker — CLI + MCP + REST API + web dashboard",
    bins: { cli: "economy", mcp: "economy-mcp", serve: "economy-serve" },
    hasDb: true,
    hasMcp: true,
    hasHttp: true,
    dataDir: "economy",
  },
  {
    name: "emails",
    npm: "@hasna/emails",
    description: "Email management CLI + MCP server + dashboard for Resend and AWS SES",
    bins: { cli: "emails", mcp: "emails-mcp", serve: "emails-serve" },
    hasDb: true,
    hasMcp: true,
    hasHttp: true,
    dataDir: "emails",
  },
  {
    name: "files",
    npm: "@hasna/files",
    description: "Agent-first file management — index local folders and S3 buckets, tag, search",
    bins: { cli: "files", mcp: "files-mcp", serve: "files-serve" },
    hasDb: true,
    hasMcp: true,
    hasHttp: true,
    dataDir: "files",
  },
  {
    name: "hooks",
    npm: "@hasna/hooks",
    description: "Open source hooks library — safety, quality, and automation hooks",
    bins: { cli: "hooks" },
    hasDb: true,
    hasMcp: false,
    hasHttp: false,
    dataDir: "hooks",
  },
  {
    name: "implementations",
    npm: "@hasna/implementations",
    description: "Plans, audits, and logs for AI coding agents",
    bins: { cli: "implementations", mcp: "implementations-mcp", serve: "implementations-serve" },
    hasDb: true,
    hasMcp: true,
    hasHttp: true,
    dataDir: "implementations",
  },
  {
    name: "logs",
    npm: "@hasna/logs",
    description: "Log aggregation + browser script + headless page scanner + performance monitoring",
    bins: { cli: "logs", mcp: "logs-mcp", serve: "logs-serve" },
    hasDb: true,
    hasMcp: true,
    hasHttp: true,
    dataDir: "logs",
  },
  {
    name: "markdown",
    npm: "@hasna/markdown",
    description: "Open Markdown Protocol (OMP) — structured markdown as intermediate representation",
    bins: { cli: "omp", mcp: "omp-mcp", serve: "omp-serve" },
    hasDb: false,
    hasMcp: true,
    hasHttp: true,
    dataDir: "markdown",
  },
  {
    name: "mcps",
    npm: "@hasna/mcps",
    description: "Meta-MCP registry & CLI — discover, manage, and proxy MCP servers",
    bins: { cli: "mcps", mcp: "mcps-mcp" },
    hasDb: true,
    hasMcp: true,
    hasHttp: false,
    dataDir: "mcps",
  },
  {
    name: "mementos",
    npm: "@hasna/mementos",
    description: "Universal memory system for AI agents — CLI + MCP server + library API",
    bins: { cli: "mementos", mcp: "mementos-mcp", serve: "mementos-serve" },
    hasDb: true,
    hasMcp: true,
    hasHttp: true,
    dataDir: "mementos",
  },
  {
    name: "microservices",
    npm: "@hasna/microservices",
    description: "Mini business apps for AI agents — invoices, contacts, bookkeeping and more",
    bins: { cli: "microservices", mcp: "microservices-mcp" },
    hasDb: true,
    hasMcp: true,
    hasHttp: false,
    dataDir: "microservices",
  },
  {
    name: "netwatch",
    npm: "@hasna/netwatch",
    description: "Live network traffic monitor — track data usage per interface",
    bins: { cli: "netwatch" },
    hasDb: false,
    hasMcp: false,
    hasHttp: false,
    dataDir: "netwatch",
  },
  {
    name: "predictor",
    npm: "@hasna/predictor",
    description: "Swarm intelligence prediction engine — multi-agent simulation, persona generation",
    bins: { cli: "predictor", mcp: "predictor-mcp" },
    hasDb: true,
    hasMcp: true,
    hasHttp: false,
    dataDir: "predictor",
  },
  {
    name: "prompts",
    npm: "@hasna/prompts",
    description: "Reusable prompt library for AI agents — CLI + MCP + REST API + web dashboard",
    bins: { cli: "prompts", mcp: "prompts-mcp", serve: "prompts-serve" },
    hasDb: true,
    hasMcp: true,
    hasHttp: true,
    dataDir: "prompts",
  },
  {
    name: "recordings",
    npm: "@hasna/recordings",
    description: "Speech-to-text recording tool — records, transcribes, and enhances text using AI",
    bins: { cli: "recordings", mcp: "recordings-mcp" },
    hasDb: true,
    hasMcp: true,
    hasHttp: false,
    dataDir: "recordings",
  },
  {
    name: "researcher",
    npm: "@hasna/researcher",
    description: "Universal autonomous experimentation framework — PFLK/GREE cycles, knowledge graphs",
    bins: { cli: "researcher" },
    hasDb: true,
    hasMcp: false,
    hasHttp: false,
    dataDir: "researcher",
  },
  {
    name: "sandboxes",
    npm: "@hasna/sandboxes",
    description: "Universal cloud sandbox manager — supports e2b, Daytona, Modal",
    bins: { cli: "sandboxes", mcp: "sandboxes-mcp", serve: "sandboxes-serve" },
    hasDb: true,
    hasMcp: true,
    hasHttp: true,
    dataDir: "sandboxes",
  },
  {
    name: "scaffolds",
    npm: "@hasna/scaffolds",
    description: "App scaffolds for AI agents — saas, agent, blog, news, social, competition",
    bins: { cli: "scaffolds", mcp: "scaffolds-mcp" },
    hasDb: false,
    hasMcp: true,
    hasHttp: false,
    dataDir: "scaffolds",
  },
  {
    name: "search",
    npm: "@hasna/search",
    description: "Unified search aggregator — 12 providers + YouTube transcription",
    bins: { cli: "search", mcp: "search-mcp", serve: "search-serve" },
    hasDb: true,
    hasMcp: true,
    hasHttp: true,
    dataDir: "search",
  },
  {
    name: "secrets",
    npm: "@hasna/secrets",
    description: "Local secrets vault for AI agents — store API keys, passwords, tokens",
    bins: { cli: "secrets" },
    hasDb: true,
    hasMcp: false,
    hasHttp: false,
    dataDir: "secrets",
  },
  {
    name: "security",
    npm: "@hasna/security",
    description: "AI-powered security scanner for git repos — CLI, MCP, API, Web Dashboard",
    bins: { cli: "security", mcp: "security-mcp", serve: "security-serve" },
    hasDb: true,
    hasMcp: true,
    hasHttp: true,
    dataDir: "security",
  },
  {
    name: "sessions",
    npm: "@hasna/sessions",
    description: "Session search and management for AI coding agents",
    bins: { cli: "sessions", mcp: "sessions-mcp", serve: "sessions-serve" },
    hasDb: true,
    hasMcp: true,
    hasHttp: true,
    dataDir: "sessions",
  },
  {
    name: "signatures",
    npm: "@hasna/signatures",
    description: "Open source e-signature platform — sign PDFs locally, manage documents",
    bins: { cli: "open-signatures", mcp: "signatures-mcp", serve: "signatures-serve" },
    hasDb: true,
    hasMcp: true,
    hasHttp: true,
    dataDir: "signatures",
  },
  {
    name: "skills",
    npm: "@hasna/skills",
    description: "Skills library for AI coding agents",
    bins: { cli: "skills", mcp: "skills-mcp" },
    hasDb: true,
    hasMcp: true,
    hasHttp: false,
    dataDir: "skills",
  },
  {
    name: "styles",
    npm: "@hasna/styles",
    description: "Style management platform — profiles, preferences, health checks, design system",
    bins: { cli: "styles", mcp: "styles-mcp" },
    hasDb: true,
    hasMcp: true,
    hasHttp: false,
    dataDir: "styles",
  },
  {
    name: "swarm",
    npm: "@hasna/swarm",
    description: "Autonomous swarm orchestrator for headless AI agent CLIs",
    bins: { cli: "swarm", mcp: "swarm-mcp", serve: "swarm-serve" },
    hasDb: true,
    hasMcp: true,
    hasHttp: true,
    dataDir: "swarm",
  },
  {
    name: "telephony",
    npm: "@hasna/telephony",
    description: "Telephony platform for AI agents — SMS, WhatsApp, voice calls, TTS/STT",
    bins: { cli: "telephony", mcp: "telephony-mcp", serve: "telephony-serve" },
    hasDb: true,
    hasMcp: true,
    hasHttp: true,
    dataDir: "telephony",
  },
  {
    name: "terminal",
    npm: "@hasna/terminal",
    description: "Smart terminal wrapper for AI agents — structured output, token compression, MCP",
    bins: { cli: "terminal" },
    hasDb: true,
    hasMcp: false,
    hasHttp: false,
    dataDir: "terminal",
  },
  {
    name: "testers",
    npm: "@hasna/testers",
    description: "AI-powered QA testing CLI — spawns cheap AI agents to test web apps",
    bins: { cli: "testers", mcp: "testers-mcp", serve: "testers-serve" },
    hasDb: true,
    hasMcp: true,
    hasHttp: true,
    dataDir: "testers",
  },
  {
    name: "tickets",
    npm: "@hasna/tickets",
    description: "MCP-native ticketing system — bugs, features, incidents",
    bins: { cli: "tickets", mcp: "tickets-mcp", serve: "tickets-serve" },
    hasDb: true,
    hasMcp: true,
    hasHttp: true,
    dataDir: "tickets",
  },
  {
    name: "todos",
    npm: "@hasna/todos",
    description: "Universal task management for AI coding agents — CLI + MCP + TUI",
    bins: { cli: "todos", mcp: "todos-mcp", serve: "todos-serve" },
    hasDb: true,
    hasMcp: true,
    hasHttp: true,
    dataDir: "todos",
  },
  {
    name: "agent-utils",
    npm: "@hasna/agent-utils",
    description: "Shared utilities for token-efficient AI agent MCP servers and CLIs",
    bins: {},
    hasDb: false,
    hasMcp: false,
    hasHttp: false,
    dataDir: "agent-utils",
  },
  {
    name: "wallets",
    npm: "@hasna/wallets",
    description: "Universal wallet management for AI agents — multi-provider support",
    bins: { cli: "wallets", mcp: "wallets-mcp" },
    hasDb: true,
    hasMcp: true,
    hasHttp: false,
    dataDir: "wallets",
  },
];

export function findPackage(name: string): PackageEntry | undefined {
  return REGISTRY.find((p) => p.name === name);
}

export function mcpPackages(): PackageEntry[] {
  return REGISTRY.filter((p) => p.hasMcp);
}

export function dbPackages(): PackageEntry[] {
  return REGISTRY.filter((p) => p.hasDb);
}

export const PACKAGE_COUNT = REGISTRY.length;
