// Public SDK exports. Internal modules still use storage-layer workspace names;
// the package boundary exposes the project domain.
export {
  AGENT_KINDS,
  AGENT_RUN_STATUSES,
  EVENT_SOURCES,
  MACHINE_ROLES,
  PROJECT_AGENT_ROLES,
  PROJECT_RESOURCE_AUTHORITIES,
  PROJECT_RESOURCE_LINK_DEFAULT_MAX_ITEMS,
  PROJECT_RESOURCE_LINK_MIGRATION_STATES,
  PROJECT_RESOURCE_LINK_SCOPES,
  PROJECT_RESOURCE_LOCATOR_KINDS,
  WORKSPACE_KINDS as PROJECT_KINDS,
  WORKSPACE_STATUSES as PROJECT_STATUSES,
} from "./types/workspace.js";
export type {
  Agent,
  AgentKind,
  AgentRun,
  AgentRunStatus,
  CreateAgentInput,
  CreateRecipeInput,
  CreateRootInput,
  CreateTmuxProfileInput,
  CreateTmuxProfileWindowInput,
  CreateWorkspaceInput as CreateProjectInput,
  EventSource,
  JsonObject,
  Machine,
  MachineRole,
  ProjectAgentRole,
  ProjectResourceAuthority,
  ProjectResourceExternalUuidLocator,
  ProjectResourceLink,
  ProjectResourceLinkInput,
  ProjectResourceLinkLabels,
  ProjectResourceLinkLocator,
  ProjectResourceLinkMutationMode,
  ProjectResourceLinkMutationRequest,
  ProjectResourceLinkMutationResult,
  ProjectResourceLinkMigrationAdvanceRequest,
  ProjectResourceLinkMigrationEvent,
  ProjectResourceLinkMigrationItem,
  ProjectResourceLinkMigrationManifestV1,
  ProjectResourceLinkMigrationPlanRequest,
  ProjectResourceLinkMigrationReadRequest,
  ProjectResourceLinkMigrationResult,
  ProjectResourceLinkMigrationRollbackRequest,
  ProjectResourceLinkMigrationState,
  ProjectResourceLinkProducerBinding,
  ProjectResourceLinkProducerEvidence,
  ProjectResourceLinkProjectsReferenceProof,
  ProjectResourceLinkReadRequest,
  ProjectResourceLinkReadResult,
  ProjectResourceLinkRollbackRequest,
  ProjectResourceLinkScope,
  ProjectResourceLinkSnapshot,
  ProjectResourceLocatorKind,
  ProjectResourceTargetKind,
  Recipe,
  RecordWorkspaceEventInput as RecordProjectEventInput,
  Root,
  TmuxProfile,
  TmuxProfileWindow,
  UpdateRootInput,
  UpdateWorkspaceInput as UpdateProjectInput,
  Workspace as Project,
  WorkspaceAgentAssignment as ProjectAgentAssignment,
  WorkspaceEvent as ProjectEvent,
  WorkspaceIntegrations as ProjectIntegrations,
  WorkspaceKind as ProjectKind,
  WorkspaceLocation as ProjectLocation,
  WorkspaceLock as ProjectLock,
  WorkspaceStatus as ProjectStatus,
} from "./types/workspace.js";
export {
  normalizeProjectResourceLink,
  normalizeProjectResourceLinks,
  projectResourceLinkId,
  projectResourceLinkIdentity,
  projectResourceLinkIntegrationProjection,
  projectResourceLinkCollection,
  projectResourceLinksDigest,
  projectResourceLinkSnapshot,
} from "./lib/project-resource-links.js";
export {
  buildProjectResourceLinkMigrationPlan,
  projectResourceLinkMigrationEventId,
  projectResourceLinkMigrationManifestId,
  projectResourceLinkProducerAttestationId,
  projectResourceLinkProducerEvidenceDigest,
  type AsyncProjectResourceLinkProducerEvidenceVerifier,
  type ProjectResourceLinkProducerAttestation,
  type ProjectResourceLinkProducerAttestationPhase,
  type ProjectResourceLinkProducerEvidenceVerifier,
  type ProjectResourceLinkProducerVerificationInput,
} from "./lib/project-resource-link-migrations.js";
export {
  ProjectResourceAuthoritySchema,
  ProjectResourceLinkCollectionV1Schema,
  ProjectResourceLinkInputSchema,
  ProjectResourceLinkLabelsSchema,
  ProjectResourceLinkLocatorSchema,
  ProjectResourceLinkSchema,
  ProjectResourceTargetKindSchema,
} from "@hasna/contracts/schemas";
export {
  PROJECT_CONTACT_LINK_STEPS,
  PROJECT_CONTACT_RESOURCE_LINK_TYPE,
  ProjectContactLinkOperationError,
  attachProjectContact,
  detachProjectContact,
  listProjectContacts,
  projectContactResourceLink,
} from "./lib/project-contact-links.js";
export type {
  ContactProjectMembershipAuthority,
  ContactProjectMembershipListResult,
  ContactProjectMembershipMutationInput,
  ContactProjectMembershipMutationResult,
  ContactProjectMembershipSnapshot,
  ProjectContactLinkBounds,
  ProjectContactLinkDependencies,
  ProjectContactLinkErrorCode,
  ProjectContactLinkEvidence,
  ProjectContactLinkListOutput,
  ProjectContactLinkMutationInput,
  ProjectContactLinkMutationOutput,
} from "./lib/project-contact-links.js";
export {
  ContactsAuthorityHttpError,
  ContactsHttpProjectMembershipAuthority,
  createContactsProjectMembershipAuthorityFromEnv,
} from "./lib/contacts-authority-adapter.js";
export type {
  ContactsAuthorityEnvironment,
  ContactsHttpProjectMembershipAuthorityOptions,
} from "./lib/contacts-authority-adapter.js";
export {
  listProjectResourceLinks,
  mutateProjectResourceLinks,
  advanceProjectResourceLinkMigration,
  planProjectResourceLinkMigration,
  readProjectResourceLinkMigration,
  readProjectResourceLinks,
  rollbackProjectResourceLinkMigration,
  rollbackProjectResourceLinks,
} from "./db/workspaces.js";
export { getDatabase } from "./db/database.js";
export {
  PROJECT_STORE_SCHEMA_VERSION,
  PROJECT_STORE_TABLES,
  createProjectDataModel,
  createProjectDataRecord,
  deleteProjectDataExact,
  ensureProjectStore as ensureProjectAppStore,
  ensureProjectStoreDirs as ensureProjectAppStoreDirs,
  getProjectDataModel,
  getProjectDataRecord,
  getProjectDatabase as getProjectAppDatabase,
  getProjectLoopLink,
  getProjectStorePaths as getProjectAppStorePaths,
  inspectProjectStore as inspectProjectAppStore,
  inspectProjectStoreWithLoops as inspectProjectAppStoreWithLoops,
  linkProjectLoop,
  listProjectDataModels,
  listProjectDataRecords,
  listProjectLoopLinks,
  listProjectLoopSummaries,
  runProjectStoreMigrations,
} from "./db/project-store.js";
export type {
  CreateProjectDataModelInput,
  CreateProjectDataRecordInput,
  DeleteProjectDataExactInput,
  LinkProjectLoopInput,
  LoopsClientLike,
  ProjectDataModel,
  ProjectDataModelDeleteTarget,
  ProjectDataRecord,
  ProjectDataRecordDeleteTarget,
  ProjectDataExactDeleteResult,
  ProjectLoopLink,
  ProjectLoopRunSummary,
  ProjectLoopSummary,
  ProjectStorePaths as ProjectAppStorePaths,
  ProjectStoreProject as ProjectAppStoreProject,
  ProjectStoreSummary as ProjectAppStoreSummary,
  ProjectStoreTable as ProjectAppStoreTable,
} from "./db/project-store.js";
export {
  createRoot,
  getRoot,
  getRootBySlug,
  listRoots,
  updateRoot,
  deleteRoot,
  scoreRoots,
  matchRoot,
  matchRootForPath,
  createAgent,
  getAgent,
  getAgentBySlug,
  listAgents,
  getMachine,
  listMachines,
  ensureCliAgent,
  mergeAgentPermissions,
  createRecipe,
  getRecipe,
  getRecipeBySlug,
  listRecipes,
  createTmuxProfile,
  getTmuxProfile,
  getTmuxProfileBySlug,
  resolveTmuxProfile,
  listTmuxProfiles,
  addTmuxProfileWindow,
  listTmuxProfileWindows,
  createWorkspace as createProject,
  updateWorkspace as updateProject,
  archiveWorkspace as archiveProject,
  unarchiveWorkspace as unarchiveProject,
  deleteWorkspace as deleteProject,
  getWorkspace as getProject,
  getWorkspaceBySlug as getProjectBySlug,
  getWorkspaceByPath as getProjectByPath,
  listWorkspacesByPath as listProjectsByPath,
  listWorkspaces as listProjects,
  resolveWorkspace as resolveProject,
  addWorkspaceLocation as addProjectLocation,
  listWorkspaceLocations as listProjectLocations,
  getWorkspaceLocationByPath as getProjectLocationByPath,
  assignAgentToWorkspace as assignAgentToProject,
  listWorkspaceAgents as listProjectAgents,
  recordWorkspaceEvent as recordProjectEvent,
  listWorkspaceEvents as listProjectEvents,
  startAgentRun,
  completeAgentRun,
  listAgentRuns,
  acquireWorkspaceLock as acquireProjectLock,
  releaseWorkspaceLock as releaseProjectLock,
  listWorkspaceLocks as listProjectLocks,
  linkWorkspaceIntegrations as linkProjectIntegrations,
  inferWorkspaceKind as inferProjectKind,
  migrateLegacyProjectsToWorkspaces as migrateLegacyProjects,
  renderTemplate,
  workspaceSlugify as projectSlugify,
  generateWorkspaceId as generateProjectId,
  generateWorkspaceEventId as generateProjectEventId,
  generateWorkspaceLockId as generateProjectLockId,
} from "./db/workspaces.js";
export {
  applyWorkspaceTmux as applyProjectTmux,
  applyWorkspaceTmuxProfile as applyProjectTmuxProfile,
  buildWorkspaceMarker as buildProjectMarker,
  prepareWorkspaceDirectory as prepareProjectDirectory,
  projectMarkerPath,
  tmuxProfileToSpec,
  writeWorkspaceMarker as writeProjectMarker,
} from "./lib/workspace-runtime.js";
export type {
  ApplyWorkspaceTmuxOptions as ApplyProjectTmuxOptions,
  PrepareWorkspaceOptions as PrepareProjectOptions,
  WorkspaceMarker as ProjectMarker,
  WorkspaceRuntimeAction as ProjectRuntimeAction,
  WorkspaceTmuxResult as ProjectTmuxResult,
  WorkspaceTmuxWindowSpec as ProjectTmuxWindowSpec,
} from "./lib/workspace-runtime.js";
export { doctorWorkspace as doctorProject, doctorWorkspaces as doctorProjects } from "./lib/workspace-doctor.js";
export { builtInWorkspaceRecipes as builtInProjectRecipes, ensureBuiltInWorkspaceRecipes as ensureBuiltInProjectRecipes } from "./lib/workspace-defaults.js";
export {
  importWorkspaceFromGitHub as importProjectFromGitHub,
  linkWorkspaceExternalIntegrations as linkProjectExternalIntegrations,
  normalizeWorkspaceIntegrations as normalizeProjectIntegrations,
  parseGitHubRepo,
  planWorkspaceGitHubImport as planProjectGitHubImport,
  planWorkspaceGitHubPublish as planProjectGitHubPublish,
  publishWorkspaceToGitHub as publishProjectToGitHub,
  unpublishWorkspaceFromGitHub as unpublishProjectFromGitHub,
} from "./lib/workspace-github.js";
export type {
  GitHubRemoteProtocol,
  GitHubVisibility,
  WorkspaceGitHubImportOptions as ProjectGitHubImportOptions,
  WorkspaceGitHubImportResult as ProjectGitHubImportResult,
  WorkspaceGitHubPublishOptions as ProjectGitHubPublishOptions,
  WorkspaceGitHubPublishResult as ProjectGitHubPublishResult,
  WorkspaceGitHubUnpublishOptions as ProjectGitHubUnpublishOptions,
  WorkspaceGitHubUnpublishResult as ProjectGitHubUnpublishResult,
} from "./lib/workspace-github.js";
export { importRegisteredRoots, importWorkspace as importProject, importWorkspaceBulk as importProjectBulk, planWorkspaceImport as planProjectImport } from "./lib/workspace-import.js";
export {
  PROJECT_START_AGENTS,
  PROJECT_START_SESSION_POLICIES,
  parseProjectStartAgent,
  parseProjectStartSessionPolicy,
  projectStartCommand,
  resolveProjectStartTarget,
  startProject,
} from "./lib/project-start.js";
export type {
  ProjectStartAgent,
  ProjectStartOptions,
  ProjectStartResolution,
  ProjectStartResult,
  ProjectStartSessionPolicy,
} from "./lib/project-start.js";
export { projectTmuxStatus } from "./lib/project-tmux-status.js";
export type { ProjectTmuxStatusOptions, ProjectTmuxStatusResult } from "./lib/project-tmux-status.js";
export {
  PROJECT_PREFIXES,
  PROJECT_PREFIX_MIGRATION_EVENT,
  createConversationsPrefixPort,
  runProjectPrefixMigration,
  stripProjectPrefix,
} from "./lib/project-prefix-migration.js";
export type {
  CompleteChannelPopulation,
  ConversationsChannelIdentity,
  ConversationsPrefixPort,
  PrefixMigrationInventory,
  PrefixMigrationReceipt,
  PrefixMigrationResult,
  PrefixMigrationStep,
  RunProjectPrefixMigrationOptions,
} from "./lib/project-prefix-migration.js";
export {
  isProjectDirectory,
  isProjectPathLike,
  normalizeProjectPath,
  readProjectMarker,
  resolveRegisteredProjectTarget,
  resolveRegisteredProjectTargetOrThrow,
} from "./lib/project-resolver.js";
export {
  PROJECTS_HOME_ENV,
  getProjectsHome,
  isProjectWorkspaceStorePath,
  projectDataStorePath,
  projectWorkspaceStorePath,
} from "./lib/project-store-paths.js";
export {
  ensureProjectStore,
  inspectProjectStore,
  migrateProjectToStore,
  planProjectStoreMigration,
  projectStorePaths,
} from "./lib/project-store.js";
export type {
  ProjectStoreEnsureResult,
  ProjectStoreInspection,
  ProjectStoreMigrationAction,
  ProjectStoreMigrationPlan,
  ProjectStoreMigrationResult,
  ProjectStorePaths,
} from "./lib/project-store.js";
export {
  BUILD_OUTPUT_DIRS,
  DATABASE_EXTENSIONS,
  DEPENDENCY_TREE_DIRS,
  DEPENDENCY_TREE_MARKERS,
  PROVIDER_CACHE_DIRS,
  TOOL_CACHE_DIRS,
  classifyDirectory,
  classifyFile,
} from "./lib/sync-scope.js";
export type {
  ClassifyDirectoryOptions,
  ClassifyFileOptions,
  DirectoryProbe,
  SyncExclusionReason,
  SyncScopeDecision,
} from "./lib/sync-scope.js";
export {
  DEFAULT_OSS_MATRIX_LIMIT,
  MAX_OSS_MATRIX_LIMIT,
  OSS_PROJECT_MATRIX_SCHEMA_VERSION,
  buildOssProjectMatrix,
} from "./lib/oss-project-matrix.js";
export type {
  OssGitStatus,
  OssMatrixCommandOptions,
  OssMatrixCommandRunner,
  OssPackageMetadata,
  OssProjectMatrix,
  OssProjectMatrixOptions,
  OssProjectMatrixRow,
  OssPullRequestRef,
  OssTaskRef,
  OssTmuxHint,
} from "./lib/oss-project-matrix.js";
export type {
  ProjectMarkerReference,
  ProjectResolverOptions,
  ProjectResolverSource,
  ProjectTargetResolution,
} from "./lib/project-resolver.js";
export {
  PROJECT_MANAGEMENT_TAXONOMY,
  PROJECT_PRIORITIES,
  PROJECT_STAGES,
  expandProjectIntegrationUnlinkKey,
  expandProjectIntegrationUnlinkKeys,
  hasProjectIntegrationFields,
  hasProjectManagementFields,
  mergeProjectIntegrationFields,
  mergeProjectManagementMetadata,
  mergeProjectTags,
  projectDashboardSummary,
  projectExternalLinksSummary,
  projectManagementSummary,
  projectPathHealth,
  projectWithManagement,
  removeProjectTags,
  unlinkProjectIntegrationFields,
} from "./lib/project-management.js";
export type {
  ProjectDashboardSummary,
  ProjectExternalLinksSummary,
  ProjectIntegrationUnlinkGroup,
  ProjectIntegrationInput,
  ProjectManagementMetadataInput,
  ProjectManagementSummary,
  ProjectPathHealth,
  ProjectPriority,
  ProjectStage,
} from "./lib/project-management.js";
export { runWorkspaceLegacyMigration as runLegacyProjectMigration } from "./lib/workspace-migration.js";
export type {
  WorkspaceMigrationChecklistItem as LegacyProjectMigrationChecklistItem,
  WorkspaceMigrationOptions as LegacyProjectMigrationOptions,
  WorkspaceMigrationReport as LegacyProjectMigrationReport,
} from "./lib/workspace-migration.js";
export {
  cleanupWorkspaceCreation as cleanupProjectCreation,
  cleanupWorkspaceCreationTarget as cleanupProjectCreationTarget,
  executeWorkspaceCreation as executeProjectCreation,
  planWorkspaceCreation as planProjectCreation,
} from "./lib/workspace-plan.js";
export type {
  WorkspaceCreationCleanup as ProjectCreationCleanup,
  WorkspaceCreationCleanupAction as ProjectCreationCleanupAction,
  WorkspaceCreationCleanupTarget as ProjectCreationCleanupTarget,
  WorkspaceCreationExecution as ProjectCreationExecution,
  WorkspaceCreationPlan as ProjectCreationPlan,
  WorkspaceCreationPlanAction as ProjectCreationPlanAction,
  WorkspaceCreationPlanInput as ProjectCreationPlanInput,
} from "./lib/workspace-plan.js";
export {
  PROJECT_REGISTRATION_DEPENDENCY_TASKS,
  PROJECT_REGISTRATION_GOALS_FILENAME,
  PROJECT_REGISTRATION_MAX_RECEIPTS,
  PROJECT_REGISTRATION_ROUTE,
  RETIRED_PROJECT_REGISTRATION_PREFIXES,
  ProjectRegistrationPathHandle,
  assertCurrentProjectRegistrationSlug,
  deriveProjectRegistrationIdempotencyKey,
  listProjectRegistrationReceipts,
  lookupProjectRegistrationReceipt,
  preflightProjectRegistrationAuthorities,
  registerFullProject,
  unavailableProjectRegistrationAuthorities,
} from "./lib/project-registration.js";
export type {
  FullProjectRegistrationInput,
  FullProjectRegistrationProjectInput,
  FullProjectRegistrationReconciliationInput,
  FullProjectRegistrationResult,
  ProjectRegistrationExistingAuthorityReconciliation,
  ProjectRegistrationExistingConversationsChannelReconciliation,
  ProjectRegistrationExistingMementosProjectReconciliation,
  ProjectRegistrationArtifact,
  ProjectRegistrationAuthorities,
  ProjectRegistrationAuthorityAdapter,
  ProjectRegistrationAuthorityCapability,
  ProjectRegistrationAuthorityInverseVerification,
  ProjectRegistrationAuthorityLookupRequest,
  ProjectRegistrationAuthorityLookupResult,
  ProjectRegistrationAuthorityName,
  ProjectRegistrationAuthorityReceipt,
  ProjectRegistrationAuthorityRecord,
  ProjectRegistrationAuthorityRequest,
  ProjectRegistrationBounds,
  ProjectRegistrationCapabilityBlocker,
  ProjectRegistrationCapabilityReport,
  ProjectRegistrationDirection,
  ProjectRegistrationOutcome,
  ProjectRegistrationReceipt,
  ProjectRegistrationReceiptLookupInput,
  ProjectRegistrationReceiptLookupResult,
  ProjectRegistrationResourceKind,
  ProjectRegistrationResponseControl,
} from "./lib/project-registration.js";
export {
  PROJECT_CHANNEL_CLASSES,
  PROJECT_CHANNEL_CLASS_INTEGRATION_KEY,
  PROJECT_CHANNEL_INTEGRATION_KEY,
  conversationsCliRunner,
  deriveProjectChannel,
  ensureProjectChannel,
  normalizeProjectChannelName,
  projectChannelSummary,
  resolveProjectChannel,
  resolveProjectChannelClass,
  resolveProjectChannelClassDetailed,
  resolveProjectChannelForProject,
  shouldEnsureProjectChannel,
} from "./lib/project-channel.js";
export type {
  ConversationsChannelRunner,
  ConversationsRunResult,
  EnsureProjectChannelOptions,
  ProjectChannelClass,
  ProjectChannelDerivation,
  ProjectChannelEnsureResult,
  ProjectChannelResolution,
  ProjectChannelSideEffects,
} from "./lib/project-channel.js";
export {
  DEFAULT_WORKSPACE_AGENT_MODEL as DEFAULT_PROJECT_AGENT_MODEL,
  PROJECT_AGENT_DESTRUCTIVE_TOOLS,
  PROJECT_AGENT_MUTATION_TOOLS,
  PROJECT_AGENT_READ_TOOLS,
  auditProjectAgentToolCalls,
  buildProjectAgentToolCatalog,
  buildWorkspaceAgentSystemPrompt as buildProjectAgentSystemPrompt,
  buildWorkspaceInventoryContext as buildProjectInventoryContext,
  resolveOpenRouterApiKey,
  runWorkspaceAgentPrompt as runProjectAgentPrompt,
  shouldRunProjectCreateFallback,
} from "./lib/workspace-agent.js";
export type {
  ProjectAgentMutationAudit,
  WorkspaceAgentPromptOptions as ProjectAgentPromptOptions,
  WorkspaceAgentPromptResult as ProjectAgentPromptResult,
} from "./lib/workspace-agent.js";
export {
  BudgetExceededError,
  assertProjectBudgets,
  assertProjectBudgetsAfterSpend,
  createProjectBudget,
  estimateProjectCostUsd,
  getProjectBudget,
  getProjectBudgetStatuses,
  listProjectBudgets,
  modelPricing,
  normalizeProjectUsage,
  openRouterCostFromMetadata,
  recordProjectSpend,
  resetProjectBudget,
} from "./lib/budget.js";
export type {
  CreateProjectBudgetInput,
  ProjectBudget,
  ProjectBudgetContext,
  ProjectBudgetMode,
  ProjectBudgetScopeType,
  ProjectBudgetSpend,
  ProjectBudgetStatus,
  ProjectBudgetTotals,
  ProjectBudgetWindow,
  ProjectSpendInput,
  ProjectUsage,
} from "./lib/budget.js";
export {
  WORKSPACE_AGENT_EVAL_CASE_IDS as PROJECT_AGENT_EVAL_CASE_IDS,
  parseWorkspaceAgentEvalCaseIds as parseProjectAgentEvalCaseIds,
  runWorkspaceAgentEval as runProjectAgentEval,
} from "./lib/workspace-agent-eval.js";
export {
  cleanupProjectEvalArtifacts,
  filterProjectEvalArtifacts,
  isProjectEvalArtifact,
} from "./lib/project-eval-artifacts.js";

export {
  syncWorkspaceGitHubRoots,
  type WorkspaceGitHubRootSyncOptions,
  type WorkspaceGitHubRootSyncResult,
  type WorkspaceGitHubRootSyncRootResult,
} from "./lib/workspace-github.js";

export {
  PROJECT_RENDER_SCHEMA_VERSION,
  projectsJsonRenderCatalog,
  projectsJsonRenderSchema,
  validateProjectsRenderSpec,
  isProjectsRenderSpec,
  buildProjectDataModelRender,
  buildProjectListRender,
  buildProjectDetailPayload,
  buildProjectSessionsPayload,
  buildProjectStartRender,
  buildProjectStartBulkRender,
  buildProjectStatusRender,
  buildRootsRender,
  buildRecipesRender,
  type ProjectsJsonRenderSpec,
} from "./lib/project-render.js";

export {
  buildProjectAgentContext,
  buildProjectHandoff,
  explainProjectResolution,
  getProjectAgentRunDetail,
  listProjectAgentRunsView,
  suggestProjectNextActions,
  toAgentText,
} from "./lib/project-agent-assist.js";
export type {
  ProjectAgentContext,
  ProjectAgentContextOptions,
  ProjectHandoff,
  ProjectHandoffOptions,
  ProjectNextAction,
  ProjectNextOptions,
  ProjectNextResult,
  ProjectRunDetail,
  ProjectRunDetailOptions,
  ProjectRunsOptions,
  ProjectRunsResult,
  ProjectWhyResult,
  ProjectWhyStep,
} from "./lib/project-agent-assist.js";

export {
  PROJECT_REDACTED_VALUE,
  isSensitiveProjectKey,
  redactProjectJsonObject,
  redactProjectText,
  redactProjectValue,
} from "./lib/redaction.js";
export {
  repairProjectPermissions,
} from "./lib/project-permissions.js";
export type {
  ProjectPermissionRepairAction,
  ProjectPermissionRepairOptions,
  ProjectPermissionRepairReason,
  ProjectPermissionRepairResult,
} from "./lib/project-permissions.js";
