// AUTO-GENERATED by scripts/generate-sdk.ts from src/server/openapi.ts — DO NOT EDIT BY HAND.
// Regenerate: bun run scripts/generate-sdk.ts

// @generated from OpenAPI by @hasna/contracts SDK generator — DO NOT EDIT.
// Source: Contacts V1 API 0.6.34

export interface Contact { "id"?: string; "first_name"?: string; "last_name"?: string; "display_name"?: string; "nickname"?: string | null; "company_id"?: string | null; "job_title"?: string | null; "notes"?: string | null; "source"?: string; "status"?: string; "sensitivity"?: string; "archived"?: boolean; "priority"?: number; "tags": Array<Tag>; "created_at"?: string; "updated_at"?: string }

export interface Company { "id"?: string; "name"?: string; "domain"?: string | null; "industry"?: string | null; "size"?: string | null; "founded_year"?: number | null; "notes"?: string | null; "is_owned_entity"?: boolean; "created_at"?: string; "updated_at"?: string }

export interface Tag { "id"?: string; "name"?: string; "color"?: string; "description"?: string | null; "created_at"?: string }

export interface CreateContactInput { "first_name"?: string; "last_name"?: string; "display_name"?: string; "nickname"?: string; "company_id"?: string; "job_title"?: string; "notes"?: string; "source"?: string; "status"?: string; "sensitivity"?: string }

export interface UpdateContactInput { "first_name"?: string; "last_name"?: string; "display_name"?: string; "nickname"?: string; "company_id"?: string; "job_title"?: string; "notes"?: string; "status"?: string }

export interface CreateCompanyInput { "name": string; "domain"?: string; "industry"?: string; "size"?: string; "founded_year"?: number; "notes"?: string; "is_owned_entity"?: boolean }

export interface UpdateCompanyInput { "name"?: string; "domain"?: string; "industry"?: string; "notes"?: string }

export interface CreateTagInput { "name": string; "color"?: string; "description"?: string }

export interface UpdateTagInput { "name"?: string; "color"?: string; "description"?: string }

export interface ProjectIdsInput { "project_ids": Array<string> }

export interface ContactProjectMembershipSnapshot { "contact_id": string; "project_id": string; "linked": boolean; "version": string }

export interface ContactProjectMembershipMutationInput { "operation_id": string; "step_id": string; "expected_version": string }

export interface ContactProjectMembershipMutationResult { "outcome": "accepted" | "duplicate_of_accepted"; "operation_id": string; "step_id": string; "before": ContactProjectMembershipSnapshot; "after": ContactProjectMembershipSnapshot; "receipt_id": string }

export interface ContactProjectMembershipListResult { "project_id": string; "contact_ids": Array<string>; "complete": boolean; "membership_revision": string }

export interface ContactsV1ClientOptions {
  /** Base URL, e.g. process.env.APP_API_URL. */
  baseUrl: string;
  /** API key, e.g. process.env.APP_API_KEY. Sent as the 'x-api-key' header. */
  apiKey?: string;
  /** Custom fetch (defaults to global fetch). */
  fetch?: typeof fetch;
  /** Extra headers merged into every request. */
  headers?: Record<string, string>;
}

export class ApiError extends Error {
  constructor(readonly status: number, message: string, readonly body: unknown) {
    super(message);
    this.name = "ApiError";
  }
}

export class ContactsV1Client {
  private readonly baseUrl: string;
  private readonly apiKey: string | undefined;
  private readonly fetchImpl: typeof fetch;
  private readonly baseHeaders: Record<string, string>;

  constructor(options: ContactsV1ClientOptions) {
    if (!options.baseUrl) throw new Error("ContactsV1Client requires a baseUrl.");
    this.baseUrl = options.baseUrl.replace(/\/$/, "");
    this.apiKey = options.apiKey;
    this.fetchImpl = options.fetch ?? globalThis.fetch;
    this.baseHeaders = options.headers ?? {};
  }

  private async request<T>(method: string, path: string, opts: { body?: unknown; query?: Record<string, unknown>; init?: RequestInit }): Promise<T> {
    const url = new URL(this.baseUrl + path);
    if (opts.query) {
      for (const [key, value] of Object.entries(opts.query)) {
        if (value !== undefined && value !== null) url.searchParams.set(key, String(value));
      }
    }
    const headers: Record<string, string> = { Accept: "application/json", ...this.baseHeaders, ...(opts.init?.headers as Record<string, string> | undefined) };
    if (this.apiKey) headers["x-api-key"] = this.apiKey;
    let payload: BodyInit | undefined;
    if (opts.body !== undefined) {
      headers["Content-Type"] = "application/json";
      payload = JSON.stringify(opts.body);
    }
    const response = await this.fetchImpl(url.toString(), { ...opts.init, method, headers, body: payload });
    const text = await response.text();
    const data = text ? (() => { try { return JSON.parse(text); } catch { return text; } })() : undefined;
    if (!response.ok) {
      throw new ApiError(response.status, `${method} ${path} failed: ${response.status}`, data);
    }
    return data as T;
  }

    /** List companies */
    async listCompanies(query?: { "industry"?: string; "limit"?: number; "offset"?: number }, init?: RequestInit): Promise<{ "companies"?: Array<Company>; "count"?: number }> {
      return this.request("GET", `/v1/companies`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Create a company */
    async createCompany(body: CreateCompanyInput, init?: RequestInit): Promise<{ "company"?: Company }> {
      return this.request("POST", `/v1/companies`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get a company by id */
    async getCompany(id: string, init?: RequestInit): Promise<{ "company"?: Company }> {
      return this.request("GET", `/v1/companies/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Delete a company */
    async deleteCompany(id: string, init?: RequestInit): Promise<{ "deleted"?: boolean; "id"?: string }> {
      return this.request("DELETE", `/v1/companies/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Update a company */
    async updateCompany(id: string, body: UpdateCompanyInput, init?: RequestInit): Promise<{ "company"?: Company }> {
      return this.request("PATCH", `/v1/companies/${encodeURIComponent(String(id))}`, {
        body,
        query: undefined,
        init,
      });
    }

    /** List contacts */
    async listContacts(query?: { "q"?: string; "company_id"?: string; "status"?: string; "tag_id"?: string; "limit"?: number; "offset"?: number }, init?: RequestInit): Promise<{ "contacts"?: Array<Contact>; "count"?: number }> {
      return this.request("GET", `/v1/contacts`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Create a contact */
    async createContact(body: CreateContactInput, init?: RequestInit): Promise<{ "contact"?: Contact }> {
      return this.request("POST", `/v1/contacts`, {
        body,
        query: undefined,
        init,
      });
    }

    /** List project ids attached to a contact */
    async getContactProjectIds(contactId: string, init?: RequestInit): Promise<{ "contact_id"?: string; "project_ids"?: Array<string> }> {
      return this.request("GET", `/v1/contacts/${encodeURIComponent(String(contactId))}/projects`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Atomically replace a contact's project memberships */
    async setContactProjects(contactId: string, body: ProjectIdsInput, init?: RequestInit): Promise<{ "contact_id"?: string; "project_ids"?: Array<string> }> {
      return this.request("PUT", `/v1/contacts/${encodeURIComponent(String(contactId))}/projects`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Attach a contact to a project idempotently */
    async linkContactToProject(contactId: string, projectId: string, init?: RequestInit): Promise<{ "attached"?: boolean; "contact_id"?: string; "project_id"?: string }> {
      return this.request("PUT", `/v1/contacts/${encodeURIComponent(String(contactId))}/projects/${encodeURIComponent(String(projectId))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Detach a contact from a project */
    async unlinkContactFromProject(contactId: string, projectId: string, init?: RequestInit): Promise<{ "removed"?: boolean; "contact_id"?: string; "project_id"?: string }> {
      return this.request("DELETE", `/v1/contacts/${encodeURIComponent(String(contactId))}/projects/${encodeURIComponent(String(projectId))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Attach a tag to a contact idempotently */
    async addTagToContact(contactId: string, tagId: string, init?: RequestInit): Promise<{ "attached"?: boolean; "contact_id"?: string; "tag_id"?: string }> {
      return this.request("PUT", `/v1/contacts/${encodeURIComponent(String(contactId))}/tags/${encodeURIComponent(String(tagId))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Remove a tag from a contact */
    async removeTagFromContact(contactId: string, tagId: string, init?: RequestInit): Promise<{ "removed"?: boolean; "contact_id"?: string; "tag_id"?: string }> {
      return this.request("DELETE", `/v1/contacts/${encodeURIComponent(String(contactId))}/tags/${encodeURIComponent(String(tagId))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Get a contact by id */
    async getContact(id: string, init?: RequestInit): Promise<{ "contact"?: Contact }> {
      return this.request("GET", `/v1/contacts/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Delete a contact */
    async deleteContact(id: string, init?: RequestInit): Promise<{ "deleted"?: boolean; "id"?: string }> {
      return this.request("DELETE", `/v1/contacts/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Update a contact */
    async updateContact(id: string, body: UpdateContactInput, init?: RequestInit): Promise<{ "contact"?: Contact }> {
      return this.request("PATCH", `/v1/contacts/${encodeURIComponent(String(id))}`, {
        body,
        query: undefined,
        init,
      });
    }

    /** List the complete authoritative contact membership collection for a project */
    async listContactProjectMemberships(projectId: string, query?: { "max_items": number }, init?: RequestInit): Promise<ContactProjectMembershipListResult> {
      return this.request("GET", `/v1/projects/${encodeURIComponent(String(projectId))}/contact-memberships`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Read one authoritative contact-project membership snapshot */
    async readContactProjectMembership(projectId: string, contactId: string, init?: RequestInit): Promise<ContactProjectMembershipSnapshot> {
      return this.request("GET", `/v1/projects/${encodeURIComponent(String(projectId))}/contact-memberships/${encodeURIComponent(String(contactId))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Attach a contact to a project under expected-version CAS with a replay-safe receipt */
    async attachContactProjectMembership(projectId: string, contactId: string, body: ContactProjectMembershipMutationInput, init?: RequestInit): Promise<ContactProjectMembershipMutationResult> {
      return this.request("POST", `/v1/projects/${encodeURIComponent(String(projectId))}/contact-memberships/${encodeURIComponent(String(contactId))}/attach`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Detach a contact from a project under expected-version CAS with a replay-safe receipt */
    async detachContactProjectMembership(projectId: string, contactId: string, body: ContactProjectMembershipMutationInput, init?: RequestInit): Promise<ContactProjectMembershipMutationResult> {
      return this.request("POST", `/v1/projects/${encodeURIComponent(String(projectId))}/contact-memberships/${encodeURIComponent(String(contactId))}/detach`, {
        body,
        query: undefined,
        init,
      });
    }

    /** List contact ids attached to a project */
    async listContactIdsByProject(projectId: string, init?: RequestInit): Promise<{ "project_id"?: string; "contact_ids"?: Array<string> }> {
      return this.request("GET", `/v1/projects/${encodeURIComponent(String(projectId))}/contacts`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Aggregate counts */
    async getStats(init?: RequestInit): Promise<{ "contacts"?: number; "companies"?: number; "tags"?: number }> {
      return this.request("GET", `/v1/stats`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** List tags */
    async listTags(query?: { "name"?: string }, init?: RequestInit): Promise<{ "tags"?: Array<Tag>; "count"?: number }> {
      return this.request("GET", `/v1/tags`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Create a tag */
    async createTag(body: CreateTagInput, init?: RequestInit): Promise<{ "tag"?: Tag }> {
      return this.request("POST", `/v1/tags`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get a tag by id */
    async getTag(id: string, init?: RequestInit): Promise<{ "tag"?: Tag }> {
      return this.request("GET", `/v1/tags/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Delete a tag */
    async deleteTag(id: string, init?: RequestInit): Promise<{ "deleted"?: boolean; "id"?: string }> {
      return this.request("DELETE", `/v1/tags/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Update a tag */
    async updateTag(id: string, body: UpdateTagInput, init?: RequestInit): Promise<{ "tag"?: Tag }> {
      return this.request("PATCH", `/v1/tags/${encodeURIComponent(String(id))}`, {
        body,
        query: undefined,
        init,
      });
    }
}
