import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import {
  handleMcpHttpRequest as harnessHandleMcpHttpRequest,
  isHttpMode as harnessIsHttpMode,
  resolveMcpHttpPort as harnessResolveMcpHttpPort,
  startBunHttpServer,
} from "./mcp-harness.js";

/**
 * secrets MCP transport/port boilerplate — thin shim over the vendored
 * harness (./mcp-harness.ts). Public API (options-object dialect) preserved;
 * transport/port/health removed.
 * Generated by open-mcp/scripts/adopt-harness.ts.
 */

export const MCP_HTTP_HOST = "127.0.0.1";
export const MCP_SERVICE_NAME = "secrets";
export const DEFAULT_MCP_HTTP_PORT = 8848;

export function isHttpMode(args: readonly string[] = process.argv): boolean {
  return harnessIsHttpMode(args);
}
export function resolveMcpHttpPort(args: readonly string[] = process.argv): number {
  return harnessResolveMcpHttpPort({ argv: args, default: DEFAULT_MCP_HTTP_PORT });
}
export function healthPayload(name: string = MCP_SERVICE_NAME): { status: string; name: string } {
  return { status: "ok", name };
}
export async function handleMcpRequest(
  req: Request,
  buildServer: () => McpServer,
): Promise<Response> {
  return harnessHandleMcpHttpRequest(req, buildServer);
}
export function startMcpHttpServer(options: {
  name: string;
  port: number;
  buildServer: () => McpServer;
}): { port: number; stop: () => void } {
  return startBunHttpServer(options.buildServer, {
    port: options.port,
    host: MCP_HTTP_HOST,
    serviceName: options.name,
  });
}
