#!/usr/bin/env bun
/**
 * Generate the typed `/v1` SDK client from the serve OpenAPI document.
 *
 * Source of truth: src/server/openapi.ts (also served at GET /openapi.json).
 * Output: src/sdk/v1.generated.ts — a dependency-free typed fetch client.
 *
 * Usage: bun run scripts/generate-sdk.ts
 */
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { generateSdkFromOpenApi } from "@hasna/contracts/sdk";
import { buildV1OpenApiDocument } from "../src/server/openapi.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const spec = buildV1OpenApiDocument();
const { code, operations, warnings } = generateSdkFromOpenApi(spec as never, {
  className: "CalendarV1Client",
  apiKeyHeader: "x-api-key",
});

const header =
  "// AUTO-GENERATED by scripts/generate-sdk.ts from src/server/openapi.ts — DO NOT EDIT BY HAND.\n" +
  "// Regenerate: bun run scripts/generate-sdk.ts\n\n";
const outPath = join(root, "src/sdk/v1.generated.ts");
// Keep generated operation signatures/envelopes; use the same hardened domain
// transport as CLI/MCP. Fail generation if the published generator shape changes.
const start = code.indexOf("export interface CalendarV1ClientOptions");
const operationsStart = code.indexOf("    /**", code.indexOf("export class CalendarV1Client"));
if (start < 0 || operationsStart < 0) throw new Error("Unexpected SDK generator template");
const seam = `export interface CalendarV1ClientOptions {
  baseUrl: string;
  apiKey: string;
  fetch?: typeof fetch;
  headers?: HeadersInit;
}
export { HasnaHttpError as ApiError } from "../store/http-storage.js";
export class CalendarV1Client {
  #transport: HttpTransport;
  #headers: Headers;
  constructor(options: CalendarV1ClientOptions | { env: Env }) {
    this.#transport = "env" in options ? resolveStorageClient("calendar", options.env).client.transport : createHttpTransport({ name: "calendar", baseUrl: options.baseUrl, apiKey: options.apiKey, fetchImpl: options.fetch });
    this.#headers = new Headers("env" in options ? undefined : options.headers);
    for (const h of ["authorization", "x-api-key", "host", "cookie", "proxy-authorization"]) {
      if (this.#headers.has(h)) throw new Error("Calendar authority headers cannot be overridden.");
    }
  }
  private request<T>(method: string, path: string, opts: { body?: unknown; query?: Record<string, unknown>; init?: RequestInit }): Promise<T> {
    if (opts.init) for (const k of Object.keys(opts.init)) {
      if (!["headers", "signal"].includes(k)) throw new Error("Calendar request only accepts headers and signal overrides.");
    }
    const headers = new Headers(this.#headers);
    new Headers(opts.init?.headers).forEach((v,k) => headers.set(k,v));
    return this.#transport.request<T>(method, path.replace(/^\\/v1(?=\\/)/, ""), opts.body, { query: opts.query as QueryParams, headers, signal: opts.init?.signal });
  }
`;
const hardened = code.slice(0, start) + seam + code.slice(operationsStart);
writeFileSync(outPath, header + 'import { createHttpTransport, resolveStorageClient, type Env, type HttpTransport, type QueryParams } from "../store/http-storage.js";\n' + hardened);

console.log(`Wrote ${outPath}`);
console.log(`Operations: ${operations.map((o) => o.functionName).join(", ")}`);
if (warnings.length) console.log(`Warnings:\n  ${warnings.join("\n  ")}`);
