// OpenAPI 3.1 document for projects-serve. Single source of truth for the
// served /openapi.json and for the generated SDK (scripts/generate-sdk.ts uses
// @hasna/contracts/sdk `generateSdkFromOpenApi` on this exact object).

export function buildOpenApiSpec(version: string): Record<string, unknown> {
  const ID_PARAM = {
    name: "id",
    in: "path",
    required: true,
    description: "Resource id or slug",
    schema: { type: "string" },
  } as const;

  const ref = (name: string) => ({ $ref: `#/components/schemas/${name}` });
  const jsonBody = (schemaName: string, required = true) => ({
    required,
    content: { "application/json": { schema: ref(schemaName) } },
  });
  const jsonResp = (schemaName: string, description = "OK") => ({
    description,
    content: { "application/json": { schema: ref(schemaName) } },
  });

  return {
    openapi: "3.1.0",
    info: {
      title: "Projects API",
      version,
      description:
        "Self-hosted HTTP API for @hasna/projects (workspace/project management). Amendment A1 pure-remote: reads and writes go directly to cloud Postgres. All /v1 routes require an API key (x-api-key or Authorization: Bearer).",
    },
    servers: [{ url: "/" }],
    components: {
      securitySchemes: {
        apiKey: { type: "apiKey", in: "header", name: "x-api-key" },
      },
      schemas: {
        Root: {
          type: "object",
          properties: {
            id: { type: "string" },
            slug: { type: "string" },
            name: { type: "string" },
            base_path: { type: "string" },
            tags: { type: "array", items: { type: "string" } },
            default_kind: { type: "string", nullable: true },
            repo_visibility: { type: "string", nullable: true },
            allowed_recipes: { type: "array", items: { type: "string" } },
            allowed_agents: { type: "array", items: { type: "string" } },
            metadata: { type: "object", additionalProperties: true },
            created_at: { type: "string" },
            updated_at: { type: "string" },
          },
          required: ["id", "slug", "name", "base_path"],
        },
        CreateRoot: {
          type: "object",
          properties: {
            name: { type: "string" },
            base_path: { type: "string" },
            slug: { type: "string" },
            tags: { type: "array", items: { type: "string" } },
            default_kind: { type: "string" },
            repo_visibility: { type: "string", enum: ["public", "private"] },
            github_org: { type: "string" },
            metadata: { type: "object", additionalProperties: true },
          },
          required: ["name", "base_path"],
        },
        UpdateRoot: {
          type: "object",
          properties: {
            name: { type: "string" },
            base_path: { type: "string" },
            slug: { type: "string" },
            tags: { type: "array", items: { type: "string" } },
            default_kind: { type: "string" },
            repo_visibility: { type: "string", enum: ["public", "private"] },
            github_org: { type: "string" },
            metadata: { type: "object", additionalProperties: true },
          },
        },
        Agent: {
          type: "object",
          properties: {
            id: { type: "string" },
            slug: { type: "string" },
            name: { type: "string" },
            kind: { type: "string", enum: ["human", "ai", "service", "cli"] },
            provider: { type: "string", nullable: true },
            model: { type: "string", nullable: true },
            role: { type: "string", nullable: true },
            permissions: { type: "array", items: { type: "string" } },
            metadata: { type: "object", additionalProperties: true },
            created_at: { type: "string" },
            updated_at: { type: "string" },
          },
          required: ["id", "slug", "name", "kind"],
        },
        CreateAgent: {
          type: "object",
          properties: {
            name: { type: "string" },
            kind: { type: "string", enum: ["human", "ai", "service", "cli"] },
            slug: { type: "string" },
            provider: { type: "string" },
            model: { type: "string" },
            role: { type: "string" },
            permissions: { type: "array", items: { type: "string" } },
            metadata: { type: "object", additionalProperties: true },
          },
          required: ["name"],
        },
        Recipe: {
          type: "object",
          properties: {
            id: { type: "string" },
            slug: { type: "string" },
            name: { type: "string" },
            description: { type: "string", nullable: true },
            kind: { type: "string", nullable: true },
            version: { type: "integer" },
            steps: { type: "array", items: { type: "object", additionalProperties: true } },
            default_tags: { type: "array", items: { type: "string" } },
            metadata: { type: "object", additionalProperties: true },
            created_at: { type: "string" },
            updated_at: { type: "string" },
          },
          required: ["id", "slug", "name"],
        },
        CreateRecipe: {
          type: "object",
          properties: {
            name: { type: "string" },
            slug: { type: "string" },
            description: { type: "string" },
            kind: { type: "string" },
            version: { type: "integer" },
            steps: { type: "array", items: { type: "object", additionalProperties: true } },
            default_tags: { type: "array", items: { type: "string" } },
            metadata: { type: "object", additionalProperties: true },
          },
          required: ["name"],
        },
        Workspace: {
          type: "object",
          properties: {
            id: { type: "string" },
            slug: { type: "string" },
            name: { type: "string" },
            description: { type: "string", nullable: true },
            kind: { type: "string" },
            status: { type: "string", enum: ["active", "archived", "deleted"] },
            root_id: { type: "string", nullable: true },
            recipe_id: { type: "string", nullable: true },
            primary_path: { type: "string", nullable: true },
            git_remote: { type: "string", nullable: true },
            tags: { type: "array", items: { type: "string" } },
            integrations: { type: "object", additionalProperties: true },
            metadata: { type: "object", additionalProperties: true },
            created_at: { type: "string" },
            updated_at: { type: "string" },
          },
          required: ["id", "slug", "name", "kind", "status"],
        },
        CreateWorkspace: {
          type: "object",
          properties: {
            name: { type: "string" },
            slug: { type: "string" },
            description: { type: "string" },
            kind: { type: "string" },
            root_id: { type: "string" },
            recipe_id: { type: "string" },
            primary_path: { type: "string" },
            git_remote: { type: "string" },
            tags: { type: "array", items: { type: "string" } },
            integrations: { type: "object", additionalProperties: true },
            metadata: { type: "object", additionalProperties: true },
            agent_id: { type: "string" },
          },
          required: ["name"],
        },
        UpdateWorkspace: {
          type: "object",
          properties: {
            name: { type: "string" },
            slug: { type: "string" },
            description: { type: "string", nullable: true },
            kind: { type: "string" },
            status: { type: "string", enum: ["active", "archived", "deleted"] },
            root_id: { type: "string", nullable: true },
            recipe_id: { type: "string", nullable: true },
            primary_path: { type: "string", nullable: true },
            git_remote: { type: "string", nullable: true },
            tags: { type: "array", items: { type: "string" } },
            integrations: { type: "object", additionalProperties: true },
            metadata: { type: "object", additionalProperties: true },
            agent_id: { type: "string" },
          },
        },
        WorkspaceEvent: {
          type: "object",
          properties: {
            id: { type: "string" },
            workspace_id: { type: "string", nullable: true },
            agent_id: { type: "string", nullable: true },
            event_type: { type: "string" },
            source: { type: "string" },
            metadata: { type: "object", additionalProperties: true },
            created_at: { type: "string" },
          },
          required: ["id", "event_type", "source"],
        },
        WorkspaceList: {
          type: "object",
          properties: {
            workspaces: { type: "array", items: ref("Workspace") },
            count: { type: "integer" },
          },
          required: ["workspaces", "count"],
        },
        RootList: {
          type: "object",
          properties: { roots: { type: "array", items: ref("Root") }, count: { type: "integer" } },
          required: ["roots", "count"],
        },
        AgentList: {
          type: "object",
          properties: { agents: { type: "array", items: ref("Agent") }, count: { type: "integer" } },
          required: ["agents", "count"],
        },
        RecipeList: {
          type: "object",
          properties: { recipes: { type: "array", items: ref("Recipe") }, count: { type: "integer" } },
          required: ["recipes", "count"],
        },
        EventList: {
          type: "object",
          properties: { events: { type: "array", items: ref("WorkspaceEvent") }, count: { type: "integer" } },
          required: ["events", "count"],
        },
        DeleteResult: {
          type: "object",
          properties: { deleted: { type: "boolean" }, hard: { type: "boolean" }, id: { type: "string" } },
          required: ["deleted"],
        },
        Health: {
          type: "object",
          properties: { status: { type: "string" }, version: { type: "string" }, mode: { type: "string" } },
          required: ["status", "version", "mode"],
        },
        Error: {
          type: "object",
          properties: { error: { type: "string" }, reason: { type: "string" } },
          required: ["error"],
        },
        AgentRun: {
          type: "object",
          properties: {
            id: { type: "string" },
            agent_id: { type: "string", nullable: true },
            workspace_id: { type: "string", nullable: true },
            provider: { type: "string", nullable: true },
            model: { type: "string", nullable: true },
            prompt: { type: "string" },
            status: { type: "string", enum: ["planned", "running", "completed", "failed"] },
            plan_json: { type: "object", additionalProperties: true, nullable: true },
            tool_calls_json: { type: "array", items: { type: "object", additionalProperties: true } },
            result_json: { type: "object", additionalProperties: true, nullable: true },
            error: { type: "string", nullable: true },
            metadata: { type: "object", additionalProperties: true },
            started_at: { type: "string" },
            completed_at: { type: "string", nullable: true },
          },
          required: ["id", "prompt", "status"],
        },
        CreateAgentRun: {
          type: "object",
          properties: {
            agent_id: { type: "string" },
            workspace_id: { type: "string" },
            provider: { type: "string" },
            model: { type: "string" },
            prompt: { type: "string" },
            status: { type: "string", enum: ["planned", "running", "completed", "failed"] },
            plan: { type: "object", additionalProperties: true },
            tool_calls: { type: "array", items: { type: "object", additionalProperties: true } },
            result: { type: "object", additionalProperties: true },
            error: { type: "string" },
            metadata: { type: "object", additionalProperties: true },
          },
          required: ["prompt"],
        },
        UpdateAgentRun: {
          type: "object",
          properties: {
            status: { type: "string", enum: ["planned", "running", "completed", "failed"] },
            provider: { type: "string" },
            model: { type: "string" },
            plan: { type: "object", additionalProperties: true },
            tool_calls: { type: "array", items: { type: "object", additionalProperties: true } },
            result: { type: "object", additionalProperties: true },
            error: { type: "string" },
            metadata: { type: "object", additionalProperties: true },
            completed_at: { type: "string" },
          },
        },
        AgentRunList: {
          type: "object",
          properties: { runs: { type: "array", items: ref("AgentRun") }, count: { type: "integer" } },
          required: ["runs", "count"],
        },
        Budget: {
          type: "object",
          properties: {
            id: { type: "string" },
            scope_type: { type: "string", enum: ["project", "run"] },
            scope_id: { type: "string" },
            window: { type: "string", enum: ["daily", "monthly", "lifetime"] },
            mode: { type: "string", enum: ["hard", "soft"] },
            max_usd: { type: "number", nullable: true },
            max_input_tokens: { type: "integer", nullable: true },
            max_output_tokens: { type: "integer", nullable: true },
            max_total_tokens: { type: "integer", nullable: true },
            warning_threshold: { type: "number", nullable: true },
            reset_at: { type: "string", nullable: true },
            metadata: { type: "object", additionalProperties: true },
            created_at: { type: "string" },
            updated_at: { type: "string" },
          },
          required: ["id", "scope_type", "scope_id", "window", "mode"],
        },
        CreateBudget: {
          type: "object",
          properties: {
            scope_type: { type: "string", enum: ["project", "run"] },
            scope_id: { type: "string" },
            window: { type: "string", enum: ["daily", "monthly", "lifetime"] },
            mode: { type: "string", enum: ["hard", "soft"] },
            max_usd: { type: "number" },
            max_input_tokens: { type: "integer" },
            max_output_tokens: { type: "integer" },
            max_total_tokens: { type: "integer" },
            warning_threshold: { type: "number" },
            reset_at: { type: "string" },
            metadata: { type: "object", additionalProperties: true },
          },
          required: ["scope_type", "scope_id", "window"],
        },
        BudgetList: {
          type: "object",
          properties: { budgets: { type: "array", items: ref("Budget") }, count: { type: "integer" } },
          required: ["budgets", "count"],
        },
        Spend: {
          type: "object",
          properties: {
            id: { type: "string" },
            workspace_id: { type: "string", nullable: true },
            run_id: { type: "string", nullable: true },
            provider: { type: "string", nullable: true },
            model: { type: "string", nullable: true },
            usd: { type: "number" },
            input_tokens: { type: "integer" },
            output_tokens: { type: "integer" },
            total_tokens: { type: "integer" },
            metadata: { type: "object", additionalProperties: true },
            created_at: { type: "string" },
          },
          required: ["id", "usd"],
        },
        RecordSpend: {
          type: "object",
          properties: {
            workspace_id: { type: "string" },
            run_id: { type: "string" },
            provider: { type: "string" },
            model: { type: "string" },
            usd: { type: "number" },
            input_tokens: { type: "integer" },
            output_tokens: { type: "integer" },
            total_tokens: { type: "integer" },
            metadata: { type: "object", additionalProperties: true },
          },
        },
        SpendList: {
          type: "object",
          properties: { spend: { type: "array", items: ref("Spend") }, count: { type: "integer" } },
          required: ["spend", "count"],
        },
        WorkspaceLocation: {
          type: "object",
          properties: {
            id: { type: "string" },
            workspace_id: { type: "string" },
            path: { type: "string" },
            machine_id: { type: "string" },
            label: { type: "string" },
            kind: { type: "string" },
            is_primary: { type: "boolean" },
            exists_at_create: { type: "boolean" },
            metadata: { type: "object", additionalProperties: true },
            created_at: { type: "string" },
          },
          required: ["id", "workspace_id", "path", "machine_id"],
        },
        AddWorkspaceLocation: {
          type: "object",
          properties: {
            path: { type: "string" },
            machine_id: { type: "string" },
            label: { type: "string" },
            kind: { type: "string" },
            is_primary: { type: "boolean" },
            exists_at_create: { type: "boolean" },
            metadata: { type: "object", additionalProperties: true },
          },
          required: ["path", "machine_id"],
        },
        LocationList: {
          type: "object",
          properties: { locations: { type: "array", items: ref("WorkspaceLocation") }, count: { type: "integer" } },
          required: ["locations", "count"],
        },
        WorkspaceAgentAssignment: {
          type: "object",
          properties: {
            id: { type: "string" },
            workspace_id: { type: "string" },
            agent_id: { type: "string" },
            role: { type: "string" },
            assigned_by: { type: "string", nullable: true },
            metadata: { type: "object", additionalProperties: true },
            created_at: { type: "string" },
          },
          required: ["id", "workspace_id", "agent_id", "role"],
        },
        AssignWorkspaceAgent: {
          type: "object",
          properties: {
            agent_id: { type: "string" },
            role: { type: "string" },
            assigned_by: { type: "string" },
            metadata: { type: "object", additionalProperties: true },
          },
          required: ["agent_id"],
        },
        WorkspaceAgentList: {
          type: "object",
          properties: { agents: { type: "array", items: ref("WorkspaceAgentAssignment") }, count: { type: "integer" } },
          required: ["agents", "count"],
        },
        TmuxProfileWindow: {
          type: "object",
          properties: {
            id: { type: "string" },
            profile_id: { type: "string" },
            window_name_template: { type: "string" },
            path_template: { type: "string", nullable: true },
            command: { type: "string", nullable: true },
            window_index: { type: "integer", nullable: true },
            detached: { type: "boolean" },
            env: { type: "object", additionalProperties: true },
            revive: { type: "boolean" },
            created_at: { type: "string" },
          },
          required: ["id", "profile_id", "window_name_template"],
        },
        CreateTmuxProfileWindow: {
          type: "object",
          properties: {
            window_name_template: { type: "string" },
            path_template: { type: "string" },
            command: { type: "string" },
            window_index: { type: "integer" },
            detached: { type: "boolean" },
            env: { type: "object", additionalProperties: true },
            revive: { type: "boolean" },
          },
          required: ["window_name_template"],
        },
        TmuxProfileWindowList: {
          type: "object",
          properties: { windows: { type: "array", items: ref("TmuxProfileWindow") }, count: { type: "integer" } },
          required: ["windows", "count"],
        },
        TmuxProfile: {
          type: "object",
          properties: {
            id: { type: "string" },
            slug: { type: "string" },
            name: { type: "string" },
            description: { type: "string", nullable: true },
            session_template: { type: "string" },
            attach: { type: "boolean" },
            metadata: { type: "object", additionalProperties: true },
            created_at: { type: "string" },
            updated_at: { type: "string" },
          },
          required: ["id", "slug", "name"],
        },
        CreateTmuxProfile: {
          type: "object",
          properties: {
            name: { type: "string" },
            slug: { type: "string" },
            description: { type: "string" },
            session_template: { type: "string" },
            attach: { type: "boolean" },
            metadata: { type: "object", additionalProperties: true },
            windows: { type: "array", items: ref("CreateTmuxProfileWindow") },
          },
          required: ["name"],
        },
        TmuxProfileList: {
          type: "object",
          properties: { profiles: { type: "array", items: ref("TmuxProfile") }, count: { type: "integer" } },
          required: ["profiles", "count"],
        },
        WorkspaceTmuxSession: {
          type: "object",
          properties: {
            id: { type: "string" },
            workspace_id: { type: "string" },
            profile_id: { type: "string", nullable: true },
            session_name: { type: "string" },
            metadata: { type: "object", additionalProperties: true },
            created_at: { type: "string" },
          },
          required: ["id", "workspace_id", "session_name"],
        },
        RecordWorkspaceTmuxSession: {
          type: "object",
          properties: {
            profile_id: { type: "string" },
            session_name: { type: "string" },
            metadata: { type: "object", additionalProperties: true },
          },
          required: ["session_name"],
        },
        SessionList: {
          type: "object",
          properties: { sessions: { type: "array", items: ref("WorkspaceTmuxSession") }, count: { type: "integer" } },
          required: ["sessions", "count"],
        },
        WorkspaceLock: {
          type: "object",
          properties: {
            id: { type: "string" },
            lock_key: { type: "string" },
            workspace_id: { type: "string", nullable: true },
            agent_id: { type: "string", nullable: true },
            reason: { type: "string", nullable: true },
            created_at: { type: "string" },
            expires_at: { type: "string", nullable: true },
          },
          required: ["id", "lock_key"],
        },
        AcquireWorkspaceLock: {
          type: "object",
          properties: {
            lock_key: { type: "string" },
            workspace_id: { type: "string" },
            agent_id: { type: "string" },
            reason: { type: "string" },
            expires_at: { type: "string" },
          },
          required: ["lock_key"],
        },
        LockList: {
          type: "object",
          properties: { locks: { type: "array", items: ref("WorkspaceLock") }, count: { type: "integer" } },
          required: ["locks", "count"],
        },
        ReleaseResult: {
          type: "object",
          properties: { released: { type: "boolean" }, lock_key: { type: "string" } },
          required: ["released"],
        },
      },
    },
    security: [{ apiKey: [] }],
    paths: {
      "/health": {
        get: {
          operationId: "getHealth",
          summary: "Liveness probe",
          security: [],
          responses: { "200": jsonResp("Health") },
        },
      },
      "/ready": {
        get: {
          operationId: "getReady",
          summary: "Readiness probe (checks DB connectivity)",
          security: [],
          responses: { "200": jsonResp("Health"), "503": jsonResp("Health", "Not ready") },
        },
      },
      "/version": {
        get: {
          operationId: "getVersion",
          summary: "Service version",
          security: [],
          responses: { "200": jsonResp("Health") },
        },
      },
      "/v1/projects": {
        get: {
          operationId: "listProjects",
          summary: "List projects (workspaces)",
          parameters: [
            { name: "status", in: "query", required: false, schema: { type: "string" } },
            { name: "kind", in: "query", required: false, schema: { type: "string" } },
            { name: "root_id", in: "query", required: false, schema: { type: "string" } },
            { name: "query", in: "query", required: false, schema: { type: "string" } },
            { name: "tag", in: "query", required: false, schema: { type: "string" } },
            { name: "limit", in: "query", required: false, schema: { type: "integer" } },
            { name: "offset", in: "query", required: false, schema: { type: "integer" } },
          ],
          responses: { "200": jsonResp("WorkspaceList") },
        },
        post: {
          operationId: "createProject",
          summary: "Create a project (workspace)",
          requestBody: jsonBody("CreateWorkspace"),
          responses: { "201": jsonResp("Workspace", "Created"), "400": jsonResp("Error", "Invalid") },
        },
      },
      "/v1/projects/{id}": {
        get: {
          operationId: "getProject",
          summary: "Get a project by id or slug",
          parameters: [ID_PARAM],
          responses: { "200": jsonResp("Workspace"), "404": jsonResp("Error", "Not found") },
        },
        patch: {
          operationId: "updateProject",
          summary: "Update a project",
          parameters: [ID_PARAM],
          requestBody: jsonBody("UpdateWorkspace"),
          responses: { "200": jsonResp("Workspace"), "404": jsonResp("Error", "Not found") },
        },
        delete: {
          operationId: "deleteProject",
          summary: "Delete a project (soft by default, ?hard=true for hard delete)",
          parameters: [
            ID_PARAM,
            { name: "hard", in: "query", required: false, schema: { type: "boolean" } },
          ],
          responses: { "200": jsonResp("DeleteResult"), "404": jsonResp("Error", "Not found") },
        },
      },
      "/v1/projects/{id}/archive": {
        post: {
          operationId: "archiveProject",
          summary: "Archive a project",
          parameters: [ID_PARAM],
          responses: { "200": jsonResp("Workspace"), "404": jsonResp("Error", "Not found") },
        },
      },
      "/v1/projects/{id}/unarchive": {
        post: {
          operationId: "unarchiveProject",
          summary: "Unarchive a project",
          parameters: [ID_PARAM],
          responses: { "200": jsonResp("Workspace"), "404": jsonResp("Error", "Not found") },
        },
      },
      "/v1/projects/{id}/events": {
        get: {
          operationId: "listProjectEvents",
          summary: "List a project's events",
          parameters: [ID_PARAM, { name: "limit", in: "query", required: false, schema: { type: "integer" } }],
          responses: { "200": jsonResp("EventList"), "404": jsonResp("Error", "Not found") },
        },
      },
      "/v1/roots": {
        get: {
          operationId: "listRoots",
          summary: "List roots",
          responses: { "200": jsonResp("RootList") },
        },
        post: {
          operationId: "createRoot",
          summary: "Create a root",
          requestBody: jsonBody("CreateRoot"),
          responses: { "201": jsonResp("Root", "Created"), "400": jsonResp("Error", "Invalid") },
        },
      },
      "/v1/roots/{id}": {
        get: {
          operationId: "getRoot",
          summary: "Get a root by id or slug",
          parameters: [ID_PARAM],
          responses: { "200": jsonResp("Root"), "404": jsonResp("Error", "Not found") },
        },
        patch: {
          operationId: "updateRoot",
          summary: "Update a root",
          parameters: [ID_PARAM],
          requestBody: jsonBody("UpdateRoot"),
          responses: { "200": jsonResp("Root"), "404": jsonResp("Error", "Not found") },
        },
        delete: {
          operationId: "deleteRoot",
          summary: "Delete a root",
          parameters: [
            ID_PARAM,
            { name: "detach", in: "query", required: false, schema: { type: "boolean" } },
          ],
          responses: { "200": jsonResp("DeleteResult"), "404": jsonResp("Error", "Not found") },
        },
      },
      "/v1/agents": {
        get: {
          operationId: "listAgents",
          summary: "List agents",
          responses: { "200": jsonResp("AgentList") },
        },
        post: {
          operationId: "createAgent",
          summary: "Create an agent",
          requestBody: jsonBody("CreateAgent"),
          responses: { "201": jsonResp("Agent", "Created"), "400": jsonResp("Error", "Invalid") },
        },
      },
      "/v1/agents/{id}": {
        get: {
          operationId: "getAgent",
          summary: "Get an agent by id or slug",
          parameters: [ID_PARAM],
          responses: { "200": jsonResp("Agent"), "404": jsonResp("Error", "Not found") },
        },
      },
      "/v1/recipes": {
        get: {
          operationId: "listRecipes",
          summary: "List recipes",
          responses: { "200": jsonResp("RecipeList") },
        },
        post: {
          operationId: "createRecipe",
          summary: "Create a recipe",
          requestBody: jsonBody("CreateRecipe"),
          responses: { "201": jsonResp("Recipe", "Created"), "400": jsonResp("Error", "Invalid") },
        },
      },
      "/v1/recipes/{id}": {
        get: {
          operationId: "getRecipe",
          summary: "Get a recipe by id or slug",
          parameters: [ID_PARAM],
          responses: { "200": jsonResp("Recipe"), "404": jsonResp("Error", "Not found") },
        },
      },
      "/v1/projects/{id}/locations": {
        get: {
          operationId: "listProjectLocations",
          summary: "List a project's on-machine locations",
          parameters: [ID_PARAM],
          responses: { "200": jsonResp("LocationList"), "404": jsonResp("Error", "Not found") },
        },
        post: {
          operationId: "addProjectLocation",
          summary: "Register a project location (machine-local path persisted centrally)",
          parameters: [ID_PARAM],
          requestBody: jsonBody("AddWorkspaceLocation"),
          responses: { "201": jsonResp("WorkspaceLocation", "Created"), "404": jsonResp("Error", "Not found") },
        },
      },
      "/v1/projects/{id}/agents": {
        get: {
          operationId: "listProjectAgents",
          summary: "List a project's assigned agents",
          parameters: [ID_PARAM],
          responses: { "200": jsonResp("WorkspaceAgentList"), "404": jsonResp("Error", "Not found") },
        },
        post: {
          operationId: "assignProjectAgent",
          summary: "Assign an agent to a project",
          parameters: [ID_PARAM],
          requestBody: jsonBody("AssignWorkspaceAgent"),
          responses: { "201": jsonResp("WorkspaceAgentAssignment", "Created"), "404": jsonResp("Error", "Not found") },
        },
      },
      "/v1/projects/{id}/sessions": {
        get: {
          operationId: "listProjectSessions",
          summary: "List a project's recorded tmux sessions",
          parameters: [ID_PARAM],
          responses: { "200": jsonResp("SessionList"), "404": jsonResp("Error", "Not found") },
        },
        post: {
          operationId: "recordProjectSession",
          summary: "Record a project tmux session (machine-local execution state)",
          parameters: [ID_PARAM],
          requestBody: jsonBody("RecordWorkspaceTmuxSession"),
          responses: { "201": jsonResp("WorkspaceTmuxSession", "Created"), "404": jsonResp("Error", "Not found") },
        },
      },
      "/v1/projects/{id}/locks": {
        get: {
          operationId: "listProjectLocks",
          summary: "List a project's locks",
          parameters: [ID_PARAM],
          responses: { "200": jsonResp("LockList"), "404": jsonResp("Error", "Not found") },
        },
      },
      "/v1/runs": {
        get: {
          operationId: "listRuns",
          summary: "List agent runs",
          parameters: [
            { name: "workspace_id", in: "query", required: false, schema: { type: "string" } },
            { name: "agent_id", in: "query", required: false, schema: { type: "string" } },
            { name: "status", in: "query", required: false, schema: { type: "string" } },
            { name: "limit", in: "query", required: false, schema: { type: "integer" } },
            { name: "offset", in: "query", required: false, schema: { type: "integer" } },
          ],
          responses: { "200": jsonResp("AgentRunList") },
        },
        post: {
          operationId: "createRun",
          summary: "Create an agent run",
          requestBody: jsonBody("CreateAgentRun"),
          responses: { "201": jsonResp("AgentRun", "Created"), "400": jsonResp("Error", "Invalid") },
        },
      },
      "/v1/runs/{id}": {
        get: {
          operationId: "getRun",
          summary: "Get an agent run",
          parameters: [ID_PARAM],
          responses: { "200": jsonResp("AgentRun"), "404": jsonResp("Error", "Not found") },
        },
        patch: {
          operationId: "updateRun",
          summary: "Update an agent run (status/result/tool calls)",
          parameters: [ID_PARAM],
          requestBody: jsonBody("UpdateAgentRun"),
          responses: { "200": jsonResp("AgentRun"), "404": jsonResp("Error", "Not found") },
        },
      },
      "/v1/budgets": {
        get: {
          operationId: "listBudgets",
          summary: "List budgets",
          parameters: [
            { name: "scope_type", in: "query", required: false, schema: { type: "string" } },
            { name: "scope_id", in: "query", required: false, schema: { type: "string" } },
            { name: "limit", in: "query", required: false, schema: { type: "integer" } },
            { name: "offset", in: "query", required: false, schema: { type: "integer" } },
          ],
          responses: { "200": jsonResp("BudgetList") },
        },
        post: {
          operationId: "createBudget",
          summary: "Create a budget",
          requestBody: jsonBody("CreateBudget"),
          responses: { "201": jsonResp("Budget", "Created"), "400": jsonResp("Error", "Invalid") },
        },
      },
      "/v1/budgets/{id}": {
        get: {
          operationId: "getBudget",
          summary: "Get a budget",
          parameters: [ID_PARAM],
          responses: { "200": jsonResp("Budget"), "404": jsonResp("Error", "Not found") },
        },
        delete: {
          operationId: "deleteBudget",
          summary: "Delete a budget",
          parameters: [ID_PARAM],
          responses: { "200": jsonResp("DeleteResult"), "404": jsonResp("Error", "Not found") },
        },
      },
      "/v1/spend": {
        get: {
          operationId: "listSpend",
          summary: "List budget spend records",
          parameters: [
            { name: "workspace_id", in: "query", required: false, schema: { type: "string" } },
            { name: "run_id", in: "query", required: false, schema: { type: "string" } },
            { name: "limit", in: "query", required: false, schema: { type: "integer" } },
            { name: "offset", in: "query", required: false, schema: { type: "integer" } },
          ],
          responses: { "200": jsonResp("SpendList") },
        },
        post: {
          operationId: "recordSpend",
          summary: "Record a budget spend entry",
          requestBody: jsonBody("RecordSpend"),
          responses: { "201": jsonResp("Spend", "Created"), "400": jsonResp("Error", "Invalid") },
        },
      },
      "/v1/tmux-profiles": {
        get: {
          operationId: "listTmuxProfiles",
          summary: "List tmux profiles",
          responses: { "200": jsonResp("TmuxProfileList") },
        },
        post: {
          operationId: "createTmuxProfile",
          summary: "Create a tmux profile",
          requestBody: jsonBody("CreateTmuxProfile"),
          responses: { "201": jsonResp("TmuxProfile", "Created"), "400": jsonResp("Error", "Invalid") },
        },
      },
      "/v1/tmux-profiles/{id}": {
        get: {
          operationId: "getTmuxProfile",
          summary: "Get a tmux profile by id or slug",
          parameters: [ID_PARAM],
          responses: { "200": jsonResp("TmuxProfile"), "404": jsonResp("Error", "Not found") },
        },
      },
      "/v1/tmux-profiles/{id}/windows": {
        get: {
          operationId: "listTmuxProfileWindows",
          summary: "List a tmux profile's windows",
          parameters: [ID_PARAM],
          responses: { "200": jsonResp("TmuxProfileWindowList"), "404": jsonResp("Error", "Not found") },
        },
        post: {
          operationId: "addTmuxProfileWindow",
          summary: "Add a window to a tmux profile",
          parameters: [ID_PARAM],
          requestBody: jsonBody("CreateTmuxProfileWindow"),
          responses: { "201": jsonResp("TmuxProfileWindow", "Created"), "404": jsonResp("Error", "Not found") },
        },
      },
      "/v1/locks": {
        get: {
          operationId: "listLocks",
          summary: "List locks",
          parameters: [{ name: "workspace_id", in: "query", required: false, schema: { type: "string" } }],
          responses: { "200": jsonResp("LockList") },
        },
        post: {
          operationId: "acquireLock",
          summary: "Acquire a lock",
          requestBody: jsonBody("AcquireWorkspaceLock"),
          responses: { "201": jsonResp("WorkspaceLock", "Created"), "400": jsonResp("Error", "Conflict") },
        },
      },
      "/v1/locks/{id}": {
        delete: {
          operationId: "releaseLock",
          summary: "Release a lock by lock_key",
          parameters: [ID_PARAM],
          responses: { "200": jsonResp("ReleaseResult") },
        },
      },
      "/v1/locations/{id}": {
        delete: {
          operationId: "deleteLocation",
          summary: "Delete a project location",
          parameters: [ID_PARAM],
          responses: { "200": jsonResp("DeleteResult") },
        },
      },
      "/v1/workspace-agents/{id}": {
        delete: {
          operationId: "removeProjectAgent",
          summary: "Remove a project agent assignment",
          parameters: [ID_PARAM],
          responses: { "200": jsonResp("DeleteResult") },
        },
      },
      "/v1/sessions/{id}": {
        delete: {
          operationId: "deleteSession",
          summary: "Delete a recorded tmux session",
          parameters: [ID_PARAM],
          responses: { "200": jsonResp("DeleteResult") },
        },
      },
    },
  };
}
